Repository rust-lang/cargo, pull requests merged in 2019-07, with the labels that each got.

#7083 improve uncommitted changes cargo-package message
  src/cargo/ops/cargo_package.rs
  tests/testsuite/package.rs
  tests/testsuite/publish.rs
Labels: S-waiting-on-bors

#7090 Fix misleading comment in testsuite
  tests/testsuite/build.rs
Labels: S-waiting-on-bors

#7093 Fix 'getting started' internal links
  src/doc/src/getting-started/first-steps.md
  src/doc/src/getting-started/index.md
Labels: S-waiting-on-bors

#7097 Typo
  src/cargo/util/config.rs
Labels: S-waiting-on-bors

#7098 Update dependency.rs
  src/cargo/core/dependency.rs
Labels: S-waiting-on-bors

#7100 Bump to 0.39.0
  Cargo.toml
  crates/crates-io/Cargo.toml
Labels: S-waiting-on-bors

#7099 Revert "Fix 'getting started' internal links"
  src/doc/src/getting-started/first-steps.md
  src/doc/src/getting-started/index.md
Labels: S-waiting-on-bors

#7102 Update changelog.
  CHANGELOG.md
Labels: S-waiting-on-bors

#7057 Fix overwriting .d file for binary with dSYM on apple targets.
  src/cargo/core/compiler/output_depinfo.rs
  tests/testsuite/dep_info.rs
Labels: S-waiting-on-bors

#7106 Update dependencies
  Cargo.toml
  tests/testsuite/support/publish.rs
Labels: S-waiting-on-bors

#7115 Fix changelog date
  CHANGELOG.md
Labels: S-waiting-on-bors

#7116 Don't suppress error messages with `-q`
  src/cargo/core/shell.rs
  tests/testsuite/workspaces.rs
Labels: S-waiting-on-bors

#7125 Remove MyFnOnce
  src/cargo/core/compiler/fingerprint.rs
Labels: S-waiting-on-bors

#7126 [BETA] Fix `cargo new` in root directory.
  src/cargo/ops/cargo_new.rs
Labels: S-waiting-on-bors

#7118 Handle activation conflicts for `[patch]` sources
  src/cargo/core/resolver/context.rs
  src/cargo/core/resolver/mod.rs
  tests/testsuite/patch.rs
Labels: S-waiting-on-bors

#7128 [BETA] Fix `cargo new` in root directory.
  src/cargo/ops/cargo_new.rs
Labels: S-waiting-on-bors

#7129 Fix some formatting for some strings.
  crates/resolver-tests/tests/resolve.rs
  src/bin/cargo/commands/metadata.rs
  src/cargo/core/package.rs
  src/cargo/core/registry.rs
  src/cargo/ops/registry.rs
  src/cargo/sources/directory.rs
  src/cargo/util/command_prelude.rs
  src/cargo/util/diagnostic_server.rs
  tests/testsuite/bad_config.rs
  tests/testsuite/build.rs
  tests/testsuite/build_auth.rs
  tests/testsuite/build_script.rs
  tests/testsuite/cross_compile.rs
  tests/testsuite/features.rs
  tests/testsuite/fix.rs
  tests/testsuite/install.rs
  tests/testsuite/new.rs
  tests/testsuite/path.rs
  tests/testsuite/run.rs
  tests/testsuite/rustc.rs
  tests/testsuite/tool_paths.rs
Labels: S-waiting-on-bors

#7134 Also ignore remap-path-prefix in metadata for `cargo rustc`.
  src/cargo/core/compiler/context/compilation_files.rs
  tests/testsuite/rustflags.rs
Labels: S-waiting-on-bors

#7135 Fix some clippy warnings.
  src/bin/cargo/cli.rs
  src/bin/cargo/commands/install.rs
  src/cargo/core/compiler/fingerprint.rs
  src/cargo/ops/cargo_package.rs
  src/cargo/util/command_prelude.rs
  src/cargo/util/toml/mod.rs
  src/cargo/util/workspace.rs
  tests/testsuite/read_manifest.rs
  tests/testsuite/support/mod.rs
  tests/testsuite/support/paths.rs
  tests/testsuite/test.rs
  tests/testsuite/warn_on_failure.rs
Labels: S-waiting-on-bors

#7127 Remove now-unused `WorkspaceResolve`
  src/cargo/core/resolver/context.rs
  src/cargo/core/resolver/encode.rs
  src/cargo/core/resolver/mod.rs
  src/cargo/ops/lockfile.rs
Labels: S-waiting-on-bors

#7131 Remove unused feature filter.
  src/cargo/core/compiler/context/unit_dependencies.rs
Labels: S-waiting-on-bors

#7140 Update mdbook to 0.3.
  .travis.yml
  src/doc/README.md
  src/doc/asciidoc-extension.rb
  src/doc/book.toml
  src/doc/man/generated/cargo-bench.html
  src/doc/man/generated/cargo-build.html
  src/doc/man/generated/cargo-check.html
  src/doc/man/generated/cargo-clean.html
  src/doc/man/generated/cargo-doc.html
  src/doc/man/generated/cargo-fetch.html
  src/doc/man/generated/cargo-fix.html
  src/doc/man/generated/cargo-generate-lockfile.html
  src/doc/man/generated/cargo-help.html
  src/doc/man/generated/cargo-init.html
  src/doc/man/generated/cargo-install.html
  src/doc/man/generated/cargo-locate-project.html
  src/doc/man/generated/cargo-login.html
  src/doc/man/generated/cargo-metadata.html
  src/doc/man/generated/cargo-new.html
  src/doc/man/generated/cargo-owner.html
  src/doc/man/generated/cargo-package.html
  src/doc/man/generated/cargo-pkgid.html
  src/doc/man/generated/cargo-publish.html
  src/doc/man/generated/cargo-run.html
  src/doc/man/generated/cargo-rustc.html
  src/doc/man/generated/cargo-rustdoc.html
  src/doc/man/generated/cargo-search.html
  src/doc/man/generated/cargo-test.html
  src/doc/man/generated/cargo-uninstall.html
  src/doc/man/generated/cargo-update.html
  src/doc/man/generated/cargo-vendor.html
  src/doc/man/generated/cargo-verify-project.html
  src/doc/man/generated/cargo-version.html
  src/doc/man/generated/cargo-yank.html
  src/doc/man/generated/cargo.html
  src/doc/src/appendix/glossary.md
  src/doc/src/faq.md
  src/doc/src/getting-started/first-steps.md
  src/doc/src/getting-started/index.md
  src/doc/src/guide/cargo-toml-vs-cargo-lock.md
  src/doc/src/guide/dependencies.md
  src/doc/src/guide/index.md
  src/doc/src/guide/project-layout.md
  src/doc/src/guide/tests.md
  src/doc/src/index.md
  src/doc/src/reference/build-scripts.md
  src/doc/src/reference/config.md
  src/doc/src/reference/environment-variables.md
  src/doc/src/reference/index.md
  src/doc/src/reference/manifest.md
  src/doc/src/reference/publishing.md
  src/doc/src/reference/registries.md
  src/doc/src/reference/source-replacement.md
  src/doc/src/reference/specifying-dependencies.md
  src/doc/src/reference/unstable.md
Labels: S-waiting-on-bors

#7119 Add Cirrus CI badge to manifest
  src/doc/src/reference/manifest.md
Labels: S-waiting-on-bors

#7142 Add a way to disable all nightly tests
  tests/testsuite/support/mod.rs
Labels: S-waiting-on-bors

#7145 Fix a typo in an env var name
  tests/testsuite/support/mod.rs
Labels: S-waiting-on-bors

#7084 Add support for multiple --features options
  src/cargo/util/command_prelude.rs
  tests/testsuite/features.rs
Labels: S-waiting-on-bors, T-cargo, disposition-merge, final-comment-period

#7149 Don't fail if we can't acquire readonly lock
  src/cargo/util/config.rs
Labels: S-waiting-on-bors

#7146 Optimize runtime of `#[cargo_test_macro]`
  crates/cargo-test-macro/Cargo.toml
  crates/cargo-test-macro/src/lib.rs
Labels: S-waiting-on-bors

#7158 Work around rust-lang/rust#61440
  tests/testsuite/fix.rs
  tests/testsuite/freshness.rs
Labels: S-waiting-on-bors

#7157 Force clippy to run.
  src/bin/cargo/commands/clippy.rs
  tests/testsuite/clippy.rs
  tests/testsuite/main.rs
Labels: S-waiting-on-bors

#7139 Set up CI with Azure Pipelines
  .travis.yml
  README.md
  appveyor.yml
  azure-pipelines.yml
  ci/azure-install-rust.yml
  ci/azure-test-all.yml
  tests/testsuite/config.rs
  tests/testsuite/support/mod.rs
  tests/testsuite/tool_paths.rs
Labels: S-waiting-on-bors

#7165 [BETA] Don't fail if we can't acquire readonly lock
  src/cargo/util/config.rs
Labels: S-waiting-on-bors

#7070 Optimize lock file format for git merge conflicts
  src/cargo/core/resolver/encode.rs
  src/cargo/core/resolver/mod.rs
  src/cargo/core/resolver/resolve.rs
  src/cargo/ops/lockfile.rs
  tests/testsuite/lockfile_compat.rs
Labels: S-waiting-on-bors

#7170 Remove include/exclude glob warning.
  src/cargo/sources/path.rs
  tests/testsuite/package.rs
Labels: S-waiting-on-bors

#7174 Fix detection of cyclic dependencies through `[patch]`
  src/cargo/core/resolver/encode.rs
  src/cargo/core/resolver/mod.rs
  src/cargo/core/resolver/resolve.rs
  src/cargo/ops/cargo_generate_lockfile.rs
  src/cargo/ops/resolve.rs
  tests/testsuite/patch.rs
Labels: S-waiting-on-bors

#7179 Fix a deadlocking test with master libgit2
  Cargo.toml
  tests/testsuite/build_auth.rs
Labels: S-waiting-on-bors

#7176 Tighten requirements for git2 crates
  Cargo.toml
Labels: S-waiting-on-bors

#7175 Update the `url` crate to 2.0
  Cargo.toml
  crates/crates-io/Cargo.toml
  crates/crates-io/lib.rs
  src/cargo/core/dependency.rs
  src/cargo/ops/registry.rs
Labels: S-waiting-on-bors

#7185 Clean up TargetInfo
  src/cargo/core/compiler/build_context/mod.rs
  src/cargo/core/compiler/build_context/target_info.rs
  src/cargo/core/compiler/compilation.rs
  src/cargo/core/dependency.rs
  src/cargo/util/rustc.rs
  tests/testsuite/rustc_info_cache.rs
Labels: S-waiting-on-bors

#7187 Update `cargo_compile` module doc.
  src/cargo/ops/cargo_compile.rs
Labels: S-waiting-on-bors

#7143 Enable pipelined compilation by default
  src/cargo/core/compiler/build_context/target_info.rs
  src/cargo/core/compiler/context/mod.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/ops/fix.rs
  tests/testsuite/build_script.rs
  tests/testsuite/cache_messages.rs
  tests/testsuite/dep_info.rs
  tests/testsuite/profile_overrides.rs
  tests/testsuite/rustc_info_cache.rs
  tests/testsuite/rustdoc.rs
Labels: S-waiting-on-bors, relnotes

#7192 Fix excluding target dirs from backups on OSX
  src/cargo/core/compiler/layout.rs
Labels: S-waiting-on-bors

#7198 tests: Enable features to fix unstabilized `#[bench]`
  tests/testsuite/bench.rs
Labels: S-waiting-on-bors
