Repository rust-lang/cargo, pull requests merged in 2019-11, with the labels that each got.

#7513 don't download std-docs on CI
  ci/azure-install-rust.yml
Labels: S-waiting-on-bors

#7573 Use multiple requirement syntax consistently
  src/doc/src/reference/specifying-dependencies.md
Labels: S-waiting-on-bors

#7578 Add VS Code user dir to .gitignore
  .gitignore
Labels: S-waiting-on-bors

#7570 Only include "already existing ..." comment in gitignore on conflict
  src/cargo/ops/cargo_new.rs
  tests/testsuite/init.rs
Labels: S-waiting-on-bors

#7576 Add back support for `BROWSER` envvar in `cargo doc --open`.
  src/cargo/ops/cargo_doc.rs
  src/doc/man/cargo-doc.adoc
  src/doc/man/cargo-rustdoc.adoc
  src/doc/man/generated/cargo-doc.html
  src/doc/man/generated/cargo-rustdoc.html
  src/etc/man/cargo-doc.1
  src/etc/man/cargo-help.1
  src/etc/man/cargo-init.1
  src/etc/man/cargo-install.1
  src/etc/man/cargo-login.1
  src/etc/man/cargo-new.1
  src/etc/man/cargo-owner.1
  src/etc/man/cargo-rustdoc.1
  src/etc/man/cargo-search.1
  src/etc/man/cargo-uninstall.1
  src/etc/man/cargo-version.1
  src/etc/man/cargo-yank.1
  src/etc/man/cargo.1
Labels: S-waiting-on-bors

#7575 Fix unused configuration key warning for a few keys under `build`.
  src/cargo/ops/fix.rs
  src/cargo/util/config/mod.rs
Labels: S-waiting-on-bors

#7580 Don't panic when parsing `/proc/stat`
  src/cargo/util/cpu.rs
Labels: S-waiting-on-bors

#7588 Remove "cargo login" from user input when asking for login token.
  src/cargo/ops/registry.rs
Labels: S-waiting-on-bors

#7595 Document Cargo's JSON output.
  src/doc/man/generated/cargo-bench.html
  src/doc/man/generated/cargo-build.html
  src/doc/man/generated/cargo-check.html
  src/doc/man/generated/cargo-doc.html
  src/doc/man/generated/cargo-fix.html
  src/doc/man/generated/cargo-run.html
  src/doc/man/generated/cargo-rustc.html
  src/doc/man/generated/cargo-rustdoc.html
  src/doc/man/generated/cargo-test.html
  src/doc/man/options-message-format.adoc
  src/doc/src/reference/external-tools.md
  src/etc/man/cargo-bench.1
  src/etc/man/cargo-build.1
  src/etc/man/cargo-check.1
  src/etc/man/cargo-doc.1
  src/etc/man/cargo-fix.1
  src/etc/man/cargo-run.1
  src/etc/man/cargo-rustc.1
  src/etc/man/cargo-rustdoc.1
  src/etc/man/cargo-test.1
Labels: S-waiting-on-bors

#7607 Add hack for fwdansi change.
  tests/testsuite/cache_messages.rs
Labels: S-waiting-on-bors

#7602 Ignore file lock errors if unsupported, on Windows
  src/cargo/util/flock.rs
Labels: S-waiting-on-bors

#7609 bump im-rc version
  Cargo.toml
Labels: S-waiting-on-bors

#7560 Stabilize install-upgrade.
  src/bin/cargo/cli.rs
  src/bin/cargo/commands/install.rs
  src/cargo/core/features.rs
  src/cargo/ops/common_for_install_and_uninstall.rs
  src/doc/man/cargo-install.adoc
  src/doc/man/generated/cargo-install.html
  src/doc/src/reference/unstable.md
  src/etc/man/cargo-install.1
  tests/testsuite/concurrent.rs
  tests/testsuite/install.rs
  tests/testsuite/install_upgrade.rs
Labels: S-waiting-on-bors, T-cargo, disposition-merge, finished-final-comment-period

#7616 Extend documentation on security concerns of crate names in a registry.
  src/doc/src/reference/registries.md
Labels: S-waiting-on-bors, relnotes

#7623 Update documentation for custom target dependencies.
  src/doc/src/reference/specifying-dependencies.md
  tests/build-std/main.rs
Labels: S-waiting-on-bors

#7625 Some random comments and docstrings.
  src/cargo/core/compiler/context/compilation_files.rs
  src/cargo/core/compiler/context/mod.rs
  src/cargo/core/compiler/fingerprint.rs
  src/cargo/core/compiler/output_depinfo.rs
Labels: S-waiting-on-bors

#7630 Remove failing plugin tests.
  tests/testsuite/cross_compile.rs
Labels: S-waiting-on-bors

#7629 vendor: don't use canonical path in .cargo/config
  src/cargo/ops/vendor.rs
Labels: S-waiting-on-bors

#7626 Remove dep_targets.
  src/cargo/core/compiler/build_plan.rs
  src/cargo/core/compiler/context/compilation_files.rs
  src/cargo/core/compiler/context/mod.rs
  src/cargo/core/compiler/custom_build.rs
  src/cargo/core/compiler/job_queue.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/core/compiler/output_depinfo.rs
Labels: S-waiting-on-bors

#7641 Update tests for slight wording change in rustdoc error message.
  tests/testsuite/doc.rs
Labels: S-waiting-on-bors
