Repository rust-lang/cargo, pull requests merged in 2019-08, with the labels that each got.

#7201 Revert "Release a jobserver token while locking a file"
  src/cargo/util/flock.rs
Labels: S-waiting-on-bors

#7204 [beta] Revert "Release a jobserver token while locking a file"
  src/cargo/util/flock.rs
Labels: S-waiting-on-review

#7210 Remove unused AstBuilder
  tests/testsuite/cross_compile.rs
Labels: S-waiting-on-bors

#7208 Fix an old test.
  tests/testsuite/build_script.rs
Labels: S-waiting-on-bors

#7213 Remove debug panic in package-features.
  src/cargo/ops/resolve.rs
  tests/testsuite/features.rs
Labels: S-waiting-on-bors

#7215 Clean up build script stuff and documentation.
  src/cargo/core/compiler/build_context/mod.rs
  src/cargo/core/compiler/context/mod.rs
  src/cargo/core/compiler/context/unit_dependencies.rs
  src/cargo/core/compiler/custom_build.rs
  src/cargo/core/compiler/fingerprint.rs
  src/cargo/core/compiler/job_queue.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/core/compiler/output_depinfo.rs
  src/cargo/core/manifest.rs
Labels: S-waiting-on-bors

#7219 Fix remap-path-prefix from failing.
  src/cargo/core/compiler/fingerprint.rs
  tests/testsuite/rustflags.rs
Labels: S-waiting-on-bors

#7221 Bump rustfix
  Cargo.toml
Labels: S-waiting-on-bors

#7214 Add support for customizing JSON diagnostics from Cargo
  CHANGELOG.md
  src/cargo/core/compiler/build_config.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/util/command_prelude.rs
  src/doc/man/generated/cargo-bench.html
  src/doc/man/generated/cargo-build.html
  src/doc/man/generated/cargo-check.html
  src/doc/man/generated/cargo-doc.html
  src/doc/man/generated/cargo-fix.html
  src/doc/man/generated/cargo-metadata.html
  src/doc/man/generated/cargo-run.html
  src/doc/man/generated/cargo-rustc.html
  src/doc/man/generated/cargo-rustdoc.html
  src/doc/man/generated/cargo-test.html
  src/doc/man/options-message-format.adoc
  src/etc/man/cargo-bench.1
  src/etc/man/cargo-build.1
  src/etc/man/cargo-check.1
  src/etc/man/cargo-clean.1
  src/etc/man/cargo-doc.1
  src/etc/man/cargo-fetch.1
  src/etc/man/cargo-fix.1
  src/etc/man/cargo-generate-lockfile.1
  src/etc/man/cargo-help.1
  src/etc/man/cargo-init.1
  src/etc/man/cargo-install.1
  src/etc/man/cargo-locate-project.1
  src/etc/man/cargo-login.1
  src/etc/man/cargo-metadata.1
  src/etc/man/cargo-new.1
  src/etc/man/cargo-owner.1
  src/etc/man/cargo-package.1
  src/etc/man/cargo-pkgid.1
  src/etc/man/cargo-publish.1
  src/etc/man/cargo-run.1
  src/etc/man/cargo-rustc.1
  src/etc/man/cargo-rustdoc.1
  src/etc/man/cargo-search.1
  src/etc/man/cargo-test.1
  src/etc/man/cargo-uninstall.1
  src/etc/man/cargo-update.1
  src/etc/man/cargo-vendor.1
  src/etc/man/cargo-verify-project.1
  src/etc/man/cargo-version.1
  src/etc/man/cargo-yank.1
  src/etc/man/cargo.1
  tests/testsuite/build.rs
  tests/testsuite/fix.rs
  tests/testsuite/main.rs
  tests/testsuite/message_format.rs
Labels: S-waiting-on-bors, T-cargo, disposition-merge, final-comment-period

#7222 enable progress bar for FreeBSD
  src/cargo/core/shell.rs
Labels: S-waiting-on-bors

#7227 Layout docs and cleanup.
  src/cargo/core/compiler/build_context/target_info.rs
  src/cargo/core/compiler/compilation.rs
  src/cargo/core/compiler/context/compilation_files.rs
  src/cargo/core/compiler/layout.rs
  src/cargo/core/compiler/mod.rs
  src/doc/src/reference/manifest.md
Labels: S-waiting-on-bors

#7231 Update two tests for changes in rustc output
  tests/testsuite/check.rs
  tests/testsuite/metabuild.rs
Labels: S-waiting-on-bors

#7235 Remove stray file.
  tests/testsuite/check-style.sh
Labels: S-waiting-on-bors

#7236 Better error messages when `rustc` discovery parsing fails.
  src/cargo/core/compiler/build_context/target_info.rs
  src/cargo/util/rustc.rs
  tests/testsuite/cfg.rs
Labels: S-waiting-on-bors

#7238 Allow git dependency with shorthand ssh submodules to work.
  src/cargo/sources/git/utils.rs
  src/cargo/sources/registry/remote.rs
Labels: S-waiting-on-bors

#7239 Improve error message when using API command with non-remote registry.
  src/cargo/core/source/source_id.rs
  src/cargo/ops/registry.rs
  tests/testsuite/publish.rs
Labels: S-waiting-on-bors

#7248 Bump toml 0.5.3
  Cargo.toml
  tests/testsuite/bad_config.rs
  tests/testsuite/build.rs
  tests/testsuite/config.rs
  tests/testsuite/git.rs
  tests/testsuite/workspaces.rs
Labels: S-waiting-on-bors

#7243 `cargo fetch`: Display workspace warnings.
  src/cargo/ops/cargo_fetch.rs
  tests/testsuite/fetch.rs
Labels: S-waiting-on-bors

#7244 Adjust warning for rustdoc filename collision.
  src/cargo/core/compiler/context/mod.rs
  tests/testsuite/collisions.rs
Labels: S-waiting-on-bors

#7247 Update home to 0.4
  Cargo.toml
Labels: S-waiting-on-bors

#7246 `cargo install`: Remove orphaned executables.
  src/cargo/ops/cargo_compile.rs
  src/cargo/ops/cargo_install.rs
  src/cargo/ops/common_for_install_and_uninstall.rs
  tests/testsuite/install.rs
  tests/testsuite/install_upgrade.rs
Labels: S-waiting-on-bors, T-cargo, disposition-merge, final-comment-period

#7237 Allow git+version dependency to be published.
  src/cargo/ops/registry.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/publish.rs
  tests/testsuite/support/publish.rs
Labels: S-waiting-on-bors, T-cargo, disposition-merge, final-comment-period

#7269 Bump to 0.40.0, Update changelog
  CHANGELOG.md
  Cargo.toml
  crates/crates-io/Cargo.toml
Labels: S-waiting-on-bors

#7268 Fix dSYM uplifting when symlink is broken
  src/cargo/core/compiler/mod.rs
  tests/testsuite/build.rs
Labels: S-waiting-on-bors

#7274 [beta] Fix old lockfile encoding wrt newlines
  src/cargo/core/mod.rs
  src/cargo/ops/lockfile.rs
Labels: S-waiting-on-review

#7275 Update libgit2 dependencies
  Cargo.toml
Labels: S-waiting-on-bors

#7279 Fix typo
  src/doc/src/reference/config.md
Labels: S-waiting-on-bors

#7277 Update home dependencies to v0.5
  Cargo.toml
Labels: S-waiting-on-bors

#7293 Update README azure badge.
  README.md
Labels: S-waiting-on-bors

#7287 Tests: Import rustc_plugin from its new location
  tests/testsuite/cross_compile.rs
  tests/testsuite/plugins.rs
  tests/testsuite/proc_macro.rs
Labels: S-waiting-on-bors

#7294 Fix `error:`/`warning:` coloring inconsistency with rustc
  src/cargo/core/shell.rs
Labels: S-waiting-on-bors

#7263 Document that `package` can be used in `[patch]`
  src/doc/src/reference/manifest.md
  tests/testsuite/patch.rs
Labels: S-waiting-on-bors

#7296 Update and improve zsh completion
  src/etc/_cargo
Labels: S-waiting-on-bors

#7306 Improve error messages on mkdir failure
  src/cargo/core/compiler/custom_build.rs
  src/cargo/core/compiler/fingerprint.rs
  src/cargo/core/compiler/layout.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/ops/cargo_install.rs
  src/cargo/ops/cargo_new.rs
  src/cargo/ops/vendor.rs
  src/cargo/sources/git/utils.rs
  src/cargo/sources/registry/index.rs
  src/cargo/sources/registry/remote.rs
  src/cargo/util/flock.rs
  src/cargo/util/paths.rs
  src/cargo/util/vcs.rs
  tests/testsuite/out_dir.rs
Labels: S-waiting-on-bors

#7303 Fixes around multiple `[patch]` per crate
  src/cargo/core/registry.rs
  tests/testsuite/patch.rs
Labels: S-waiting-on-bors
