Repository rust-lang/cargo, pull requests merged in 2019-12, with the labels that each got.

#7637 Update comment about ResolveVersion default version.
  src/cargo/core/resolver/resolve.rs
Labels: S-waiting-on-bors

#7591 Stabilize profile-overrides.
  src/cargo/core/features.rs
  src/doc/man/cargo-bench.adoc
  src/doc/man/generated/cargo-bench.html
  src/doc/man/generated/cargo-build.html
  src/doc/man/generated/cargo-check.html
  src/doc/man/generated/cargo-doc.html
  src/doc/man/generated/cargo-fix.html
  src/doc/man/generated/cargo-run.html
  src/doc/man/generated/cargo-rustc.html
  src/doc/man/generated/cargo-rustdoc.html
  src/doc/man/generated/cargo-test.html
  src/doc/man/section-profiles.adoc
  src/doc/src/SUMMARY.md
  src/doc/src/faq.md
  src/doc/src/reference/manifest.md
  src/doc/src/reference/profiles.md
  src/doc/src/reference/unstable.md
  src/etc/man/cargo-bench.1
  src/etc/man/cargo-build.1
  src/etc/man/cargo-check.1
  src/etc/man/cargo-doc.1
  src/etc/man/cargo-fix.1
  src/etc/man/cargo-run.1
  src/etc/man/cargo-rustc.1
  src/etc/man/cargo-rustdoc.1
  src/etc/man/cargo-test.1
  tests/testsuite/profile_config.rs
  tests/testsuite/profile_custom.rs
  tests/testsuite/profile_overrides.rs
Labels: S-waiting-on-bors, T-cargo, disposition-merge, finished-final-comment-period

#7642 Various contributing docs updates.
  CONTRIBUTING.md
  README.md
  src/doc/README.md
Labels: S-waiting-on-bors

#7647 Stop ignoring .rs.bk files; rustfmt hasn't generated them in years
  src/cargo/ops/cargo_new.rs
  tests/testsuite/init.rs
  tests/testsuite/new.rs
Labels: S-waiting-on-bors

#7650 Update config and environment variable docs.
  src/doc/src/reference/build-scripts.md
  src/doc/src/reference/config.md
  src/doc/src/reference/environment-variables.md
  src/doc/src/reference/profiles.md
Labels: S-waiting-on-bors

#7652 Change some texts to links in README
  README.md
Labels: S-waiting-on-bors

#7654 Add a --offline hint.
  src/cargo/ops/lockfile.rs
  tests/testsuite/lockfile_compat.rs
Labels: S-waiting-on-bors

#7657 Change the link destination of cargo book contribution
  src/doc/src/index.md
Labels: S-waiting-on-bors

#7655 Remove --offline empty index error.
  src/cargo/sources/registry/remote.rs
  tests/testsuite/offline.rs
Labels: S-waiting-on-bors

#7658 Docs: Add an appendix on git authentication.
  src/doc/src/SUMMARY.md
  src/doc/src/appendix/git-authentication.md
  src/doc/src/reference/config.md
  src/doc/src/reference/specifying-dependencies.md
Labels: S-waiting-on-bors

#7661 Fix typo in section 'Caching the Cargo home in CI'
  src/doc/src/guide/cargo-home.md
Labels: S-waiting-on-bors

#7659 Add cargo-vendor to the list of cargo commands in doc
  src/doc/man/cargo.adoc
  src/doc/man/generated/cargo.html
  src/etc/man/cargo.1
Labels: S-waiting-on-bors

#7663 document support for Bitbucket Pipelines badges
  src/doc/src/reference/manifest.md
Labels: S-waiting-on-bors

#7666 Add test for `GIT_COMMITTER_EMAIL` when `cargo new`
  tests/testsuite/new.rs
Labels: S-waiting-on-bors

#7667 Add test for `NAME` environment variable when `cargo new`
  tests/testsuite/new.rs
Labels: S-waiting-on-bors

#7672 Fix some typos in doc
  src/doc/src/appendix/git-authentication.md
  src/doc/src/guide/creating-a-new-project.md
Labels: S-waiting-on-bors

#7682 Features and dependencies can't have the same name
  src/doc/src/reference/manifest.md
Labels: S-waiting-on-bors

#7687 Update the layout of `Cargo Commands` in doc
  src/doc/src/SUMMARY.md
  src/doc/src/commands/build-commands.md
  src/doc/src/commands/cargo.md
  src/doc/src/commands/general-commands.md
  src/doc/src/commands/index.md
  src/doc/src/commands/manifest-commands.md
  src/doc/src/commands/package-commands.md
  src/doc/src/commands/publishing-commands.md
Labels: S-waiting-on-bors

#7690 Add a test for `cargo locate-project`
  tests/testsuite/locate_project.rs
  tests/testsuite/main.rs
Labels: S-waiting-on-bors

#7693 Bump cargo-platform version.
  Cargo.toml
  crates/cargo-platform/Cargo.toml
Labels: S-waiting-on-bors

#7696 fix a couple of typos
  src/bin/cargo/commands/vendor.rs
  src/cargo/core/compiler/fingerprint.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/core/resolver/conflict_cache.rs
  src/cargo/core/resolver/context.rs
  src/cargo/core/resolver/dep_cache.rs
  src/cargo/core/resolver/errors.rs
  src/cargo/core/resolver/mod.rs
  src/cargo/ops/cargo_package.rs
  src/cargo/sources/registry/mod.rs
  src/cargo/util/lockserver.rs
  src/doc/src/reference/build-scripts.md
  src/doc/src/reference/environment-variables.md
  src/doc/src/reference/profiles.md
  tests/testsuite/package.rs
  tests/testsuite/publish.rs
  tests/testsuite/tool_paths.rs
Labels: S-waiting-on-bors

#7694 Clarify manifest format docs for [badges] section
  src/doc/src/reference/manifest.md
Labels: S-waiting-on-bors

#7699 Switch build-std to use --extern
  src/cargo/core/compiler/compilation.rs
  src/cargo/core/compiler/context/mod.rs
  src/cargo/core/compiler/job_queue.rs
  src/cargo/core/compiler/layout.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/core/compiler/standard_lib.rs
  src/cargo/core/compiler/unit_dependencies.rs
  src/cargo/ops/cargo_test.rs
  tests/testsuite/standard_lib.rs
Labels: S-waiting-on-bors

#7695 Add and move tests for jobs of `cargo build`
  tests/testsuite/bad_config.rs
  tests/testsuite/build.rs
Labels: S-waiting-on-bors

#7698 Remove use of deprecated Error::description method
  src/cargo/ops/cargo_doc.rs
Labels: S-waiting-on-bors

#7710 Pass --edition after --crate-name
  src/cargo/core/compiler/compilation.rs
  src/cargo/core/compiler/mod.rs
Labels: S-waiting-on-bors

#7700 Add proc_macro to the extern prelude.
  src/cargo/core/compiler/build_context/target_info.rs
  src/cargo/core/compiler/mod.rs
  tests/testsuite/proc_macro.rs
  tests/testsuite/rustc_info_cache.rs
Labels: S-waiting-on-bors

#7716 [beta] Disable test not forwards compatible to nightly.
  tests/testsuite/pub_priv.rs
Labels: S-waiting-on-bors

#7717 Update the output of `cargo -Z help`
  src/bin/cargo/cli.rs
  tests/testsuite/cargo_command.rs
Labels: S-waiting-on-bors

#7718 vendor: support alt registries
  src/cargo/ops/vendor.rs
  tests/testsuite/vendor.rs
Labels: S-waiting-on-review

#7724 Add config tracking issue links.
  src/doc/src/reference/unstable.md
Labels: S-waiting-on-bors

#7721 Fix indentation mistake in doc comment.
  src/cargo/core/compiler/layout.rs
Labels: S-waiting-on-bors

#7737 Read cached output line-by-line
  src/cargo/core/compiler/mod.rs
Labels: S-waiting-on-bors

#7738 Use issue = "none" instead of "0"
  tests/testsuite/mock-std/src/libtest/lib.rs
Labels: S-waiting-on-bors

#7706 bump git2 dependencies
  Cargo.toml
  crates/cargo-test-support/Cargo.toml
  crates/cargo-test-support/src/git.rs
  tests/testsuite/git.rs
Labels: S-waiting-on-bors

#7739 Correct reference link
  src/cargo/core/registry.rs
  tests/testsuite/paths.rs
Labels: S-waiting-on-bors

#7749 Fix debug message.
  src/cargo/core/compiler/fingerprint.rs
Labels: S-waiting-on-bors

#7742 Add a note to the error message for using --feature / --no-default-features in a virtual workspace
  src/cargo/util/command_prelude.rs
  tests/testsuite/features.rs
Labels: S-waiting-on-bors

#7741 Add test for `cargo pkgid`
  tests/testsuite/main.rs
  tests/testsuite/pkgid.rs
Labels: S-waiting-on-bors
