Repository rust-lang/cargo, pull requests merged in 2020-07, with the labels that each got.

#8433 Update built-in help for features
  src/cargo/util/command_prelude.rs
Labels: S-waiting-on-bors

#8436 CONTRIBUTING.md: Link to Zulip rather than Discord
  CONTRIBUTING.md
Labels: S-waiting-on-bors

#8378 Exclude the target directory from backups using CACHEDIR.TAG
  src/cargo/core/compiler/layout.rs
  src/cargo/util/paths.rs
  tests/testsuite/build.rs
  tests/testsuite/clean.rs
Labels: S-waiting-on-bors, T-cargo, disposition-merge, final-comment-period

#8446 Fix overflow error on 32-bit.
  src/cargo/core/compiler/fingerprint.rs
Labels: S-waiting-on-bors

#8451 Update metadata man page.
  src/doc/man/generated/cargo-metadata.html
  src/etc/man/cargo-metadata.1
Labels: S-waiting-on-bors

#8449 Don't overwrite existing `rustdoc` args with --document-private-items
  src/cargo/ops/cargo_compile.rs
  tests/testsuite/rustdoc.rs
Labels: S-waiting-on-bors

#8453 Write GNU tar files, supporting long names.
  src/cargo/ops/cargo_package.rs
  tests/testsuite/package.rs
Labels: S-waiting-on-bors

#8454 Add support for deserializing enums in config files
  src/cargo/util/config/de.rs
  tests/testsuite/config.rs
Labels: S-waiting-on-bors

#8469 Disable long_file_names test if not supported on Windows.
  tests/testsuite/package.rs
Labels: S-waiting-on-bors

#8473 Avoid colliding with older Cargo fingerprint changes
  src/cargo/core/compiler/context/compilation_files.rs
Labels: S-waiting-on-bors

#8427 Add support for rustc's `-Z terminal-width`.
  src/bin/cargo/cli.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/core/features.rs
  src/cargo/core/shell.rs
  src/cargo/util/progress.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/build.rs
Labels: S-waiting-on-bors

#8393 Allow configuring unstable flags via config file
  src/cargo/core/compiler/rustdoc.rs
  src/cargo/core/features.rs
  src/cargo/util/config/de.rs
  src/cargo/util/config/mod.rs
  src/cargo/util/toml/mod.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/config.rs
Labels: S-waiting-on-bors

#8476 fix: add space to comments
  src/cargo/ops/cargo_new.rs
  tests/testsuite/init.rs
Labels: S-waiting-on-bors

#8488 [beta] Avoid colliding with older Cargo fingerprint changes
  src/cargo/core/compiler/context/compilation_files.rs
Labels: S-waiting-on-bors

#8489 Make `cargo metadata` output deterministic
  crates/cargo-test-support/src/lib.rs
  src/cargo/ops/cargo_output_metadata.rs
  tests/testsuite/alt_registry.rs
  tests/testsuite/metadata.rs
  tests/testsuite/update.rs
Labels: S-waiting-on-bors

#8491 Ensure `unstable.build-std` works like `-Zbuild-std`
  src/cargo/core/features.rs
  tests/testsuite/standard_lib.rs
Labels: S-waiting-on-bors

#8492 Fix self-publish script.
  publish.py
Labels: S-waiting-on-bors

#8495 clippy cleanups
  src/cargo/lib.rs
  src/cargo/sources/git/source.rs
  src/cargo/sources/git/utils.rs
  src/cargo/sources/registry/remote.rs
  src/cargo/util/paths.rs
  tests/testsuite/dep_info.rs
Labels: S-waiting-on-bors

#8490 Add a `-Zbuild-std-features` flag
  src/cargo/core/compiler/standard_lib.rs
  src/cargo/core/features.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/mock-std/src/libstd/Cargo.toml
  tests/testsuite/mock-std/src/libstd/lib.rs
  tests/testsuite/mock-std/src/libtest/Cargo.toml
  tests/testsuite/standard_lib.rs
Labels: S-waiting-on-bors

#8497 Fix freshness checks for build scripts on renamed dirs
  src/cargo/core/workspace.rs
  src/cargo/sources/path.rs
  tests/testsuite/freshness.rs
Labels: S-waiting-on-bors

#8503 [beta] Revert "Improve support for non-`master` main branches"
  src/bin/cargo/commands/install.rs
  src/cargo/core/source/source_id.rs
  src/cargo/ops/vendor.rs
  src/cargo/sources/config.rs
  src/cargo/sources/git/source.rs
  src/cargo/sources/git/utils.rs
  src/cargo/sources/registry/remote.rs
  src/cargo/util/toml/mod.rs
  src/doc/src/reference/specifying-dependencies.md
  tests/build-std/main.rs
  tests/testsuite/git.rs
Labels: S-waiting-on-review

#8500 Build host dependencies with opt-level 0 by default
  crates/cargo-test-support/src/lib.rs
  src/cargo/core/profiles.rs
  tests/testsuite/lto.rs
  tests/testsuite/profile_config.rs
  tests/testsuite/profile_targets.rs
Labels: S-waiting-on-bors, relnotes

#8494 Add back Manifest::targets_mut
  src/cargo/core/manifest.rs
Labels: S-waiting-on-bors

#8510 doc: Replace "regenerate" with "revoke" for API tokens
  src/doc/src/reference/publishing.md
Labels: S-waiting-on-bors

#8528 Fix nightly tests for intra-doc links.
  tests/testsuite/doc.rs
Labels: S-waiting-on-bors

#8485 Apply workspace.exclude to workspace.default-members.
  src/cargo/core/workspace.rs
  tests/testsuite/workspaces.rs
Labels: S-waiting-on-bors

#8508 Bump to 0.48.0, update changelog
  CHANGELOG.md
  Cargo.toml
  src/cargo/core/compiler/build_context/target_info.rs
  src/cargo/core/compiler/mod.rs
  tests/testsuite/lto.rs
  tests/testsuite/rustc_info_cache.rs
Labels: S-waiting-on-bors

#8511 Check workspace member existence as dir.
  src/cargo/core/workspace.rs
  tests/testsuite/main.rs
  tests/testsuite/member_discovery.rs
Labels: S-waiting-on-bors

#8515 Fix the help display for the target-triple option
  src/cargo/util/command_prelude.rs
Labels: S-waiting-on-bors

#8520 Flag git zlib errors as spurious errors
  src/cargo/util/network.rs
Labels: S-waiting-on-bors

#8523 Mask out system core.autocrlf settings before resetting git repos
  src/cargo/sources/git/utils.rs
  tests/testsuite/vendor.rs
Labels: S-waiting-on-bors

#8526 Remove unused CompileMode::all_modes
  src/cargo/core/compiler/build_config.rs
Labels: S-waiting-on-bors

#8529 Fix typo in docs
  src/doc/src/reference/publishing.md
Labels: S-waiting-on-bors

#8509 Stabilize -Z crate-versions
  src/bin/cargo/cli.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/core/features.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/doc.rs
  tests/testsuite/rustdoc.rs
Labels: S-waiting-on-bors

#8530 Update features set in CI.
  .github/workflows/main.yml
Labels: S-waiting-on-bors

#8534 [beta] Add back Manifest::targets_mut
  src/cargo/core/manifest.rs
Labels: S-waiting-on-review

#8535 [beta] Fix CI on beta to get a green build on Azure
  tests/build-std/main.rs
  tests/testsuite/doc.rs
Labels: S-waiting-on-review

#8543 Cargo book nitpick in Manifest section
  src/doc/src/reference/manifest.md
Labels: S-waiting-on-bors

#8540 Update termcolor and fwdansi versions
  Cargo.toml
Labels: S-waiting-on-bors

#8547 Include `+` for crates.io feature requirements in the Cargo Book section on features
  src/doc/src/reference/features.md
Labels: S-waiting-on-bors

#8522 Prepare for not defaulting to master branch for git deps
  src/cargo/core/dependency.rs
  src/cargo/core/registry.rs
  src/cargo/core/resolver/context.rs
  src/cargo/core/resolver/dep_cache.rs
  src/cargo/core/resolver/encode.rs
  src/cargo/core/resolver/mod.rs
  src/cargo/core/resolver/resolve.rs
  src/cargo/core/source/source_id.rs
  src/cargo/ops/lockfile.rs
  src/cargo/sources/git/source.rs
  src/cargo/sources/git/utils.rs
  src/cargo/sources/registry/remote.rs
  tests/testsuite/git.rs
  tests/testsuite/lockfile_compat.rs
Labels: S-waiting-on-bors

#8551 Revert Cargo Book changes for default edition
  src/doc/src/reference/manifest.md
Labels: S-waiting-on-bors

#8552 Clarify test name filter usage
  src/doc/man/cargo-test.adoc
  src/doc/man/generated/cargo-test.html
  src/etc/man/cargo-test.1
Labels: S-waiting-on-bors

#7950 Check manifest for requiring nonexistent features
  src/cargo/ops/cargo_compile.rs
  tests/testsuite/bench.rs
  tests/testsuite/features.rs
Labels: S-waiting-on-bors

#8542 Display builtin aliases with `cargo --list`
  src/bin/cargo/main.rs
  tests/testsuite/cargo_command.rs
Labels: S-waiting-on-bors

#8553 Flag git http errors as maybe spurious
  src/cargo/util/network.rs
Labels: S-waiting-on-bors

#8559 Fix sporadic lto test failures.
  tests/testsuite/lto.rs
Labels: S-waiting-on-bors

#8554 Update lock file encodings on changes
  src/cargo/core/resolver/encode.rs
  src/cargo/core/resolver/mod.rs
  src/cargo/core/resolver/resolve.rs
  src/cargo/ops/cargo_generate_lockfile.rs
  src/cargo/ops/cargo_package.rs
  src/cargo/ops/lockfile.rs
  src/cargo/ops/resolve.rs
  tests/testsuite/lockfile_compat.rs
Labels: S-waiting-on-bors

#8561 Emphasize git dependency version locking behavior.
  src/doc/src/reference/specifying-dependencies.md
Labels: S-waiting-on-bors

#8560 Fix O0 build scripts by default without `[profile.release]`
  src/cargo/core/profiles.rs
  src/doc/src/reference/profiles.md
  tests/testsuite/build.rs
Labels: S-waiting-on-bors

#8478 Emit the `test` field in cargo metadata
  src/cargo/core/manifest.rs
  src/doc/man/cargo-metadata.adoc
  src/doc/man/generated/cargo-metadata.html
  src/doc/src/reference/external-tools.md
  src/doc/src/reference/unstable.md
  src/etc/man/cargo-metadata.1
  tests/testsuite/bench.rs
  tests/testsuite/build.rs
  tests/testsuite/metabuild.rs
  tests/testsuite/metadata.rs
  tests/testsuite/read_manifest.rs
  tests/testsuite/test.rs
  tests/testsuite/unit_graph.rs
  tests/testsuite/update.rs
Labels: S-waiting-on-bors

#8569 relax deprecated diagnostic message check
  tests/testsuite/fix.rs
Labels: S-waiting-on-bors

#8566 Don't print to raw stderr in test
  tests/testsuite/build.rs
Labels: S-waiting-on-bors

#8573 Use the same index location on nightly as beta
  src/cargo/core/source/source_id.rs
Labels: S-waiting-on-bors
