Repository rust-lang/cargo, pull requests merged in 2020-01, with the labels that each got.

#7748 Fix config env vars that are prefix of another with underscore.
  src/cargo/util/config/de.rs
  src/cargo/util/config/mod.rs
  src/cargo/util/config/value.rs
  tests/testsuite/build.rs
  tests/testsuite/config.rs
Labels: S-waiting-on-bors

#7735 Fix typo.
  src/doc/src/reference/specifying-dependencies.md
Labels: S-waiting-on-bors

#7751 Check for a source defined multiple times.
  src/cargo/sources/config.rs
  tests/testsuite/bad_config.rs
Labels: S-waiting-on-bors

#7756 Remove metadata dep_kinds duplicates.
  src/cargo/ops/cargo_output_metadata.rs
  tests/testsuite/metadata.rs
Labels: S-waiting-on-bors

#7763 Fix CARGO_TARGET_triple_LINKER environment variable.
  src/cargo/core/compiler/build_context/mod.rs
  src/cargo/core/compiler/custom_build.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/util/config/mod.rs
  src/cargo/util/config/target.rs
  tests/testsuite/bad_config.rs
  tests/testsuite/cross_compile.rs
  tests/testsuite/plugins.rs
  tests/testsuite/tool_paths.rs
Labels: S-waiting-on-bors

#7758 Fix dynamic linking for Windows UWP MSVC targets
  src/cargo/core/compiler/build_context/target_info.rs
Labels: S-waiting-on-bors

#7771 Fix several needless_borrow clippy lints.
  src/bin/cargo/cli.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/util/config/de.rs
  src/cargo/util/config/mod.rs
  src/cargo/util/config/target.rs
Labels: S-waiting-on-bors

#7778 Bump crates-io
  Cargo.toml
  crates/crates-io/Cargo.toml
Labels: S-waiting-on-bors

#7779 Fix .gitignore of Cargo.lock in a subdirectory.
  src/cargo/ops/cargo_package.rs
  tests/testsuite/publish_lockfile.rs
Labels: S-waiting-on-bors

#7787 Fix tests with `url` crate update
  src/cargo/util/canonical_url.rs
Labels: S-waiting-on-bors

#7783 Some small tweaks around error in configuration
  src/cargo/util/config/de.rs
  src/cargo/util/config/mod.rs
  tests/testsuite/bad_config.rs
  tests/testsuite/config.rs
Labels: S-waiting-on-bors

#7788 Add another curl spurious network error
  src/cargo/util/network.rs
Labels: S-waiting-on-bors

#7789 Update bash completion
  src/etc/cargo.bashcomp.sh
Labels: S-waiting-on-bors

#7791 Rename `Kind`
  crates/resolver-tests/src/lib.rs
  crates/resolver-tests/tests/resolve.rs
  src/cargo/core/compiler/unit_dependencies.rs
  src/cargo/core/dependency.rs
  src/cargo/core/resolver/resolve.rs
  src/cargo/core/source/source_id.rs
  src/cargo/ops/cargo_output_metadata.rs
  src/cargo/ops/registry.rs
  src/cargo/sources/registry/mod.rs
  src/cargo/util/toml/mod.rs
Labels: S-waiting-on-bors

#7755 Make cargo-rustc crate-type-aware
  src/cargo/core/workspace.rs
Labels: S-waiting-on-bors

#7799 Consistently use em-dash in environment documentation page.
  src/doc/src/reference/environment-variables.md
Labels: S-waiting-on-bors

#7800 Add and update some doc comments.
  src/cargo/core/compiler/build_context/target_info.rs
  src/cargo/core/compiler/context/compilation_files.rs
Labels: S-waiting-on-bors

#7803 Don't assume iowait always increases on Linux
  src/cargo/util/cpu.rs
Labels: S-waiting-on-bors

#7808 fix some clippy warnings
  crates/cargo-test-support/src/lib.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/core/resolver/encode.rs
  src/cargo/ops/cargo_compile.rs
  src/cargo/ops/cargo_new.rs
  src/cargo/ops/common_for_install_and_uninstall.rs
  src/cargo/util/config/mod.rs
  src/cargo/util/cpu.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/build.rs
Labels: S-waiting-on-bors

#7814 Fix some erroneous em-dashes in man pages.
  src/doc/man/cargo-bench.adoc
  src/doc/man/cargo-test.adoc
  src/doc/man/generated/cargo-bench.html
  src/doc/man/generated/cargo-test.html
  src/etc/man/cargo-bench.1
  src/etc/man/cargo-test.1
Labels: S-waiting-on-bors

#7817 Fix doc_target test which no longer works on stable/beta.
  tests/testsuite/doc.rs
Labels: S-waiting-on-bors

#7798 Fix wrong directories in host_libdir.
  src/cargo/core/compiler/compilation.rs
Labels: S-waiting-on-bors

#7819 Fix cache replay including extra newlines.
  src/cargo/core/compiler/mod.rs
  tests/testsuite/cache_messages.rs
Labels: S-waiting-on-bors

#7826 test: allow some flexibility in check::error_from_deep_recursion's expected diagnostic.
  tests/testsuite/check.rs
Labels: S-waiting-on-bors

#7829 Store maximum queue length
  src/cargo/core/compiler/job_queue.rs
  src/cargo/util/progress.rs
Labels: S-waiting-on-bors

#7836 Polish code to clarify meaning
  src/cargo/core/compiler/context/mod.rs
Labels: S-waiting-on-bors

#7810 Support out-dir in build section of Cargo configuration file
  src/bin/cargo/commands/build.rs
  src/cargo/util/config/mod.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/out_dir.rs
Labels: S-waiting-on-bors, T-cargo, disposition-merge, finished-final-comment-period

#7844 Swap std::sync::mpsc channel with crossbeam_channel
  Cargo.toml
  src/cargo/core/compiler/job_queue.rs
Labels: S-waiting-on-bors

#7848 [beta] Revert scalable jobserver.
  src/cargo/core/compiler/context/mod.rs
  src/cargo/core/compiler/job_queue.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/core/compiler/timings.rs
  src/cargo/core/features.rs
  src/cargo/util/progress.rs
Labels: S-waiting-on-bors

#7823 Stabilize config-profile.
  src/bin/cargo/cli.rs
  src/cargo/core/features.rs
  src/cargo/core/profiles.rs
  src/doc/src/reference/config.md
  src/doc/src/reference/environment-variables.md
  src/doc/src/reference/profiles.md
  src/doc/src/reference/unstable.md
  tests/testsuite/profile_config.rs
Labels: S-waiting-on-bors, T-cargo, disposition-merge, final-comment-period

#7837 Fix using global options before an alias.
  crates/resolver-tests/tests/resolve.rs
  src/bin/cargo/cli.rs
  src/cargo/util/config/mod.rs
  tests/testsuite/cargo_alias_config.rs
  tests/testsuite/config.rs
Labels: S-waiting-on-bors
