Repository rust-lang/cargo, pull requests merged in 2020-11, with the labels that each got.

#8824 Normalize SourceID in `cargo metadata`.
  src/cargo/ops/cargo_output_metadata.rs
  tests/testsuite/git.rs
Labels: S-waiting-on-bors

#8826 Bump `anyhow` dependency to `1.0.34` in `crates-io` crate
  crates/crates-io/Cargo.toml
Labels: S-waiting-on-bors

#8828 fix: remove install command `$`, for copying friendly
  src/doc/src/getting-started/installation.md
Labels: S-waiting-on-bors

#8823 Avoid some extra downloads with new feature resolver.
  src/cargo/core/package.rs
  src/cargo/core/resolver/features.rs
  src/cargo/ops/resolve.rs
  src/cargo/ops/tree/mod.rs
  tests/testsuite/features2.rs
Labels: S-waiting-on-bors

#8818 Implement weak dependency features.
  src/bin/cargo/cli.rs
  src/cargo/core/features.rs
  src/cargo/core/resolver/dep_cache.rs
  src/cargo/core/resolver/features.rs
  src/cargo/core/summary.rs
  src/cargo/ops/cargo_compile.rs
  src/cargo/ops/tree/graph.rs
  src/cargo/sources/registry/index.rs
  src/cargo/util/toml/mod.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/main.rs
  tests/testsuite/weak_dep_features.rs
Labels: S-waiting-on-bors

#8835 Skip extracting .cargo-ok files from packages
  src/cargo/sources/registry/mod.rs
  tests/testsuite/registry.rs
Labels: S-waiting-on-bors

#8844 Avoid constructing an anyhow::Error when not necessary
  src/cargo/core/compiler/job_queue.rs
Labels: S-waiting-on-bors

#8847 Use u32/64::to/from_le_bytes instead of bit fiddling
  crates/crates-io/lib.rs
  src/cargo/core/compiler/fingerprint.rs
  src/cargo/util/hex.rs
  tests/testsuite/dep_info.rs
Labels: S-waiting-on-bors

#8837 Improve performance of almost fresh builds
  src/cargo/core/compiler/custom_build.rs
  src/cargo/core/compiler/fingerprint.rs
  src/cargo/core/compiler/job.rs
  src/cargo/core/compiler/job_queue.rs
  src/cargo/core/compiler/mod.rs
Labels: S-waiting-on-bors

#8834 Check if rust-src contains a vendor dir, and patch it in
  src/cargo/core/compiler/standard_lib.rs
  tests/testsuite/mock-std/library/test/Cargo.toml
  tests/testsuite/mock-std/library/test/src/lib.rs
  tests/testsuite/mock-std/vendor/registry-dep-only-used-by-test/Cargo.toml
  tests/testsuite/mock-std/vendor/registry-dep-only-used-by-test/src/lib.rs
  tests/testsuite/mock-std/vendor/registry-dep-using-alloc/Cargo.toml
  tests/testsuite/mock-std/vendor/registry-dep-using-alloc/src/lib.rs
  tests/testsuite/mock-std/vendor/registry-dep-using-core/Cargo.toml
  tests/testsuite/mock-std/vendor/registry-dep-using-core/src/lib.rs
  tests/testsuite/mock-std/vendor/registry-dep-using-std/Cargo.toml
  tests/testsuite/mock-std/vendor/registry-dep-using-std/src/lib.rs
  tests/testsuite/mock-std/vendor/rustc-std-workspace-alloc/Cargo.toml
  tests/testsuite/mock-std/vendor/rustc-std-workspace-core/Cargo.toml
  tests/testsuite/mock-std/vendor/rustc-std-workspace-std/Cargo.toml
  tests/testsuite/standard_lib.rs
Labels: S-waiting-on-bors

#8851 Minor typo in features.md
  src/doc/src/reference/features.md
Labels: S-waiting-on-bors

#8853 Fix publishing with optional dependencies.
  src/cargo/ops/registry.rs
  tests/testsuite/features_namespaced.rs
Labels: S-waiting-on-bors

#8857 Allow resolver="1" to explicitly use the old resolver behavior.
  src/cargo/core/resolver/types.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/features2.rs
Labels: S-waiting-on-bors

#8864 Reproducible crate builds
  src/cargo/ops/cargo_package.rs
  tests/testsuite/package.rs
Labels: S-waiting-on-bors

#8441 Finish implementation of `-Zextra-link-arg`.
  src/cargo/core/compiler/custom_build.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/core/features.rs
  src/cargo/util/config/target.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/build_script_extra_link_arg.rs
  tests/testsuite/main.rs
Labels: S-waiting-on-bors, T-cargo

#8884 Relaxes expectation of `cargo test` tests to accept test execution time
  tests/testsuite/test.rs
Labels: S-waiting-on-bors

#8869 Publish target's "doc" setting when emitting metadata
  src/cargo/core/manifest.rs
  src/doc/man/cargo-metadata.md
  src/doc/man/generated_txt/cargo-metadata.txt
  src/doc/src/commands/cargo-metadata.md
  src/etc/man/cargo-metadata.1
  tests/testsuite/bench.rs
  tests/testsuite/build.rs
  tests/testsuite/metabuild.rs
  tests/testsuite/metadata.rs
  tests/testsuite/read_manifest.rs
  tests/testsuite/test.rs
  tests/testsuite/unit_graph.rs
  tests/testsuite/update.rs
Labels: S-waiting-on-bors, T-cargo, disposition-merge, final-comment-period

#8894 Bump to 0.51.0, update changelog
  CHANGELOG.md
  Cargo.toml
  tests/testsuite/dep_info.rs
  tests/testsuite/doc.rs
  tests/testsuite/profiles.rs
  tests/testsuite/pub_priv.rs
  tests/testsuite/required_features.rs
Labels: S-waiting-on-bors

#8893 [beta] backport fix for publishing with optional dependencies.
  src/cargo/ops/registry.rs
  tests/testsuite/features_namespaced.rs
Labels: S-waiting-on-bors

#8891 Fix documentation for CARGO_PRIMARY_PACKAGE.
  src/doc/src/reference/environment-variables.md
Labels: S-waiting-on-bors

#8886 Start searching git config at new path
  src/cargo/ops/cargo_new.rs
  tests/testsuite/new.rs
Labels: S-waiting-on-bors

#8887 Add some comments to the toml code
  src/cargo/core/manifest.rs
  src/cargo/core/source/source_id.rs
  src/cargo/util/toml/mod.rs
Labels: S-waiting-on-bors

#8892 Shrink the progress bar, to give more space after it.
  src/cargo/util/progress.rs
Labels: S-waiting-on-bors

#8896 [beta] backport doc fix for CARGO_PRIMARY_PACKAGE
  src/doc/src/reference/environment-variables.md
Labels: S-waiting-on-bors

#8855 doc (book): add "Getting Started" subsection: "Essential Terminology"
  src/doc/src/appendix/glossary.md
  src/doc/src/getting-started/first-steps.md
  src/doc/src/getting-started/index.md
  src/doc/src/guide/build-cache.md
  src/doc/src/guide/cargo-home.md
  src/doc/src/guide/cargo-toml-vs-cargo-lock.md
  src/doc/src/guide/continuous-integration.md
  src/doc/src/guide/creating-a-new-project.md
  src/doc/src/guide/dependencies.md
  src/doc/src/guide/project-layout.md
  src/doc/src/guide/tests.md
  src/doc/src/guide/why-cargo-exists.md
  src/doc/src/guide/working-on-an-existing-project.md
  src/doc/src/index.md
Labels: S-waiting-on-bors

#8900 fix: we don't ignore `version` for `git`/`path` deps now
  src/doc/src/reference/specifying-dependencies.md
Labels: S-waiting-on-bors

#8907 Fix custom_target_dependency test.
  tests/testsuite/custom_target.rs
Labels: S-waiting-on-bors

#8906 Remove unnecessary trailing semicolons
  src/cargo/core/features.rs
  src/cargo/core/workspace.rs
Labels: S-waiting-on-bors

#8909 Bump miow dependency to not invalidly assume memory layout
  Cargo.toml
Labels: S-waiting-on-bors

#8911 Fix some rustdoc warnings.
  src/cargo/core/compiler/rustdoc.rs
  src/cargo/core/source/source_id.rs
  src/cargo/sources/registry/mod.rs
Labels: S-waiting-on-bors

#8908 update dependency queue to consider cost for each node
  src/cargo/core/compiler/job_queue.rs
  src/cargo/util/dependency_queue.rs
Labels: S-waiting-on-bors

#8920 Remove version from dev-dependencies to make it easier to publish.
  Cargo.toml
Labels: S-waiting-on-bors

#8921 [beta] Remove version from dev-dependencies to make it easier to publish.
  Cargo.toml
  tests/testsuite/custom_target.rs
  tests/testsuite/test.rs
Labels: S-waiting-on-bors
