Repository rust-lang/cargo, pull requests merged in 2020-06, with the labels that each got.

#8301 Disable strip_works test on macos.
  tests/testsuite/profiles.rs
Labels: S-waiting-on-bors

#8274 reset lockfile information between resolutions
  crates/cargo-test-support/src/registry.rs
  crates/resolver-tests/tests/resolve.rs
  src/cargo/core/registry.rs
  src/cargo/ops/resolve.rs
  tests/testsuite/build.rs
Labels: S-waiting-on-bors

#8297 Warn if using hash in git URL, Fixes #8241
  src/cargo/util/toml/mod.rs
  tests/testsuite/bad_config.rs
Labels: S-waiting-on-bors

#8307 Show alias in help message
  src/bin/cargo/cli.rs
Labels: S-waiting-on-bors

#8314 Use mem::take to replace with Default values
  src/cargo/core/compiler/unit_dependencies.rs
  src/cargo/core/package.rs
  src/cargo/core/summary.rs
  src/cargo/util/config/mod.rs
  src/cargo/util/profile.rs
Labels: S-waiting-on-bors

#8319 Fix an accidental raw access of field
  src/cargo/util/toml/mod.rs
  src/cargo/util/toml/targets.rs
  tests/testsuite/proc_macro.rs
Labels: S-waiting-on-bors

#8320 Require latest libgit2 to pull in bugfixes
  Cargo.toml
Labels: S-waiting-on-bors

#8324 fix clippy warnings
  crates/cargo-platform/src/error.rs
  src/cargo/core/compiler/fingerprint.rs
  src/cargo/core/compiler/rustdoc.rs
  src/cargo/core/registry.rs
  src/cargo/core/workspace.rs
  src/cargo/lib.rs
  src/cargo/ops/cargo_install.rs
  src/cargo/ops/cargo_read_manifest.rs
  src/cargo/util/flock.rs
  src/cargo/util/process_builder.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/main.rs
Labels: S-waiting-on-bors

#8329 Don't hash executable filenames on apple platforms.
  src/cargo/core/compiler/context/compilation_files.rs
  tests/testsuite/build.rs
  tests/testsuite/collisions.rs
  tests/testsuite/freshness.rs
Labels: S-waiting-on-bors

#8321 Better error message when passing in relative path to Workspace::new
  src/cargo/core/workspace.rs
Labels: S-waiting-on-bors

#8335 1.45 beta backports
  src/cargo/core/compiler/context/compilation_files.rs
  src/cargo/core/compiler/fingerprint.rs
  tests/testsuite/build.rs
  tests/testsuite/collisions.rs
  tests/testsuite/freshness.rs
Labels: S-waiting-on-bors

#8334 Nits: Remove unneeded mut and loop
  src/cargo/core/resolver/resolve.rs
  src/cargo/ops/resolve.rs
Labels: S-waiting-on-bors

#8336 Bump to 0.47.0, update changelog
  CHANGELOG.md
  Cargo.toml
Labels: S-waiting-on-bors

#8270 Add environment variables to identify the binary and crate name
  src/cargo/core/compiler/compilation.rs
  src/doc/src/reference/environment-variables.md
  tests/testsuite/build.rs
Labels: S-waiting-on-bors, T-cargo, disposition-merge, finished-final-comment-period

#8267 Support `{prefix}` and `{lowerprefix}` markers in `config.json` `dl` key
  src/cargo/sources/registry/mod.rs
  src/cargo/sources/registry/remote.rs
  src/doc/src/reference/registries.md
Labels: S-waiting-on-bors, T-cargo, disposition-merge, finished-final-comment-period

#8342 Fix tree completions.
  src/etc/_cargo
  src/etc/cargo.bashcomp.sh
Labels: S-waiting-on-bors

#8277 Default values for `readme` if not specified
  src/cargo/util/toml/mod.rs
  src/doc/src/reference/manifest.md
  tests/testsuite/metadata.rs
  tests/testsuite/read_manifest.rs
Labels: S-waiting-on-bors, T-cargo, disposition-merge, finished-final-comment-period

#8349 Some LTO fixes.
  src/cargo/core/compiler/crate_type.rs
  src/cargo/core/compiler/lto.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/core/profiles.rs
  tests/testsuite/lto.rs
Labels: S-waiting-on-bors

#8350 1.44.1 stable backports
  Cargo.toml
  src/cargo/core/compiler/context/compilation_files.rs
  tests/testsuite/build.rs
  tests/testsuite/collisions.rs
  tests/testsuite/cross_compile.rs
  tests/testsuite/freshness.rs
  tests/testsuite/plugins.rs
Labels: S-waiting-on-bors

#8353 Fix failure with missing readme.
  src/cargo/ops/registry.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/publish.rs
  tests/testsuite/read_manifest.rs
Labels: S-waiting-on-bors

#8344 Allow passing a registry index url directly to `cargo install`
  src/bin/cargo/commands/install.rs
  src/doc/man/cargo-install.adoc
  src/doc/man/generated/cargo-install.html
  src/etc/man/cargo-install.1
  tests/testsuite/install.rs
Labels: S-waiting-on-bors

#8358 Fix doctests not running with --target=HOST.
  src/cargo/core/compiler/compilation.rs
  src/cargo/ops/cargo_test.rs
  tests/testsuite/cross_compile.rs
Labels: S-waiting-on-bors

#8359 Support linker with -Zdoctest-xcompile.
  src/cargo/core/compiler/compilation.rs
  src/cargo/core/compiler/context/mod.rs
  src/cargo/ops/cargo_test.rs
  tests/testsuite/cross_compile.rs
Labels: S-waiting-on-bors

#8361 [Beta] Fix doctests not running with --target=HOST.
  src/cargo/core/compiler/compilation.rs
  src/cargo/ops/cargo_test.rs
  tests/testsuite/cross_compile.rs
Labels: S-waiting-on-bors

#8363 Cut down on data fetch from git dependencies
  src/cargo/sources/git/mod.rs
  src/cargo/sources/git/source.rs
  src/cargo/sources/git/utils.rs
  src/cargo/sources/registry/remote.rs
  tests/testsuite/git.rs
Labels: S-waiting-on-bors

#8325 Adding environment variable CARGO_PKG_LICENSE
  src/cargo/core/compiler/compilation.rs
  src/doc/src/reference/environment-variables.md
  tests/testsuite/build.rs
Labels: S-waiting-on-bors, T-cargo, disposition-merge, finished-final-comment-period, relnotes

#8386 Add missing license field.
  crates/cargo-test-support/Cargo.toml
Labels: S-waiting-on-bors

#8389 Correct mispelling of `cargo`.
  src/cargo/util/job.rs
Labels: S-waiting-on-bors

#8395 Fix order-dependent feature resolution.
  src/cargo/core/resolver/dep_cache.rs
  tests/testsuite/features.rs
Labels: S-waiting-on-bors

#8398 Fix overzealous `clean -p` for reserved names.
  src/cargo/ops/cargo_clean.rs
  tests/testsuite/clean.rs
Labels: S-waiting-on-bors

#8323 Add support for `workspace.metadata` table
  src/cargo/core/compiler/standard_lib.rs
  src/cargo/core/workspace.rs
  src/cargo/ops/cargo_output_metadata.rs
  src/cargo/util/toml/mod.rs
  src/doc/man/cargo-metadata.adoc
  src/doc/src/reference/manifest.md
  src/doc/src/reference/workspaces.md
  tests/testsuite/alt_registry.rs
  tests/testsuite/build.rs
  tests/testsuite/metadata.rs
  tests/testsuite/update.rs
Labels: S-waiting-on-bors, T-cargo, disposition-merge, finished-final-comment-period

#8391 Enable "--target-dir" in "cargo install"
  src/bin/cargo/commands/install.rs
  src/doc/man/cargo-install.adoc
  src/doc/man/generated/cargo-install.html
  src/etc/man/cargo-install.1
  tests/testsuite/install.rs
Labels: S-waiting-on-bors

#8387 Adding environment variable CARGO_PKG_LICENSE_FILE
  src/cargo/core/compiler/compilation.rs
  src/doc/src/reference/environment-variables.md
  tests/testsuite/build.rs
Labels: S-waiting-on-bors

#8364 Improve support for non-`master` main branches
  src/bin/cargo/commands/install.rs
  src/cargo/core/source/source_id.rs
  src/cargo/ops/vendor.rs
  src/cargo/sources/config.rs
  src/cargo/sources/git/source.rs
  src/cargo/sources/git/utils.rs
  src/cargo/sources/registry/remote.rs
  src/cargo/util/toml/mod.rs
  src/doc/src/reference/specifying-dependencies.md
  tests/build-std/main.rs
  tests/testsuite/git.rs
Labels: S-waiting-on-bors

#8408 Improve the description of Config.home_path
  src/cargo/util/config/mod.rs
Labels: S-waiting-on-bors

#8409 Improve git error messages a bit
  src/cargo/core/resolver/errors.rs
  src/cargo/lib.rs
  src/cargo/sources/git/utils.rs
  src/cargo/util/network.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/bad_config.rs
  tests/testsuite/cargo_features.rs
  tests/testsuite/directory.rs
  tests/testsuite/features.rs
  tests/testsuite/features2.rs
  tests/testsuite/git_auth.rs
  tests/testsuite/metabuild.rs
  tests/testsuite/offline.rs
  tests/testsuite/package.rs
  tests/testsuite/patch.rs
  tests/testsuite/profile_config.rs
  tests/testsuite/profiles.rs
  tests/testsuite/pub_priv.rs
  tests/testsuite/registry.rs
  tests/testsuite/replace.rs
  tests/testsuite/required_features.rs
  tests/testsuite/run.rs
  tests/testsuite/vendor.rs
Labels: S-waiting-on-bors

#8412 Remove unused remove_dir_all dependency
  Cargo.toml
Labels: S-waiting-on-bors

#8416 Remove unused serde_derive dependency from the crates.io crate
  crates/crates-io/Cargo.toml
Labels: S-waiting-on-bors

#8418 Expose built cdylib artifacts in the Compilation structure
  src/cargo/core/compiler/compilation.rs
  src/cargo/core/compiler/context/mod.rs
  tests/testsuite/build.rs
Labels: S-waiting-on-bors

#8419 Move string interning to util
  src/cargo/core/compiler/build_config.rs
  src/cargo/core/compiler/build_context/mod.rs
  src/cargo/core/compiler/compile_kind.rs
  src/cargo/core/compiler/fingerprint.rs
  src/cargo/core/compiler/lto.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/core/compiler/unit.rs
  src/cargo/core/compiler/unit_dependencies.rs
  src/cargo/core/compiler/unit_graph.rs
  src/cargo/core/dependency.rs
  src/cargo/core/manifest.rs
  src/cargo/core/mod.rs
  src/cargo/core/package.rs
  src/cargo/core/package_id.rs
  src/cargo/core/package_id_spec.rs
  src/cargo/core/profiles.rs
  src/cargo/core/registry.rs
  src/cargo/core/resolver/context.rs
  src/cargo/core/resolver/dep_cache.rs
  src/cargo/core/resolver/encode.rs
  src/cargo/core/resolver/features.rs
  src/cargo/core/resolver/resolve.rs
  src/cargo/core/resolver/types.rs
  src/cargo/core/summary.rs
  src/cargo/core/workspace.rs
  src/cargo/ops/cargo_clean.rs
  src/cargo/ops/cargo_output_metadata.rs
  src/cargo/ops/tree/graph.rs
  src/cargo/sources/registry/index.rs
  src/cargo/sources/registry/local.rs
  src/cargo/sources/registry/mod.rs
  src/cargo/sources/registry/remote.rs
  src/cargo/util/command_prelude.rs
  src/cargo/util/interning.rs
  src/cargo/util/mod.rs
  src/cargo/util/rustc.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/config.rs
  tests/testsuite/profile_config.rs
Labels: S-waiting-on-bors

#8421 Parse `# env-dep` directives in dep-info files
  src/cargo/core/compiler/context/compilation_files.rs
  src/cargo/core/compiler/fingerprint.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/core/compiler/output_depinfo.rs
  tests/internal.rs
  tests/testsuite/dep_info.rs
  tests/testsuite/freshness.rs
Labels: S-waiting-on-bors
