Repository rust-lang/cargo, pull requests merged in 2021-03, with the labels that each got.

#9214 Some minor code cleanup.
  src/bin/cargo/main.rs
  src/cargo/core/compiler/build_context/target_info.rs
  src/cargo/core/compiler/compilation.rs
  src/cargo/core/package.rs
  src/cargo/core/resolver/resolve.rs
  src/cargo/core/resolver/types.rs
  src/cargo/ops/cargo_new.rs
  src/cargo/ops/cargo_test.rs
  src/cargo/sources/registry/index.rs
  src/cargo/util/config/mod.rs
  src/cargo/util/process_builder.rs
  tests/testsuite/old_cargos.rs
  tests/testsuite/update.rs
Labels: S-waiting-on-bors

#9213 Minor update to registry API error messages.
  crates/crates-io/lib.rs
  src/cargo/ops/registry.rs
  tests/testsuite/owner.rs
  tests/testsuite/publish.rs
  tests/testsuite/yank.rs
Labels: S-waiting-on-bors

#9224 Update split-debuginfo docs around the default.
  src/doc/src/reference/profiles.md
Labels: S-waiting-on-bors

#9202 Correct default cargo new edition
  src/doc/src/reference/manifest.md
Labels: S-waiting-on-bors

#9225 Fix `cargo_target_empty_cfg` test with env var.
  src/cargo/util/config/mod.rs
Labels: S-waiting-on-bors

#9223 Detect changes for JSON spec targets.
  src/cargo/core/compiler/build_context/target_info.rs
  src/cargo/core/compiler/compile_kind.rs
  src/cargo/core/compiler/fingerprint.rs
  src/cargo/util/rustc.rs
  tests/testsuite/custom_target.rs
Labels: S-waiting-on-bors

#9226 Don't panic when printing JSON with non-utf8 paths
  src/bin/cargo/commands/locate_project.rs
  src/bin/cargo/commands/metadata.rs
  src/bin/cargo/commands/read_manifest.rs
  src/bin/cargo/commands/verify_project.rs
  src/cargo/core/shell.rs
  tests/testsuite/metadata.rs
Labels: S-waiting-on-bors

#9181 Forbid setting `RUSTC_BOOTSTRAP` from a build script on stable
  crates/resolver-tests/tests/resolve.rs
  src/bin/cargo/cli.rs
  src/bin/cargo/commands/logout.rs
  src/bin/cargo/main.rs
  src/cargo/core/compiler/custom_build.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/core/compiler/unit_graph.rs
  src/cargo/core/features.rs
  src/cargo/core/mod.rs
  src/cargo/ops/cargo_compile.rs
  src/cargo/ops/fix.rs
  src/cargo/util/config/mod.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/build_script_env.rs
  tests/testsuite/config.rs
  tests/testsuite/profile_config.rs
Labels: S-waiting-on-bors

#9231 Use ANSI clear-to-EOL if color is force-enabled
  src/cargo/core/shell.rs
Labels: S-waiting-on-bors

#9236 track_caller on custom assert functions
  crates/cargo-test-support/src/install.rs
  crates/cargo-test-support/src/lib.rs
  crates/resolver-tests/src/lib.rs
  tests/testsuite/bad_manifest_path.rs
  tests/testsuite/clean.rs
  tests/testsuite/config.rs
  tests/testsuite/dep_info.rs
  tests/testsuite/lockfile_compat.rs
Labels: S-waiting-on-bors

#9230 Explain `cargo install` is not for libraries
  src/cargo/ops/cargo_install.rs
  tests/testsuite/install.rs
Labels: S-waiting-on-bors

#9022 Add the path to the manifest in json output
  src/cargo/core/compiler/mod.rs
  src/cargo/util/machine_message.rs
  tests/testsuite/bench.rs
  tests/testsuite/build.rs
  tests/testsuite/doc.rs
  tests/testsuite/metabuild.rs
  tests/testsuite/test.rs
Labels: S-waiting-on-bors, T-cargo, disposition-merge, finished-final-comment-period, to-announce

#8825 Implement future incompatibility report support
  Cargo.toml
  src/bin/cargo/commands/build.rs
  src/bin/cargo/commands/check.rs
  src/bin/cargo/commands/describe_future_incompatibilities.rs
  src/bin/cargo/commands/mod.rs
  src/bin/cargo/commands/rustc.rs
  src/cargo/core/compiler/build_config.rs
  src/cargo/core/compiler/future_incompat.rs
  src/cargo/core/compiler/job_queue.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/core/features.rs
  src/cargo/util/command_prelude.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/future_incompat_report.rs
  tests/testsuite/main.rs
Labels: S-waiting-on-bors

#9229 Fix a `BorrowMut` error when stdout is closed
  src/cargo/core/compiler/job_queue.rs
Labels: S-waiting-on-bors

#9243 Document the configurable-env unstable option
  src/doc/src/reference/unstable.md
Labels: S-waiting-on-bors

#9246 Fix filter_platform to run on targets other than x86.
  tests/testsuite/metadata.rs
Labels: S-waiting-on-bors

#9247 Add documentation for JSON message_path.
  src/doc/src/reference/external-tools.md
Labels: S-waiting-on-bors

#9188 Package ID specification urls must contain a host
  src/cargo/core/package_id_spec.rs
  src/doc/man/cargo-pkgid.md
  src/doc/man/generated_txt/cargo-pkgid.txt
  src/doc/src/commands/cargo-pkgid.md
  src/etc/man/cargo-pkgid.1
  tests/testsuite/pkgid.rs
Labels: S-waiting-on-bors

#9233 Wordsmith the edition documentation a bit more
  src/doc/src/reference/manifest.md
Labels: S-waiting-on-bors

#9249 Update pkgid-spec docs.
  src/doc/src/reference/pkgid-spec.md
Labels: S-waiting-on-bors

#9255 Fix issue with filtering exclusive target dependencies.
  src/cargo/core/compiler/unit_dependencies.rs
  tests/testsuite/cfg.rs
Labels: S-waiting-on-bors

#9257 [beta] Fix issue with filtering exclusive target dependencies.
  src/cargo/core/compiler/unit_dependencies.rs
  tests/testsuite/cfg.rs
Labels: S-waiting-on-bors

#9252 Fix logic for determining prefer-dynamic for a dylib.
  src/cargo/core/compiler/mod.rs
Labels: S-waiting-on-bors

#9262 🍱 Crop favicon
  src/doc/theme/favicon.png
Labels: S-waiting-on-bors

#9264 Add `--future-incompat-report` support to `cargo test`
  src/bin/cargo/commands/test.rs
  tests/testsuite/future_incompat_report.rs
Labels: S-waiting-on-bors

#9204 Support [patch] in .cargo/config files
  src/cargo/core/features.rs
  src/cargo/core/resolver/encode.rs
  src/cargo/core/workspace.rs
  src/cargo/ops/resolve.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/patch.rs
Labels: S-waiting-on-bors

#9270 Document `-Zpatch-in-config`
  src/doc/src/reference/unstable.md
Labels: S-waiting-on-bors

#9271 Add CLI help text for patch-in-config
  src/bin/cargo/cli.rs
Labels: S-waiting-on-bors

#9276 Fix doc duplicate removal of root units.
  src/cargo/ops/cargo_compile.rs
  tests/testsuite/collisions.rs
Labels: S-waiting-on-bors

#9275 Fix --feature pkg/feat for V1 resolver for non-member.
  src/cargo/core/workspace.rs
  tests/testsuite/package_features.rs
Labels: S-waiting-on-bors

#9268 Add report if `cargo fix --edition` changes features.
  src/cargo/core/mod.rs
  src/cargo/core/resolver/features.rs
  src/cargo/core/workspace.rs
  src/cargo/ops/cargo_compile.rs
  src/cargo/ops/fix.rs
  src/cargo/ops/resolve.rs
  tests/testsuite/fix.rs
Labels: S-waiting-on-bors

#9277 [beta] 1.51 backports
  src/cargo/core/workspace.rs
  src/cargo/ops/cargo_compile.rs
  tests/testsuite/collisions.rs
  tests/testsuite/package_features.rs
Labels: S-waiting-on-bors

#9285 Fix typo in faq.md
  src/doc/src/faq.md
Labels: S-waiting-on-bors

#9279 Allow `cargo update` to operate with the --offline flag
  src/cargo/ops/cargo_generate_lockfile.rs
  tests/testsuite/offline.rs
Labels: S-waiting-on-bors

#9237 Use serde's error message option to avoid implementing `Deserialize`.
  Cargo.toml
  src/cargo/util/toml/mod.rs
  tests/testsuite/bad_config.rs
Labels: S-waiting-on-bors

#9293 Fix redundant_semicolons warning in resolver-tests.
  crates/resolver-tests/src/lib.rs
Labels: S-waiting-on-bors

#9290 Refactor feature handling, and improve error messages.
  src/bin/cargo/commands/metadata.rs
  src/bin/cargo/commands/package.rs
  src/bin/cargo/commands/publish.rs
  src/bin/cargo/commands/tree.rs
  src/cargo/core/compiler/standard_lib.rs
  src/cargo/core/resolver/context.rs
  src/cargo/core/resolver/dep_cache.rs
  src/cargo/core/resolver/features.rs
  src/cargo/core/resolver/mod.rs
  src/cargo/core/resolver/types.rs
  src/cargo/core/summary.rs
  src/cargo/core/workspace.rs
  src/cargo/ops/cargo_compile.rs
  src/cargo/ops/cargo_doc.rs
  src/cargo/ops/cargo_generate_lockfile.rs
  src/cargo/ops/cargo_output_metadata.rs
  src/cargo/ops/cargo_package.rs
  src/cargo/ops/common_for_install_and_uninstall.rs
  src/cargo/ops/fix.rs
  src/cargo/ops/registry.rs
  src/cargo/ops/resolve.rs
  src/cargo/ops/tree/graph.rs
  src/cargo/ops/tree/mod.rs
  src/cargo/util/command_prelude.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/features.rs
  tests/testsuite/features_namespaced.rs
  tests/testsuite/package_features.rs
  tests/testsuite/weak_dep_features.rs
Labels: S-waiting-on-bors

#9282 RFC 3052: Stop including authors field in manifests made by cargo new
  src/cargo/ops/cargo_new.rs
  src/doc/man/cargo-init.md
  src/doc/man/cargo-new.md
  src/doc/man/generated_txt/cargo-init.txt
  src/doc/man/generated_txt/cargo-new.txt
  src/doc/man/includes/description-new-authors.md
  src/doc/src/commands/cargo-init.md
  src/doc/src/commands/cargo-new.md
  src/doc/src/getting-started/first-steps.md
  src/doc/src/guide/cargo-toml-vs-cargo-lock.md
  src/doc/src/guide/creating-a-new-project.md
  src/doc/src/guide/dependencies.md
  src/doc/src/reference/config.md
  src/doc/src/reference/environment-variables.md
  src/doc/src/reference/manifest.md
  src/doc/src/reference/overriding-dependencies.md
  src/doc/src/reference/publishing.md
  src/doc/src/reference/registries.md
  src/etc/man/cargo-init.1
  src/etc/man/cargo-new.1
  tests/testsuite/bad_config.rs
  tests/testsuite/cargo_command.rs
  tests/testsuite/init.rs
  tests/testsuite/new.rs
  tests/testsuite/workspaces.rs
Labels: S-waiting-on-bors

#9263 Emit note when `--future-incompat-report` had nothing to report
  src/cargo/core/compiler/job_queue.rs
  tests/testsuite/future_incompat_report.rs
Labels: S-waiting-on-bors

#9299 Fix config includes not working.
  src/cargo/util/config/mod.rs
  tests/testsuite/config_include.rs
Labels: S-waiting-on-bors

#9300 Fix publication of packages with metadata and resolver
  src/cargo/util/toml/mod.rs
  tests/testsuite/package.rs
Labels: S-waiting-on-bors

#9298 Default macOS targets to `unpacked` debuginfo
  crates/cargo-test-support/src/lib.rs
  src/cargo/core/compiler/standard_lib.rs
  src/cargo/core/compiler/unit_dependencies.rs
  src/cargo/core/profiles.rs
  src/cargo/ops/cargo_compile.rs
  src/doc/src/reference/profiles.md
  tests/testsuite/profile_config.rs
Labels: S-waiting-on-bors, T-cargo, disposition-merge, final-comment-period

#9304 [beta] Fix publication of packages with metadata and resolver
  src/cargo/util/toml/mod.rs
  tests/testsuite/package.rs
Labels: S-waiting-on-bors

#9307 tests: Tolerate "exit status" in error messages
  tests/testsuite/build_script.rs
  tests/testsuite/run.rs
Labels: S-waiting-on-bors

#9309 Make the URL to the tracking issue for `--out-dir` into a link
  src/doc/man/cargo-build.md
  src/doc/man/generated_txt/cargo-build.txt
  src/doc/src/commands/cargo-build.md
  src/etc/man/cargo-build.1
Labels: S-waiting-on-bors

#9308 Bump to 0.54.0, update changelog
  CHANGELOG.md
  Cargo.toml
  tests/testsuite/message_format.rs
Labels: S-waiting-on-bors

#9313 Give one more example for the --featuers CLI
  src/doc/src/reference/features.md
Labels: S-waiting-on-bors

#9302 Add `cargo config` subcommand.
  Cargo.toml
  crates/cargo-test-support/src/lib.rs
  crates/cargo-test-support/src/publish.rs
  src/bin/cargo/commands/config.rs
  src/bin/cargo/commands/logout.rs
  src/bin/cargo/commands/mod.rs
  src/cargo/core/features.rs
  src/cargo/ops/cargo_config.rs
  src/cargo/ops/mod.rs
  src/cargo/util/config/de.rs
  src/cargo/util/config/key.rs
  src/cargo/util/config/mod.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/bad_config.rs
  tests/testsuite/cargo_config.rs
  tests/testsuite/main.rs
Labels: S-waiting-on-bors

#9316 Fix semver docs for 1.51.
  src/doc/src/reference/semver.md
Labels: S-waiting-on-bors
