Repository rust-lang/cargo, pull requests merged in 2021-09, with the labels that each got.

#9862 Swap out some outdated repo urls in documentation
  src/cargo/util/canonical_url.rs
  src/doc/src/guide/cargo-toml-vs-cargo-lock.md
  src/doc/src/guide/tests.md
  src/doc/src/guide/working-on-an-existing-project.md
  src/doc/src/reference/specifying-dependencies.md
  tests/testsuite/install.rs
Labels: S-waiting-on-bors

#9796 Make library created with `cargo new` clippy happy
  src/cargo/ops/cargo_new.rs
  tests/testsuite/init.rs
  tests/testsuite/new.rs
Labels: T-cargo, final-comment-period, disposition-merge, S-waiting-on-bors

#9808 Adding the cargo doc --examples subcommand
  src/bin/cargo/commands/doc.rs
  src/cargo/util/command_prelude.rs
  src/doc/man/cargo-doc.md
  src/doc/man/generated_txt/cargo-doc.txt
  src/doc/src/commands/cargo-doc.md
  src/etc/man/cargo-doc.1
  tests/testsuite/doc.rs
Labels: S-waiting-on-bors

#9839 Stabilize patch-in-config (and prefer config over manifest)
  src/cargo/core/features.rs
  src/cargo/core/workspace.rs
  src/doc/src/reference/config.md
  src/doc/src/reference/unstable.md
  tests/testsuite/patch.rs
Labels: relnotes, T-cargo, final-comment-period, disposition-merge, S-waiting-on-bors

#9800 Stabilize 2021 edition
  src/cargo/core/compiler/build_context/target_info.rs
  src/cargo/core/features.rs
  src/cargo/ops/fix.rs
  src/doc/man/generated_txt/cargo-init.txt
  src/doc/man/generated_txt/cargo-new.txt
  src/doc/man/includes/options-new.md
  src/doc/src/commands/cargo-init.md
  src/doc/src/commands/cargo-new.md
  src/doc/src/reference/manifest.md
  src/doc/src/reference/resolver.md
  src/doc/src/reference/unstable.md
  src/etc/man/cargo-init.1
  src/etc/man/cargo-new.1
  tests/testsuite/fix.rs
  tests/testsuite/new.rs
Labels: S-waiting-on-bors

#9850 print the full destination path when no track duplicates
  src/cargo/ops/cargo_install.rs
  tests/testsuite/install_upgrade.rs
Labels: S-waiting-on-bors

#9865 Use serde_json to generate cargo_vcs_info.json
  src/cargo/ops/cargo_package.rs
Labels: S-waiting-on-bors

#9869 Improve error message when unable to initialize git index repo
  src/cargo/sources/registry/remote.rs
Labels: S-waiting-on-bors

#9871 clarify what goes into "*-sys" crates
  src/doc/src/reference/build-scripts.md
Labels: S-waiting-on-bors

#9877 Update suggestion message on bad project name error
  src/cargo/ops/cargo_new.rs
  tests/testsuite/init.rs
  tests/testsuite/new.rs
Labels: S-waiting-on-bors

#9859 rev = "refs/pull/𑑛/head"
  src/cargo/sources/git/utils.rs
  src/doc/src/reference/specifying-dependencies.md
  tests/testsuite/git.rs
Labels: T-cargo, final-comment-period, disposition-merge, S-waiting-on-bors

#9873 Remove log output that may leak tokens
  src/cargo/ops/registry.rs
Labels: S-waiting-on-bors

#9890 Fix `cargo fix --edition` on stable.
  src/cargo/ops/fix.rs
Labels: S-waiting-on-bors

#9889 Enable strip test on macos.
  tests/testsuite/profiles.rs
Labels: S-waiting-on-bors

#9893 Enable some tests on windows.
  crates/cargo-test-support/src/tools.rs
  tests/testsuite/doc.rs
Labels: S-waiting-on-bors

#9896 config.md: fix typo
  src/doc/src/reference/config.md
Labels: S-waiting-on-bors

#9898 Fix rustc --profile=dev unstable check.
  src/cargo/util/command_prelude.rs
  tests/testsuite/profile_custom.rs
Labels: S-waiting-on-bors, beta-nominated

#9900 Bump to 0.58.0, update changelog
  CHANGELOG.md
  Cargo.toml
  tests/testsuite/tool_paths.rs
Labels: S-waiting-on-bors

#9901 [beta] Fix rustc --profile=dev unstable check.
  src/cargo/util/command_prelude.rs
  tests/testsuite/profile_custom.rs
Labels: S-waiting-on-bors

#9906 Fix warnings from better precision of `dead_code` lint
  tests/testsuite/config.rs
Labels: S-waiting-on-bors

#9905 Improve "wrong output" error.
  src/cargo/core/compiler/custom_build.rs
  tests/testsuite/build_script.rs
Labels: S-waiting-on-bors

#9903 Fix warnings when documenting with `--document-private-items`
  src/cargo/core/manifest.rs
  src/cargo/core/resolver/version_prefs.rs
  src/cargo/util/rustc.rs
Labels: S-waiting-on-bors

#9904 Add some contributor docs for debugging testsuite tests.
  src/doc/contrib/src/tests/writing.md
Labels: S-waiting-on-bors

#9911 Revert "When a dependency does not have a version, git or path, fails directly"
  src/cargo/util/toml/mod.rs
  tests/testsuite/bad_config.rs
Labels: S-waiting-on-bors

#9912 [beta] Revert "When a dependency does not have a version, git or path…
  src/cargo/util/toml/mod.rs
  tests/testsuite/bad_config.rs
  tests/testsuite/config.rs
Labels: S-waiting-on-bors

#9914 Bump Cargo's curl requirement to 7.79.0
  Cargo.toml
Labels: S-waiting-on-bors, beta-nominated

#9917 Update curl-sys
  Cargo.toml
Labels: S-waiting-on-bors

#9920 Temporarily revert curl-sys update.
  Cargo.toml
Labels: S-waiting-on-review

#9928 Remove broken link in contrib docs.
  src/doc/contrib/src/process/working-on-cargo.md
Labels: S-waiting-on-bors

#9927 Change diesel compatibility messages
  src/cargo/core/compiler/job_queue.rs
  src/cargo/ops/fix.rs
Labels: S-waiting-on-bors, beta-nominated

#9934 Differentiate tests in progress bar.
  src/cargo/core/compiler/job_queue.rs
Labels: S-waiting-on-bors

#9921 Add fetch smoke test.
  .github/workflows/main.yml
  ci/fetch-smoke-test.sh
Labels: S-waiting-on-bors

#9937 Bump curl-sys dependency
  Cargo.toml
Labels: S-waiting-on-bors

#9939 Implement example completion for zsh
  src/etc/_cargo
Labels: S-waiting-on-bors

#9933 Fix the problem that help cannot be displayed properly
  src/bin/cargo/cli.rs
  tests/testsuite/help.rs
Labels: S-waiting-on-bors

#9941 Add some clarity on the license/license-file warning.
  src/cargo/util/toml/mod.rs
Labels: S-waiting-on-bors

#9948 Doc about InstallTracker files and `install.root`
  src/doc/src/guide/cargo-home.md
  src/doc/src/reference/config.md
Labels: S-waiting-on-bors

#9866 Support path_in_vcs as part of cargo_vcs_metadata
  src/cargo/ops/cargo_package.rs
  src/doc/man/cargo-package.md
  src/doc/man/generated_txt/cargo-package.txt
  src/doc/src/commands/cargo-package.md
  src/etc/man/cargo-package.1
  tests/testsuite/package.rs
Labels: T-cargo, S-waiting-on-bors

#9945 Allow `cargo update --precise` with metadata.
  src/cargo/ops/cargo_generate_lockfile.rs
  src/cargo/sources/registry/index.rs
  tests/testsuite/update.rs
Labels: S-waiting-on-bors
