Repository rust-lang/cargo, pull requests merged in 2021-06, with the labels that each got.

#9526 Consolidate doc collision detection.
  src/cargo/core/compiler/compilation.rs
  src/cargo/core/compiler/context/mod.rs
  src/cargo/ops/cargo_compile.rs
  src/cargo/ops/cargo_doc.rs
  tests/testsuite/doc.rs
Labels: S-waiting-on-bors

#9524 Add a note about rustflags compatibility.
  src/doc/src/reference/config.md
Labels: S-waiting-on-bors

#9529 Extract common `make_dep_path` to cargo_util
  crates/cargo-test-support/src/registry.rs
  crates/cargo-util/src/lib.rs
  crates/cargo-util/src/registry.rs
  src/cargo/sources/registry/index.rs
  src/cargo/sources/registry/remote.rs
Labels: S-waiting-on-bors

#9420 Implement suggestions for unknown features in workspace
  Cargo.toml
  src/cargo/core/workspace.rs
  tests/testsuite/package_features.rs
Labels: S-waiting-on-bors

#9523 Add some validation to rustc-link-arg
  src/cargo/core/compiler/custom_build.rs
  tests/testsuite/build_script_extra_link_arg.rs
Labels: S-waiting-on-bors

#9322 Configure hosts separately from targets when --target is specified.
  src/cargo/core/compiler/build_context/target_info.rs
  src/cargo/core/features.rs
  src/cargo/util/config/mod.rs
  src/cargo/util/config/target.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/build_script.rs
Labels: S-waiting-on-bors, T-cargo, disposition-merge, final-comment-period

#9533 Replace deprecated `[replace]` references with `[patch]`
  src/cargo/core/registry.rs
  src/cargo/sources/directory.rs
  tests/testsuite/directory.rs
  tests/testsuite/paths.rs
Labels: S-waiting-on-bors

#9534 Bump mdbook version for contrib guide.
  .github/workflows/contrib.yml
Labels: S-waiting-on-bors

#9538 Update documentation for include/exclude.
  src/doc/src/reference/manifest.md
Labels: S-waiting-on-bors

#9540 Add some tracking issues to unstable docs.
  src/doc/src/reference/unstable.md
Labels: S-waiting-on-bors

#9544 Pull in semver 1.0.3 'x' fix
  Cargo.toml
Labels: S-waiting-on-bors

#9515 Add additional test for CJK progress width
  src/cargo/util/progress.rs
Labels: S-waiting-on-bors

#9546 Remove some dead code.
  src/cargo/core/compiler/fingerprint.rs
Labels: S-waiting-on-bors

#9551 Make clippy happy
  src/cargo/core/compiler/mod.rs
Labels: S-waiting-on-bors

#9552 Fix typos in command_prelude.rs
  src/cargo/util/command_prelude.rs
Labels: S-waiting-on-bors

#9556 Fix typo in gitignore docs.
  src/doc/src/reference/manifest.md
Labels: S-waiting-on-bors

#9520 Add `--prune` option for cargo-tree
  src/bin/cargo/commands/tree.rs
  src/cargo/ops/tree/mod.rs
  src/doc/man/cargo-tree.md
  src/doc/man/generated_txt/cargo-tree.txt
  src/doc/src/commands/cargo-tree.md
  src/etc/man/cargo-tree.1
  tests/testsuite/tree.rs
Labels: S-waiting-on-bors, T-cargo, disposition-merge, final-comment-period

#9547 Add a mean to mutably access the members of a workspace
  src/cargo/core/mod.rs
  src/cargo/core/workspace.rs
Labels: S-waiting-on-bors

#9522 respect user choice of lib/bin over heuristics
  src/bin/cargo/commands/init.rs
  src/cargo/ops/cargo_new.rs
  tests/testsuite/init.rs
Labels: S-waiting-on-bors

#9550 add default_run to SerializedPackage
  src/cargo/core/package.rs
  src/doc/man/cargo-metadata.md
  src/doc/man/generated_txt/cargo-metadata.txt
  src/doc/src/commands/cargo-metadata.md
  src/etc/man/cargo-metadata.1
  tests/testsuite/alt_registry.rs
  tests/testsuite/features_namespaced.rs
  tests/testsuite/git.rs
  tests/testsuite/metadata.rs
  tests/testsuite/read_manifest.rs
  tests/testsuite/update.rs
Labels: S-waiting-on-bors

#9549 Warn if an "all" target is specified, but we don't match anything
  src/cargo/ops/cargo_compile.rs
  tests/testsuite/cargo_targets.rs
Labels: S-waiting-on-bors

#9567 Update rustfix.
  Cargo.toml
  tests/testsuite/fix.rs
Labels: S-waiting-on-bors

#9566 Fix rustc/rustdoc config values to be config-relative.
  crates/cargo-test-support/src/lib.rs
  crates/cargo-test-support/src/paths.rs
  crates/cargo-test-support/src/tools.rs
  src/cargo/util/config/mod.rs
  src/cargo/util/config/path.rs
  tests/testsuite/build.rs
  tests/testsuite/cache_messages.rs
  tests/testsuite/check.rs
  tests/testsuite/fix.rs
Labels: S-waiting-on-bors

#9569 Make clippy happy
  src/cargo/ops/cargo_compile.rs
Labels: S-waiting-on-bors

#9561 Implement warning for ignored trailing arguments
  src/bin/cargo/cli.rs
  tests/testsuite/cargo_alias_config.rs
Labels: S-waiting-on-bors

#9565 Add mising documentation regarding `cargo doc`
  src/doc/man/cargo-doc.md
  src/doc/man/generated_txt/cargo-doc.txt
  src/doc/src/commands/cargo-doc.md
  src/etc/man/cargo-doc.1
Labels: S-waiting-on-bors

#9571 Change how the fix_deny_warnings_but_not_others test works
  tests/testsuite/fix.rs
Labels: S-waiting-on-bors

#9577 Fix package_default_run test.
  crates/cargo-test-support/src/lib.rs
  tests/testsuite/metabuild.rs
  tests/testsuite/metadata.rs
Labels: S-waiting-on-bors

#9568 More information for links conflicting
  src/cargo/core/resolver/errors.rs
  tests/testsuite/build_script.rs
Labels: S-waiting-on-bors

#9582 Add more details for installing git repository errors
  src/cargo/ops/common_for_install_and_uninstall.rs
  tests/testsuite/install.rs
Labels: S-waiting-on-bors

#9588 Enable support for fix --edition for 2021.
  src/cargo/core/features.rs
  src/cargo/ops/fix.rs
  tests/testsuite/fix.rs
Labels: S-waiting-on-bors

#9590 Fix typo
  src/cargo/util/toml/mod.rs
Labels: S-waiting-on-bors

#9589 Enhancements to testsuite error output.
  crates/cargo-test-support/Cargo.toml
  crates/cargo-test-support/src/compare.rs
  crates/cargo-test-support/src/diff.rs
  crates/cargo-test-support/src/lib.rs
  crates/cargo-test-support/src/publish.rs
  src/doc/contrib/src/tests/writing.md
  tests/testsuite/bad_config.rs
  tests/testsuite/bench.rs
  tests/testsuite/build.rs
  tests/testsuite/build_script.rs
  tests/testsuite/cargo_command.rs
  tests/testsuite/cargo_config.rs
  tests/testsuite/config.rs
  tests/testsuite/doc.rs
  tests/testsuite/features_namespaced.rs
  tests/testsuite/locate_project.rs
  tests/testsuite/lockfile_compat.rs
  tests/testsuite/metabuild.rs
  tests/testsuite/publish.rs
  tests/testsuite/verify_project.rs
  tests/testsuite/weak_dep_features.rs
Labels: S-waiting-on-bors

#9584 Handle "jobs = 0" case in cargo config files
  src/cargo/core/compiler/build_config.rs
  tests/testsuite/build.rs
Labels: S-waiting-on-bors

#9595 Relax doc collision error.
  src/cargo/core/compiler/context/mod.rs
  tests/testsuite/doc.rs
Labels: S-waiting-on-bors, beta-nominated

#9596 Fix dep-info files including non-local build script paths.
  src/cargo/core/compiler/output_depinfo.rs
  tests/testsuite/dep_info.rs
Labels: S-waiting-on-bors

#9597 Bump to 0.56.0, update changelog
  CHANGELOG.md
  Cargo.toml
Labels: S-waiting-on-bors

#9586 Avoid quadratic complexity when splitting output into lines
  crates/cargo-util/src/process_builder.rs
Labels: S-waiting-on-bors

#9604 Disambiguate is_symlink.
  crates/cargo-test-support/src/paths.rs
  tests/testsuite/build.rs
  tests/testsuite/clean.rs
Labels: S-waiting-on-bors

#9579 Don't allow config env to modify vars set by cargo
  src/cargo/core/compiler/compilation.rs
  tests/testsuite/cargo_env_config.rs
Labels: S-waiting-on-bors

#9602 Add a compatibility notice for diesel and the new resolver.
  src/cargo/core/compiler/job_queue.rs
  src/cargo/ops/fix.rs
Labels: S-waiting-on-bors

#9606 Updates to future-incompatible reporting.
  Cargo.toml
  src/bin/cargo/commands/report.rs
  src/cargo/core/compiler/future_incompat.rs
  src/cargo/core/compiler/job_queue.rs
  src/cargo/core/shell.rs
  tests/testsuite/future_incompat_report.rs
Labels: S-waiting-on-bors

#9563 Change `rustc-cdylib-link-arg` error to a warning.
  src/cargo/core/compiler/custom_build.rs
  src/cargo/core/compiler/mod.rs
  tests/testsuite/build_script_extra_link_arg.rs
Labels: S-waiting-on-bors, beta-nominated

#9574 Unify weak and namespaced features.
  src/cargo/core/resolver/dep_cache.rs
  src/cargo/core/resolver/features.rs
  src/cargo/core/summary.rs
  src/cargo/core/workspace.rs
  src/cargo/ops/cargo_compile.rs
  src/cargo/ops/tree/graph.rs
  tests/testsuite/features_namespaced.rs
  tests/testsuite/weak_dep_features.rs
Labels: S-waiting-on-bors, T-cargo, disposition-merge, final-comment-period

#9607 Detect incorrectly named cargo.toml
  src/cargo/ops/cargo_install.rs
  src/cargo/ops/cargo_read_manifest.rs
  src/cargo/util/important_paths.rs
  tests/testsuite/build.rs
  tests/testsuite/install.rs
Labels: S-waiting-on-bors

#9611 Beta 1.54 backports
  crates/cargo-test-support/src/paths.rs
  src/cargo/core/compiler/context/mod.rs
  src/cargo/core/compiler/custom_build.rs
  src/cargo/core/compiler/mod.rs
  tests/testsuite/build.rs
  tests/testsuite/build_script_extra_link_arg.rs
  tests/testsuite/clean.rs
  tests/testsuite/doc.rs
Labels: S-waiting-on-bors

#9620 use 'writeln' instead of appending newline character
  tests/testsuite/weak_dep_features.rs
Labels: S-waiting-on-bors

#9614 tidy some closures and iterators
  src/cargo/core/compiler/custom_build.rs
  src/cargo/core/compiler/fingerprint.rs
  src/cargo/core/compiler/job_queue.rs
  src/cargo/core/compiler/timings.rs
  src/cargo/ops/cargo_compile.rs
Labels: S-waiting-on-bors

#9615 simply 'if' block
  src/cargo/core/dependency.rs
Labels: S-waiting-on-bors

#9612 Error when packaging with git dependencies without version
  src/cargo/ops/cargo_package.rs
  src/cargo/ops/mod.rs
  src/cargo/ops/registry.rs
  tests/testsuite/package.rs
Labels: S-waiting-on-bors

#9625 Include toolchain specification in error message
  src/cargo/core/compiler/standard_lib.rs
Labels: S-waiting-on-bors

#9638 Temporarily disable future_incompat tests.
  tests/testsuite/future_incompat_report.rs
Labels: S-waiting-on-bors

#9642 Temporarily ignore 2021 edition fix.
  tests/testsuite/fix.rs
Labels: S-waiting-on-bors
