Repository rust-lang/cargo, pull requests merged in 2021-08, with the labels that each got.

#9732 Stabilize the rust-version field
  CHANGELOG.md
  src/cargo/core/features.rs
  src/cargo/util/command_prelude.rs
  src/cargo/util/toml/mod.rs
  src/doc/man/cargo-bench.md
  src/doc/man/cargo-build.md
  src/doc/man/cargo-check.md
  src/doc/man/cargo-doc.md
  src/doc/man/cargo-fix.md
  src/doc/man/cargo-run.md
  src/doc/man/cargo-rustc.md
  src/doc/man/cargo-rustdoc.md
  src/doc/man/cargo-test.md
  src/doc/man/generated_txt/cargo-bench.txt
  src/doc/man/generated_txt/cargo-build.txt
  src/doc/man/generated_txt/cargo-check.txt
  src/doc/man/generated_txt/cargo-doc.txt
  src/doc/man/generated_txt/cargo-fix.txt
  src/doc/man/generated_txt/cargo-run.txt
  src/doc/man/generated_txt/cargo-rustc.txt
  src/doc/man/generated_txt/cargo-rustdoc.txt
  src/doc/man/generated_txt/cargo-test.txt
  src/doc/man/includes/options-ignore-rust-version.md
  src/doc/src/commands/cargo-bench.md
  src/doc/src/commands/cargo-build.md
  src/doc/src/commands/cargo-check.md
  src/doc/src/commands/cargo-doc.md
  src/doc/src/commands/cargo-fix.md
  src/doc/src/commands/cargo-run.md
  src/doc/src/commands/cargo-rustc.md
  src/doc/src/commands/cargo-rustdoc.md
  src/doc/src/commands/cargo-test.md
  src/doc/src/reference/manifest.md
  src/doc/src/reference/unstable.md
  src/etc/man/cargo-bench.1
  src/etc/man/cargo-build.1
  src/etc/man/cargo-check.1
  src/etc/man/cargo-doc.1
  src/etc/man/cargo-fix.1
  src/etc/man/cargo-run.1
  src/etc/man/cargo-rustc.1
  src/etc/man/cargo-rustdoc.1
  src/etc/man/cargo-test.1
  tests/testsuite/rust_version.rs
Labels: S-waiting-on-bors, T-cargo, disposition-merge, final-comment-period, relnotes

#9763 Fix semver check for rust 1.54.0
  src/doc/src/reference/semver.md
Labels: S-waiting-on-bors

#9760 Bump to the latest jobserver dependency
  Cargo.toml
Labels: S-waiting-on-bors

#9762 Update cargo-platform to 0.1.2
  Cargo.toml
  crates/cargo-platform/Cargo.toml
  src/doc/src/reference/pkgid-spec.md
Labels: S-waiting-on-bors

#9767 Refactor fake_file() away from cargo_command tests
  crates/cargo-test-support/src/lib.rs
  tests/testsuite/cargo_command.rs
Labels: S-waiting-on-bors

#9613 collapse nested if blocks
  src/cargo/core/compiler/context/mod.rs
  src/cargo/ops/cargo_config.rs
  src/cargo/ops/cargo_install.rs
  src/cargo/sources/registry/index.rs
  src/cargo/util/config/target.rs
Labels: S-waiting-on-bors

#9617 remove useless conversions
  src/cargo/core/compiler/output_depinfo.rs
Labels: S-waiting-on-bors

#9118 Add a profile option to select the codegen backend
  src/cargo/core/compiler/mod.rs
  src/cargo/core/features.rs
  src/cargo/core/profiles.rs
  src/cargo/util/toml/mod.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/unit_graph.rs
Labels: S-waiting-on-bors

#9764 Include aliases with other commands
  src/bin/cargo/cli.rs
  src/bin/cargo/main.rs
  src/cargo/util/command_prelude.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/cargo_command.rs
Labels: S-waiting-on-bors

#9773 Deduplicate entries in cargo --list
  src/bin/cargo/cli.rs
  src/bin/cargo/main.rs
  src/cargo/util/command_prelude.rs
  tests/testsuite/cargo_command.rs
Labels: S-waiting-on-bors

#9627 Ability to specify the output name for a bin target different from the crate name
  src/cargo/core/compiler/build_context/target_info.rs
  src/cargo/core/compiler/compilation.rs
  src/cargo/core/compiler/context/compilation_files.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/core/features.rs
  src/cargo/core/manifest.rs
  src/cargo/util/toml/mod.rs
  src/cargo/util/toml/targets.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/binary_name.rs
  tests/testsuite/main.rs
Labels: S-waiting-on-bors

#9790 Fix plugin registrar change.
  tests/testsuite/cross_compile.rs
  tests/testsuite/plugins.rs
  tests/testsuite/proc_macro.rs
Labels: S-waiting-on-bors

#9789 Fix value-after-table error with profiles.
  src/cargo/util/toml/mod.rs
  tests/testsuite/config.rs
Labels: S-waiting-on-bors

#9791 Teach cargo to failfast on recursive/corecursive aliases
  crates/cargo-test-support/src/tools.rs
  src/bin/cargo/cli.rs
  tests/testsuite/cargo_alias_config.rs
  tests/testsuite/cargo_command.rs
Labels: S-waiting-on-bors

#9795 Render build-std web links as hyperlinks
  src/doc/src/reference/unstable.md
Labels: S-waiting-on-bors

#9798 Bump jobserver.
  Cargo.toml
Labels: S-waiting-on-bors

#9799 Show information about abnormal `fix` errors.
  src/cargo/ops/fix.rs
  src/cargo/util/diagnostic_server.rs
  tests/testsuite/fix.rs
Labels: S-waiting-on-bors

#9802 Support using rustbot to ping the Windows group
  triagebot.toml
Labels: S-waiting-on-bors

#9803 Show feature resolver differences for dev-dependencies.
  src/cargo/ops/fix.rs
  tests/testsuite/fix.rs
Labels: S-waiting-on-bors

#9793 Determine packages to install prior to installing
  src/cargo/ops/cargo_install.rs
  tests/testsuite/install.rs
  tests/testsuite/install_upgrade.rs
Labels: S-waiting-on-bors

#9809 Bump curl.
  Cargo.toml
Labels: S-waiting-on-bors, beta-nominated

#9774 Implement `[future-incompat-report]` config section
  src/cargo/core/compiler/job_queue.rs
  src/cargo/util/config/mod.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/config.rs
  tests/testsuite/future_incompat_report.rs
Labels: S-waiting-on-bors

#9810 [beta] Bump curl
  Cargo.toml
  src/doc/src/reference/semver.md
  tests/testsuite/cross_compile.rs
  tests/testsuite/plugins.rs
  tests/testsuite/proc_macro.rs
Labels: S-waiting-on-bors

#9813 Fix test incorrectly validating CARGO_PKG_LICENSE_FILE.
  tests/testsuite/build.rs
Labels: S-waiting-on-bors

#9814 Move `tmp` test directory.
  src/cargo/core/compiler/layout.rs
  src/cargo/util/toml/mod.rs
  src/doc/src/reference/environment-variables.md
  tests/testsuite/build.rs
Labels: S-waiting-on-bors, beta-nominated

#9824 Temporarily disable extern-html-root-url test.
  tests/testsuite/rustdoc_extern_html.rs
Labels: S-waiting-on-bors

#9771 Warning for no lib dependencies
  src/cargo/core/package.rs
  src/cargo/ops/resolve.rs
  tests/testsuite/run.rs
Labels: S-waiting-on-bors

#9792 Emit warning for migrating to unstable edition in stable channel
  src/cargo/ops/fix.rs
  src/cargo/util/diagnostic_server.rs
  tests/testsuite/fix.rs
Labels: S-waiting-on-bors

#9801 Allow crate download by checksum
  src/cargo/sources/registry/mod.rs
  src/cargo/sources/registry/remote.rs
  src/doc/src/reference/registries.md
Labels: T-cargo, final-comment-period, disposition-merge, S-waiting-on-bors

#9818 unset the FIX_ENV when executing the real rustc
  src/cargo/ops/fix.rs
  tests/testsuite/fix.rs
Labels: S-waiting-on-bors

#9830 Add documentation about third-party registries.
  src/doc/src/reference/registries.md
Labels: S-waiting-on-bors

#9819 [beta] Move `tmp` test directory.
  src/cargo/core/compiler/layout.rs
  src/cargo/util/toml/mod.rs
  src/doc/src/reference/environment-variables.md
  tests/testsuite/build.rs
  tests/testsuite/rustdoc_extern_html.rs
Labels: S-waiting-on-bors

#9831 Add some debug logging for `cargo fix`
  src/cargo/ops/fix.rs
Labels: S-waiting-on-bors

#9832 Fix typo in git-authentication.md
  src/doc/src/appendix/git-authentication.md
Labels: S-waiting-on-bors

#9821 Fix typos “a”→“an”
  src/cargo/core/compiler/job_queue.rs
  src/cargo/core/resolver/conflict_cache.rs
  src/cargo/core/resolver/mod.rs
  src/cargo/core/resolver/types.rs
  src/cargo/core/source/source_id.rs
  src/cargo/ops/tree/mod.rs
  src/cargo/sources/git/utils.rs
  src/cargo/sources/registry/index.rs
  src/cargo/util/config/mod.rs
  tests/testsuite/features_namespaced.rs
  tests/testsuite/weak_dep_features.rs
Labels: S-waiting-on-bors

#9834 Fix panic with build-std of a proc-macro.
  src/cargo/core/compiler/unit_dependencies.rs
  tests/testsuite/standard_lib.rs
Labels: S-waiting-on-bors

#9836 Add hint for cargo metadata in environment section
  src/doc/src/reference/environment-variables.md
Labels: S-waiting-on-bors

#9846 Change `cargo fix --edition` to only fix edition lints.
  src/cargo/ops/fix.rs
  tests/testsuite/fix.rs
Labels: S-waiting-on-bors
