Repository rust-lang/cargo, pull requests merged in 2021-07, with the labels that each got.

#9531 Fix `BorrowMutError` when calling `cargo doc --open`
  src/cargo/ops/cargo_doc.rs
  tests/testsuite/doc.rs
Labels: S-waiting-on-bors

#9644 Adjust error message with offline and frozen.
  src/cargo/ops/lockfile.rs
  tests/testsuite/lockfile_compat.rs
  tests/testsuite/offline.rs
Labels: S-waiting-on-bors

#9645 Handle git deleted files with dirty worktree.
  src/cargo/sources/path.rs
  tests/testsuite/package.rs
Labels: S-waiting-on-bors

#9646 Temporarily disable windows env test.
  tests/testsuite/tool_paths.rs
Labels: S-waiting-on-bors

#9647 Include the linker in the fingerprint.
  crates/cargo-test-support/src/lib.rs
  src/cargo/core/compiler/fingerprint.rs
  tests/testsuite/freshness.rs
  tests/testsuite/tool_paths.rs
Labels: S-waiting-on-bors

#9649 Adjust the edition2021 resolver diff report.
  src/cargo/core/resolver/features.rs
  src/cargo/ops/fix.rs
  tests/testsuite/fix.rs
Labels: S-waiting-on-bors

#9655 Unify cargo and rustc's error reporting
  src/cargo/core/compiler/future_incompat.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/lib.rs
  tests/testsuite/build.rs
  tests/testsuite/build_script.rs
  tests/testsuite/check.rs
  tests/testsuite/fix.rs
  tests/testsuite/install.rs
Labels: S-waiting-on-bors

#9666 Warning when using features in patch
  src/cargo/core/registry.rs
  tests/testsuite/patch.rs
Labels: S-waiting-on-bors

#9662 Unignore fix_edition_2021.
  tests/testsuite/fix.rs
Labels: S-waiting-on-bors

#9654 Update Windows env uppercase key check.
  src/cargo/util/config/mod.rs
  tests/testsuite/tool_paths.rs
Labels: S-waiting-on-bors

#9657 Update nightly failure notification.
  src/cargo/core/compiler/context/mod.rs
  src/cargo/core/features.rs
  src/cargo/lib.rs
  src/cargo/ops/registry.rs
  src/cargo/util/toml/mod.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/cargo_features.rs
  tests/testsuite/edition.rs
  tests/testsuite/metabuild.rs
  tests/testsuite/profile_config.rs
  tests/testsuite/profiles.rs
  tests/testsuite/pub_priv.rs
  tests/testsuite/publish_lockfile.rs
Labels: S-waiting-on-bors

#9658 Don't recommend filing issues on rust-lang/cargo for Cargo.toml errors.
  src/cargo/core/package.rs
Labels: S-waiting-on-bors

#9677 Serialize `cargo fix`
  src/cargo/ops/fix.rs
  tests/testsuite/fix.rs
Labels: S-waiting-on-bors

#9679 Make it easier to run testsuite with a custom toolchain.
  crates/cargo-test-support/src/lib.rs
Labels: S-waiting-on-bors

#9616 remove unnecessary 'collect'
  src/cargo/core/features.rs
Labels: S-waiting-on-bors

#9665 Spot the crate typo easily
  src/cargo/core/resolver/errors.rs
  tests/testsuite/directory.rs
  tests/testsuite/path.rs
  tests/testsuite/registry.rs
Labels: S-waiting-on-bors

#9686 When a dependency does not have a version, git or path, fails directly
  src/cargo/util/toml/mod.rs
  tests/testsuite/bad_config.rs
Labels: S-waiting-on-bors

#9639 Prefer patched versions of dependencies
  crates/resolver-tests/src/lib.rs
  src/cargo/core/resolver/dep_cache.rs
  src/cargo/core/resolver/mod.rs
  src/cargo/ops/resolve.rs
  tests/testsuite/patch.rs
Labels: S-waiting-on-bors

#9663 Add format option to `cargo tree` to print the lib_name
  src/cargo/ops/tree/format/mod.rs
  src/doc/man/cargo-tree.md
  src/doc/man/generated_txt/cargo-tree.txt
  src/doc/src/commands/cargo-tree.md
  src/etc/man/cargo-tree.1
  tests/testsuite/tree.rs
Labels: S-waiting-on-bors, T-cargo, disposition-merge, final-comment-period

#9689 Change some warnings to errors
  src/cargo/util/toml/mod.rs
  tests/testsuite/bad_config.rs
Labels: S-waiting-on-bors

#9674 Document cargo limitation w/ workspaces & configs
  src/doc/src/reference/config.md
Labels: S-waiting-on-bors

#9694 `cargo fix --edition`: extend warning when on latest edition
  src/cargo/util/diagnostic_server.rs
  tests/testsuite/fix.rs
Labels: S-waiting-on-bors

#9680 Add `d` as an alias for `doc`
  src/bin/cargo/cli.rs
  src/bin/cargo/commands/doc.rs
  src/bin/cargo/main.rs
  src/doc/src/reference/config.md
Labels: S-waiting-on-bors, T-cargo, disposition-merge, final-comment-period

#9695 Flag another curl error as possibly spurious
  src/cargo/util/network.rs
Labels: S-waiting-on-bors

#9698 Re-enable future-incompatible tests.
  tests/testsuite/future_incompat_report.rs
Labels: S-waiting-on-bors

#9675 Deduplicate compiler diagnostics.
  src/cargo/core/compiler/custom_build.rs
  src/cargo/core/compiler/job.rs
  src/cargo/core/compiler/job_queue.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/core/manifest.rs
  tests/testsuite/cache_messages.rs
  tests/testsuite/main.rs
  tests/testsuite/messages.rs
Labels: S-waiting-on-bors

#9704 docs: Fix sentence & update link for GitLab CI docs
  src/doc/src/guide/continuous-integration.md
Labels: S-waiting-on-bors

#9703 Factor version preferences into a struct
  crates/resolver-tests/src/lib.rs
  src/cargo/core/resolver/dep_cache.rs
  src/cargo/core/resolver/mod.rs
  src/cargo/core/resolver/version_prefs.rs
  src/cargo/ops/resolve.rs
Labels: S-waiting-on-bors

#9601 Inform build scripts of rustc compiler context
  src/cargo/core/compiler/build_context/target_info.rs
  src/cargo/core/compiler/custom_build.rs
  src/doc/src/reference/environment-variables.md
  tests/testsuite/build_script.rs
Labels: S-waiting-on-bors, T-cargo, disposition-merge, final-comment-period

#9685 Named profile updates
  src/bin/cargo/commands/bench.rs
  src/bin/cargo/commands/build.rs
  src/bin/cargo/commands/check.rs
  src/bin/cargo/commands/clean.rs
  src/bin/cargo/commands/doc.rs
  src/bin/cargo/commands/fix.rs
  src/bin/cargo/commands/install.rs
  src/bin/cargo/commands/run.rs
  src/bin/cargo/commands/rustc.rs
  src/bin/cargo/commands/rustdoc.rs
  src/bin/cargo/commands/test.rs
  src/cargo/core/profiles.rs
  src/cargo/util/command_prelude.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/bad_config.rs
  tests/testsuite/profile_custom.rs
Labels: S-waiting-on-bors, T-cargo, disposition-merge, final-comment-period

#9632 Display registry name instead of registry URL when possible
  src/cargo/core/compiler/rustdoc.rs
  src/cargo/core/package_id.rs
  src/cargo/core/source/source_id.rs
  src/cargo/ops/mod.rs
  src/cargo/ops/registry.rs
  src/cargo/ops/vendor.rs
  src/cargo/sources/config.rs
  src/cargo/sources/mod.rs
  src/cargo/sources/registry/mod.rs
  tests/testsuite/alt_registry.rs
  tests/testsuite/bad_config.rs
  tests/testsuite/build.rs
  tests/testsuite/cargo_features.rs
  tests/testsuite/cross_publish.rs
  tests/testsuite/directory.rs
  tests/testsuite/features_namespaced.rs
  tests/testsuite/install.rs
  tests/testsuite/install_upgrade.rs
  tests/testsuite/local_registry.rs
  tests/testsuite/offline.rs
  tests/testsuite/patch.rs
  tests/testsuite/publish.rs
  tests/testsuite/publish_lockfile.rs
  tests/testsuite/registry.rs
  tests/testsuite/replace.rs
  tests/testsuite/weak_dep_features.rs
Labels: S-waiting-on-bors

#9714 Changes rustc argument from `--force-warns` to `--force-warn`
  src/cargo/ops/fix.rs
Labels: S-waiting-on-bors

#9653 Update should_use_metadata function
  src/cargo/core/compiler/context/compilation_files.rs
  tests/testsuite/freshness.rs
Labels: S-waiting-on-bors

#9720 Weather is not nice today..
  crates/resolver-tests/tests/resolve.rs
  src/cargo/core/resolver/context.rs
Labels: S-waiting-on-bors

#9721 Refactor if let chains to matches! macro
  src/cargo/core/resolver/types.rs
Labels: S-waiting-on-bors

#9681 Warning when using features in replace
  src/cargo/ops/resolve.rs
  tests/testsuite/replace.rs
Labels: S-waiting-on-bors

#9557 Stabilize the rustc-link-arg option
  src/cargo/core/compiler/custom_build.rs
  src/cargo/core/features.rs
  src/cargo/util/config/target.rs
  src/doc/src/reference/build-scripts.md
  src/doc/src/reference/unstable.md
  tests/testsuite/build_script_extra_link_arg.rs
Labels: S-waiting-on-bors, T-cargo, disposition-merge, final-comment-period

#9723 Better msg for wrong position
  src/cargo/util/toml/mod.rs
  tests/testsuite/cargo_features.rs
Labels: S-waiting-on-bors

#9559 Allow publishing from workspace root.
  src/bin/cargo/commands/package.rs
  src/bin/cargo/commands/publish.rs
  src/cargo/ops/cargo_package.rs
  src/cargo/ops/mod.rs
  src/cargo/ops/registry.rs
  tests/testsuite/package.rs
  tests/testsuite/publish.rs
Labels: S-waiting-on-bors

#9727 Fix version string.
  src/bin/cargo/cli.rs
  tests/testsuite/version.rs
Labels: S-waiting-on-bors, beta-nominated, regression-from-stable-to-beta

#9730 doc test supports silent output
  src/cargo/ops/cargo_test.rs
  tests/testsuite/test.rs
Labels: S-waiting-on-bors

#9734 [Beta] backport version string fix
  src/bin/cargo/cli.rs
  tests/testsuite/version.rs
Labels: S-waiting-on-bors

#9737 Fix typo in features doc
  src/doc/src/reference/features.md
Labels: S-waiting-on-bors

#9736 Make clippy happy
  src/cargo/ops/cargo_package.rs
  src/cargo/ops/registry.rs
Labels: S-waiting-on-bors

#9745 Bump cargo-util version.
  Cargo.toml
  crates/cargo-util/Cargo.toml
Labels: S-waiting-on-bors

#9747 doc: Clarify [doc].browser docs, document PathAndArgs better
  src/doc/src/reference/config.md
Labels: S-waiting-on-bors

#9746 [beta] Backport cargo-util version fix
  Cargo.toml
  crates/cargo-util/Cargo.toml
Labels: S-waiting-on-bors

#9411 Stabilize `[env]` sections
  src/cargo/core/compiler/compilation.rs
  src/cargo/core/features.rs
  src/doc/src/reference/config.md
  src/doc/src/reference/unstable.md
  tests/testsuite/cargo_env_config.rs
Labels: S-waiting-on-bors, T-cargo, disposition-merge, finished-final-comment-period, relnotes, to-announce

#9748 Bump to 0.57.0, update changelog
  CHANGELOG.md
  Cargo.toml
Labels: S-waiting-on-bors

#9749 Some minor updates for package/publish package selection.
  src/bin/cargo/commands/package.rs
  src/cargo/util/command_prelude.rs
  src/doc/man/cargo-package.md
  src/doc/man/cargo-publish.md
  src/doc/man/generated_txt/cargo-package.txt
  src/doc/man/generated_txt/cargo-publish.txt
  src/doc/src/commands/cargo-package.md
  src/doc/src/commands/cargo-publish.md
  src/etc/man/cargo-package.1
  src/etc/man/cargo-publish.1
Labels: S-waiting-on-bors

#9750 Update unstable documentation TOC.
  src/doc/src/reference/unstable.md
Labels: S-waiting-on-bors

#9751 Remove nbsp characters.
  crates/mdman/doc/mdman.md
  crates/mdman/doc/out/mdman.1
  crates/mdman/doc/out/mdman.md
  crates/mdman/doc/out/mdman.txt
  src/cargo/core/compiler/timings.rs
  src/cargo/core/profiles.rs
  src/doc/contrib/src/architecture/codebase.md
  src/doc/contrib/src/architecture/packages.md
  src/doc/contrib/src/issues.md
  src/doc/src/index.md
  src/doc/src/reference/build-scripts.md
  src/doc/src/reference/environment-variables.md
  src/doc/src/reference/manifest.md
  src/doc/src/reference/profiles.md
  src/doc/src/reference/unstable.md
  tests/testsuite/features2.rs
Labels: S-waiting-on-bors
