Repository rust-lang/cargo, pull requests merged in 2021-02, with the labels that each got.

#9120 Flip 'foo' and 'bar' to be consistent
  src/doc/src/reference/specifying-dependencies.md
Labels: S-waiting-on-bors

#9121 Document -Z extra-link-arg.
  src/bin/cargo/cli.rs
Labels: S-waiting-on-bors

#9108 Impl warn for locked install without Cargo.lock
  src/cargo/ops/cargo_install.rs
  src/cargo/util/config/mod.rs
  tests/testsuite/install.rs
Labels: S-waiting-on-bors

#9122 Fix env/cfg set for `cargo test` and `cargo run`.
  src/cargo/core/compiler/compilation.rs
  src/cargo/core/compiler/context/mod.rs
  src/cargo/core/compiler/custom_build.rs
  src/cargo/core/compiler/fingerprint.rs
  src/cargo/core/compiler/job_queue.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/core/compiler/output_depinfo.rs
  src/cargo/ops/cargo_install.rs
  src/cargo/ops/cargo_run.rs
  src/cargo/ops/cargo_test.rs
  src/doc/src/reference/build-scripts.md
  tests/testsuite/build.rs
  tests/testsuite/build_script.rs
Labels: S-waiting-on-bors

#9125 Add some documentation for index and registry stuff.
  src/cargo/sources/registry/index.rs
  src/cargo/sources/registry/local.rs
  src/cargo/sources/registry/mod.rs
  src/cargo/sources/registry/remote.rs
  src/cargo/util/toml/mod.rs
Labels: S-waiting-on-bors

#9126 Add RegistryBuilder for tests, and update crates-io error handling.
  crates/cargo-test-support/src/registry.rs
  crates/crates-io/lib.rs
  tests/testsuite/alt_registry.rs
  tests/testsuite/credential_process.rs
  tests/testsuite/install_upgrade.rs
  tests/testsuite/login.rs
  tests/testsuite/logout.rs
  tests/testsuite/package.rs
  tests/testsuite/patch.rs
  tests/testsuite/publish.rs
  tests/testsuite/rename_deps.rs
  tests/testsuite/rustdoc_extern_html.rs
  tests/testsuite/vendor.rs
Labels: S-waiting-on-bors

#9129 Backport #9102 to the 1.50 release branch
  src/cargo/util/config/de.rs
Labels: S-waiting-on-bors

#9130 Backport #9102 to the 1.49 release branch
  Cargo.toml
  src/cargo/util/config/de.rs
Labels: S-waiting-on-review

#9112 Add split-debuginfo profile option
  crates/cargo-test-support/src/lib.rs
  src/bin/cargo/commands/bench.rs
  src/bin/cargo/commands/run.rs
  src/bin/cargo/commands/test.rs
  src/bin/cargo/main.rs
  src/cargo/core/compiler/build_context/target_info.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/core/profiles.rs
  src/cargo/ops/cargo_clean.rs
  src/cargo/ops/cargo_compile.rs
  src/cargo/util/errors.rs
  src/cargo/util/mod.rs
  src/cargo/util/rustc.rs
  src/cargo/util/toml/mod.rs
  src/doc/src/reference/profiles.md
  tests/testsuite/build.rs
  tests/testsuite/out_dir.rs
  tests/testsuite/profile_config.rs
  tests/testsuite/unit_graph.rs
Labels: S-waiting-on-bors

#9132 [BETA] Revert "Slightly optimize `cargo vendor`"
  src/cargo/ops/vendor.rs
Labels: S-waiting-on-bors

#9131 Fix permission issue with `cargo vendor`.
  crates/cargo-test-support/src/registry.rs
  src/cargo/ops/vendor.rs
  tests/testsuite/vendor.rs
Labels: S-waiting-on-bors

#9142 Fix panic with doc collision orphan.
  src/cargo/ops/cargo_compile.rs
  tests/testsuite/collisions.rs
Labels: S-waiting-on-bors

#9148 Fix warnings of the new non_fmt_panic lint
  crates/cargo-test-support/src/cross_compile.rs
  tests/testsuite/cargo_command.rs
  tests/testsuite/new.rs
Labels: S-waiting-on-bors

#9152 appendix auth gcm link to new repo (which is xplat)
  src/doc/src/appendix/git-authentication.md
Labels: S-waiting-on-bors

#9164 Prevent testsuite from loading config out of sandbox.
  src/bin/cargo/commands/install.rs
  src/cargo/core/workspace.rs
  src/cargo/ops/cargo_new.rs
  src/cargo/util/config/mod.rs
  src/cargo/util/important_paths.rs
  src/cargo/util/paths.rs
  tests/testsuite/config.rs
Labels: S-waiting-on-bors

#9168 Bump to 0.53.0, update changelog
  CHANGELOG.md
  Cargo.toml
Labels: S-waiting-on-bors

#8640 Implement Rustdoc versioning checks
  src/cargo/core/compiler/build_context/mod.rs
  src/cargo/core/compiler/build_context/target_info.rs
  src/cargo/core/compiler/context/mod.rs
  src/cargo/core/compiler/mod.rs
  tests/testsuite/doc.rs
Labels: S-waiting-on-bors

#9169 Emit warning on env variable case mismatch
  src/cargo/util/config/mod.rs
  tests/testsuite/tool_paths.rs
Labels: S-waiting-on-bors

#9173 Remove mention of --message-format taking multiple values
  src/doc/man/generated_txt/cargo-bench.txt
  src/doc/man/generated_txt/cargo-build.txt
  src/doc/man/generated_txt/cargo-check.txt
  src/doc/man/generated_txt/cargo-doc.txt
  src/doc/man/generated_txt/cargo-fix.txt
  src/doc/man/generated_txt/cargo-run.txt
  src/doc/man/generated_txt/cargo-rustc.txt
  src/doc/man/generated_txt/cargo-rustdoc.txt
  src/doc/man/generated_txt/cargo-test.txt
  src/doc/man/includes/options-message-format.md
  src/doc/src/commands/cargo-bench.md
  src/doc/src/commands/cargo-build.md
  src/doc/src/commands/cargo-check.md
  src/doc/src/commands/cargo-doc.md
  src/doc/src/commands/cargo-fix.md
  src/doc/src/commands/cargo-run.md
  src/doc/src/commands/cargo-rustc.md
  src/doc/src/commands/cargo-rustdoc.md
  src/doc/src/commands/cargo-test.md
  src/etc/man/cargo-bench.1
  src/etc/man/cargo-build.1
  src/etc/man/cargo-check.1
  src/etc/man/cargo-doc.1
  src/etc/man/cargo-fix.1
  src/etc/man/cargo-run.1
  src/etc/man/cargo-rustc.1
  src/etc/man/cargo-rustdoc.1
  src/etc/man/cargo-test.1
Labels: S-waiting-on-bors

#9174 Update link for no_std attribute.
  src/doc/src/reference/features-examples.md
  src/doc/src/reference/features.md
  src/doc/src/reference/semver.md
Labels: S-waiting-on-bors

#9183 refactor: make deref intentions more straightforward
  src/cargo/core/manifest.rs
  src/cargo/core/source/mod.rs
  src/cargo/ops/lockfile.rs
  src/cargo/ops/vendor.rs
Labels: S-waiting-on-bors

#9182 Propagate `lto=off` harder
  src/cargo/core/compiler/lto.rs
  src/cargo/core/compiler/mod.rs
  tests/testsuite/lto.rs
Labels: S-waiting-on-bors

#9185 Do not exit prematurely if anything failed installing.
  src/cargo/ops/cargo_install.rs
  tests/testsuite/install.rs
Labels: S-waiting-on-bors

#9189 Document the default location where cargo install emitting build artifacts
  src/doc/man/cargo-install.md
  src/doc/man/generated_txt/cargo-install.txt
  src/doc/man/includes/options-target-dir.md
  src/doc/src/commands/cargo-bench.md
  src/doc/src/commands/cargo-build.md
  src/doc/src/commands/cargo-check.md
  src/doc/src/commands/cargo-clean.md
  src/doc/src/commands/cargo-doc.md
  src/doc/src/commands/cargo-fix.md
  src/doc/src/commands/cargo-install.md
  src/doc/src/commands/cargo-package.md
  src/doc/src/commands/cargo-publish.md
  src/doc/src/commands/cargo-run.md
  src/doc/src/commands/cargo-rustc.md
  src/doc/src/commands/cargo-rustdoc.md
  src/doc/src/commands/cargo-test.md
  src/etc/man/cargo-bench.1
  src/etc/man/cargo-build.1
  src/etc/man/cargo-check.1
  src/etc/man/cargo-clean.1
  src/etc/man/cargo-doc.1
  src/etc/man/cargo-fix.1
  src/etc/man/cargo-install.1
  src/etc/man/cargo-package.1
  src/etc/man/cargo-publish.1
  src/etc/man/cargo-run.1
  src/etc/man/cargo-rustc.1
  src/etc/man/cargo-rustdoc.1
  src/etc/man/cargo-test.1
Labels: S-waiting-on-bors

#9161 Add schema field and `features2` to the index.
  crates/cargo-test-support/src/registry.rs
  crates/crates-io/lib.rs
  src/cargo/core/summary.rs
  src/cargo/ops/registry.rs
  src/cargo/sources/registry/index.rs
  src/cargo/sources/registry/mod.rs
  tests/testsuite/features_namespaced.rs
  tests/testsuite/main.rs
  tests/testsuite/old_cargos.rs
  tests/testsuite/registry.rs
  tests/testsuite/weak_dep_features.rs
Labels: S-waiting-on-bors

#9196 [beta] backports for 1.51
  crates/cargo-test-support/src/cross_compile.rs
  crates/cargo-test-support/src/registry.rs
  crates/crates-io/lib.rs
  src/cargo/ops/cargo_compile.rs
  src/cargo/ops/cargo_install.rs
  src/cargo/ops/registry.rs
  src/cargo/sources/registry/index.rs
  src/cargo/sources/registry/mod.rs
  tests/testsuite/cargo_command.rs
  tests/testsuite/collisions.rs
  tests/testsuite/install.rs
  tests/testsuite/new.rs
  tests/testsuite/registry.rs
Labels: S-waiting-on-bors

#9175 Add support for [env] section in .cargo/config.toml
  src/cargo/core/compiler/compilation.rs
  src/cargo/core/features.rs
  src/cargo/util/config/mod.rs
  tests/testsuite/cargo_env_config.rs
  tests/testsuite/main.rs
Labels: S-waiting-on-bors

#9105 Run rustdoc doctests relative to the workspace
  src/cargo/core/compiler/fingerprint.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/core/features.rs
  src/cargo/ops/cargo_test.rs
  src/cargo/util/mod.rs
  src/cargo/util/workspace.rs
  tests/testsuite/build_script.rs
  tests/testsuite/cross_compile.rs
  tests/testsuite/doc.rs
  tests/testsuite/lto.rs
  tests/testsuite/rename_deps.rs
  tests/testsuite/test.rs
Labels: S-waiting-on-bors

#9002 Add --cfg and --rustc-cfg flags to output compiler configuration
  src/bin/cargo/commands/rustc.rs
  src/cargo/ops/cargo_compile.rs
  src/cargo/ops/mod.rs
  src/cargo/util/command_prelude.rs
  tests/testsuite/rustc.rs
Labels: S-waiting-on-bors

#9184 Updates to edition handling.
  crates/cargo-test-support/src/lib.rs
  src/bin/cargo/commands/fix.rs
  src/cargo/core/compiler/compilation.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/core/features.rs
  src/cargo/core/workspace.rs
  src/cargo/ops/cargo_new.rs
  src/cargo/ops/fix.rs
  src/cargo/util/command_prelude.rs
  src/cargo/util/diagnostic_server.rs
  src/cargo/util/toml/mod.rs
  src/doc/man/cargo-fix.md
  src/doc/man/generated_txt/cargo-fix.txt
  src/doc/src/commands/cargo-fix.md
  src/doc/src/reference/unstable.md
  src/etc/man/cargo-fix.1
  tests/testsuite/edition.rs
  tests/testsuite/features2.rs
  tests/testsuite/fix.rs
  tests/testsuite/glob_targets.rs
Labels: S-waiting-on-bors

#9195 Make it more clear which module is being tested when running cargo test
  src/cargo/ops/cargo_test.rs
  tests/testsuite/bench.rs
  tests/testsuite/cross_compile.rs
  tests/testsuite/freshness.rs
  tests/testsuite/git.rs
  tests/testsuite/path.rs
  tests/testsuite/required_features.rs
  tests/testsuite/test.rs
Labels: S-waiting-on-bors, T-cargo, disposition-merge, final-comment-period

#9201 Fix hang on broken stderr.
  src/cargo/core/compiler/job_queue.rs
  tests/testsuite/build.rs
Labels: S-waiting-on-bors

#9203 Fix test target_in_environment_contains_lower_case
  tests/testsuite/tool_paths.rs
Labels: S-waiting-on-bors

#9128 Pass the error message format to rustdoc
  src/cargo/core/compiler/context/mod.rs
  tests/testsuite/message_format.rs
Labels: S-waiting-on-bors

#9206 testsuite: Improve performance when using rustup.
  crates/cargo-test-support/src/lib.rs
  tests/testsuite/old_cargos.rs
Labels: S-waiting-on-bors

#9207 testsuite: Use split debuginfo on macos.
  crates/cargo-test-support/src/lib.rs
  tests/testsuite/build.rs
  tests/testsuite/lto.rs
Labels: S-waiting-on-bors

#8939 Throw error if CARGO_TARGET_DIR is an empty string
  src/cargo/util/config/mod.rs
  src/cargo/util/config/path.rs
  tests/testsuite/config.rs
Labels: S-waiting-on-bors

#9209 Update SPDX version in docs.
  src/doc/src/reference/manifest.md
Labels: S-waiting-on-bors

#9212 doc: Fix spelling worksapce->workspace
  src/bin/cargo/commands/install.rs
  src/doc/src/guide/build-cache.md
Labels: S-waiting-on-bors
