Repository rust-lang/cargo, pull requests merged in 2022-10, with the labels that each got.

#11168 Remove lingering unstable flag `-Zfeatures`
  src/cargo/core/features.rs
Labels: S-waiting-on-bors

#11172 Provide a better error message when mixing dep: with /
  src/cargo/core/summary.rs
  tests/testsuite/features_namespaced.rs
Labels: S-waiting-on-bors

#11185 doc(features2): polish docs a bit
  src/cargo/core/resolver/features.rs
Labels: S-waiting-on-bors

#11177 Fix sparse registry lockfile urls containing 'registry+sparse+'
  src/cargo/core/source/source_id.rs
  tests/testsuite/alt_registry.rs
Labels: S-waiting-on-bors

#11190 fix(test): Distinguish 'testname' from escaped arguments
  src/bin/cargo/commands/bench.rs
  src/bin/cargo/commands/test.rs
  tests/testsuite/test.rs
Labels: S-waiting-on-bors

#11069 Add retry support to sparse registries
  crates/cargo-test-support/src/registry.rs
  src/cargo/core/package.rs
  src/cargo/ops/registry.rs
  src/cargo/sources/registry/http_remote.rs
  src/cargo/util/errors.rs
  src/cargo/util/mod.rs
  src/cargo/util/network.rs
  tests/testsuite/publish.rs
  tests/testsuite/registry.rs
  tests/testsuite/search.rs
Labels: S-waiting-on-bors, Z-sparse-registry

#11145 Check empty input for login
  src/cargo/ops/registry.rs
  tests/testsuite/login.rs
Labels: T-cargo, finished-final-comment-period, disposition-merge, S-waiting-on-bors, to-announce

#11193 Use correct version of cargo in test
  tests/testsuite/cargo_remove/offline/mod.rs
Labels: S-waiting-on-bors

#10907 Implement RFC 3289: source replacement ambiguity
  crates/cargo-test-support/src/lib.rs
  crates/cargo-test-support/src/registry.rs
  src/bin/cargo/commands/add.rs
  src/cargo/core/compiler/rustdoc.rs
  src/cargo/core/package_id.rs
  src/cargo/core/source/source_id.rs
  src/cargo/ops/registry.rs
  src/cargo/ops/tree/format/mod.rs
  src/cargo/ops/vendor.rs
  src/cargo/sources/config.rs
  src/cargo/sources/registry/mod.rs
  src/cargo/util/command_prelude.rs
  src/doc/src/reference/config.md
  src/doc/src/reference/source-replacement.md
  tests/testsuite/alt_registry.rs
  tests/testsuite/artifact_dep.rs
  tests/testsuite/bad_config.rs
  tests/testsuite/cargo_features.rs
  tests/testsuite/credential_process.rs
  tests/testsuite/cross_publish.rs
  tests/testsuite/features_namespaced.rs
  tests/testsuite/inheritable_workspace_fields.rs
  tests/testsuite/login.rs
  tests/testsuite/logout.rs
  tests/testsuite/main.rs
  tests/testsuite/owner.rs
  tests/testsuite/publish.rs
  tests/testsuite/registry.rs
  tests/testsuite/search.rs
  tests/testsuite/source_replacement.rs
  tests/testsuite/weak_dep_features.rs
  tests/testsuite/yank.rs
Labels: T-cargo, finished-final-comment-period, disposition-merge, S-waiting-on-bors, to-announce

#11197 Use `#[default]` when possible
  src/cargo/core/compiler/fingerprint.rs
  src/cargo/core/resolver/resolve.rs
  src/cargo/util/config/mod.rs
Labels: S-waiting-on-bors

#11077 Config file loaded via CLI takes priority over env vars
  src/cargo/util/config/de.rs
  src/cargo/util/config/mod.rs
  src/cargo/util/config/value.rs
  tests/testsuite/config_cli.rs
  tests/testsuite/config_include.rs
Labels: A-configuration, S-waiting-on-bors, A-config-cli

#11204 Add completions for `cargo remove`
  src/etc/_cargo
  src/etc/cargo.bashcomp.sh
Labels: S-waiting-on-bors

#11208 docs: fix
  src/doc/src/guide/tests.md
Labels: S-waiting-on-bors

#11207 Add more doc comments for three modules
  src/cargo/core/compiler/unit_dependencies.rs
  src/cargo/ops/cargo_compile.rs
  src/cargo/util/profile.rs
Labels: S-waiting-on-bors

#11215 Add configuration option for controlling crates.io protocol
  src/cargo/core/source/source_id.rs
  src/cargo/sources/config.rs
  tests/testsuite/registry.rs
Labels: S-waiting-on-bors

#11210 refactor(tests): Prepare for wait-for-publish test changes
  tests/testsuite/publish.rs
Labels: S-waiting-on-bors

#11221 Fix rustdoc warning about unclosed HTML tag
  src/cargo/util/toml/mod.rs
Labels: S-waiting-on-bors

#11184 refactor: New variant `FeaturesFor::ArtifactDep`
  src/cargo/core/compiler/standard_lib.rs
  src/cargo/core/resolver/features.rs
  src/cargo/ops/cargo_compile.rs
  src/cargo/ops/tree/graph.rs
Labels: S-waiting-on-bors

#11205 Fix deadlock when build scripts are waiting for input on stdin
  crates/cargo-util/Cargo.toml
  crates/cargo-util/src/process_builder.rs
  tests/testsuite/build_script.rs
Labels: S-waiting-on-bors

#11209 Add new SourceKind::SparseRegistry to differentiate sparse registries
  src/cargo/core/source/source_id.rs
  src/cargo/sources/registry/http_remote.rs
  src/cargo/sources/registry/mod.rs
  tests/testsuite/registry.rs
Labels: S-waiting-on-bors

#11216 refactor(publish): Clarify which SourceId is being used
  src/cargo/ops/registry.rs
Labels: S-waiting-on-bors

#11219 doc(profiles): add module level doc
  src/cargo/core/profiles.rs
Labels: S-waiting-on-bors

#11231 Add missing edition
  src/doc/src/reference/build-script-examples.md
Labels: S-waiting-on-bors

#11230 feat(publish): Support 'publish.timeout' config behind '-Zpublish-timeout'
  crates/cargo-test-support/src/compare.rs
  src/cargo/core/features.rs
  src/cargo/ops/registry.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/publish.rs
Labels: S-waiting-on-bors

#11235 chore: Update tests for latest clap
  Cargo.toml
  tests/testsuite/metadata.rs
  tests/testsuite/new.rs
Labels: S-waiting-on-bors

#11170 Differentiate the warning when an alias (built-in or user-defined) shadows an external subcommand
  src/bin/cargo/cli.rs
  tests/testsuite/cargo_alias_config.rs
Labels: S-waiting-on-bors

#11239 fix: Update help headings to match clap
  src/bin/cargo/commands/add.rs
  src/bin/cargo/commands/remove.rs
Labels: S-waiting-on-bors

#11227 Document `cargo remove`
  src/bin/cargo/cli.rs
  src/doc/man/cargo-add.md
  src/doc/man/cargo-remove.md
  src/doc/man/generated_txt/cargo-add.txt
  src/doc/man/generated_txt/cargo-remove.txt
  src/doc/src/SUMMARY.md
  src/doc/src/commands/cargo-add.md
  src/doc/src/commands/cargo-remove.md
  src/doc/src/commands/manifest-commands.md
  src/etc/man/cargo-add.1
  src/etc/man/cargo-remove.1
Labels: S-waiting-on-bors

#11240 docs(add): Add missing flags to reference
  src/doc/man/cargo-add.md
  src/doc/man/generated_txt/cargo-add.txt
  src/doc/src/commands/cargo-add.md
  src/etc/man/cargo-add.1
Labels: S-waiting-on-bors

#11247 Remove sparse+ prefix for index.crates.io
  src/cargo/sources/registry/mod.rs
Labels: S-waiting-on-bors

#11241 Polish docs for module `build_context`
  src/cargo/core/compiler/build_context/mod.rs
  src/cargo/core/compiler/build_context/target_info.rs
Labels: S-waiting-on-bors

#11243 Some tiny refactors around `ops::cargo_compile`
  src/cargo/ops/cargo_compile/compile_filter.rs
  src/cargo/ops/cargo_compile/mod.rs
  src/cargo/ops/cargo_compile/packages.rs
  src/cargo/ops/cargo_package.rs
  src/cargo/ops/common_for_install_and_uninstall.rs
  src/cargo/util/command_prelude.rs
Labels: S-waiting-on-bors

#11258 Fix typo
  src/doc/src/reference/publishing.md
Labels: S-waiting-on-bors

#11255 fix(publish): Check remote git registry more than once post-publish
  src/cargo/sources/registry/remote.rs
Labels: S-waiting-on-bors

#11268 Fix publishing with a dependency on a sparse registry
  src/cargo/util/toml/mod.rs
  tests/testsuite/alt_registry.rs
Labels: S-waiting-on-bors

#11273 fix: Remove leading newline in vendor output
  Cargo.toml
  benches/capture/Cargo.toml
  crates/cargo-test-support/Cargo.toml
  tests/testsuite/vendor.rs
Labels: S-waiting-on-bors

#11278 Add test for deleted index entry
  src/cargo/sources/registry/index.rs
  tests/testsuite/registry.rs
Labels: S-waiting-on-bors

#11280 Improve the error message if `publish` is `false` or empty list
  src/cargo/ops/registry.rs
  tests/testsuite/publish.rs
Labels: S-waiting-on-bors

#11282 doc(cargo-tree): mention it considering feature unification
  src/doc/man/cargo-tree.md
  src/doc/man/generated_txt/cargo-tree.txt
  src/doc/src/commands/cargo-tree.md
  src/etc/man/cargo-tree.1
Labels: S-waiting-on-bors

#11281 Fix inequality in "stale mtime" log messages
  src/cargo/core/compiler/fingerprint.rs
Labels: S-waiting-on-bors

#11286 Fix 410 gone response handling
  src/cargo/sources/registry/http_remote.rs
Labels: S-waiting-on-bors

#11283 Fix confusing error messages when using -Zsparse-registry
  src/cargo/core/source/source_id.rs
  src/cargo/sources/replaced.rs
  tests/testsuite/publish.rs
Labels: S-waiting-on-bors

#11293 Migrate from highfive to triagebot
  triagebot.toml
Labels: S-waiting-on-bors

#11294 Update contrib docs for highfive transition
  src/doc/contrib/src/process/index.md
  src/doc/contrib/src/process/working-on-cargo.md
Labels: S-waiting-on-bors

#11292 Add Accept-Encoding request header to enable compression
  src/cargo/ops/registry.rs
Labels: S-waiting-on-bors

#11062 fix(publish): Block until it is in index
  src/cargo/ops/registry.rs
  tests/testsuite/artifact_dep.rs
  tests/testsuite/credential_process.rs
  tests/testsuite/cross_publish.rs
  tests/testsuite/features_namespaced.rs
  tests/testsuite/publish.rs
  tests/testsuite/source_replacement.rs
  tests/testsuite/weak_dep_features.rs
Labels: Command-publish, T-cargo, final-comment-period, disposition-merge, S-waiting-on-bors

#11300 Fix singular verb in tests page
  src/doc/src/guide/tests.md
Labels: S-waiting-on-bors

#11183 artifact deps shoud works when target field specified coexists with `optional = true`
  src/cargo/core/compiler/unit_dependencies.rs
  src/cargo/core/resolver/features.rs
  src/cargo/ops/tree/graph.rs
  tests/testsuite/artifact_dep.rs
Labels: S-waiting-on-bors

#11307 Update libcurl
  Cargo.toml
  src/cargo/ops/registry.rs
Labels: S-waiting-on-bors

#10989 add a note that some warnings (and/or errors) can be auto-fixed
  src/cargo/core/compiler/job_queue.rs
  src/cargo/core/compiler/mod.rs
  tests/testsuite/check.rs
  tests/testsuite/install.rs
Labels: S-waiting-on-bors
