Repository rust-lang/cargo, pull requests merged in 2022-01, with the labels that each got.

#10244 Fix typo: substract -> subtract
  src/bin/cargo/cli.rs
Labels: S-waiting-on-bors

#10248 Update docs for windows ssh-agent.
  src/doc/src/appendix/git-authentication.md
Labels: S-waiting-on-bors

#10088 Stabilize the `strip` profile option, now that rustc has stable `-C strip`
  src/cargo/core/compiler/mod.rs
  src/cargo/core/features.rs
  src/cargo/util/toml/mod.rs
  src/doc/src/reference/profiles.md
  src/doc/src/reference/unstable.md
  tests/testsuite/profiles.rs
Labels: relnotes, T-cargo, final-comment-period, disposition-merge, S-waiting-on-bors

#10218 The first version of pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: T-cargo, finished-final-comment-period, disposition-merge, S-waiting-on-bors

#10254 Make rmeta_required no longer depend on whether timing is enabled
  src/cargo/core/compiler/context/mod.rs
Labels: S-waiting-on-bors

#10258 Remove the option to disable pipelining
  src/cargo/core/compiler/context/mod.rs
  src/cargo/core/compiler/job_queue.rs
  src/cargo/util/config/mod.rs
  src/doc/src/reference/config.md
  src/doc/src/reference/environment-variables.md
  tests/testsuite/build.rs
Labels: S-waiting-on-bors

#10214 Be resilient to most IO error and filesystem loop while walking dirs
  src/cargo/sources/path.rs
  tests/testsuite/build.rs
  tests/testsuite/build_script.rs
  tests/testsuite/package.rs
Labels: S-waiting-on-bors

#10267 Make bors ignore the PR template so it doesn't end up in merge messages
  .github/PULL_REQUEST_TEMPLATE.md
Labels: S-waiting-on-bors

#10217 feat: support rustflags per profile
  src/cargo/core/compiler/mod.rs
  src/cargo/core/features.rs
  src/cargo/core/profiles.rs
  src/cargo/ops/cargo_compile.rs
  src/cargo/util/toml/mod.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/config.rs
  tests/testsuite/profiles.rs
Labels: T-cargo, final-comment-period, disposition-merge, S-waiting-on-bors

#10265 Port cargo to clap3
  Cargo.toml
  src/bin/cargo/cli.rs
  src/bin/cargo/commands/bench.rs
  src/bin/cargo/commands/build.rs
  src/bin/cargo/commands/check.rs
  src/bin/cargo/commands/clean.rs
  src/bin/cargo/commands/config.rs
  src/bin/cargo/commands/doc.rs
  src/bin/cargo/commands/fetch.rs
  src/bin/cargo/commands/fix.rs
  src/bin/cargo/commands/generate_lockfile.rs
  src/bin/cargo/commands/git_checkout.rs
  src/bin/cargo/commands/init.rs
  src/bin/cargo/commands/install.rs
  src/bin/cargo/commands/locate_project.rs
  src/bin/cargo/commands/login.rs
  src/bin/cargo/commands/logout.rs
  src/bin/cargo/commands/metadata.rs
  src/bin/cargo/commands/mod.rs
  src/bin/cargo/commands/new.rs
  src/bin/cargo/commands/owner.rs
  src/bin/cargo/commands/package.rs
  src/bin/cargo/commands/pkgid.rs
  src/bin/cargo/commands/publish.rs
  src/bin/cargo/commands/read_manifest.rs
  src/bin/cargo/commands/report.rs
  src/bin/cargo/commands/run.rs
  src/bin/cargo/commands/rustc.rs
  src/bin/cargo/commands/rustdoc.rs
  src/bin/cargo/commands/search.rs
  src/bin/cargo/commands/test.rs
  src/bin/cargo/commands/tree.rs
  src/bin/cargo/commands/uninstall.rs
  src/bin/cargo/commands/update.rs
  src/bin/cargo/commands/vendor.rs
  src/bin/cargo/commands/verify_project.rs
  src/bin/cargo/commands/version.rs
  src/bin/cargo/commands/yank.rs
  src/bin/cargo/main.rs
  src/cargo/lib.rs
  src/cargo/util/command_prelude.rs
  src/cargo/util/errors.rs
  tests/testsuite/cargo_config.rs
  tests/testsuite/metadata.rs
  tests/testsuite/new.rs
  tests/testsuite/run.rs
  tests/testsuite/rustc.rs
Labels: S-waiting-on-bors

#10269 Stabilize namespaced and weak dependency features.
  Cargo.toml
  crates/crates-io/Cargo.toml
  crates/crates-io/lib.rs
  src/bin/cargo/commands/read_manifest.rs
  src/cargo/core/features.rs
  src/cargo/core/package.rs
  src/cargo/core/resolver/features.rs
  src/cargo/core/summary.rs
  src/cargo/ops/cargo_output_metadata.rs
  src/cargo/ops/registry.rs
  src/cargo/sources/registry/index.rs
  src/cargo/util/toml/mod.rs
  src/doc/src/reference/features.md
  src/doc/src/reference/registries.md
  src/doc/src/reference/unstable.md
  tests/testsuite/features.rs
  tests/testsuite/features_namespaced.rs
  tests/testsuite/old_cargos.rs
  tests/testsuite/weak_dep_features.rs
Labels: T-cargo, final-comment-period, disposition-merge, S-waiting-on-bors

#10286 [Beta] backport "Be resilient to most IO error and filesystem loop while walking dirs"
  src/cargo/sources/path.rs
  tests/testsuite/build.rs
  tests/testsuite/build_script.rs
  tests/testsuite/package.rs
Labels: S-waiting-on-bors

#10290 Use `is_symlink()` method
  crates/cargo-test-support/src/paths.rs
  crates/cargo-util/src/paths.rs
  tests/testsuite/build.rs
  tests/testsuite/clean.rs
Labels: S-waiting-on-bors

#10287 Add `run-fail` to semver-check for docs
  src/doc/semver-check/src/main.rs
Labels: S-waiting-on-bors

#10291 use new cargo fmt option
  .github/workflows/main.yml
Labels: S-waiting-on-bors

#10294 Bump to 0.61.0, update changelog
  CHANGELOG.md
  Cargo.toml
  tests/testsuite/profiles.rs
Labels: S-waiting-on-bors

#10298 Enable shortcut for triage bot
  triagebot.toml
Labels: S-waiting-on-bors

#10296 Downgrade some log messages.
  src/cargo/core/compiler/context/compilation_files.rs
  src/cargo/core/compiler/job_queue.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/sources/git/utils.rs
Labels: S-waiting-on-bors

#10295 Add report subcommand to bash completion.
  src/etc/cargo.bashcomp.sh
Labels: S-waiting-on-bors

#10300 Include `help` in `--list`
  src/bin/cargo/main.rs
Labels: S-waiting-on-bors

#10243 Error when setting crate type of both dylib and cdylib in library
  src/cargo/util/toml/targets.rs
  tests/testsuite/build.rs
Labels: S-waiting-on-bors

#10306 Fix new::git_default_branch with different default
  tests/testsuite/new.rs
Labels: S-waiting-on-bors

#10086 Port cargo from toml-rs to toml_edit
  Cargo.toml
  benches/capture/Cargo.toml
  benches/capture/src/main.rs
  crates/cargo-test-support/Cargo.toml
  crates/cargo-test-support/src/registry.rs
  src/cargo/core/manifest.rs
  src/cargo/core/package.rs
  src/cargo/core/workspace.rs
  src/cargo/ops/cargo_config.rs
  src/cargo/ops/cargo_new.rs
  src/cargo/ops/cargo_output_metadata.rs
  src/cargo/ops/common_for_install_and_uninstall.rs
  src/cargo/ops/lockfile.rs
  src/cargo/ops/vendor.rs
  src/cargo/util/config/key.rs
  src/cargo/util/config/mod.rs
  src/cargo/util/config/target.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/bad_config.rs
  tests/testsuite/build.rs
  tests/testsuite/config.rs
  tests/testsuite/config_cli.rs
  tests/testsuite/config_include.rs
  tests/testsuite/features_namespaced.rs
  tests/testsuite/git.rs
  tests/testsuite/install.rs
  tests/testsuite/install_upgrade.rs
  tests/testsuite/login.rs
  tests/testsuite/logout.rs
  tests/testsuite/package.rs
  tests/testsuite/patch.rs
  tests/testsuite/publish.rs
  tests/testsuite/weak_dep_features.rs
  tests/testsuite/workspaces.rs
Labels: T-cargo, final-comment-period, disposition-merge, S-waiting-on-bors

#10305 do not compile test for bins flagged as `test = false`
  src/bin/cargo/commands/fix.rs
  src/bin/cargo/commands/run.rs
  src/bin/cargo/commands/test.rs
  src/cargo/ops/cargo_compile.rs
  tests/testsuite/test.rs
Labels: S-waiting-on-bors

#10324 Fix documenting with undocumented dependencies.
  src/cargo/core/compiler/unit_dependencies.rs
  tests/testsuite/doc.rs
Labels: S-waiting-on-bors

#10325 [beta] Fix documenting with undocumented dependencies.
  src/cargo/core/compiler/unit_dependencies.rs
  tests/testsuite/doc.rs
Labels: S-waiting-on-bors

#10323 Use local git info for version.
  build.rs
  src/bin/cargo/cli.rs
  src/cargo/core/features.rs
  src/cargo/version.rs
Labels: S-waiting-on-bors

#10327 Remove deprecated --host arg for search and publish cmds
  src/cargo/util/command_prelude.rs
Labels: S-waiting-on-bors

#10176 Check --config for dotted keys only
  src/cargo/util/config/mod.rs
  tests/testsuite/config_cli.rs
  tests/testsuite/config_include.rs
Labels: S-waiting-on-bors

#10328 [beta] backport remove --host flag
  src/cargo/util/command_prelude.rs
Labels: S-waiting-on-bors

#10329 Sync toml_edit versions
  benches/capture/Cargo.toml
  crates/cargo-test-support/Cargo.toml
Labels: S-waiting-on-bors

#10336 Bump clap to v3.0.13
  Cargo.toml
  tests/testsuite/run.rs
  tests/testsuite/rustc.rs
Labels: S-waiting-on-bors

#10335 Normalize --path when install bin outside current workspace
  src/bin/cargo/commands/install.rs
  tests/testsuite/install.rs
Labels: S-waiting-on-bors

#10338 Update publishing link for semver rules.
  src/doc/src/reference/publishing.md
Labels: S-waiting-on-bors

#10340 Make clippy happy
  src/bin/cargo/commands/install.rs
Labels: S-waiting-on-bors

#10274 extra-link-arg-etc: support all link types (credit @davidhewitt)
  src/cargo/core/compiler/custom_build.rs
  src/cargo/util/config/target.rs
  src/doc/src/reference/build-scripts.md
  tests/testsuite/build_script_extra_link_arg.rs
Labels: T-cargo, finished-final-comment-period, disposition-merge, S-waiting-on-bors, to-announce

#10350 test: Fix compatibilty with new toml_edit
  Cargo.toml
  tests/testsuite/publish.rs
Labels: S-waiting-on-bors

#10337 Do not ignore `--features` when `--all-features` is present
  src/cargo/core/resolver/dep_cache.rs
  src/cargo/core/resolver/features.rs
  src/cargo/core/workspace.rs
  src/cargo/ops/tree/graph.rs
  tests/testsuite/features2.rs
  tests/testsuite/features_namespaced.rs
  tests/testsuite/tree_graph_features.rs
Labels: S-waiting-on-bors

#10347 Add bash completion for `cargo clippy`
  src/etc/cargo.bashcomp.sh
Labels: S-waiting-on-bors

#10348 fix(vendor): Use tables for sample config
  src/cargo/ops/vendor.rs
  tests/testsuite/vendor.rs
Labels: S-waiting-on-bors
