Repository rust-lang/cargo, pull requests merged in 2022-09, with the labels that each got.

#11040 chore: Don't show genned docs in ripgrep
  .ignore
Labels: S-waiting-on-bors

#11029 refactor(cli): Lazy load config
  Cargo.toml
  src/bin/cargo/cli.rs
  src/bin/cargo/commands/help.rs
  src/bin/cargo/commands/mod.rs
  src/bin/cargo/main.rs
  src/cargo/ops/fix.rs
  src/cargo/ops/mod.rs
Labels: S-waiting-on-bors

#10511 Support inheriting jobserver fd for external subcommands
  src/bin/cargo/main.rs
  tests/testsuite/jobserver.rs
Labels: S-waiting-on-bors

#11051 fix: specifies the max length for crate name
  src/doc/src/reference/manifest.md
Labels: S-waiting-on-bors

#11044 Cache index files based on contents hash
  src/cargo/sources/registry/remote.rs
Labels: S-waiting-on-bors

#11055 chore(ci): Ensure intradoc links are valid
  .github/workflows/main.yml
  src/cargo/lib.rs
  src/cargo/ops/fix.rs
Labels: S-waiting-on-bors

#11068 Change progress indicator for sparse registries
  src/cargo/sources/registry/http_remote.rs
  src/cargo/util/progress.rs
Labels: S-waiting-on-bors

#11080 Remove dead code
  src/bin/cargo/cli.rs
Labels: S-waiting-on-bors

#11023 Do not add home bin path to PATH if it's already there
  src/bin/cargo/main.rs
  tests/testsuite/cargo_command.rs
Labels: T-cargo, final-comment-period, disposition-merge, S-waiting-on-bors

#11075 fix(add): Clarify which version the features are added for
  src/cargo/ops/cargo_add/dependency.rs
  src/cargo/ops/cargo_add/mod.rs
  tests/testsuite/cargo_add/detect_workspace_inherit_features/stderr.log
  tests/testsuite/cargo_add/dev_prefer_existing_version/stderr.log
  tests/testsuite/cargo_add/merge_activated_features/stderr.log
  tests/testsuite/cargo_add/overwrite_inherit_features_noop/stderr.log
  tests/testsuite/cargo_add/unknown_inherited_feature/stderr.log
Labels: S-waiting-on-bors, Command-add

#11032 Take priority into account within the pending queue
  src/cargo/core/compiler/job_queue.rs
  src/cargo/util/dependency_queue.rs
Labels: T-cargo, final-comment-period, disposition-merge, S-waiting-on-bors

#11059 Expose cargo add internals as edit API
  src/bin/cargo/commands/add.rs
  src/cargo/ops/cargo_add/crate_spec.rs
  src/cargo/ops/cargo_add/mod.rs
  src/cargo/util/mod.rs
  src/cargo/util/toml_mut/dependency.rs
  src/cargo/util/toml_mut/manifest.rs
  src/cargo/util/toml_mut/mod.rs
Labels: A-cargo-api, S-waiting-on-bors

#11088 [beta] Fix for CVE-2022-36113 and CVE-2022-36114
  crates/cargo-test-support/src/registry.rs
  src/cargo/sources/registry/mod.rs
  src/cargo/util/io.rs
  src/cargo/util/mod.rs
  tests/testsuite/registry.rs
Labels: S-waiting-on-bors

#11089 [master] Fix for CVE-2022-36113 and CVE-2022-36114
  crates/cargo-test-support/src/registry.rs
  src/cargo/sources/registry/mod.rs
  src/cargo/util/io.rs
  src/cargo/util/mod.rs
  tests/testsuite/registry.rs
Labels: S-waiting-on-bors

#11092 Clarify when cargo detects changes
  src/doc/src/reference/build-scripts.md
Labels: S-waiting-on-bors

#11090 [Beta] Run `reach_max_unpack_size` test only on debug build
  tests/testsuite/registry.rs
Labels: S-waiting-on-bors

#11091 [master] Run `reach_max_unpack_size` test only on debug build
  tests/testsuite/registry.rs
Labels: S-waiting-on-bors

#11095 Update comment about ResolveVersion default version
  src/cargo/core/resolver/resolve.rs
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#11082 docs(ref): Clarify workspace settings
  src/doc/src/reference/manifest.md
  src/doc/src/reference/overriding-dependencies.md
  src/doc/src/reference/resolver.md
  src/doc/src/reference/specifying-dependencies.md
  src/doc/src/reference/unstable.md
  src/doc/src/reference/workspaces.md
Labels: A-documenting-cargo-itself, A-workspaces, S-waiting-on-bors

#11097 Beta backport #11082
  src/doc/src/reference/manifest.md
  src/doc/src/reference/overriding-dependencies.md
  src/doc/src/reference/resolver.md
  src/doc/src/reference/specifying-dependencies.md
  src/doc/src/reference/unstable.md
  src/doc/src/reference/workspaces.md
Labels: S-waiting-on-bors

#11103 Fix links to workspace inheritance headings in workspace docs
  CHANGELOG.md
Labels: S-waiting-on-bors

#11107 Revert "Clarify when cargo detects changes"
  src/doc/src/reference/build-scripts.md
Labels: S-waiting-on-bors

#11104 doc(changelog): mention CVE fixes
  CHANGELOG.md
Labels: S-waiting-on-bors

#11093 Add a minor clarification
  src/doc/src/reference/build-scripts.md
Labels: S-waiting-on-bors

#11119 fix(cli): Error trailing args rather than ignore
  src/bin/cargo/cli.rs
  tests/testsuite/cargo_alias_config.rs
Labels: S-waiting-on-bors

#11116 refactor(cli): Prepare for clap v4
  src/bin/cargo/cli.rs
  src/bin/cargo/commands/add.rs
  src/bin/cargo/commands/bench.rs
  src/bin/cargo/commands/build.rs
  src/bin/cargo/commands/check.rs
  src/bin/cargo/commands/clean.rs
  src/bin/cargo/commands/config.rs
  src/bin/cargo/commands/doc.rs
  src/bin/cargo/commands/fetch.rs
  src/bin/cargo/commands/fix.rs
  src/bin/cargo/commands/generate_lockfile.rs
  src/bin/cargo/commands/git_checkout.rs
  src/bin/cargo/commands/help.rs
  src/bin/cargo/commands/init.rs
  src/bin/cargo/commands/install.rs
  src/bin/cargo/commands/locate_project.rs
  src/bin/cargo/commands/login.rs
  src/bin/cargo/commands/logout.rs
  src/bin/cargo/commands/metadata.rs
  src/bin/cargo/commands/mod.rs
  src/bin/cargo/commands/new.rs
  src/bin/cargo/commands/owner.rs
  src/bin/cargo/commands/package.rs
  src/bin/cargo/commands/pkgid.rs
  src/bin/cargo/commands/publish.rs
  src/bin/cargo/commands/read_manifest.rs
  src/bin/cargo/commands/report.rs
  src/bin/cargo/commands/run.rs
  src/bin/cargo/commands/rustc.rs
  src/bin/cargo/commands/rustdoc.rs
  src/bin/cargo/commands/search.rs
  src/bin/cargo/commands/test.rs
  src/bin/cargo/commands/tree.rs
  src/bin/cargo/commands/uninstall.rs
  src/bin/cargo/commands/update.rs
  src/bin/cargo/commands/vendor.rs
  src/bin/cargo/commands/verify_project.rs
  src/bin/cargo/commands/version.rs
  src/bin/cargo/commands/yank.rs
  src/cargo/util/command_prelude.rs
Labels: S-waiting-on-bors

#11122 Unlink old final artifacts before compilation
  Cargo.toml
  src/cargo/core/compiler/mod.rs
  tests/testsuite/build.rs
Labels: S-waiting-on-bors

#11098 make unknown features on `cargo add` more discoverable
  src/cargo/ops/cargo_add/mod.rs
  tests/testsuite/cargo_add/features_unknown/stderr.log
  tests/testsuite/cargo_add/features_unknown_no_features/in
  tests/testsuite/cargo_add/features_unknown_no_features/mod.rs
  tests/testsuite/cargo_add/features_unknown_no_features/out/Cargo.toml
  tests/testsuite/cargo_add/features_unknown_no_features/stderr.log
  tests/testsuite/cargo_add/features_unknown_no_features/stdout.log
  tests/testsuite/cargo_add/mod.rs
  tests/testsuite/cargo_add/unknown_inherited_feature/in/dependency/Cargo.toml
  tests/testsuite/cargo_add/unknown_inherited_feature/out/dependency/Cargo.toml
  tests/testsuite/cargo_add/unknown_inherited_feature/stderr.log
Labels: S-waiting-on-bors

#11106 Add support for relative git submodule paths
  src/cargo/sources/git/source.rs
  src/cargo/sources/git/utils.rs
  tests/testsuite/git.rs
Labels: S-waiting-on-bors

#10938 This change adds an example to the authors attribute in the manifest.
  src/doc/src/reference/manifest.md
Labels: S-waiting-on-bors

#11118 fix(cli): Forward non-UTF8 arguments to external subcommands
  src/bin/cargo/cli.rs
  src/bin/cargo/commands/help.rs
  src/bin/cargo/main.rs
Labels: S-waiting-on-bors

#11127 minor: remove unused mut
  src/cargo/core/resolver/dep_cache.rs
Labels: S-waiting-on-bors

#11130 switch to `std::task::ready!()` where possible
  src/cargo/core/registry.rs
  src/cargo/sources/registry/http_remote.rs
  src/cargo/sources/registry/index.rs
  src/cargo/sources/registry/remote.rs
Labels: S-waiting-on-bors

#11113 Improve errors for TOML fields that support workspace inheritance
  Cargo.toml
  src/cargo/util/toml/mod.rs
  tests/testsuite/metadata.rs
Labels: S-waiting-on-bors

#11111 Http publish not noop
  crates/cargo-test-support/Cargo.toml
  crates/cargo-test-support/src/publish.rs
  crates/cargo-test-support/src/registry.rs
  crates/crates-io/lib.rs
  tests/testsuite/publish.rs
Labels: S-waiting-on-bors

#11134 ci: update toolchain for building api doc
  .github/workflows/contrib.yml
Labels: S-waiting-on-bors

#11137 Bump to 0.67.0, update changelog
  CHANGELOG.md
  Cargo.toml
Labels: S-waiting-on-bors

#11139 Call out that not all config values can be set via env vars
  src/doc/src/reference/config.md
  src/doc/src/reference/environment-variables.md
Labels: S-waiting-on-bors

#11146 update comment about `CARGO_BIN_EXE_`
  src/cargo/core/compiler/mod.rs
  tests/testsuite/test.rs
Labels: S-waiting-on-bors

#11114 Iteratively construct target cfg
  src/cargo/core/compiler/build_context/target_info.rs
  tests/testsuite/build_script_env.rs
Labels: S-waiting-on-bors

#11135 Reduce references to `[project]` within cargo
  src/cargo/util/toml/mod.rs
  src/doc/src/reference/specifying-dependencies.md
  src/doc/src/reference/unstable.md
  src/doc/src/reference/workspaces.md
  tests/testsuite/alt_registry.rs
  tests/testsuite/artifact_dep.rs
  tests/testsuite/bad_config.rs
  tests/testsuite/bench.rs
  tests/testsuite/binary_name.rs
  tests/testsuite/build.rs
  tests/testsuite/build_plan.rs
  tests/testsuite/build_script.rs
  tests/testsuite/check.rs
  tests/testsuite/check_cfg.rs
  tests/testsuite/corrupt_git.rs
  tests/testsuite/cross_compile.rs
  tests/testsuite/doc.rs
  tests/testsuite/features.rs
  tests/testsuite/freshness.rs
  tests/testsuite/git.rs
  tests/testsuite/git_auth.rs
  tests/testsuite/inheritable_workspace_fields.rs
  tests/testsuite/local_registry.rs
  tests/testsuite/lockfile_compat.rs
  tests/testsuite/member_discovery.rs
  tests/testsuite/member_errors.rs
  tests/testsuite/metadata.rs
  tests/testsuite/net_config.rs
  tests/testsuite/offline.rs
  tests/testsuite/out_dir.rs
  tests/testsuite/owner.rs
  tests/testsuite/package.rs
  tests/testsuite/patch.rs
  tests/testsuite/path.rs
  tests/testsuite/profiles.rs
  tests/testsuite/publish.rs
  tests/testsuite/registry.rs
  tests/testsuite/rename_deps.rs
  tests/testsuite/required_features.rs
  tests/testsuite/run.rs
  tests/testsuite/rust_version.rs
  tests/testsuite/shell_quoting.rs
  tests/testsuite/test.rs
  tests/testsuite/workspaces.rs
  tests/testsuite/yank.rs
Labels: A-errors, A-manifest, S-waiting-on-bors

#10770 Indicate how Cargo locates the manifest
  src/doc/man/cargo-locate-project.md
  src/doc/man/generated_txt/cargo-locate-project.txt
  src/doc/src/commands/cargo-locate-project.md
  src/doc/src/reference/manifest.md
  src/etc/man/cargo-locate-project.1
Labels: S-waiting-on-bors

#11150 build-scripts.md: Use em dash consistently.
  src/doc/src/reference/build-scripts.md
Labels: S-waiting-on-bors

#11155 Remove outdated comments
  src/cargo/core/resolver/features.rs
Labels: S-waiting-on-bors

#11158 Remove `multitarget` from -Zhelp
  src/cargo/core/features.rs
Labels: S-waiting-on-bors

#11157 Expose guide to adding a new edition as rustdoc
  src/cargo/core/features.rs
Labels: S-waiting-on-bors

#11159 refactor(cli): Upgrade to clap v4
  Cargo.toml
  src/bin/cargo/cli.rs
  src/bin/cargo/commands/add.rs
  src/bin/cargo/commands/bench.rs
  src/bin/cargo/commands/config.rs
  src/bin/cargo/commands/git_checkout.rs
  src/bin/cargo/commands/help.rs
  src/bin/cargo/commands/init.rs
  src/bin/cargo/commands/install.rs
  src/bin/cargo/commands/login.rs
  src/bin/cargo/commands/new.rs
  src/bin/cargo/commands/owner.rs
  src/bin/cargo/commands/pkgid.rs
  src/bin/cargo/commands/run.rs
  src/bin/cargo/commands/rustc.rs
  src/bin/cargo/commands/rustdoc.rs
  src/bin/cargo/commands/search.rs
  src/bin/cargo/commands/test.rs
  src/bin/cargo/commands/uninstall.rs
  src/bin/cargo/commands/vendor.rs
  src/bin/cargo/commands/yank.rs
  src/bin/cargo/main.rs
  src/cargo/util/command_prelude.rs
  tests/testsuite/cargo_add/dev_build_conflict/stderr.log
  tests/testsuite/cargo_add/invalid_arg/stderr.log
  tests/testsuite/cargo_add/invalid_target_empty/stderr.log
  tests/testsuite/cargo_add/no_args/stderr.log
  tests/testsuite/cargo_command.rs
  tests/testsuite/init/unknown_flags/stderr.log
  tests/testsuite/install.rs
  tests/testsuite/metadata.rs
  tests/testsuite/new.rs
  tests/testsuite/run.rs
  tests/testsuite/rustc.rs
  tests/testsuite/vendor.rs
Labels: S-waiting-on-bors

#11162 Expose libgit2-sys/vendored feature as vendored-libgit2
  Cargo.toml
Labels: S-waiting-on-bors
