Repository rust-lang/cargo, pull requests merged in 2022-04, with the labels that each got.

#10508 Don't error if no binaries were installed
  src/cargo/ops/cargo_install.rs
  tests/testsuite/required_features.rs
Labels: S-waiting-on-bors

#10521 tools: update checkout action on CI
  .github/workflows/contrib.yml
  .github/workflows/main.yml
Labels: S-waiting-on-bors

#10507 File Cache is valid if checkout or contents hasn't changed
  src/cargo/sources/registry/remote.rs
Labels: S-waiting-on-bors

#10517 Part 2 of RFC2906 -- allow inheriting from a different `Cargo.toml`
  src/cargo/core/manifest.rs
  src/cargo/core/mod.rs
  src/cargo/core/workspace.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/inheritable_workspace_fields.rs
Labels: S-waiting-on-bors

#10544 Bump to 0.63.0, update changelog
  CHANGELOG.md
  Cargo.toml
Labels: S-waiting-on-bors

#10538 Part 3 of RFC2906 - Add support for inheriting `license-path`, and `depednency.path`
  Cargo.toml
  src/cargo/core/mod.rs
  src/cargo/core/workspace.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/inheritable_workspace_fields.rs
Labels: S-waiting-on-bors

#10548 Part 4 of RFC2906 - Add support for inheriting `readme`
  src/cargo/core/workspace.rs
  src/cargo/ops/cargo_package.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/inheritable_workspace_fields.rs
Labels: S-waiting-on-bors

#10550 Fix docs: Bindeps env vars are passed to build script at runtime
  src/doc/src/reference/unstable.md
Labels: S-waiting-on-bors

#10549 Ensure host units don't depend on Docscrape units, fixes #10545
  src/cargo/core/compiler/mod.rs
  src/cargo/core/compiler/unit_dependencies.rs
  src/cargo/core/workspace.rs
  tests/testsuite/doc.rs
Labels: S-waiting-on-bors

#10236 Add a progress indicator for `cargo clean`
  src/cargo/ops/cargo_clean.rs
Labels: T-cargo, finished-final-comment-period, disposition-merge, S-waiting-on-bors, to-announce

#10546 Retry command invocation with argfile
  .github/workflows/main.yml
  Cargo.toml
  crates/cargo-test-support/src/tools.rs
  crates/cargo-util/Cargo.toml
  crates/cargo-util/src/process_builder.rs
  crates/cargo-util/src/process_error.rs
  src/cargo/core/compiler/build_plan.rs
  src/cargo/core/compiler/compilation.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/ops/fix.rs
  src/cargo/util/rustc.rs
  tests/testsuite/fix.rs
  tests/testsuite/rustdocflags.rs
Labels: S-waiting-on-bors

#10551 Reserve filename `Cargo.toml.orig` in `cargo package`
  src/cargo/ops/cargo_package.rs
  tests/testsuite/package.rs
Labels: relnotes, S-waiting-on-bors

#10486 Add support for rustc --check-cfg well known names and values
  src/cargo/core/compiler/context/mod.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/core/features.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/build.rs
  tests/testsuite/check.rs
  tests/testsuite/test.rs
Labels: S-waiting-on-bors

#10563 Part 5 of RFC2906 - Add support for inheriting `rust-version`
  src/cargo/core/workspace.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/inheritable_workspace_fields.rs
Labels: S-waiting-on-bors

#10557 Backport git2 update #10442 as 0.61.1
  Cargo.toml
  crates/cargo-test-support/Cargo.toml
Labels: S-waiting-on-bors

#10564 Part 6 of RFC2906 - Switch the inheritance source from `workspace` to…
  src/cargo/core/mod.rs
  src/cargo/core/workspace.rs
  src/cargo/util/toml/mod.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/inheritable_workspace_fields.rs
Labels: S-waiting-on-bors

#10565 Part 7 of RFC2906 - Add support for inheriting `exclude` and `include`
  src/cargo/util/toml/mod.rs
  tests/testsuite/inheritable_workspace_fields.rs
Labels: S-waiting-on-bors

#10568 Part 8 of RFC2906 - Keep `InheritableFields` in a `LazyCell` inside `…
  src/cargo/util/toml/mod.rs
Labels: S-waiting-on-bors

#10492 Add a link to the document in the timings report
  src/cargo/core/compiler/timings.rs
Labels: S-waiting-on-bors

#10577 Completion support for `cargo-add`
  src/etc/_cargo
  src/etc/cargo.bashcomp.sh
Labels: S-waiting-on-bors

#10576 feat: Support '-F' as an alias for '--features'
  src/cargo/util/command_prelude.rs
  src/doc/man/generated_txt/cargo-bench.txt
  src/doc/man/generated_txt/cargo-build.txt
  src/doc/man/generated_txt/cargo-check.txt
  src/doc/man/generated_txt/cargo-doc.txt
  src/doc/man/generated_txt/cargo-fix.txt
  src/doc/man/generated_txt/cargo-install.txt
  src/doc/man/generated_txt/cargo-metadata.txt
  src/doc/man/generated_txt/cargo-package.txt
  src/doc/man/generated_txt/cargo-publish.txt
  src/doc/man/generated_txt/cargo-run.txt
  src/doc/man/generated_txt/cargo-rustc.txt
  src/doc/man/generated_txt/cargo-rustdoc.txt
  src/doc/man/generated_txt/cargo-test.txt
  src/doc/man/generated_txt/cargo-tree.txt
  src/doc/man/includes/section-features.md
  src/doc/src/commands/cargo-bench.md
  src/doc/src/commands/cargo-build.md
  src/doc/src/commands/cargo-check.md
  src/doc/src/commands/cargo-doc.md
  src/doc/src/commands/cargo-fix.md
  src/doc/src/commands/cargo-install.md
  src/doc/src/commands/cargo-metadata.md
  src/doc/src/commands/cargo-package.md
  src/doc/src/commands/cargo-publish.md
  src/doc/src/commands/cargo-run.md
  src/doc/src/commands/cargo-rustc.md
  src/doc/src/commands/cargo-rustdoc.md
  src/doc/src/commands/cargo-test.md
  src/doc/src/commands/cargo-tree.md
  src/etc/_cargo
  src/etc/cargo.bashcomp.sh
  src/etc/man/cargo-bench.1
  src/etc/man/cargo-build.1
  src/etc/man/cargo-check.1
  src/etc/man/cargo-doc.1
  src/etc/man/cargo-fix.1
  src/etc/man/cargo-install.1
  src/etc/man/cargo-metadata.1
  src/etc/man/cargo-package.1
  src/etc/man/cargo-publish.1
  src/etc/man/cargo-run.1
  src/etc/man/cargo-rustc.1
  src/etc/man/cargo-rustdoc.1
  src/etc/man/cargo-test.1
  src/etc/man/cargo-tree.1
Labels: S-waiting-on-bors

#10578 Document cargo-add
  src/bin/cargo/cli.rs
  src/doc/man/cargo-add.md
  src/doc/man/generated_txt/cargo-add.txt
  src/doc/src/SUMMARY.md
  src/doc/src/commands/cargo-add.md
  src/doc/src/commands/manifest-commands.md
  src/etc/man/cargo-add.1
Labels: S-waiting-on-bors

#10584 Prefer `key.workspace = true` to `key = { workspace = true }`
  src/cargo/util/toml/mod.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/inheritable_workspace_fields.rs
Labels: S-waiting-on-bors

#10579 Set cargo --version git hash length to 9
  build.rs
Labels: S-waiting-on-bors

#10580 Disallow setting registry tokens with --config
  src/cargo/util/config/mod.rs
  tests/testsuite/config_cli.rs
Labels: S-waiting-on-bors

#10575 fix(yank): Use '--version' like install
  src/bin/cargo/commands/yank.rs
  src/cargo/ops/cargo_install.rs
  src/doc/man/cargo-yank.md
  src/doc/man/generated_txt/cargo-yank.txt
  src/doc/src/commands/cargo-yank.md
  src/doc/src/reference/publishing.md
  src/etc/_cargo
  src/etc/cargo.bashcomp.sh
  src/etc/man/cargo-yank.1
  tests/testsuite/alt_registry.rs
  tests/testsuite/credential_process.rs
  tests/testsuite/install.rs
  tests/testsuite/install_upgrade.rs
  tests/testsuite/yank.rs
Labels: T-cargo, final-comment-period, disposition-merge, S-waiting-on-bors

#10553 Mark .cargo/git and .cargo/registry as cache dirs
  crates/cargo-util/src/paths.rs
  src/cargo/sources/git/source.rs
  src/cargo/sources/registry/mod.rs
  src/cargo/util/config/mod.rs
  tests/testsuite/git.rs
  tests/testsuite/registry.rs
Labels: T-cargo, final-comment-period, disposition-merge, S-waiting-on-bors

#10603 chore: Upgrade toml_edit
  Cargo.toml
  src/cargo/util/toml/mod.rs
Labels: S-waiting-on-bors

#10609 move workspace inheritance untable docs to the correct place
  src/doc/src/reference/unstable.md
Labels: S-waiting-on-bors

#10581 Integrate snapbox in with cargo-test-support
  crates/cargo-test-support/Cargo.toml
  crates/cargo-test-support/src/compare.rs
  crates/cargo-test-support/src/lib.rs
  tests/snapshots/add/invalid_vers.stderr
  tests/testsuite/cargo_add.rs
Labels: S-waiting-on-bors

#10616 move workspace inheritance unstable docs to the correct place
  src/doc/src/reference/unstable.md
Labels: S-waiting-on-bors

#10618 Update GitHub Actions actions/checkout@v2 to v3
  .github/workflows/main.yml
  src/doc/src/guide/continuous-integration.md
Labels: S-waiting-on-bors
