Repository rust-lang/cargo, pull requests merged in 2022-02, with the labels that each got.

#10349 fix(install): Keep v1 file formatting the same
  src/cargo/ops/common_for_install_and_uninstall.rs
  tests/testsuite/install.rs
Labels: S-waiting-on-bors

#10341 Compute non custom build and non transitive deps for doc
  src/cargo/core/compiler/unit_dependencies.rs
  tests/testsuite/doc.rs
Labels: S-waiting-on-bors

#10360 Remove needless borrow
  src/cargo/ops/resolve.rs
Labels: S-waiting-on-bors

#10365 Improve startup time of bash completion.
  src/etc/cargo.bashcomp.sh
Labels: S-waiting-on-bors

#10375 Fix unmatched backticks
  src/doc/src/reference/future-incompat-report.md
Labels: S-waiting-on-bors

#10376 Remove `strip = "off"` (and undocumented `strip = "n"`/`strip = "no"`)
  src/cargo/core/profiles.rs
  src/doc/src/reference/profiles.md
Labels: S-waiting-on-bors, beta-nominated

#10377 [beta] Remove `strip = "off"` (and undocumented `strip = "n"`/`strip = "no"`)
  src/cargo/core/profiles.rs
  src/doc/src/reference/profiles.md
Labels: S-waiting-on-bors

#10380 Remove outdated badges
  README.md
Labels: S-waiting-on-bors

#10385 Add a badge for github actions
  README.md
Labels: S-waiting-on-bors

#10379 cargo-new should not add ignore rule on Cargo.lock inside subdirs
  src/cargo/ops/cargo_new.rs
  tests/testsuite/init.rs
  tests/testsuite/new.rs
Labels: T-cargo, final-comment-period, disposition-merge, S-waiting-on-bors

#10396 Avoid new deprecation warnings from clap 3.1.0
  Cargo.toml
  src/bin/cargo/cli.rs
  src/bin/cargo/commands/bench.rs
  src/bin/cargo/commands/config.rs
  src/bin/cargo/commands/git_checkout.rs
  src/bin/cargo/commands/report.rs
  src/bin/cargo/commands/run.rs
  src/bin/cargo/commands/rustc.rs
  src/bin/cargo/commands/rustdoc.rs
  src/bin/cargo/commands/test.rs
  src/cargo/util/command_prelude.rs
Labels: S-waiting-on-bors

#10346 Print executable name on cargo test --no-run #2
  crates/cargo-test-support/src/compare.rs
  src/cargo/ops/cargo_test.rs
  tests/testsuite/bench.rs
  tests/testsuite/features2.rs
  tests/testsuite/freshness.rs
  tests/testsuite/lto.rs
  tests/testsuite/messages.rs
  tests/testsuite/profile_config.rs
  tests/testsuite/profiles.rs
  tests/testsuite/rustflags.rs
  tests/testsuite/test.rs
Labels: S-waiting-on-bors

#9992 Implement "artifact dependencies" (RFC-3028)
  crates/cargo-test-support/src/cross_compile.rs
  crates/cargo-test-support/src/registry.rs
  src/cargo/core/compiler/artifact.rs
  src/cargo/core/compiler/build_context/target_info.rs
  src/cargo/core/compiler/compilation.rs
  src/cargo/core/compiler/compile_kind.rs
  src/cargo/core/compiler/context/compilation_files.rs
  src/cargo/core/compiler/context/mod.rs
  src/cargo/core/compiler/custom_build.rs
  src/cargo/core/compiler/job_queue.rs
  src/cargo/core/compiler/layout.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/core/compiler/standard_lib.rs
  src/cargo/core/compiler/unit.rs
  src/cargo/core/compiler/unit_dependencies.rs
  src/cargo/core/compiler/unit_graph.rs
  src/cargo/core/dependency.rs
  src/cargo/core/features.rs
  src/cargo/core/manifest.rs
  src/cargo/core/package.rs
  src/cargo/core/profiles.rs
  src/cargo/core/resolver/features.rs
  src/cargo/core/resolver/resolve.rs
  src/cargo/ops/cargo_compile.rs
  src/cargo/ops/cargo_output_metadata.rs
  src/cargo/ops/cargo_test.rs
  src/cargo/ops/fix.rs
  src/cargo/ops/resolve.rs
  src/cargo/ops/tree/graph.rs
  src/cargo/util/dependency_queue.rs
  src/cargo/util/toml/mod.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/artifact_dep.rs
  tests/testsuite/main.rs
  tests/testsuite/metadata.rs
  tests/testsuite/profile_config.rs
Labels: T-cargo, proposed-final-comment-period, disposition-merge, S-waiting-on-bors

#10404 Fix some broken doc links.
  src/doc/src/reference/config.md
Labels: S-waiting-on-bors

#10401 Remove invalid target-specific dependency example.
  src/doc/src/reference/specifying-dependencies.md
Labels: S-waiting-on-bors

#10408 Add -Z check-cfg-features to enable compile-time checking of features
  src/cargo/core/compiler/mod.rs
  src/cargo/core/features.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/build.rs
  tests/testsuite/check.rs
  tests/testsuite/test.rs
Labels: S-waiting-on-bors

#10411 Add common profile validation.
  src/cargo/util/toml/mod.rs
  tests/testsuite/profiles.rs
Labels: S-waiting-on-bors

#10413 [beta] Add common profile validation.
  Cargo.toml
  src/bin/cargo/cli.rs
  src/bin/cargo/commands/bench.rs
  src/bin/cargo/commands/config.rs
  src/bin/cargo/commands/git_checkout.rs
  src/bin/cargo/commands/report.rs
  src/bin/cargo/commands/run.rs
  src/bin/cargo/commands/rustc.rs
  src/bin/cargo/commands/rustdoc.rs
  src/bin/cargo/commands/test.rs
  src/cargo/util/command_prelude.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/profiles.rs
Labels: S-waiting-on-bors

#10417 Documentation change to cargo-test.md
  src/doc/man/cargo-test.md
  src/doc/man/generated_txt/cargo-test.txt
  src/doc/src/commands/cargo-test.md
  src/etc/man/cargo-test.1
Labels: S-waiting-on-bors

#10416 Some small clean ups.
  crates/mdman/src/hbs.rs
  src/bin/cargo/commands/verify_project.rs
  src/cargo/core/compiler/rustdoc.rs
  src/cargo/core/compiler/standard_lib.rs
  src/cargo/core/profiles.rs
  src/cargo/ops/registry.rs
  src/cargo/util/config/mod.rs
  src/cargo/util/diagnostic_server.rs
Labels: S-waiting-on-bors

#10420 Bump to 0.62.0, update changelog
  CHANGELOG.md
  Cargo.toml
  src/cargo/core/compiler/build_context/target_info.rs
  src/cargo/core/compiler/mod.rs
Labels: S-waiting-on-bors

#10372 Test: ensure dep-infos do not collide when cdylib and bin coexist
  tests/testsuite/build.rs
Labels: S-waiting-on-bors

#10429 Fix term.verbose without quiet, and vice versa
  src/cargo/util/config/mod.rs
  tests/testsuite/run.rs
Labels: S-waiting-on-bors

#10167 Use 1.51.0 in old cargos test
  tests/testsuite/old_cargos.rs
Labels: S-waiting-on-bors

#10388 Override target crate-type for `cargo rustc --crate-type`
  src/cargo/core/compiler/build_context/mod.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/ops/cargo_compile.rs
  tests/testsuite/rustc.rs
Labels: S-waiting-on-bors

#10428 Add -Z check-cfg-features support for rustdoc
  src/cargo/core/compiler/context/mod.rs
  src/cargo/core/compiler/mod.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/doc.rs
  tests/testsuite/test.rs
Labels: S-waiting-on-bors

#10425 feat(search): Highlight search term
  src/cargo/core/shell.rs
  src/cargo/ops/registry.rs
  tests/testsuite/search.rs
Labels: S-waiting-on-bors

#10395 Enable propagating host rustflags to build scripts
  src/cargo/core/compiler/build_context/target_info.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/build_script.rs
  tests/testsuite/rustflags.rs
Labels: S-waiting-on-bors

#10434 Stop gating stable features
  src/cargo/core/compiler/standard_lib.rs
  src/cargo/core/compiler/unit_dependencies.rs
  src/cargo/core/profiles.rs
  src/cargo/ops/cargo_compile.rs
  src/cargo/util/toml/mod.rs
  src/cargo/util/toml/targets.rs
  tests/testsuite/profile_config.rs
Labels: S-waiting-on-bors
