Repository rust-lang/cargo, pull requests merged in 2022-08, with the labels that each got.

#9892 Add requirements to cargo_test.
  crates/cargo-test-macro/src/lib.rs
  crates/cargo-test-support/src/lib.rs
  src/doc/contrib/src/tests/writing.md
  tests/build-std/main.rs
  tests/testsuite/bench.rs
  tests/testsuite/build.rs
  tests/testsuite/cargo_features.rs
  tests/testsuite/check_cfg.rs
  tests/testsuite/cross_compile.rs
  tests/testsuite/custom_target.rs
  tests/testsuite/dep_info.rs
  tests/testsuite/doc.rs
  tests/testsuite/edition.rs
  tests/testsuite/fix.rs
  tests/testsuite/future_incompat_report.rs
  tests/testsuite/git.rs
  tests/testsuite/git_gc.rs
  tests/testsuite/init/formats_source/mod.rs
  tests/testsuite/init/mod.rs
  tests/testsuite/init/simple_hg/mod.rs
  tests/testsuite/jobserver.rs
  tests/testsuite/plugins.rs
  tests/testsuite/proc_macro.rs
  tests/testsuite/profiles.rs
  tests/testsuite/pub_priv.rs
  tests/testsuite/required_features.rs
  tests/testsuite/rustdoc_extern_html.rs
  tests/testsuite/standard_lib.rs
  tests/testsuite/test.rs
Labels: S-waiting-on-bors

#10844 Support for negative --jobs parameter, counting backwards from max CPUs
  src/cargo/core/compiler/build_config.rs
  src/cargo/core/compiler/context/mod.rs
  src/cargo/core/compiler/timings.rs
  src/cargo/ops/cargo_package.rs
  src/cargo/ops/registry.rs
  src/cargo/util/command_prelude.rs
  src/cargo/util/config/mod.rs
  src/doc/man/generated_txt/cargo-bench.txt
  src/doc/man/generated_txt/cargo-build.txt
  src/doc/man/generated_txt/cargo-check.txt
  src/doc/man/generated_txt/cargo-doc.txt
  src/doc/man/generated_txt/cargo-fix.txt
  src/doc/man/generated_txt/cargo-install.txt
  src/doc/man/generated_txt/cargo-package.txt
  src/doc/man/generated_txt/cargo-publish.txt
  src/doc/man/generated_txt/cargo-run.txt
  src/doc/man/generated_txt/cargo-rustc.txt
  src/doc/man/generated_txt/cargo-rustdoc.txt
  src/doc/man/generated_txt/cargo-test.txt
  src/doc/man/includes/options-jobs.md
  src/doc/src/commands/cargo-bench.md
  src/doc/src/commands/cargo-build.md
  src/doc/src/commands/cargo-check.md
  src/doc/src/commands/cargo-doc.md
  src/doc/src/commands/cargo-fix.md
  src/doc/src/commands/cargo-install.md
  src/doc/src/commands/cargo-package.md
  src/doc/src/commands/cargo-publish.md
  src/doc/src/commands/cargo-run.md
  src/doc/src/commands/cargo-rustc.md
  src/doc/src/commands/cargo-rustdoc.md
  src/doc/src/commands/cargo-test.md
  src/doc/src/reference/config.md
  src/etc/man/cargo-bench.1
  src/etc/man/cargo-build.1
  src/etc/man/cargo-check.1
  src/etc/man/cargo-doc.1
  src/etc/man/cargo-fix.1
  src/etc/man/cargo-install.1
  src/etc/man/cargo-package.1
  src/etc/man/cargo-publish.1
  src/etc/man/cargo-run.1
  src/etc/man/cargo-rustc.1
  src/etc/man/cargo-rustdoc.1
  src/etc/man/cargo-test.1
  tests/testsuite/bad_config.rs
  tests/testsuite/build.rs
Labels: T-cargo, S-waiting-on-bors

#10916 Contrib: Add docs on the rustbot ready command
  src/doc/contrib/src/process/working-on-cargo.md
Labels: S-waiting-on-bors

#10921 Disable scrape_examples_complex_reverse_dependencies
  tests/testsuite/doc.rs
Labels: S-waiting-on-bors

#10918 Fix formats_source test requiring rustfmt.
  src/cargo/ops/cargo_new.rs
  tests/testsuite/init/formats_source/mod.rs
Labels: S-waiting-on-bors

#10931 Always allow hg to be missing on CI.
  crates/cargo-test-macro/src/lib.rs
Labels: S-waiting-on-bors

#10933 Grammar fixup unused patch message
  src/cargo/ops/resolve.rs
  tests/testsuite/patch.rs
Labels: S-waiting-on-bors

#10929 Add reasons to all ignored tests.
  crates/cargo-test-macro/src/lib.rs
  tests/testsuite/advanced_env.rs
  tests/testsuite/artifact_dep.rs
  tests/testsuite/build_script.rs
  tests/testsuite/collisions.rs
  tests/testsuite/cross_compile.rs
  tests/testsuite/doc.rs
  tests/testsuite/old_cargos.rs
  tests/testsuite/profile_custom.rs
  tests/testsuite/rustdoc_extern_html.rs
Labels: S-waiting-on-bors

#10924 improve error message for `no such subcommand`
  src/bin/cargo/main.rs
  tests/testsuite/cargo_command.rs
Labels: S-waiting-on-bors

#10322 Test if reserved filenames are allowed in Windows
  crates/cargo-test-support/Cargo.toml
  crates/cargo-test-support/src/paths.rs
  tests/testsuite/package.rs
Labels: S-waiting-on-bors

#10935 Mention that aliases are recursive
  src/doc/src/reference/config.md
Labels: S-waiting-on-bors

#10941 Mark --timings=html unstable in the document
  src/doc/man/generated_txt/cargo-bench.txt
  src/doc/man/generated_txt/cargo-build.txt
  src/doc/man/generated_txt/cargo-check.txt
  src/doc/man/generated_txt/cargo-doc.txt
  src/doc/man/generated_txt/cargo-fix.txt
  src/doc/man/generated_txt/cargo-install.txt
  src/doc/man/generated_txt/cargo-run.txt
  src/doc/man/generated_txt/cargo-rustc.txt
  src/doc/man/generated_txt/cargo-rustdoc.txt
  src/doc/man/generated_txt/cargo-test.txt
  src/doc/man/includes/options-timings.md
  src/doc/src/commands/cargo-bench.md
  src/doc/src/commands/cargo-build.md
  src/doc/src/commands/cargo-check.md
  src/doc/src/commands/cargo-doc.md
  src/doc/src/commands/cargo-fix.md
  src/doc/src/commands/cargo-install.md
  src/doc/src/commands/cargo-run.md
  src/doc/src/commands/cargo-rustc.md
  src/doc/src/commands/cargo-rustdoc.md
  src/doc/src/commands/cargo-test.md
  src/etc/man/cargo-bench.1
  src/etc/man/cargo-build.1
  src/etc/man/cargo-check.1
  src/etc/man/cargo-doc.1
  src/etc/man/cargo-fix.1
  src/etc/man/cargo-install.1
  src/etc/man/cargo-run.1
  src/etc/man/cargo-rustc.1
  src/etc/man/cargo-rustdoc.1
  src/etc/man/cargo-test.1
Labels: S-waiting-on-bors

#10943 Bump os_info to 3.5.0
  Cargo.toml
Labels: S-waiting-on-bors

#10946 resolver docs: link to version requirements syntax full explanation
  src/doc/src/reference/resolver.md
Labels: S-waiting-on-bors

#10891 Make the `rust-version` error recommend `cargo update --precise -p crate@ver`
  src/cargo/ops/cargo_compile.rs
  tests/testsuite/rust_version.rs
Labels: S-waiting-on-bors

#10967 Add `CARGO_LOG` to "Environment variables Cargo reads"
  src/doc/src/reference/environment-variables.md
Labels: S-waiting-on-bors

#10961 Only override published resolver when the workspace is different
  src/cargo/core/features.rs
  src/cargo/core/workspace.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/features_namespaced.rs
  tests/testsuite/inheritable_workspace_fields.rs
  tests/testsuite/package.rs
  tests/testsuite/publish.rs
  tests/testsuite/weak_dep_features.rs
Labels: S-waiting-on-bors

#10969 Switch back to `available_parallelism`
  Cargo.toml
  src/cargo/core/compiler/build_config.rs
  src/cargo/core/compiler/timings.rs
Labels: S-waiting-on-bors

#10962 Ensure rustc-echo-wrapper works with an overridden build.target-dir
  crates/cargo-test-support/src/lib.rs
Labels: S-waiting-on-bors

#10970 [BETA 1.64] Only override published resolver when the workspace is different
  src/cargo/core/features.rs
  src/cargo/core/workspace.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/features_namespaced.rs
  tests/testsuite/inheritable_workspace_fields.rs
  tests/testsuite/package.rs
  tests/testsuite/publish.rs
  tests/testsuite/weak_dep_features.rs
Labels: S-waiting-on-bors

#10968 Improve error msg for get target runner
  src/cargo/core/compiler/compilation.rs
  tests/testsuite/tool_paths.rs
Labels: S-waiting-on-bors

#10930 Enable two windows tests
  tests/testsuite/concurrent.rs
  tests/testsuite/version.rs
Labels: S-waiting-on-bors

#10978 [docs] Remove extra "in" from `cargo-test.md`
  src/doc/man/generated_txt/cargo-bench.txt
  src/doc/man/generated_txt/cargo-build.txt
  src/doc/man/generated_txt/cargo-check.txt
  src/doc/man/generated_txt/cargo-doc.txt
  src/doc/man/generated_txt/cargo-fix.txt
  src/doc/man/generated_txt/cargo-install.txt
  src/doc/man/generated_txt/cargo-run.txt
  src/doc/man/generated_txt/cargo-rustc.txt
  src/doc/man/generated_txt/cargo-rustdoc.txt
  src/doc/man/generated_txt/cargo-test.txt
  src/doc/man/includes/options-message-format.md
  src/doc/src/commands/cargo-bench.md
  src/doc/src/commands/cargo-build.md
  src/doc/src/commands/cargo-check.md
  src/doc/src/commands/cargo-doc.md
  src/doc/src/commands/cargo-fix.md
  src/doc/src/commands/cargo-install.md
  src/doc/src/commands/cargo-run.md
  src/doc/src/commands/cargo-rustc.md
  src/doc/src/commands/cargo-rustdoc.md
  src/doc/src/commands/cargo-test.md
  src/etc/man/cargo-bench.1
  src/etc/man/cargo-build.1
  src/etc/man/cargo-check.1
  src/etc/man/cargo-doc.1
  src/etc/man/cargo-fix.1
  src/etc/man/cargo-install.1
  src/etc/man/cargo-run.1
  src/etc/man/cargo-rustc.1
  src/etc/man/cargo-rustdoc.1
  src/etc/man/cargo-test.1
Labels: S-waiting-on-bors

#10977 Use `std::thread::scope` to replace crossbeam
  Cargo.toml
  src/cargo/core/compiler/job_queue.rs
Labels: S-waiting-on-bors

#10983 Bump to 0.66.0, update changelog
  CHANGELOG.md
  Cargo.toml
Labels: S-waiting-on-bors

#10975 Fix file locking being not supported on Android raising an error
  src/cargo/util/flock.rs
Labels: S-waiting-on-bors

#10944 Improve error message for an array value in the manifest
  src/cargo/util/toml/mod.rs
  tests/testsuite/metadata.rs
Labels: S-waiting-on-bors

#10988 Warning when precise or aggressive without -p flag
  src/cargo/ops/cargo_generate_lockfile.rs
  tests/testsuite/update.rs
Labels: S-waiting-on-bors

#11001 remove missed reference to workspace inheritance in unstable.md
  src/doc/src/reference/unstable.md
Labels: S-waiting-on-bors

#11002 beta backport: remove missed reference to workspace inheritance in unstable.md
  src/doc/src/reference/unstable.md
Labels: S-waiting-on-bors

#11005 Bump snapbox to 0.3
  Cargo.toml
  crates/cargo-test-support/Cargo.toml
Labels: S-waiting-on-bors

#10999 Improve error message for wrong target names
  src/cargo/ops/cargo_compile.rs
  tests/testsuite/build.rs
  tests/testsuite/run.rs
  tests/testsuite/test.rs
Labels: S-waiting-on-bors

#11008 Ignore broken but excluded file during traversing
  src/cargo/sources/path.rs
  tests/testsuite/package.rs
Labels: S-waiting-on-bors

#11011 Add more tests for aggressive or precise update
  tests/testsuite/update.rs
Labels: S-waiting-on-bors

#11017 Update non-ASCII crate name warning message
  src/cargo/ops/cargo_new.rs
  tests/testsuite/new.rs
Labels: S-waiting-on-bors

#10807 Apply GitHub fast path even for partial hashes
  src/cargo/sources/git/utils.rs
Labels: T-cargo, final-comment-period, disposition-merge, S-waiting-on-bors

#11021 Update cargo-toml-vs-cargo-lock.md
  src/doc/src/guide/cargo-toml-vs-cargo-lock.md
Labels: S-waiting-on-bors

#11025 Fix typo
  src/cargo/core/compiler/build_context/target_info.rs
Labels: S-waiting-on-bors

#11004 Bump git2 to 0.15 and libgit2-sys to 0.14
  Cargo.toml
  crates/cargo-test-support/Cargo.toml
  src/bin/cargo/main.rs
Labels: relnotes, S-waiting-on-bors

#11027 doc: pause, for readability
  src/doc/src/reference/specifying-dependencies.md
Labels: S-waiting-on-bors

#11030 Update compiling requirements.
  README.md
Labels: S-waiting-on-bors

#11033 Very slight `cargo add` documentation improvements
  src/doc/man/cargo-add.md
  src/doc/man/generated_txt/cargo-add.txt
  src/doc/src/commands/cargo-add.md
  src/etc/man/cargo-add.1
Labels: S-waiting-on-bors

#11028 Rework test error handling
  src/bin/cargo/commands/bench.rs
  src/bin/cargo/commands/test.rs
  src/cargo/ops/cargo_test.rs
  src/cargo/util/errors.rs
  src/cargo/util/mod.rs
  tests/testsuite/bench.rs
  tests/testsuite/test.rs
Labels: S-waiting-on-bors

#11039 Add names to CI jobs
  .github/workflows/main.yml
Labels: S-waiting-on-bors

#11019 Document private items for Cargo and publish under contributor guide
  .github/workflows/contrib.yml
  src/cargo/lib.rs
  src/cargo/ops/registry.rs
Labels: S-waiting-on-bors
