Repository rust-lang/cargo, pull requests merged in 2023-06, with the labels that each got.

#12215 nit: fix typo in changelog for 1.70
  CHANGELOG.md
Labels: S-waiting-on-bors

#12217 refactor: housekeeping for 1.70.0
  .github/workflows/main.yml
  Cargo.lock
  Cargo.toml
  crates/cargo-test-support/src/paths.rs
  crates/cargo-test-support/src/tools.rs
  crates/resolver-tests/Cargo.toml
  crates/resolver-tests/tests/resolve.rs
  src/bin/cargo/cli.rs
  src/cargo/core/package_id.rs
  src/cargo/core/shell.rs
  src/cargo/core/source/source_id.rs
  src/cargo/ops/cargo_test.rs
  src/cargo/util/interning.rs
Labels: Command-test, A-dependency-resolution, A-console-output, A-testing-cargo-itself, S-waiting-on-bors, A-cli, A-infrastructure

#12219 Bump to 0.73.0; update changelog
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#12218 Update curl-sys
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#12223 chore: Sort `-Z` flags match statement
  src/cargo/core/features.rs
Labels: S-waiting-on-bors, A-unstable

#12227 Fix typo in changelog
  CHANGELOG.md
Labels: S-waiting-on-bors

#12222 Support "default" option for `build.jobs`
  src/cargo/core/compiler/build_config.rs
  src/cargo/ops/cargo_fetch.rs
  src/cargo/ops/cargo_package.rs
  src/cargo/ops/registry.rs
  src/cargo/util/command_prelude.rs
  src/cargo/util/config/mod.rs
  src/doc/man/generated_txt/cargo-bench.txt
  src/doc/man/generated_txt/cargo-build.txt
  src/doc/man/generated_txt/cargo-check.txt
  src/doc/man/generated_txt/cargo-doc.txt
  src/doc/man/generated_txt/cargo-fix.txt
  src/doc/man/generated_txt/cargo-install.txt
  src/doc/man/generated_txt/cargo-package.txt
  src/doc/man/generated_txt/cargo-publish.txt
  src/doc/man/generated_txt/cargo-run.txt
  src/doc/man/generated_txt/cargo-rustc.txt
  src/doc/man/generated_txt/cargo-rustdoc.txt
  src/doc/man/generated_txt/cargo-test.txt
  src/doc/man/includes/options-jobs.md
  src/doc/src/commands/cargo-bench.md
  src/doc/src/commands/cargo-build.md
  src/doc/src/commands/cargo-check.md
  src/doc/src/commands/cargo-doc.md
  src/doc/src/commands/cargo-fix.md
  src/doc/src/commands/cargo-install.md
  src/doc/src/commands/cargo-package.md
  src/doc/src/commands/cargo-publish.md
  src/doc/src/commands/cargo-run.md
  src/doc/src/commands/cargo-rustc.md
  src/doc/src/commands/cargo-rustdoc.md
  src/doc/src/commands/cargo-test.md
  src/doc/src/reference/config.md
  src/etc/man/cargo-bench.1
  src/etc/man/cargo-build.1
  src/etc/man/cargo-check.1
  src/etc/man/cargo-doc.1
  src/etc/man/cargo-fix.1
  src/etc/man/cargo-install.1
  src/etc/man/cargo-package.1
  src/etc/man/cargo-publish.1
  src/etc/man/cargo-run.1
  src/etc/man/cargo-rustc.1
  src/etc/man/cargo-rustdoc.1
  src/etc/man/cargo-test.1
  tests/testsuite/build.rs
  tests/testsuite/config.rs
Labels: A-documenting-cargo-itself, A-configuration, A-interacts-with-crates.io, Command-fetch, Command-package, S-waiting-on-bors, A-cli, A-cli-help

#12226 Emit error when users try to use a toolchain via the `add` or `install` command
  src/bin/cargo/commands/add.rs
  src/bin/cargo/commands/install.rs
  tests/testsuite/cargo_add/add_toolchain/in
  tests/testsuite/cargo_add/add_toolchain/mod.rs
  tests/testsuite/cargo_add/add_toolchain/out/Cargo.toml
  tests/testsuite/cargo_add/add_toolchain/stderr.log
  tests/testsuite/cargo_add/add_toolchain/stdout.log
  tests/testsuite/cargo_add/mod.rs
  tests/testsuite/install.rs
Labels: Command-install, S-waiting-on-bors, A-cli, Command-add

#12228 doc: the first line should be a simple sentence instead of a heading
  src/cargo/core/compiler/fingerprint/mod.rs
  src/cargo/core/compiler/unit_dependencies.rs
  src/cargo/core/profiles.rs
  src/cargo/core/resolver/features.rs
  src/cargo/ops/cargo_compile/mod.rs
  src/cargo/util/profile.rs
Labels: A-profiles, A-rebuild-detection, A-dependency-resolution, S-waiting-on-bors, A-features2

#12236 Upgrade to `gix` v0.45 for multi-round pack negotiations.
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#12237 doc: point to nightly cargo doc
  README.md
Labels: S-waiting-on-bors

#12239 docs: doc comments for registry source and index
  src/cargo/sources/config.rs
  src/cargo/sources/registry/index.rs
  src/cargo/sources/registry/mod.rs
Labels: A-registries, S-waiting-on-bors

#12234 fix: disable multiplexing on macOS for some versions of curl
  src/bin/cargo/main.rs
  src/cargo/ops/registry.rs
  src/cargo/util/config/mod.rs
  src/cargo/util/network/mod.rs
  src/cargo/util/network/proxy.rs
Labels: A-configuration, A-interacts-with-crates.io, A-networking, S-waiting-on-bors, A-cli, beta-nominated

#12241 test: loose overly matches for git cli output
  tests/testsuite/git.rs
Labels: S-waiting-on-bors

#12240 refactor: registry source cleanup
  crates/cargo-test-support/src/registry.rs
  src/cargo/sources/registry/download.rs
  src/cargo/sources/registry/index.rs
  src/cargo/sources/registry/mod.rs
Labels: A-registries, A-testing-cargo-itself, S-waiting-on-bors

#12242 [beta-1.70] backport #12234
  src/bin/cargo/main.rs
  src/cargo/ops/registry.rs
  src/cargo/util/config/mod.rs
  src/cargo/util/network/mod.rs
  src/cargo/util/network/proxy.rs
  tests/testsuite/git.rs
Labels: A-configuration, A-interacts-with-crates.io, A-networking, S-waiting-on-bors, A-cli

#12244 fix: fetch nested git submodules
  src/cargo/sources/git/utils.rs
  tests/testsuite/git.rs
Labels: A-git, S-waiting-on-bors

#12247 docs: doc comments for all registry kinds
  src/cargo/sources/registry/download.rs
  src/cargo/sources/registry/http_remote.rs
  src/cargo/sources/registry/local.rs
  src/cargo/sources/registry/mod.rs
  src/cargo/sources/registry/remote.rs
  src/cargo/util/config/mod.rs
Labels: A-configuration, A-registries, S-waiting-on-bors, A-local-registry-source, A-sparse-registry

#12248 refactor: registry data kinds cleanup
  src/cargo/core/package.rs
  src/cargo/core/package_id.rs
  src/cargo/ops/cargo_package.rs
  src/cargo/sources/registry/download.rs
  src/cargo/sources/registry/http_remote.rs
  src/cargo/sources/registry/local.rs
  src/cargo/sources/registry/mod.rs
  src/cargo/sources/registry/remote.rs
  src/cargo/util/network/mod.rs
Labels: Command-package, A-registries, A-networking, S-waiting-on-bors, A-local-registry-source, A-sparse-registry

#12224 test(z-flags): Verify `-Z` flags list is sorted
  src/cargo/core/features.rs
Labels: S-waiting-on-bors, A-unstable

#12245 feat: Initial support for single-file packages
  Cargo.lock
  Cargo.toml
  crates/cargo-test-support/src/lib.rs
  deny.toml
  src/bin/cargo/cli.rs
  src/bin/cargo/commands/run.rs
  src/cargo/core/features.rs
  src/cargo/util/toml/embedded.rs
  src/cargo/util/toml/mod.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/main.rs
  tests/testsuite/script.rs
Labels: A-documenting-cargo-itself, Command-run, A-manifest, A-testing-cargo-itself, S-waiting-on-bors, A-cli, A-unstable, A-infrastructure

#12251 docs: clarify the use of `default` branch instead of `main` by default
  src/doc/src/reference/specifying-dependencies.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12262 refactor(embedded)
  src/bin/cargo/commands/run.rs
  src/cargo/util/toml/embedded.rs
Labels: Command-run, S-waiting-on-bors, A-cli

#12261 chore: update dependencies
  Cargo.lock
Labels: S-waiting-on-bors

#12264 Show a better error when container tests fail.
  crates/cargo-test-support/src/containers.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors

#12265 Update triagebot links.
  CHANGELOG.md
  src/doc/contrib/src/process/index.md
  src/doc/contrib/src/process/working-on-cargo.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12267 Fix version requirement example in Dependency Resolution, SemVer compatibility section
  src/doc/src/reference/resolver.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12269 fix(embedded): Don't append hash to bin names
  src/cargo/util/toml/embedded.rs
  tests/testsuite/script.rs
Labels: Command-run, Command-package, A-workspaces, A-manifest, S-waiting-on-bors, A-cli, A-infrastructure

#12276 Clarify the default behavior of cargo-install.
  src/doc/man/cargo-install.md
  src/doc/man/generated_txt/cargo-install.txt
  src/doc/src/commands/cargo-install.md
  src/etc/man/cargo-install.1
Labels: A-documenting-cargo-itself, S-waiting-on-bors, A-cli-help

#12255 fix(embedded): Align package name sanitization with cargo-new
  src/cargo/ops/cargo_new.rs
  src/cargo/util/restricted_names.rs
  src/cargo/util/toml/embedded.rs
  tests/testsuite/script.rs
Labels: Command-run, Command-new, S-waiting-on-bors, A-cli

#12258 refactor(embedded): Switch to `syn` for parsing doc comments
  Cargo.lock
  Cargo.toml
  src/cargo/util/toml/embedded.rs
Labels: S-waiting-on-bors, Z-script

#12268 fix(embedded): Don't create an intermediate manifest
  Cargo.lock
  Cargo.toml
  deny.toml
  src/bin/cargo/commands/run.rs
  src/cargo/core/manifest.rs
  src/cargo/core/workspace.rs
  src/cargo/ops/cargo_package.rs
  src/cargo/util/toml/embedded.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/script.rs
Labels: Command-run, Command-package, A-workspaces, A-manifest, S-waiting-on-bors, A-cli, A-infrastructure

#12279 feat: prepare for the next lockfile bump
  src/cargo/core/features.rs
  src/cargo/core/resolver/encode.rs
  src/cargo/core/resolver/resolve.rs
  src/cargo/ops/lockfile.rs
  tests/testsuite/lockfile_compat.rs
Labels: A-dependency-resolution, S-waiting-on-bors, A-lockfile, A-unstable

#12282 fix(embeded): Don't pollute the scripts dir with `target/`
  src/cargo/core/workspace.rs
  tests/testsuite/script.rs
Labels: A-workspaces, S-waiting-on-bors

#12283 fix(embedded): Don't auto-discover build.rs files
  src/cargo/util/toml/embedded.rs
  tests/testsuite/script.rs
Labels: S-waiting-on-bors

#12221 Enable `doctest-in-workspace` by default
  src/cargo/core/features.rs
  src/cargo/ops/cargo_test.rs
  src/doc/man/cargo-test.md
  src/doc/man/generated_txt/cargo-test.txt
  src/doc/src/commands/cargo-test.md
  src/doc/src/reference/unstable.md
  src/etc/man/cargo-test.1
  tests/testsuite/build_script.rs
  tests/testsuite/doc.rs
Labels: A-documenting-cargo-itself, Command-test, S-waiting-on-bors, A-cli-help, A-unstable

#12288 docs: some tweaks around `cargo test`
  src/doc/man/cargo-test.md
  src/doc/man/generated_txt/cargo-test.txt
  src/doc/src/commands/cargo-test.md
  src/doc/src/reference/unstable.md
  src/etc/man/cargo-test.1
Labels: A-documenting-cargo-itself, S-waiting-on-bors, A-cli-help

#12285 fix: remove `-Zjobserver-per-rustc` again
  src/cargo/core/features.rs
Labels: S-waiting-on-bors, A-unstable

#12291 Convert valid feature name warning to an error.
  crates/resolver-tests/src/lib.rs
  src/cargo/core/resolver/version_prefs.rs
  src/cargo/core/summary.rs
  src/cargo/sources/registry/index.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/features.rs
Labels: A-dependency-resolution, A-registries, A-manifest, S-waiting-on-bors

#12281 feat(cli): Support `cargo Cargo.toml`
  src/bin/cargo/cli.rs
  src/bin/cargo/commands/run.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/script.rs
Labels: A-documenting-cargo-itself, Command-run, S-waiting-on-bors, A-cli

#12289 fix: Allow embedded manifests in all commands
  src/bin/cargo/commands/run.rs
  src/cargo/util/command_prelude.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/script.rs
Labels: Command-run, A-manifest, S-waiting-on-bors, A-cli

#12299 docs(unstable): Point stable-unstable docs to nightly docs
  src/doc/src/reference/unstable.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12298 Add `.toml` file extension restriction for `-Zconfig-include`
  src/cargo/util/config/mod.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/config_include.rs
Labels: A-documenting-cargo-itself, A-configuration, S-waiting-on-bors

#12302 -Znext-lockfile-bump: Don't suggest using -Z on stable
  src/cargo/core/resolver/encode.rs
  tests/testsuite/lockfile_compat.rs
Labels: A-dependency-resolution, S-waiting-on-bors, A-lockfile

#12303 fix(script): Process config relative to script, not CWD
  src/bin/cargo/commands/run.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/script.rs
Labels: A-documenting-cargo-itself, Command-run, S-waiting-on-bors, A-cli

#12287 cargo script example needs nightly -Zscript feature
  src/doc/src/reference/unstable.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors, Z-script

#12308 docs(unstable): Update script documentation
  src/doc/src/reference/unstable.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12305 fix(script): Be quiet on programmatic output
  src/bin/cargo/cli.rs
  src/bin/cargo/commands/mod.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/script.rs
Labels: A-documenting-cargo-itself, S-waiting-on-bors, A-cli

#12290 refactor(registry): extract and rearrange items to their own modules
  src/bin/cargo/main.rs
  src/cargo/core/package.rs
  src/cargo/ops/mod.rs
  src/cargo/ops/registry.rs
  src/cargo/ops/registry/login.rs
  src/cargo/ops/registry/logout.rs
  src/cargo/ops/registry/mod.rs
  src/cargo/ops/registry/owner.rs
  src/cargo/ops/registry/publish.rs
  src/cargo/ops/registry/search.rs
  src/cargo/ops/registry/yank.rs
  src/cargo/sources/git/oxide.rs
  src/cargo/sources/registry/http_remote.rs
  src/cargo/util/auth/asymmetric.rs
  src/cargo/util/auth/mod.rs
  src/cargo/util/config/mod.rs
  src/cargo/util/network/http.rs
  src/cargo/util/network/mod.rs
  triagebot.toml
Labels: A-git, A-configuration, A-interacts-with-crates.io, A-registries, A-networking, S-waiting-on-bors, A-cli, A-sparse-registry, A-infrastructure

#12318 doc: should be `.cargo-ok`
  src/cargo/sources/registry/mod.rs
Labels: A-registries, S-waiting-on-bors

#12317 refactor: use macro to remove duplication of workspace inheritable fields getters
  src/cargo/util/toml/mod.rs
Labels: A-manifest, S-waiting-on-bors

#12321 Don't try to compile cargo-credential-gnome-secret on non-Linux platforms.
  credential/cargo-credential-gnome-secret/build.rs
  credential/cargo-credential-gnome-secret/src/libsecret.rs
  credential/cargo-credential-gnome-secret/src/main.rs
Labels: S-waiting-on-bors, A-registry-authentication

#12319 Add some more documentation for Source download functions.
  src/cargo/core/source/mod.rs
Labels: S-waiting-on-bors

#12322 Add READMEs for the credential helpers.
  credential/cargo-credential-1password/README.md
  credential/cargo-credential-gnome-secret/README.md
  credential/cargo-credential-macos-keychain/README.md
  credential/cargo-credential-wincred/README.md
Labels: S-waiting-on-bors, A-registry-authentication
