Repository rust-lang/cargo, pull requests merged in 2023-02, with the labels that each got.

#11665 Handle .cargo-ok being truncated
  src/cargo/sources/registry/mod.rs
  tests/testsuite/registry.rs
Labels: S-waiting-on-bors

#11656 Replace `winapi` with `windows-sys` crate.
  Cargo.toml
  crates/cargo-test-support/Cargo.toml
  crates/cargo-test-support/src/paths.rs
  crates/cargo-util/Cargo.toml
  crates/cargo-util/src/paths.rs
  crates/cargo-util/src/process_builder.rs
  crates/cargo-util/src/process_error.rs
  crates/cargo-util/src/read2.rs
  crates/credential/cargo-credential-wincred/Cargo.toml
  crates/credential/cargo-credential-wincred/src/main.rs
  crates/home/Cargo.toml
  crates/home/src/lib.rs
  crates/home/src/windows.rs
  src/cargo/core/shell.rs
  src/cargo/util/cpu.rs
  src/cargo/util/flock.rs
  src/cargo/util/job.rs
Labels: S-waiting-on-bors

#11635 Add partial support for SSH known hosts markers
  src/cargo/sources/git/known_hosts.rs
Labels: S-waiting-on-bors

#11651 Fix the wrong comment
  src/cargo/ops/registry.rs
  src/cargo/util/auth.rs
Labels: S-waiting-on-bors

#11644 config: Deny CARGO_HOME in [env] table (fixes #11590)
  src/cargo/util/config/mod.rs
  tests/testsuite/cargo_env_config.rs
Labels: S-waiting-on-bors

#11252 Turn off debuginfo for build dependencies v2
  src/cargo/core/compiler/custom_build.rs
  src/cargo/core/compiler/job_queue.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/core/profiles.rs
  src/cargo/ops/cargo_compile/mod.rs
  src/doc/src/reference/profiles.md
  tests/testsuite/build.rs
  tests/testsuite/build_script.rs
  tests/testsuite/features2.rs
  tests/testsuite/freshness.rs
  tests/testsuite/profile_config.rs
  tests/testsuite/profile_targets.rs
Labels: T-cargo, S-waiting-on-bors

#11669 doc: more doc comments and intra-doc links
  src/cargo/core/compiler/build_context/mod.rs
  src/cargo/core/compiler/context/compilation_files.rs
  src/cargo/core/compiler/context/mod.rs
  src/cargo/core/compiler/crate_type.rs
  src/cargo/core/compiler/fingerprint.rs
  src/cargo/core/compiler/fingerprint/dirty_reason.rs
Labels: S-waiting-on-bors

#11672 Verify source before recompile
  src/cargo/core/compiler/fingerprint.rs
  tests/testsuite/freshness.rs
Labels: S-waiting-on-bors

#11673 refactor: mod.rs over "name".rs for consistency
  src/cargo/core/compiler/fingerprint/mod.rs
Labels: S-waiting-on-bors

#11676 Fix unstable chapter layout for codegen-backend
  src/doc/src/reference/unstable.md
Labels: S-waiting-on-bors

#11675 Add more guidance on how to implement unstable features
  src/cargo/core/features.rs
Labels: S-waiting-on-bors

#11678 util toml targets: Do not infer directory as a file
  src/cargo/util/toml/targets.rs
  tests/testsuite/build.rs
Labels: S-waiting-on-bors

#11674 [beta-1.68] Backport fixes
  src/cargo/core/compiler/fingerprint.rs
  src/cargo/sources/registry/http_remote.rs
  src/cargo/sources/registry/remote.rs
  tests/testsuite/freshness.rs
  tests/testsuite/registry_auth.rs
Labels: S-waiting-on-bors

#11679 chore: autolabel more for `A-*`
  triagebot.toml
Labels: S-waiting-on-bors

#11692 Update 1password to the version 2 CLI
  crates/credential/cargo-credential-1password/src/main.rs
Labels: S-waiting-on-bors, A-registry-authentication

#11690 Update CHANGELOG for 1.68 backports
  CHANGELOG.md
Labels: S-waiting-on-bors

#11700 Re-export cargo_new::NewProjectKind as public
  src/cargo/ops/mod.rs
Labels: S-waiting-on-bors

#11701 add comment to lto.rs
  src/cargo/core/compiler/lto.rs
Labels: S-waiting-on-bors, A-lto

#11699 Deny warnings in CI, not locally
  .github/workflows/main.yml
  Cargo.toml
  crates/cargo-test-support/Cargo.toml
  crates/cargo-test-support/src/lib.rs
  src/cargo/lib.rs
  tests/testsuite/main.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors

#11703 doc: more doc comments and intra-doc links
  src/cargo/core/compiler/artifact.rs
  src/cargo/core/compiler/context/mod.rs
  src/cargo/core/compiler/fingerprint/mod.rs
  src/cargo/core/compiler/job.rs
  src/cargo/core/compiler/output_depinfo.rs
  src/cargo/core/compiler/rustdoc.rs
  src/cargo/util/queue.rs
Labels: A-build-execution, A-rebuild-detection, S-waiting-on-bors, A-dep-info

#11618 chore: Update to toml v0.6, toml_edit v0.18
  Cargo.toml
  benches/capture/Cargo.toml
  benches/capture/src/main.rs
  crates/cargo-test-support/Cargo.toml
  crates/cargo-test-support/src/registry.rs
  src/cargo/core/manifest.rs
  src/cargo/core/package.rs
  src/cargo/core/workspace.rs
  src/cargo/ops/cargo_config.rs
  src/cargo/ops/cargo_new.rs
  src/cargo/ops/cargo_output_metadata.rs
  src/cargo/ops/common_for_install_and_uninstall.rs
  src/cargo/ops/lockfile.rs
  src/cargo/ops/vendor.rs
  src/cargo/util/config/key.rs
  src/cargo/util/config/mod.rs
  src/cargo/util/config/target.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/bad_config.rs
  tests/testsuite/build.rs
  tests/testsuite/cargo_add/invalid_manifest/stderr.log
  tests/testsuite/cargo_alias_config.rs
  tests/testsuite/config.rs
  tests/testsuite/config_cli.rs
  tests/testsuite/git.rs
  tests/testsuite/inheritable_workspace_fields.rs
  tests/testsuite/install.rs
  tests/testsuite/install_upgrade.rs
  tests/testsuite/login.rs
  tests/testsuite/logout.rs
  tests/testsuite/metadata.rs
  tests/testsuite/patch.rs
  tests/testsuite/workspaces.rs
Labels: A-configuration, Command-new, Command-metadata, A-workspaces, A-manifest, A-testing-cargo-itself, S-waiting-on-bors, Command-vendor, A-lockfile

#11705 Set CARGO_BIN_NAME environment variable also for binary examples
  src/cargo/core/compiler/compilation.rs
  src/doc/src/reference/environment-variables.md
  tests/testsuite/build.rs
Labels: A-documenting-cargo-itself, A-build-execution, S-waiting-on-bors

#11711 doc: doc comments and intra-doc links for `core::compiler`
  src/cargo/core/compiler/compilation.rs
  src/cargo/core/compiler/compile_kind.rs
  src/cargo/core/compiler/context/mod.rs
  src/cargo/core/compiler/future_incompat.rs
  src/cargo/core/compiler/links.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/core/compiler/timings.rs
  src/cargo/core/compiler/unit.rs
  src/cargo/core/compiler/unit_graph.rs
Labels: A-documenting-cargo-itself, A-build-execution, S-waiting-on-bors, A-timings, A-links, A-future-incompat

#11712 Run CI for macOS on nightly
  .github/workflows/main.yml
  tests/testsuite/clean.rs
Labels: S-waiting-on-bors

#11715 Amend `mdman` tests.
  crates/mdman/tests/compare/expected/formatting.1
  crates/mdman/tests/compare/expected/formatting.md
  crates/mdman/tests/compare/expected/formatting.txt
  crates/mdman/tests/compare/formatting.md
Labels: S-waiting-on-bors, A-cli-help

#11716 chore: bump mdbook to 0.4.27
  .github/workflows/contrib.yml
  .github/workflows/main.yml
Labels: S-waiting-on-bors

#11719 chore: Make dependencies alphabetical order
  Cargo.toml
  crates/cargo-test-support/Cargo.toml
  crates/crates-io/Cargo.toml
  crates/resolver-tests/Cargo.toml
Labels: A-interacts-with-crates.io, A-dependency-resolution, A-testing-cargo-itself, S-waiting-on-bors

#11722 Add clippy lints
  .github/workflows/main.yml
  src/cargo/lib.rs
Labels: S-waiting-on-bors

#11600 Error on invalid alphanumeric token for crates.io
  crates/crates-io/lib.rs
  src/cargo/ops/registry.rs
  tests/testsuite/login.rs
Labels: relnotes, A-interacts-with-crates.io, I-nominated, S-waiting-on-bors

#11733 fix: unsupported protocol error on old macos version
  src/cargo/core/package.rs
  src/cargo/sources/registry/http_remote.rs
  src/cargo/util/network.rs
Labels: A-registries, A-networking, S-waiting-on-bors, A-sparse-registry

#11724 Update comment about cargo-ok
  src/cargo/sources/registry/mod.rs
Labels: A-registries, S-waiting-on-bors

#11735 [beta-1.68] backport #11733
  src/cargo/core/package.rs
  src/cargo/sources/registry/http_remote.rs
  src/cargo/util/network.rs
Labels: A-registries, A-networking, S-waiting-on-bors, A-sparse-registry

#11741 Fix typo
  src/doc/src/reference/manifest.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#11740 Enhance help texts of position args
  src/bin/cargo/commands/run.rs
  src/bin/cargo/commands/rustc.rs
  src/bin/cargo/commands/rustdoc.rs
Labels: Command-run, Command-rustc, Command-rustdoc, S-waiting-on-bors, A-cli

#11747 mdman: update pretty_assertions to reduce deps
  crates/mdman/Cargo.lock
  crates/mdman/Cargo.toml
Labels: S-waiting-on-bors, A-cli-help

#11749 Update curl-sys to use libcurl 7.88.1
  Cargo.toml
Labels: S-waiting-on-bors

#11727 Read environment variables through `Config` instead of `std::env::var(_os)`
  src/bin/cargo/main.rs
  src/cargo/core/compiler/build_context/target_info.rs
  src/cargo/core/compiler/compilation.rs
  src/cargo/core/compiler/context/compilation_files.rs
  src/cargo/core/compiler/standard_lib.rs
  src/cargo/core/profiles.rs
  src/cargo/ops/cargo_compile/mod.rs
  src/cargo/ops/cargo_config.rs
  src/cargo/ops/cargo_doc.rs
  src/cargo/ops/cargo_install.rs
  src/cargo/ops/cargo_new.rs
  src/cargo/ops/common_for_install_and_uninstall.rs
  src/cargo/ops/fix.rs
  src/cargo/ops/registry.rs
  src/cargo/sources/config.rs
  src/cargo/sources/git/known_hosts.rs
  src/cargo/sources/git/utils.rs
  src/cargo/sources/registry/mod.rs
  src/cargo/util/auth.rs
  src/cargo/util/config/de.rs
  src/cargo/util/config/mod.rs
  src/cargo/util/diagnostic_server.rs
  src/cargo/util/progress.rs
Labels: A-git, Command-doc, A-configuration, A-errors, Command-new, Command-install, A-interacts-with-crates.io, A-build-execution, A-profiles, A-registries, A-console-output, Command-fix, S-waiting-on-bors, A-cli, A-cfg-expr, A-layout, A-registry-authentication

#11750 reuse url encoding from `url` crate, don't use separate `percent-encoding`
  Cargo.toml
  src/cargo/ops/registry.rs
Labels: A-interacts-with-crates.io, S-waiting-on-bors

#11753 Fix typo in sparse-registry warning message
  src/cargo/core/features.rs
Labels: S-waiting-on-bors, A-unstable

#11725 Switch some tests from `build` to `check`
  tests/testsuite/alt_registry.rs
  tests/testsuite/bad_config.rs
  tests/testsuite/bad_manifest_path.rs
  tests/testsuite/build_script_env.rs
  tests/testsuite/cache_messages.rs
  tests/testsuite/cargo_env_config.rs
  tests/testsuite/cargo_features.rs
  tests/testsuite/cfg.rs
  tests/testsuite/check_cfg.rs
  tests/testsuite/config.rs
  tests/testsuite/config_include.rs
  tests/testsuite/corrupt_git.rs
  tests/testsuite/death.rs
  tests/testsuite/dep_info.rs
  tests/testsuite/directory.rs
  tests/testsuite/doc.rs
  tests/testsuite/edition.rs
  tests/testsuite/features.rs
  tests/testsuite/features2.rs
  tests/testsuite/features_namespaced.rs
  tests/testsuite/fix.rs
  tests/testsuite/future_incompat_report.rs
  tests/testsuite/git.rs
  tests/testsuite/git_auth.rs
  tests/testsuite/git_gc.rs
  tests/testsuite/inheritable_workspace_fields.rs
  tests/testsuite/jobserver.rs
  tests/testsuite/local_registry.rs
  tests/testsuite/lockfile_compat.rs
  tests/testsuite/message_format.rs
  tests/testsuite/metabuild.rs
  tests/testsuite/net_config.rs
  tests/testsuite/offline.rs
  tests/testsuite/package.rs
  tests/testsuite/package_features.rs
  tests/testsuite/patch.rs
  tests/testsuite/path.rs
  tests/testsuite/paths.rs
  tests/testsuite/proc_macro.rs
  tests/testsuite/profile_overrides.rs
  tests/testsuite/progress.rs
  tests/testsuite/pub_priv.rs
  tests/testsuite/registry.rs
  tests/testsuite/registry_auth.rs
  tests/testsuite/replace.rs
  tests/testsuite/rust_version.rs
  tests/testsuite/rustflags.rs
  tests/testsuite/update.rs
  tests/testsuite/vendor.rs
  tests/testsuite/workspaces.rs
Labels: S-waiting-on-bors

#11748 use consistent case
  src/doc/src/reference/workspaces.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#11755 Revert "Update curl-sys to use libcurl 7.88.1"
  Cargo.toml
Labels: S-waiting-on-bors

#11754 Make more reads of environment variables go through the `Config`
  src/cargo/core/compiler/fingerprint/mod.rs
  src/cargo/util/config/mod.rs
  src/cargo/util/rustc.rs
Labels: A-configuration, A-build-execution, A-rebuild-detection, A-build-scripts, A-dependency-resolution, S-waiting-on-bors, A-cache-messages, A-features2

#11757 Scrub more of the test environment
  crates/cargo-test-support/src/lib.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors

#11758 refactor(job_queue): docs and move types around
  src/cargo/core/compiler/custom_build.rs
  src/cargo/core/compiler/fingerprint/mod.rs
  src/cargo/core/compiler/job_queue/job.rs
  src/cargo/core/compiler/job_queue/job_state.rs
  src/cargo/core/compiler/job_queue/mod.rs
  src/cargo/core/compiler/mod.rs
Labels: A-build-execution, A-rebuild-detection, A-build-scripts, S-waiting-on-bors

#11759 chore: bump is-terminal to 0.4.4
  Cargo.toml
Labels: S-waiting-on-bors, beta-nominated

#11760 [beta-1.68] backport #11759
  Cargo.toml
Labels: S-waiting-on-bors

#11410 Suggest cargo add when installing library crate
  src/cargo/ops/cargo_install.rs
  tests/testsuite/install.rs
Labels: Command-install, S-waiting-on-bors

#11650 Make some blocking tests non-blocking
  crates/cargo-test-support/src/registry.rs
  tests/testsuite/alt_registry.rs
  tests/testsuite/artifact_dep.rs
  tests/testsuite/cargo_features.rs
  tests/testsuite/credential_process.rs
  tests/testsuite/features_namespaced.rs
  tests/testsuite/inheritable_workspace_fields.rs
  tests/testsuite/publish.rs
  tests/testsuite/weak_dep_features.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors

#11766 Fix tests with nondeterministic ordering
  tests/testsuite/inheritable_workspace_fields.rs
Labels: S-waiting-on-bors

#11643 Error message for transitive artifact dependencies with targets the package doesn't directly interact with
  src/cargo/core/compiler/build_context/target_info.rs
  src/cargo/core/compiler/compilation.rs
  tests/testsuite/artifact_dep.rs
Labels: S-waiting-on-bors

#11771 Fix warning with tempfile
  src/cargo/ops/cargo_install.rs
  tests/testsuite/install.rs
Labels: Command-install, S-waiting-on-bors

#11756 Fix Cargo removing the sparse+ prefix from sparse URLs in .crates.toml
  src/cargo/core/source/source_id.rs
  src/cargo/util/canonical_url.rs
  tests/testsuite/install.rs
Labels: S-waiting-on-bors, beta-nominated

#11763 Added documentation for the configuration discovery of `cargo install` to the man pages
  src/doc/man/cargo-install.md
  src/doc/man/generated_txt/cargo-install.txt
  src/doc/src/commands/cargo-install.md
  src/etc/man/cargo-install.1
Labels: A-documenting-cargo-itself, Command-install, S-waiting-on-bors, A-cli, A-cli-help

#11773 [beta-1.68] backport #11756
  src/cargo/core/source/source_id.rs
  src/cargo/ops/cargo_install.rs
  src/cargo/util/canonical_url.rs
  tests/testsuite/install.rs
Labels: Command-install, S-waiting-on-bors

#11774 Addition of support for -F as an alias for --features
  src/doc/man/cargo-add.md
  src/doc/man/generated_txt/cargo-add.txt
  src/doc/src/commands/cargo-add.md
  src/etc/man/cargo-add.1
Labels: A-documenting-cargo-itself, S-waiting-on-bors, A-cli-help

#11767 bump jobserver to respect `--jobserver-auth=fifo:PATH`
  Cargo.toml
  crates/cargo-util/Cargo.toml
  tests/testsuite/jobserver.rs
Labels: S-waiting-on-bors
