Repository rust-lang/cargo, pull requests merged in 2023-04, with the labels that each got.

#11881 Add delays to network retries.
  Cargo.toml
  crates/cargo-test-support/src/registry.rs
  src/cargo/core/package.rs
  src/cargo/sources/git/oxide.rs
  src/cargo/sources/git/utils.rs
  src/cargo/sources/registry/http_remote.rs
  src/cargo/util/network/mod.rs
  src/cargo/util/network/retry.rs
  src/cargo/util/network/sleep.rs
  src/doc/src/reference/config.md
  tests/testsuite/git_auth.rs
  tests/testsuite/registry.rs
Labels: A-documenting-cargo-itself, A-git, A-registries, A-testing-cargo-itself, S-waiting-on-bors, A-sparse-registry

#11927 Call out the differences between the index JSON and the API or metadata.
  src/doc/src/reference/registry-index.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#11926 Publish docs: Clarify requirements about the state of the index after publish.
  src/doc/src/reference/registry-web-api.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#11928 Update git2
  Cargo.toml
  crates/cargo-test-support/Cargo.toml
  src/cargo/sources/git/utils.rs
  tests/testsuite/https.rs
  tests/testsuite/ssh.rs
Labels: A-git, A-testing-cargo-itself, S-waiting-on-bors

#11933 Switch benchsuite to the index archive.
  benches/benchsuite/src/lib.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors

#11930 Fix Cargo warning about unused sparse configuration key
  src/cargo/util/auth.rs
  tests/testsuite/alt_registry.rs
Labels: S-waiting-on-bors, A-sparse-registry, A-registry-authentication

#11931 Fix typo in variable name
  src/cargo/ops/cargo_new.rs
Labels: Command-new, S-waiting-on-bors

#11936 Don't query permutations of the path prefix.
  crates/cargo-test-support/src/registry.rs
  src/cargo/sources/registry/index.rs
  tests/testsuite/registry.rs
Labels: A-registries, A-testing-cargo-itself, S-waiting-on-bors

#11937 Stop using UncanonicalizedIter for QueryKind::Exact
  src/cargo/sources/registry/index.rs
  src/cargo/sources/registry/mod.rs
  tests/testsuite/publish.rs
Labels: A-registries, S-waiting-on-bors

#11942 doc(changelog): `[env]` is a table, not a stable
  CHANGELOG.md
Labels: S-waiting-on-bors

#11941 Update home repo URL
  crates/home/Cargo.toml
Labels: A-environment-variables, S-waiting-on-bors

#11943 docs(changelog): Change wording about auto-fix message
  CHANGELOG.md
Labels: S-waiting-on-bors

#11944 Fix typo
  crates/home/README.md
Labels: A-environment-variables, S-waiting-on-bors

#11866 Add `try_canonicalize` and use it over `std::fs::canonicalize`
  src/cargo/core/compiler/compile_kind.rs
  src/cargo/core/compiler/fingerprint/mod.rs
  src/cargo/ops/vendor.rs
  src/cargo/util/config/mod.rs
  src/cargo/util/mod.rs
Labels: A-configuration, A-rebuild-detection, S-waiting-on-bors, Command-vendor

#11952 Validate token on publish.
  crates/crates-io/lib.rs
  tests/testsuite/publish.rs
Labels: A-interacts-with-crates.io, S-waiting-on-bors

#11951 Fix credential token format validation.
  crates/crates-io/lib.rs
  tests/testsuite/login.rs
Labels: A-interacts-with-crates.io, S-waiting-on-bors

#11878 Add more information to HTTP errors to help with debugging.
  src/cargo/core/package.rs
  src/cargo/sources/registry/http_remote.rs
  src/cargo/util/errors.rs
  src/cargo/util/network/retry.rs
  tests/testsuite/registry.rs
  tests/testsuite/registry_auth.rs
Labels: A-registries, A-networking, S-waiting-on-bors, A-sparse-registry

#11882 Correct the bug report for `cargo clippy --fix`
  crates/cargo-test-support/src/lib.rs
  src/cargo/core/compiler/job_queue/mod.rs
  src/cargo/util/diagnostic_server.rs
  tests/testsuite/check.rs
  tests/testsuite/fix.rs
Labels: A-errors, A-build-execution, A-testing-cargo-itself, S-waiting-on-bors

#11963 Use restricted Damerau-Levenshtein algorithm
  src/cargo/core/package_id_spec.rs
  src/cargo/core/resolver/errors.rs
  src/cargo/core/workspace.rs
  src/cargo/ops/cargo_clean.rs
  src/cargo/util/edit_distance.rs
  src/cargo/util/lev_distance.rs
  src/cargo/util/mod.rs
Labels: Command-clean, A-workspaces, A-dependency-resolution, S-waiting-on-bors

#11976 Fix flaky not_found_permutations test.
  tests/testsuite/registry.rs
Labels: S-waiting-on-bors

#11851 Make cargo a workspace
  .github/workflows/main.yml
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#11979 chore: use openssl only on non-Windows platforms
  Cargo.toml
Labels: S-waiting-on-bors

#11982 Clarify some 1.69 changelog entries.
  CHANGELOG.md
Labels: S-waiting-on-bors

#11983 [beta-1.70] Backport not_found_permutations test fix.
  tests/testsuite/registry.rs
Labels: S-waiting-on-bors

#11981 Recompile on profile rustflags changes
  src/cargo/core/profiles.rs
Labels: A-profiles, S-waiting-on-bors

#11994 ci: check if Cargo.lock is up-to-date
  .github/workflows/main.yml
  ci/validate-man.sh
Labels: S-waiting-on-bors

#11995 Add S-triage auto-label.
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: S-waiting-on-bors

#11993 fix: Allow win/mac credential managers to build on all platforms
  crates/credential/cargo-credential-macos-keychain/src/main.rs
  crates/credential/cargo-credential-wincred/src/main.rs
  crates/credential/cargo-credential/src/lib.rs
Labels: S-waiting-on-bors, A-registry-authentication

#11996 chore: Use globs for workspace members
  Cargo.toml
  credential/README.md
  credential/cargo-credential-1password/Cargo.toml
  credential/cargo-credential-1password/src/main.rs
  credential/cargo-credential-gnome-secret/Cargo.toml
  credential/cargo-credential-gnome-secret/build.rs
  credential/cargo-credential-gnome-secret/src/main.rs
  credential/cargo-credential-macos-keychain/Cargo.toml
  credential/cargo-credential-macos-keychain/src/main.rs
  credential/cargo-credential-wincred/Cargo.toml
  credential/cargo-credential-wincred/src/main.rs
  credential/cargo-credential/Cargo.toml
  credential/cargo-credential/README.md
  credential/cargo-credential/src/lib.rs
  src/cargo/lib.rs
  triagebot.toml
Labels: S-waiting-on-bors

#11998 Update linux-raw-sys to 0.3.2
  Cargo.lock
Labels: S-waiting-on-bors

#12002 Fix broken links in contributor guide.
  src/doc/contrib/src/implementation/console.md
  src/doc/contrib/src/implementation/filesystem.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12003 Update contributor guide with new issue labels.
  src/doc/contrib/src/index.md
  src/doc/contrib/src/issues.md
  src/doc/contrib/src/process/index.md
  src/doc/contrib/src/process/unstable.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12011 Fix semver checks for 1.69
  src/doc/src/reference/semver.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12013 `--help` output use line wrap
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#12000 Remove `src/doc` from `exclude` list in Cargo.toml
  .github/workflows/main.yml
  Cargo.lock
  Cargo.toml
  crates/semver-check/Cargo.toml
  crates/semver-check/src/main.rs
Labels: S-waiting-on-bors

#12012 Bump to 0.72.0; update changelog
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#11958 Allow named debuginfo options in Cargo.toml
  src/cargo/core/compiler/mod.rs
  src/cargo/core/profiles.rs
  src/cargo/util/machine_message.rs
  src/cargo/util/toml/mod.rs
  src/doc/src/reference/profiles.md
  tests/testsuite/bad_config.rs
  tests/testsuite/config.rs
  tests/testsuite/profile_config.rs
Labels: A-documenting-cargo-itself, A-build-execution, A-profiles, A-console-output, A-manifest, S-waiting-on-bors

#12018 Update outdated crates.io URLs in publishing guide
  src/doc/src/reference/publishing.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12016 Add the Win32_System_Console feature since it is used
  Cargo.toml
Labels: S-waiting-on-bors

#12019 Bump versions of local crates
  Cargo.lock
  Cargo.toml
  crates/cargo-platform/Cargo.toml
  crates/crates-io/Cargo.toml
Labels: A-interacts-with-crates.io, S-waiting-on-bors, A-cfg-expr, beta-nominated

#12020 Remove wrong url in benchsuite manifest.
  benches/benchsuite/Cargo.toml
Labels: A-testing-cargo-itself, S-waiting-on-bors

#12001 Improve error message for empty dep
  src/cargo/util/toml/mod.rs
  tests/testsuite/bad_config.rs
  tests/testsuite/inheritable_workspace_fields.rs
Labels: A-manifest, S-waiting-on-bors

#12005 Update openssl-src to 111.25.3+1.1.1t
  Cargo.lock
Labels: S-waiting-on-bors

#12014 Bump libc to 0.2.142
  Cargo.lock
Labels: S-waiting-on-bors

#12021 Update windows-sys
  Cargo.lock
  Cargo.toml
  crates/cargo-test-support/Cargo.toml
  crates/cargo-util/Cargo.toml
  crates/home/CHANGELOG.md
  crates/home/Cargo.toml
  crates/home/src/lib.rs
  credential/cargo-credential-wincred/Cargo.toml
  src/cargo/core/shell.rs
Labels: A-console-output, A-environment-variables, A-testing-cargo-itself, S-waiting-on-bors, A-registry-authentication

#12026 ci: requires `test_gitoxide` and `lockfile` for both bors success and failure
  .github/workflows/main.yml
Labels: S-waiting-on-bors

#12024 CI: use `-p` to specify workspace members instead of `--manifest-path`
  .github/workflows/main.yml
  src/doc/build-man.sh
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12027 chore: make credential dependencies platform-specific
  .github/workflows/main.yml
  credential/cargo-credential-macos-keychain/Cargo.toml
  credential/cargo-credential-wincred/Cargo.toml
Labels: S-waiting-on-bors, A-registry-authentication

#12025 CI: ensure intra links for all members are checked
  .github/workflows/main.yml
Labels: S-waiting-on-bors

#12029 fix: apply `[env]` to target info discovery rustc
  src/cargo/core/compiler/build_context/target_info.rs
  src/cargo/core/compiler/compilation.rs
  src/cargo/core/compiler/mod.rs
  tests/testsuite/cargo_env_config.rs
Labels: A-build-execution, S-waiting-on-bors, A-cfg-expr

#12032 Clarify documentation around test target setting.
  src/doc/man/cargo-bench.md
  src/doc/man/cargo-test.md
  src/doc/man/generated_txt/cargo-bench.txt
  src/doc/man/generated_txt/cargo-test.txt
  src/doc/src/commands/cargo-bench.md
  src/doc/src/commands/cargo-test.md
  src/etc/man/cargo-bench.1
  src/etc/man/cargo-test.1
Labels: A-documenting-cargo-itself, S-waiting-on-bors, A-cli-help

#12038 [beta-1.70] backport add the Win32_System_Console feature
  Cargo.toml
  src/doc/src/reference/semver.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12036 Warn instead of error in `cargo package` on empty `readme` or `license-file` in manifest
  src/cargo/ops/cargo_package.rs
  tests/testsuite/package.rs
  tests/testsuite/publish.rs
Labels: Command-package, S-waiting-on-bors

#12037 Update home dependency
  Cargo.lock
  Cargo.toml
  crates/home/CHANGELOG.md
Labels: A-environment-variables, S-waiting-on-bors

#12040 docs(ref): Specify 'rust_version' in Index format
  src/doc/src/reference/registry-index.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12039 chore(xtask): Add `cargo xtask unpublished`
  .cargo/config.toml
  .gitignore
  Cargo.lock
  crates/xtask-unpublished/Cargo.toml
  crates/xtask-unpublished/src/main.rs
  crates/xtask-unpublished/src/xtask.rs
Labels: S-waiting-on-bors, A-infrastructure

#12041 Include rust-version in publish request
  crates/crates-io/lib.rs
  src/cargo/core/manifest.rs
  src/cargo/ops/registry.rs
  src/cargo/util/toml/mod.rs
  src/doc/src/reference/registry-index.md
  src/doc/src/reference/registry-web-api.md
  tests/testsuite/alt_registry.rs
  tests/testsuite/artifact_dep.rs
  tests/testsuite/features_namespaced.rs
  tests/testsuite/inheritable_workspace_fields.rs
  tests/testsuite/publish.rs
  tests/testsuite/weak_dep_features.rs
Labels: A-documenting-cargo-itself, A-interacts-with-crates.io, A-manifest, S-waiting-on-bors

#12045 chore: Mark unpublished crates as such
  Cargo.lock
  benches/benchsuite/Cargo.toml
  crates/mdman/Cargo.toml
  crates/resolver-tests/Cargo.toml
  crates/semver-check/Cargo.toml
Labels: A-dependency-resolution, A-testing-cargo-itself, S-waiting-on-bors, A-cli-help

#12047 home: fix & enhance documentation
  Cargo.lock
  crates/home/CHANGELOG.md
  crates/home/Cargo.toml
  crates/home/src/lib.rs
Labels: A-environment-variables, S-waiting-on-bors

#12049 fix broken markdown in docs
  src/cargo/core/compiler/build_context/target_info.rs
  src/cargo/lib.rs
  src/cargo/sources/registry/mod.rs
Labels: A-registries, S-waiting-on-bors, A-cfg-expr

#12052 chore: update trigger_files in autolabel
  triagebot.toml
Labels: S-waiting-on-bors

#12044 cargo-tree: Handle -e no-proc-macro when building the graph
  src/cargo/ops/tree/graph.rs
  src/cargo/ops/tree/mod.rs
  tests/testsuite/tree.rs
Labels: S-waiting-on-bors, Command-tree

#12051 chore: new xtask to check stale paths in autolabel defintions
  .cargo/config.toml
  .github/workflows/main.yml
  Cargo.lock
  crates/xtask-stale-label/Cargo.toml
  crates/xtask-stale-label/src/main.rs
Labels: S-waiting-on-bors, A-infrastructure

#12043 feat: Add `-Zmsrv-policy` feature flag
  crates/cargo-test-support/src/publish.rs
  crates/cargo-test-support/src/registry.rs
  crates/resolver-tests/src/lib.rs
  src/cargo/core/features.rs
  src/cargo/core/resolver/version_prefs.rs
  src/cargo/core/summary.rs
  src/cargo/sources/registry/index.rs
  src/cargo/sources/registry/mod.rs
  src/cargo/util/toml/mod.rs
  src/doc/src/reference/unstable.md
Labels: A-documenting-cargo-itself, A-dependency-resolution, A-registries, A-manifest, A-testing-cargo-itself, S-waiting-on-bors, A-unstable

#12048 chore: move build-man workflow away from shell
  .cargo/config.toml
  Cargo.lock
  ci/validate-man.sh
  crates/mdman/Cargo.lock
  crates/mdman/build-man.sh
  crates/mdman/doc/out/mdman.1
  crates/mdman/doc/out/mdman.md
  crates/mdman/doc/out/mdman.txt
  crates/xtask-build-man/Cargo.toml
  crates/xtask-build-man/src/main.rs
  src/doc/README.md
  src/doc/build-man.sh
Labels: A-documenting-cargo-itself, S-waiting-on-bors, A-cli-help, A-infrastructure
