Repository rust-lang/cargo, pull requests merged in 2023-12, with the labels that each got.

#13085 Add more options to registry test support.
  crates/cargo-test-support/src/registry.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors

#13053 Fixed uninstall a running binary failed on Windows
  src/cargo/ops/cargo_uninstall.rs
  src/cargo/ops/common_for_install_and_uninstall.rs
  tests/testsuite/install.rs
Labels: Command-uninstall, S-waiting-on-bors

#13091 test(trim-paths): exercise with real world debugger
  .github/workflows/main.yml
  crates/cargo-test-macro/src/lib.rs
  tests/testsuite/profile_trim_paths.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors, A-infrastructure

#13046 Add `--public` for `cargo add`
  src/bin/cargo/commands/add.rs
  src/cargo/ops/cargo_add/mod.rs
  src/cargo/util/toml_mut/dependency.rs
  tests/testsuite/cargo_add/detect_workspace_inherit_public/in/Cargo.toml
  tests/testsuite/cargo_add/detect_workspace_inherit_public/in/dependency/Cargo.toml
  tests/testsuite/cargo_add/detect_workspace_inherit_public/in/dependency/src/lib.rs
  tests/testsuite/cargo_add/detect_workspace_inherit_public/in/primary/Cargo.toml
  tests/testsuite/cargo_add/detect_workspace_inherit_public/in/primary/src/lib.rs
  tests/testsuite/cargo_add/detect_workspace_inherit_public/mod.rs
  tests/testsuite/cargo_add/detect_workspace_inherit_public/out/Cargo.toml
  tests/testsuite/cargo_add/detect_workspace_inherit_public/out/dependency/Cargo.toml
  tests/testsuite/cargo_add/detect_workspace_inherit_public/out/primary/Cargo.toml
  tests/testsuite/cargo_add/detect_workspace_inherit_public/stderr.log
  tests/testsuite/cargo_add/detect_workspace_inherit_public/stdout.log
  tests/testsuite/cargo_add/help/stdout.log
  tests/testsuite/cargo_add/mod.rs
  tests/testsuite/cargo_add/no_public/in/Cargo.toml
  tests/testsuite/cargo_add/no_public/in/src/lib.rs
  tests/testsuite/cargo_add/no_public/mod.rs
  tests/testsuite/cargo_add/no_public/out/Cargo.toml
  tests/testsuite/cargo_add/no_public/stderr.log
  tests/testsuite/cargo_add/no_public/stdout.log
  tests/testsuite/cargo_add/overwrite_no_public/in/Cargo.toml
  tests/testsuite/cargo_add/overwrite_no_public/in/src/lib.rs
  tests/testsuite/cargo_add/overwrite_no_public/mod.rs
  tests/testsuite/cargo_add/overwrite_no_public/out/Cargo.toml
  tests/testsuite/cargo_add/overwrite_no_public/stderr.log
  tests/testsuite/cargo_add/overwrite_no_public/stdout.log
  tests/testsuite/cargo_add/overwrite_no_public_with_public/in/Cargo.toml
  tests/testsuite/cargo_add/overwrite_no_public_with_public/in/src/lib.rs
  tests/testsuite/cargo_add/overwrite_no_public_with_public/mod.rs
  tests/testsuite/cargo_add/overwrite_no_public_with_public/out/Cargo.toml
  tests/testsuite/cargo_add/overwrite_no_public_with_public/stderr.log
  tests/testsuite/cargo_add/overwrite_no_public_with_public/stdout.log
  tests/testsuite/cargo_add/overwrite_public/in/Cargo.toml
  tests/testsuite/cargo_add/overwrite_public/in/src/lib.rs
  tests/testsuite/cargo_add/overwrite_public/mod.rs
  tests/testsuite/cargo_add/overwrite_public/out/Cargo.toml
  tests/testsuite/cargo_add/overwrite_public/stderr.log
  tests/testsuite/cargo_add/overwrite_public/stdout.log
  tests/testsuite/cargo_add/overwrite_public_with_no_public/in/Cargo.toml
  tests/testsuite/cargo_add/overwrite_public_with_no_public/in/src/lib.rs
  tests/testsuite/cargo_add/overwrite_public_with_no_public/mod.rs
  tests/testsuite/cargo_add/overwrite_public_with_no_public/out/Cargo.toml
  tests/testsuite/cargo_add/overwrite_public_with_no_public/stderr.log
  tests/testsuite/cargo_add/overwrite_public_with_no_public/stdout.log
  tests/testsuite/cargo_add/public/in/Cargo.toml
  tests/testsuite/cargo_add/public/in/src/lib.rs
  tests/testsuite/cargo_add/public/mod.rs
  tests/testsuite/cargo_add/public/out/Cargo.toml
  tests/testsuite/cargo_add/public/stderr.log
  tests/testsuite/cargo_add/public/stdout.log
Labels: A-manifest, S-waiting-on-bors, A-cli, Command-add

#13080 refactor(toml): Decouple logic from schema
  src/cargo/core/features.rs
  src/cargo/core/package.rs
  src/cargo/core/profiles.rs
  src/cargo/core/workspace.rs
  src/cargo/ops/cargo_package.rs
  src/cargo/util/toml/mod.rs
  src/cargo/util/toml/schema.rs
Labels: Command-package, A-workspaces, A-profiles, A-manifest, S-waiting-on-bors, A-unstable

#13093 chore(ci): Always update gix packages together
  .github/renovate.json5
Labels: S-waiting-on-bors, A-infrastructure

#13012 Include declared list of features in fingerprint for `-Zcheck-cfg`
  src/cargo/core/compiler/fingerprint/dirty_reason.rs
  src/cargo/core/compiler/fingerprint/mod.rs
  tests/testsuite/check_cfg.rs
Labels: A-rebuild-detection, S-waiting-on-bors

#13098 test(mdman): Switch to snapbox
  Cargo.lock
  Cargo.toml
  crates/mdman/Cargo.toml
  crates/mdman/tests/compare.rs
  crates/mdman/tests/invalid.rs
Labels: S-waiting-on-bors, A-cli-help

#13099 test(install): use TCP connection instead of thread sleep
  tests/testsuite/install.rs
Labels: S-waiting-on-bors

#13101 Revert "chore(deps): update rust crate openssl to 0.10.60 [security]"
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#13097 refactor(schemas): Pull out mod for proposed schemas package
  src/bin/cargo/main.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/core/manifest.rs
  src/cargo/core/profiles.rs
  src/cargo/core/workspace.rs
  src/cargo/lib.rs
  src/cargo/util/command_prelude.rs
  src/cargo/util/toml/mod.rs
  src/cargo/util/toml/targets.rs
  src/cargo/util_schemas/manifest.rs
  src/cargo/util_schemas/mod.rs
  tests/testsuite/config.rs
  tests/testsuite/profile_config.rs
Labels: A-build-execution, A-workspaces, A-profiles, A-manifest, S-waiting-on-bors, A-cli

#13118 test(trim-paths): assert `OSO` and `SO` cannot be trimmed
  tests/testsuite/profile_trim_paths.rs
Labels: S-waiting-on-bors

#12933 feat(spec): Extend PackageIdSpec with source kind + git ref for unambiguous specs
  src/cargo/core/mod.rs
  src/cargo/core/package_id_spec.rs
  src/cargo/core/source_id.rs
  src/doc/src/reference/pkgid-spec.md
  tests/testsuite/pkgid.rs
Labels: A-documenting-cargo-itself, T-cargo, final-comment-period, disposition-merge, S-waiting-on-bors, to-announce

#13117 re-enable previously disabled tests with Windows-specific fix
  Cargo.lock
  Cargo.toml
  tests/testsuite/git_auth.rs
Labels: S-waiting-on-bors

#13125 fix(toml): Disallow inheriting of dependency public status
  src/cargo/util/toml/mod.rs
  src/cargo/util_schemas/manifest.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/pub_priv.rs
Labels: A-documenting-cargo-itself, A-manifest, S-waiting-on-bors

#13126 fix bash completion in directory with spaces
  src/etc/cargo.bashcomp.sh
Labels: S-waiting-on-bors, A-completions

#13130 re-enable flaky tests thanks to update to `gix-config`. (#11821)
  Cargo.lock
  tests/testsuite/git_auth.rs
Labels: S-waiting-on-bors

#13132 Avoid writing CACHEDIR.TAG if it already exists
  crates/cargo-util/src/paths.rs
Labels: S-waiting-on-bors

#13131 Add a windows manifest file
  build.rs
  windows.manifest.xml
Labels: S-waiting-on-bors, A-infrastructure

#13140 fix: Print rustc messages colored on wincon
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#13128 refactor: Pull PackageIdSpec into schema
  src/bin/cargo/commands/remove.rs
  src/cargo/core/mod.rs
  src/cargo/core/package_id.rs
  src/cargo/core/package_id_spec.rs
  src/cargo/core/profiles.rs
  src/cargo/core/resolver/dep_cache.rs
  src/cargo/core/resolver/resolve.rs
  src/cargo/core/source_id.rs
  src/cargo/core/workspace.rs
  src/cargo/ops/cargo_clean.rs
  src/cargo/ops/cargo_compile/packages.rs
  src/cargo/ops/cargo_generate_lockfile.rs
  src/cargo/ops/cargo_install.rs
  src/cargo/ops/cargo_pkgid.rs
  src/cargo/ops/cargo_uninstall.rs
  src/cargo/ops/registry/publish.rs
  src/cargo/ops/resolve.rs
  src/cargo/ops/tree/mod.rs
  src/cargo/util_schemas/core/mod.rs
  src/cargo/util_schemas/core/package_id_spec.rs
  src/cargo/util_schemas/core/source_kind.rs
  src/cargo/util_schemas/manifest.rs
  src/cargo/util_schemas/mod.rs
Labels: Command-clean, Command-publish, Command-install, A-interacts-with-crates.io, Command-generate-lockfile, Command-pkgid, Command-uninstall, A-workspaces, A-profiles, A-dependency-resolution, S-waiting-on-bors, A-cli, Command-tree, Command-remove

#13143 Don't rely on mtime to test changes
  tests/testsuite/build_script.rs
  tests/testsuite/build_script_env.rs
  tests/testsuite/freshness.rs
Labels: S-waiting-on-bors

#13114 fix: explicitly remap current dir by using `.`
  src/cargo/core/compiler/mod.rs
  tests/testsuite/profile_trim_paths.rs
Labels: A-build-execution, S-waiting-on-bors, Z-trim-paths

#13144 chore: downgrade to openssl v1.1.1
  Cargo.lock
Labels: S-waiting-on-bors

#13147 Update curl-sys to bring in curl 8.5.0
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#13148 chore: update to gix-index@0.27.1
  Cargo.lock
Labels: S-waiting-on-bors

#13135 Limit exported-private-dependencies lints to libraries
  src/cargo/core/compiler/mod.rs
  tests/testsuite/pub_priv.rs
Labels: A-build-execution, S-waiting-on-bors

#13155 fix(toml)!: Disallow `[lints]` in virtual workspaces
  src/cargo/util/toml/mod.rs
  src/cargo/util_schemas/manifest.rs
  tests/testsuite/workspaces.rs
Labels: A-manifest, S-waiting-on-bors

#13154 refactor(schema): Remove reliance on cargo types
  crates/resolver-tests/src/lib.rs
  src/cargo/core/manifest.rs
  src/cargo/core/package.rs
  src/cargo/core/resolver/version_prefs.rs
  src/cargo/core/summary.rs
  src/cargo/core/workspace.rs
  src/cargo/ops/cargo_add/mod.rs
  src/cargo/ops/resolve.rs
  src/cargo/sources/registry/index.rs
  src/cargo/util/mod.rs
  src/cargo/util/semver_ext.rs
  src/cargo/util/toml/mod.rs
  src/cargo/util_schemas/core/package_id_spec.rs
  src/cargo/util_schemas/manifest.rs
Labels: A-workspaces, A-dependency-resolution, A-registries, A-manifest, S-waiting-on-bors, A-semver, Command-add

#13156 Remove the deleted feature test_2018_feature from the test
  tests/testsuite/cargo_features.rs
Labels: S-waiting-on-bors

#13158 crates-io: Add support for other 2xx HTTP status codes
  crates/crates-io/lib.rs
Labels: A-interacts-with-crates.io, S-waiting-on-bors

#13160 doc/registry-web-api: Adjust success response code documentation
  src/doc/src/reference/registry-web-api.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#13134 `all-static` feature should include `vendored-libgit2`
  Cargo.toml
Labels: S-waiting-on-bors

#13152 Do not allow empty name in package ID spec
  src/cargo/util_schemas/core/package_id_spec.rs
Labels: S-waiting-on-bors

#13164 fix: Fill in more empty name holes
  src/cargo/util/restricted_names.rs
  src/cargo/util/toml/mod.rs
  src/cargo/util_schemas/core/package_id_spec.rs
  tests/testsuite/alt_registry.rs
  tests/testsuite/build.rs
  tests/testsuite/cargo_add/empty_dep_name/in
  tests/testsuite/cargo_add/empty_dep_name/mod.rs
  tests/testsuite/cargo_add/empty_dep_name/out/Cargo.toml
  tests/testsuite/cargo_add/empty_dep_name/stderr.log
  tests/testsuite/cargo_add/empty_dep_name/stdout.log
  tests/testsuite/cargo_add/mod.rs
  tests/testsuite/cargo_new/empty_name/in/.keep
  tests/testsuite/cargo_new/empty_name/mod.rs
  tests/testsuite/cargo_new/empty_name/out/.keep
  tests/testsuite/cargo_new/empty_name/stderr.log
  tests/testsuite/cargo_new/empty_name/stdout.log
  tests/testsuite/cargo_new/mod.rs
  tests/testsuite/patch.rs
Labels: A-manifest, S-waiting-on-bors

#13173 Replace SHGetFolderPathW with SHGetKnownFolderPath
  crates/home/Cargo.toml
  crates/home/src/lib.rs
  crates/home/src/windows.rs
  src/cargo/sources/git/known_hosts.rs
Labels: A-git, A-environment-variables, S-waiting-on-bors, A-home

#13166 refactor: Pull name validation into `util_schemas`
  src/cargo/core/summary.rs
  src/cargo/ops/cargo_add/crate_spec.rs
  src/cargo/ops/cargo_new.rs
  src/cargo/util/command_prelude.rs
  src/cargo/util/config/mod.rs
  src/cargo/util/mod.rs
  src/cargo/util/restricted_names.rs
  src/cargo/util/toml/embedded.rs
  src/cargo/util/toml/mod.rs
  src/cargo/util/toml/targets.rs
  src/cargo/util_schemas/core/package_id_spec.rs
  src/cargo/util_schemas/manifest.rs
  src/cargo/util_schemas/mod.rs
  src/cargo/util_schemas/restricted_names.rs
  tests/testsuite/alt_registry.rs
  tests/testsuite/build.rs
  tests/testsuite/cargo_add/empty_dep_name/stderr.log
  tests/testsuite/features.rs
  tests/testsuite/features_namespaced.rs
  tests/testsuite/profile_custom.rs
Labels: A-configuration, Command-new, A-manifest, S-waiting-on-bors, A-cli, Command-add

#13177 docs(home): prepare the changelog for 0.5.9
  crates/home/CHANGELOG.md
Labels: A-environment-variables, S-waiting-on-bors, A-home

#13179 chore: downgrade to openssl v1.1.1
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#13181 chore(rustfix): rename Readme.md to README.md
  crates/rustfix/CHANGELOG.md
  crates/rustfix/README.md
Labels: Command-fix, S-waiting-on-bors

#13178 refactor(schemas): Pull out as `cargo-util-schemas`
  Cargo.lock
  Cargo.toml
  crates/cargo-util-schemas/Cargo.toml
  crates/cargo-util-schemas/LICENSE-APACHE
  crates/cargo-util-schemas/LICENSE-MIT
  crates/cargo-util-schemas/src/core/mod.rs
  crates/cargo-util-schemas/src/core/package_id_spec.rs
  crates/cargo-util-schemas/src/core/partial_version.rs
  crates/cargo-util-schemas/src/core/source_kind.rs
  crates/cargo-util-schemas/src/lib.rs
  crates/cargo-util-schemas/src/manifest.rs
  crates/cargo-util-schemas/src/restricted_names.rs
  crates/resolver-tests/Cargo.toml
  crates/resolver-tests/src/lib.rs
  crates/xtask-bump-check/src/xtask.rs
  publish.py
  src/bin/cargo/commands/install.rs
  src/bin/cargo/main.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/core/manifest.rs
  src/cargo/core/mod.rs
  src/cargo/core/package.rs
  src/cargo/core/profiles.rs
  src/cargo/core/resolver/errors.rs
  src/cargo/core/resolver/version_prefs.rs
  src/cargo/core/summary.rs
  src/cargo/core/workspace.rs
  src/cargo/lib.rs
  src/cargo/ops/cargo_add/crate_spec.rs
  src/cargo/ops/cargo_add/mod.rs
  src/cargo/ops/cargo_new.rs
  src/cargo/ops/resolve.rs
  src/cargo/sources/git/mod.rs
  src/cargo/sources/git/utils.rs
  src/cargo/sources/registry/index.rs
  src/cargo/sources/registry/remote.rs
  src/cargo/util/command_prelude.rs
  src/cargo/util/config/mod.rs
  src/cargo/util/mod.rs
  src/cargo/util/semver_ext.rs
  src/cargo/util/toml/embedded.rs
  src/cargo/util/toml/mod.rs
  src/cargo/util/toml/targets.rs
  tests/testsuite/config.rs
  tests/testsuite/profile_config.rs
Labels: A-git, A-configuration, Command-new, Command-install, A-build-execution, A-workspaces, A-profiles, A-dependency-resolution, A-registries, T-cargo, A-manifest, final-comment-period, disposition-merge, S-waiting-on-bors, A-cli, A-semver, Command-add, A-infrastructure

#13185 ci: check SemVer for cargo-util-schemas on CI
  crates/xtask-bump-check/src/xtask.rs
Labels: S-waiting-on-bors, A-infrastructure

#13184 refactor: clean up package metadata
  Cargo.lock
  Cargo.toml
  crates/cargo-platform/Cargo.toml
  crates/cargo-test-macro/Cargo.toml
  crates/cargo-util-schemas/Cargo.toml
  crates/cargo-util/Cargo.toml
  crates/crates-io/Cargo.toml
  crates/home/Cargo.toml
  crates/rustfix/Cargo.toml
  credential/cargo-credential-1password/Cargo.toml
  credential/cargo-credential-libsecret/Cargo.toml
  credential/cargo-credential-macos-keychain/Cargo.toml
  credential/cargo-credential-wincred/Cargo.toml
  credential/cargo-credential/Cargo.toml
Labels: A-interacts-with-crates.io, A-environment-variables, A-testing-cargo-itself, Command-fix, S-waiting-on-bors, A-cfg-expr, A-credential-provider, A-home

#12509 Hold the mutate exclusive lock when vendoring
  src/cargo/ops/vendor.rs
Labels: S-waiting-on-bors, Command-vendor

#13186 refactor: custom error types for `cargo-util-schemas`
  Cargo.lock
  Cargo.toml
  crates/cargo-util-schemas/Cargo.toml
  crates/cargo-util-schemas/src/core/mod.rs
  crates/cargo-util-schemas/src/core/package_id_spec.rs
  crates/cargo-util-schemas/src/core/partial_version.rs
  crates/cargo-util-schemas/src/manifest.rs
  crates/cargo-util-schemas/src/restricted_names.rs
  src/cargo/ops/cargo_compile/packages.rs
  src/cargo/ops/tree/mod.rs
  tests/testsuite/features.rs
  tests/testsuite/new.rs
  tests/testsuite/profile_custom.rs
Labels: S-waiting-on-bors, Command-tree

#13192 Bump to 0.78.0; update changelog
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#13187 refactor: centralize git checkouts and db paths
  src/cargo/core/global_cache_tracker.rs
  src/cargo/sources/git/source.rs
  src/cargo/util/config/mod.rs
Labels: A-git, A-configuration, S-waiting-on-bors

#13195 Rework `--check-cfg` generation comment
  src/cargo/core/compiler/mod.rs
Labels: A-build-execution, S-waiting-on-bors

#12201 Extend the build directive syntax with `cargo::`
  src/cargo/core/compiler/custom_build.rs
  src/cargo/core/compiler/fingerprint/dirty_reason.rs
  src/doc/src/faq.md
  src/doc/src/reference/build-script-examples.md
  src/doc/src/reference/build-scripts.md
  src/doc/src/reference/external-tools.md
  src/doc/src/reference/unstable.md
  tests/testsuite/build.rs
  tests/testsuite/build_script.rs
  tests/testsuite/build_script_env.rs
  tests/testsuite/build_script_extra_link_arg.rs
  tests/testsuite/check_cfg.rs
  tests/testsuite/cross_compile.rs
  tests/testsuite/dep_info.rs
  tests/testsuite/doc.rs
  tests/testsuite/features2.rs
  tests/testsuite/freshness.rs
  tests/testsuite/profile_overrides.rs
  tests/testsuite/run.rs
  tests/testsuite/warn_on_failure.rs
Labels: A-documenting-cargo-itself, relnotes, A-build-execution, A-rebuild-detection, A-build-scripts, T-cargo, finished-final-comment-period, disposition-merge, S-waiting-on-bors, S-blocked-external, to-announce

#13201 chore: fix a typo
  src/cargo/core/compiler/custom_build.rs
Labels: A-build-scripts, S-waiting-on-bors

#13202 refactor: give some better examples for package ID spec
  crates/cargo-util-schemas/src/core/package_id_spec.rs
Labels: S-waiting-on-bors

#13205 fix: clarify `--path` is the installation source not destination
  src/bin/cargo/cli.rs
  src/bin/cargo/commands/install.rs
  src/cargo/ops/cargo_install.rs
  src/doc/man/cargo-install.md
  src/doc/man/generated_txt/cargo-install.txt
  src/doc/src/commands/cargo-install.md
  src/etc/man/cargo-install.1
  tests/testsuite/cargo/help/stdout.log
  tests/testsuite/cargo_install/help/stdout.log
  tests/testsuite/install.rs
Labels: A-documenting-cargo-itself, Command-install, S-waiting-on-bors, A-cli, A-cli-help

#13206 doc: improve word usage
  src/doc/src/reference/build-script-examples.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#13209 docs: fix link to nightly doc of cargo-util-schemas
  src/cargo/lib.rs
Labels: S-waiting-on-bors

#13203 chore(doc): doc for custom subcommands look up.
  src/doc/src/reference/external-tools.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#13212 Add cargo:rustc-cdylib-link-arg into RESERVED_PREFIXES list
  src/cargo/core/compiler/custom_build.rs
Labels: A-build-scripts, S-waiting-on-bors

#13216 Remove repetitive words
  credential/cargo-credential/examples/stdout-redirected.rs
  credential/cargo-credential/tests/examples.rs
  src/cargo/sources/registry/mod.rs
  src/doc/src/reference/specifying-dependencies.md
  tests/testsuite/global_cache_tracker.rs
Labels: A-documenting-cargo-itself, A-registries, S-waiting-on-bors, A-credential-provider

#13213 `cargo add` - fix for adding features from repository with multiple packages.
  src/cargo/ops/cargo_add/mod.rs
  tests/testsuite/cargo_add/git_multiple_packages_features/in
  tests/testsuite/cargo_add/git_multiple_packages_features/mod.rs
  tests/testsuite/cargo_add/git_multiple_packages_features/out/Cargo.toml
  tests/testsuite/cargo_add/git_multiple_packages_features/stderr.log
  tests/testsuite/cargo_add/git_multiple_packages_features/stdout.log
  tests/testsuite/cargo_add/mod.rs
Labels: S-waiting-on-bors, Command-add

#13221 Bump cargo-credential to 0.4.3
  Cargo.lock
  credential/cargo-credential/Cargo.toml
Labels: S-waiting-on-bors, A-credential-provider

#13225 `cargo fix`: always inherit the jobserver
  src/cargo/ops/fix.rs
Labels: Command-fix, S-waiting-on-bors

#13224 cleanup: Remove error-format special-case in `cargo fix`
  src/cargo/ops/fix.rs
Labels: Command-fix, S-waiting-on-bors
