Repository rust-lang/cargo, pull requests merged in 2023-07, with the labels that each got.

#12323 docs(ref): Provide guidance on version requirements
  src/doc/src/reference/specifying-dependencies.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12313 doc: state `PackageId`/`SourceId` string is opaque
  src/doc/man/cargo-metadata.md
  src/doc/man/generated_txt/cargo-metadata.txt
  src/doc/src/commands/cargo-metadata.md
  src/etc/man/cargo-metadata.1
Labels: A-documenting-cargo-itself, S-waiting-on-bors, A-cli-help

#12335 update re: multiple versions that differ only in the metadata tag
  src/doc/src/reference/resolver.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12337 Add profile strip to config docs.
  src/doc/src/reference/config.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12340 Minor: Use "number" instead of "digit" when explaining Cargo's use of semver
  src/doc/src/reference/specifying-dependencies.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12343 docs: Put cargo-add change under nightly
  CHANGELOG.md
Labels: S-waiting-on-bors

#12344 contrib docs: Add some more detail about how publishing works
  publish.py
  src/doc/contrib/src/process/release.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors, A-infrastructure

#12342 chore(ci): Automatically test new packages by using `--workspace`
  .github/workflows/main.yml
Labels: S-waiting-on-bors, A-infrastructure

#12350 fix(embedded): Error on intentionally unsupported commands
  src/bin/cargo/commands/package.rs
  src/bin/cargo/commands/pkgid.rs
  src/bin/cargo/commands/publish.rs
  tests/testsuite/script.rs
Labels: Command-publish, Command-package, Command-pkgid, S-waiting-on-bors, A-cli

#12349 fix(embedded): Always generate valid package names
  src/cargo/util/restricted_names.rs
  tests/testsuite/script.rs
Labels: S-waiting-on-bors

#12351 Rustfmt with latest nightly.
  crates/xtask-stale-label/src/main.rs
  src/cargo/sources/git/known_hosts.rs
  src/cargo/sources/registry/http_remote.rs
  src/cargo/util/auth/asymmetric.rs
  src/cargo/util/toml/embedded.rs
  src/cargo/util/toml/mod.rs
Labels: S-waiting-on-bors

#12339 docs: Use heading attributes to control the fragment.
  .github/workflows/main.yml
  src/doc/src/reference/build-scripts.md
  src/doc/src/reference/manifest.md
  src/doc/src/reference/semver.md
  src/doc/src/reference/workspaces.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors, A-infrastructure

#12341 chore: Automatically update dependencies monthly
  .github/renovate.json5
Labels: S-waiting-on-bors, A-infrastructure

#12355 [stable-1.71] Bump version of crates-io due to unintentional semver-breaking change
  Cargo.lock
  Cargo.toml
  crates/crates-io/Cargo.toml
Labels: A-interacts-with-crates.io, S-waiting-on-bors

#12356 [beta-1.72] Bump version of crates-io due to unintentional semver-breaking change
  Cargo.lock
  Cargo.toml
  crates/crates-io/Cargo.toml
Labels: A-interacts-with-crates.io, S-waiting-on-bors

#12357 Bump version of crates-io due to unintentional semver-breaking change
  Cargo.lock
  Cargo.toml
  crates/crates-io/Cargo.toml
Labels: A-interacts-with-crates.io, S-waiting-on-bors

#12361 Bump to 0.74.0; update changelog
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#12364 Replace invalid `panic_unwind` std feature with `panic-unwind`
  src/doc/src/reference/unstable.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12363 Correct unspecifiead to unspecified
  src/cargo/util/toml/embedded.rs
  tests/testsuite/script.rs
Labels: S-waiting-on-bors

#12352 refactor: Clean up package metadata
  Cargo.lock
  Cargo.toml
  benches/benchsuite/Cargo.toml
  benches/capture/Cargo.toml
  crates/cargo-platform/Cargo.toml
  crates/cargo-test-macro/Cargo.toml
  crates/cargo-test-support/Cargo.toml
  crates/cargo-util/Cargo.toml
  crates/crates-io/Cargo.toml
  crates/home/Cargo.toml
  crates/mdman/Cargo.toml
  crates/resolver-tests/Cargo.toml
  crates/semver-check/Cargo.toml
  crates/xtask-build-man/Cargo.toml
  crates/xtask-stale-label/Cargo.toml
  crates/xtask-unpublished/Cargo.toml
  credential/cargo-credential-1password/Cargo.toml
  credential/cargo-credential-gnome-secret/Cargo.toml
  credential/cargo-credential-macos-keychain/Cargo.toml
  credential/cargo-credential-wincred/Cargo.toml
  credential/cargo-credential/Cargo.toml
Labels: A-interacts-with-crates.io, A-dependency-resolution, A-environment-variables, A-testing-cargo-itself, S-waiting-on-bors, A-cfg-expr, A-semver, A-cli-help, A-registry-authentication, A-infrastructure

#12368 Upgrade to indexmap v2
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#12359 fix(git): respect scp-like URL for nested submodules
  src/cargo/sources/git/utils.rs
  tests/testsuite/git.rs
Labels: A-git, S-waiting-on-bors

#12376 Update docs for artifact JSON debuginfo levels.
  src/doc/src/reference/external-tools.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12369 fix: only skip mtime check on `~/.cargo/{git,registry}`
  src/cargo/core/compiler/fingerprint/mod.rs
  tests/testsuite/freshness.rs
Labels: A-rebuild-detection, S-waiting-on-bors

#12380 chore: Don't update test data
  .github/renovate.json5
Labels: S-waiting-on-bors, A-infrastructure

#12310 feat(crates-io): expose HTTP headers and Error type
  Cargo.lock
  Cargo.toml
  crates/crates-io/Cargo.toml
  crates/crates-io/lib.rs
  tests/testsuite/publish.rs
Labels: A-interacts-with-crates.io, A-registries, S-waiting-on-bors

#12334 credential provider implementation
  Cargo.lock
  Cargo.toml
  crates/cargo-test-support/src/compare.rs
  crates/cargo-test-support/src/registry.rs
  credential/cargo-credential-1password/Cargo.toml
  credential/cargo-credential-1password/src/lib.rs
  credential/cargo-credential-gnome-secret/Cargo.toml
  credential/cargo-credential-gnome-secret/src/libsecret.rs
  credential/cargo-credential-macos-keychain/Cargo.toml
  credential/cargo-credential-macos-keychain/src/lib.rs
  credential/cargo-credential-macos-keychain/src/main.rs
  credential/cargo-credential-wincred/Cargo.toml
  credential/cargo-credential-wincred/src/lib.rs
  credential/cargo-credential-wincred/src/main.rs
  credential/cargo-credential/Cargo.toml
  credential/cargo-credential/README.md
  credential/cargo-credential/src/lib.rs
  credential/cargo-credential/src/secret.rs
  src/bin/cargo/commands/login.rs
  src/bin/cargo/commands/owner.rs
  src/bin/cargo/commands/yank.rs
  src/cargo/core/package.rs
  src/cargo/ops/registry/login.rs
  src/cargo/ops/registry/logout.rs
  src/cargo/ops/registry/mod.rs
  src/cargo/ops/registry/owner.rs
  src/cargo/ops/registry/publish.rs
  src/cargo/ops/registry/yank.rs
  src/cargo/sources/registry/download.rs
  src/cargo/sources/registry/http_remote.rs
  src/cargo/util/auth/asymmetric.rs
  src/cargo/util/auth/mod.rs
  src/cargo/util/config/mod.rs
  src/cargo/util/config/path.rs
  src/cargo/util/credential/adaptor.rs
  src/cargo/util/credential/mod.rs
  src/cargo/util/credential/paseto.rs
  src/cargo/util/credential/process.rs
  src/cargo/util/credential/token.rs
  src/cargo/util/errors.rs
  src/cargo/util/mod.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/credential_process.rs
  tests/testsuite/login.rs
  tests/testsuite/owner.rs
  tests/testsuite/publish.rs
  tests/testsuite/registry_auth.rs
  tests/testsuite/yank.rs
Labels: A-documenting-cargo-itself, A-git, A-configuration, Command-publish, A-interacts-with-crates.io, Command-login, Command-owner, Command-yank, A-registries, A-manifest, A-testing-cargo-itself, S-waiting-on-bors, A-cli, Command-logout, A-sparse-registry, A-registry-authentication, A-infrastructure

#12392 docs: format config override caveat as a note
  src/doc/src/reference/overriding-dependencies.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12280 fix: encode URL params correctly for SourceId in Cargo.lock
  src/cargo/core/resolver/encode.rs
  src/cargo/core/resolver/resolve.rs
  src/cargo/core/source/source_id.rs
  src/cargo/sources/git/source.rs
  src/cargo/util/toml_mut/dependency.rs
  tests/testsuite/lockfile_compat.rs
Labels: A-git, A-dependency-resolution, T-cargo, A-manifest, finished-final-comment-period, disposition-merge, S-waiting-on-bors, A-lockfile, to-announce

#12398 refactor(test): Move cargo-config into a dir
  tests/testsuite/cargo_config/mod.rs
Labels: S-waiting-on-bors

#12400 Update curl-sys to pull in curl 8.2.0
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#12401 chore: update `home` to 0.5.7
  Cargo.lock
  crates/home/Cargo.toml
Labels: A-environment-variables, S-waiting-on-bors

#12388 docs: raise awareness of resolver used inside workspace
  src/doc/src/reference/workspaces.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12406 Update curl-sys to pull in curl 8.2.1
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#12408 doc: add missing reference to `CARGO_PROFILE_<name>_STRIP` in environment variables docs
  src/doc/src/reference/environment-variables.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12407 Clarify `lto` setting passing `-Clinker-plugin-lto`
  src/doc/src/reference/profiles.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12399 fix(package): Recognize and normalize `cargo.toml`
  Cargo.lock
  Cargo.toml
  src/cargo/ops/cargo_package.rs
  tests/testsuite/package.rs
Labels: Command-package, S-waiting-on-bors

#12413 test: relax assertions of panic handler message format
  tests/testsuite/bench.rs
  tests/testsuite/install.rs
  tests/testsuite/test.rs
Labels: S-waiting-on-bors

#12416 test: relax help text assertion
  tests/testsuite/cargo/help/stdout.log
Labels: S-waiting-on-bors

#12411 fix: normalize relative git submodule urls with `ssh://`
  src/cargo/sources/git/utils.rs
  tests/testsuite/git.rs
Labels: A-git, S-waiting-on-bors

#12417 [beta-1.72] backport #12411
  src/cargo/sources/git/utils.rs
  tests/testsuite/git.rs
Labels: A-git, S-waiting-on-bors

#12418 fix: align `cargo --help` text
  src/bin/cargo/cli.rs
Labels: S-waiting-on-bors, A-cli

#12422 Clarify in `--help` that `cargo test --all-targets` excludes doctests
  src/bin/cargo/commands/test.rs
  tests/testsuite/cargo_test/help/stdout.log
Labels: Command-test, S-waiting-on-bors, A-cli

#12424 Use thiserror for credential provider errors
  Cargo.lock
  credential/cargo-credential-1password/src/lib.rs
  credential/cargo-credential-macos-keychain/src/lib.rs
  credential/cargo-credential-wincred/src/lib.rs
  credential/cargo-credential/Cargo.toml
  credential/cargo-credential/src/error.rs
  credential/cargo-credential/src/lib.rs
  src/cargo/util/credential/adaptor.rs
  src/cargo/util/credential/paseto.rs
  src/cargo/util/credential/process.rs
  src/cargo/util/credential/token.rs
  tests/testsuite/credential_process.rs
  tests/testsuite/login.rs
Labels: S-waiting-on-bors, A-registry-authentication
