Repository rust-lang/cargo, pull requests merged in 2023-01, with the labels that each got.

#11529 Fix a typo `fresheness` -> `freshness`
  src/cargo/core/source/mod.rs
Labels: S-waiting-on-bors

#11531 Add note to release notes about rejecting multiple registries.
  CHANGELOG.md
Labels: S-waiting-on-bors

#11534 test: revive nightly plugin tests to work
  tests/testsuite/plugins.rs
Labels: S-waiting-on-bors

#11535 Fix a typo in the registries documentation.
  src/doc/src/reference/registries.md
Labels: S-waiting-on-bors

#11533 Cargo by default saves credentials to `.cargo/credentials.toml`
  crates/cargo-test-support/src/registry.rs
  src/cargo/util/config/mod.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/alt_registry.rs
  tests/testsuite/build.rs
  tests/testsuite/login.rs
  tests/testsuite/logout.rs
  tests/testsuite/publish.rs
Labels: S-waiting-on-bors

#11538 Fix some doc links
  src/doc/src/reference/registries.md
  src/doc/src/reference/registry-index.md
Labels: S-waiting-on-bors

#11541 Fix panic on target dependency errors.
  src/cargo/util/toml/mod.rs
  tests/testsuite/bad_config.rs
Labels: S-waiting-on-bors

#11556 Add fix for CVE-2022-46176
  CHANGELOG.md
  Cargo.toml
  crates/cargo-test-support/Cargo.toml
  src/cargo/sources/git/known_hosts.rs
  src/cargo/sources/git/mod.rs
  src/cargo/sources/git/utils.rs
  src/cargo/util/config/de.rs
  src/cargo/util/config/mod.rs
  src/doc/src/appendix/git-authentication.md
  src/doc/src/reference/config.md
  tests/testsuite/config.rs
Labels: S-waiting-on-bors

#11561 chore: Fix typos
  CHANGELOG.md
  crates/cargo-util/src/paths.rs
  src/cargo/core/compiler/build_context/target_info.rs
  src/cargo/core/compiler/unit_dependencies.rs
  src/cargo/core/profiles.rs
  src/cargo/ops/cargo_compile/packages.rs
  src/cargo/ops/cargo_compile/unit_generator.rs
  src/cargo/ops/registry.rs
  src/cargo/sources/registry/mod.rs
  src/cargo/util/auth.rs
  src/doc/man/cargo-locate-project.md
  src/doc/man/generated_txt/cargo-locate-project.txt
  src/doc/src/commands/cargo-locate-project.md
  src/etc/man/cargo-locate-project.1
  tests/testsuite/cargo_command.rs
  tests/testsuite/config_cli.rs
  tests/testsuite/login.rs
  tests/testsuite/registry_auth.rs
Labels: S-waiting-on-bors

#11568 Redirect nightly apidoc to `doc.rust-lang.org/nightly/nightly-rustc/cargo`
  .github/workflows/contrib.yml
  CHANGELOG.md
  src/cargo/lib.rs
  src/doc/contrib/book.toml
Labels: S-waiting-on-bors

#11578 ci: reflect to clap updates
  Cargo.toml
  tests/testsuite/cargo_add/dev_build_conflict/stderr.log
  tests/testsuite/cargo_add/invalid_arg/stderr.log
  tests/testsuite/cargo_add/invalid_target_empty/stderr.log
  tests/testsuite/cargo_add/no_args/stderr.log
  tests/testsuite/cargo_remove/invalid_arg/stderr.log
  tests/testsuite/cargo_remove/no_arg/stderr.log
  tests/testsuite/init/unknown_flags/stderr.log
  tests/testsuite/install.rs
  tests/testsuite/login.rs
  tests/testsuite/metadata.rs
  tests/testsuite/new.rs
  tests/testsuite/run.rs
  tests/testsuite/rustc.rs
  tests/testsuite/vendor.rs
Labels: S-waiting-on-bors

#11562 Support `codegen-backend` and `rustflags` in profiles in config file
  src/cargo/core/features.rs
  src/cargo/core/profiles.rs
  src/cargo/util/toml/mod.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/profile_config.rs
Labels: S-waiting-on-bors

#11582 Enable source_config_env test on Windows
  tests/testsuite/advanced_env.rs
Labels: S-waiting-on-bors

#11585 Fix typo
  src/cargo/core/package.rs
  src/cargo/sources/registry/index.rs
Labels: S-waiting-on-bors

#11586 add documentation that SSH markers aren't supported
  src/doc/src/appendix/git-authentication.md
Labels: S-waiting-on-bors

#11504 fix(docs): add required "inherits" option to example profile
  src/doc/src/reference/config.md
Labels: S-waiting-on-bors

#11550 `cargo metadata` supports artifact dependencies
  src/cargo/core/compiler/artifact.rs
  src/cargo/core/compiler/unit_dependencies.rs
  src/cargo/core/dependency.rs
  src/cargo/ops/cargo_output_metadata.rs
  tests/testsuite/metadata.rs
Labels: S-waiting-on-bors

#11579 Show progress of crates.io index update even `net.git-fetch-with-cli` option enabled
  src/cargo/sources/git/utils.rs
  tests/testsuite/git.rs
Labels: T-cargo, final-comment-period, disposition-merge, S-waiting-on-bors

#11583 Add network container tests
  .github/workflows/main.yml
  crates/cargo-test-macro/src/lib.rs
  crates/cargo-test-support/build.rs
  crates/cargo-test-support/containers/apache/Dockerfile
  crates/cargo-test-support/containers/apache/bar/Cargo.toml
  crates/cargo-test-support/containers/apache/bar/src/lib.rs
  crates/cargo-test-support/containers/apache/httpd-cargo.conf
  crates/cargo-test-support/containers/sshd/Dockerfile
  crates/cargo-test-support/containers/sshd/bar/Cargo.toml
  crates/cargo-test-support/containers/sshd/bar/src/lib.rs
  crates/cargo-test-support/src/containers.rs
  crates/cargo-test-support/src/lib.rs
  src/cargo/sources/git/known_hosts.rs
  src/cargo/util/network.rs
  src/doc/contrib/src/tests/running.md
  src/doc/contrib/src/tests/writing.md
  tests/testsuite/https.rs
  tests/testsuite/main.rs
  tests/testsuite/ssh.rs
Labels: S-waiting-on-bors

#11592 Corrected documentation of how to cache binaries installed with `cargo install` in CI workflows
  src/doc/src/guide/cargo-home.md
Labels: S-waiting-on-bors

#11067 Ignore `workspace.default-members` when running `cargo install` on root package of a non-virtual workspace
  src/cargo/core/compiler/build_config.rs
  src/cargo/ops/cargo_compile/compile_filter.rs
  src/cargo/ops/cargo_compile/mod.rs
  src/cargo/ops/cargo_compile/packages.rs
  src/cargo/ops/cargo_install.rs
  tests/testsuite/install.rs
Labels: S-waiting-on-bors

#11596 Add semver rule for lints
  src/doc/semver-check/src/main.rs
  src/doc/src/reference/semver.md
Labels: S-waiting-on-bors

#11545 Wrapper type for data that should never be logged
  src/bin/cargo/commands/login.rs
  src/bin/cargo/commands/owner.rs
  src/bin/cargo/commands/publish.rs
  src/bin/cargo/commands/yank.rs
  src/cargo/ops/registry.rs
  src/cargo/util/auth.rs
  src/cargo/util/config/mod.rs
Labels: S-waiting-on-bors

#11224 Stabilize sparse-registry
  src/cargo/core/features.rs
  src/cargo/sources/registry/http_remote.rs
  src/doc/src/reference/config.md
  src/doc/src/reference/registries.md
  src/doc/src/reference/registry-index.md
  src/doc/src/reference/unstable.md
  tests/testsuite/alt_registry.rs
  tests/testsuite/publish.rs
  tests/testsuite/registry.rs
  tests/testsuite/registry_auth.rs
Labels: relnotes, T-cargo, finished-final-comment-period, disposition-merge, S-waiting-on-bors, to-announce, Z-sparse-registry

#11409 fix(toml): Add `default-features` to `TomlWorkspaceDependency`
  src/cargo/util/toml/mod.rs
  tests/testsuite/inheritable_workspace_fields.rs
Labels: T-cargo, finished-final-comment-period, disposition-merge, S-waiting-on-bors, to-announce

#11610 Disable network SSH tests on windows.
  tests/testsuite/ssh.rs
Labels: S-waiting-on-bors

#11609 Temporarily pin libgit2-sys.
  Cargo.toml
Labels: S-waiting-on-bors

#11576 Clarify the difference between CARGO_CRATE_NAME and CARGO_PKG_NAME
  src/doc/src/reference/environment-variables.md
Labels: S-waiting-on-bors

#11558 feat: stabilize auto fix note
  src/cargo/core/compiler/job_queue.rs
  tests/testsuite/check.rs
  tests/testsuite/install.rs
  tests/testsuite/messages.rs
Labels: T-cargo, finished-final-comment-period, disposition-merge, S-waiting-on-bors, to-announce

#11603 [Doc]: Added links to the `Target` section of the glossary for occurences of `target triple`
  src/doc/man/cargo-metadata.md
  src/doc/man/cargo-tree.md
  src/doc/man/generated_txt/cargo-metadata.txt
  src/doc/man/generated_txt/cargo-tree.txt
  src/doc/src/commands/cargo-metadata.md
  src/doc/src/commands/cargo-tree.md
  src/doc/src/guide/build-cache.md
  src/doc/src/reference/config.md
  src/doc/src/reference/unstable.md
  src/etc/man/cargo-metadata.1
  src/etc/man/cargo-tree.1
Labels: S-waiting-on-bors

#11614 Fix unused attribute on Windows.
  crates/cargo-test-macro/src/lib.rs
  src/doc/contrib/src/tests/writing.md
  tests/testsuite/ssh.rs
Labels: S-waiting-on-bors

#11619 test: Update for clap 4.1.3
  Cargo.toml
  tests/testsuite/cargo_add/invalid_arg/stderr.log
Labels: S-waiting-on-bors

#11613 Improve CI caching by skipping mtime checks for paths in $CARGO_HOME
  src/cargo/core/compiler/fingerprint.rs
  tests/testsuite/build_script.rs
Labels: S-waiting-on-bors

#11620 Add a note about verifying your email address on crates.io
  src/doc/src/reference/publishing.md
Labels: S-waiting-on-bors

#11621 Add more labels to triagebot
  triagebot.toml
Labels: S-waiting-on-bors

#11622 Link CoC to www.rust-lang.org/conduct.html
  CODE_OF_CONDUCT.md
Labels: S-waiting-on-bors

#11612 `cargo add` check `[dependencies]` order without considering the dotted item
  src/cargo/ops/cargo_add/mod.rs
  tests/testsuite/cargo_add/mod.rs
  tests/testsuite/cargo_add/sorted_table_with_dotted_item/in/Cargo.toml
  tests/testsuite/cargo_add/sorted_table_with_dotted_item/in/src/lib.rs
  tests/testsuite/cargo_add/sorted_table_with_dotted_item/mod.rs
  tests/testsuite/cargo_add/sorted_table_with_dotted_item/out/Cargo.toml
  tests/testsuite/cargo_add/sorted_table_with_dotted_item/stderr.log
  tests/testsuite/cargo_add/sorted_table_with_dotted_item/stdout.log
Labels: S-waiting-on-bors

#11604 book: describe how the current resolver sometimes duplicates deps
  src/doc/src/reference/resolver.md
Labels: S-waiting-on-bors

#11565 refactor(toml): Move `TomlWorkspaceDependency` out of `TomlDependency`
  src/cargo/util/toml/mod.rs
  tests/testsuite/inheritable_workspace_fields.rs
Labels: S-waiting-on-bors

#11347 Fix split-debuginfo support detection
  src/cargo/core/compiler/build_context/target_info.rs
  src/cargo/core/compiler/mod.rs
Labels: S-waiting-on-bors

#11640 Bump to 0.70.0; update changelog
  CHANGELOG.md
  Cargo.toml
Labels: S-waiting-on-bors

#11633 Reduce target info rustc query calls
  src/cargo/core/compiler/build_context/target_info.rs
  tests/testsuite/cfg.rs
Labels: S-waiting-on-bors, beta-nominated

#11572 Make cargo aware of dwp files.
  crates/cargo-test-support/src/lib.rs
  src/cargo/core/compiler/build_context/target_info.rs
  src/cargo/ops/cargo_clean.rs
  tests/testsuite/build.rs
Labels: S-waiting-on-bors

#11648 Avoid saving the same future_incompat warning multiple times
  src/cargo/core/compiler/future_incompat.rs
Labels: S-waiting-on-bors

#11655 Warn on commits to non-default branches.
  triagebot.toml
Labels: S-waiting-on-bors

#11649 [beta-1.68] Backport fixes of split-debuginfo detection
  Cargo.toml
  src/cargo/core/compiler/build_context/target_info.rs
  src/cargo/core/compiler/mod.rs
  tests/testsuite/cargo_add/invalid_arg/stderr.log
  tests/testsuite/cfg.rs
  tests/testsuite/ssh.rs
Labels: S-waiting-on-bors

#11661 Do not error for `auth-required: true` without `-Z sparse-registry`
  src/cargo/sources/registry/http_remote.rs
  src/cargo/sources/registry/remote.rs
  tests/testsuite/registry_auth.rs
Labels: T-cargo, final-comment-period, disposition-merge, S-waiting-on-bors

#11647 Make cargo install report needed features
  src/cargo/ops/cargo_install.rs
  tests/testsuite/required_features.rs
Labels: S-waiting-on-bors

#11663 Update cross test instructions for aarch64-apple-darwin
  crates/cargo-test-support/src/cross_compile.rs
Labels: S-waiting-on-bors

#11664 chore: Add autolabel for `Command-*` labels
  triagebot.toml
Labels: S-waiting-on-bors
