Repository rust-lang/cargo, pull requests merged in 2023-11, with the labels that each got.

#12907 Add regression test for issue 6915: features and transitive dev deps
  tests/testsuite/features.rs
Labels: S-waiting-on-bors

#12908 fix: merge `trim-paths` from different profiles
  src/cargo/util/toml/mod.rs
  tests/testsuite/profile_trim_paths.rs
Labels: A-manifest, S-waiting-on-bors, Z-trim-paths

#12913 Updating "features" documentation to add a note about the new limit on number of features
  src/doc/src/reference/features.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12915 fix(cli): Clarify --test is for targets, not test functions
  src/bin/cargo/commands/bench.rs
  src/bin/cargo/commands/build.rs
  src/bin/cargo/commands/check.rs
  src/bin/cargo/commands/fix.rs
  src/bin/cargo/commands/rustc.rs
  src/bin/cargo/commands/rustdoc.rs
  src/bin/cargo/commands/test.rs
  src/cargo/util/workspace.rs
  tests/testsuite/cargo_bench/help/stdout.log
  tests/testsuite/cargo_build/help/stdout.log
  tests/testsuite/cargo_check/help/stdout.log
  tests/testsuite/cargo_fix/help/stdout.log
  tests/testsuite/cargo_rustc/help/stdout.log
  tests/testsuite/cargo_rustdoc/help/stdout.log
  tests/testsuite/cargo_test/help/stdout.log
  tests/testsuite/list_availables.rs
Labels: Command-test, Command-check, Command-bench, Command-build, Command-rustc, Command-rustdoc, A-workspaces, Command-fix, S-waiting-on-bors, A-cli

#12921 tests: Remove plugin tests
  tests/testsuite/cross_compile.rs
  tests/testsuite/main.rs
  tests/testsuite/plugins.rs
  tests/testsuite/proc_macro.rs
Labels: S-waiting-on-bors

#12911 refactor(toml): Pull out the schema
  src/bin/cargo/main.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/core/features.rs
  src/cargo/core/manifest.rs
  src/cargo/core/mod.rs
  src/cargo/core/profiles.rs
  src/cargo/core/workspace.rs
  src/cargo/lib.rs
  src/cargo/ops/cargo_package.rs
  src/cargo/util/command_prelude.rs
  src/cargo/util/toml/mod.rs
  src/cargo/util/toml/schema.rs
  src/cargo/util/toml/targets.rs
  tests/testsuite/config.rs
  tests/testsuite/profile_config.rs
Labels: A-build-execution, Command-package, A-workspaces, A-profiles, A-manifest, S-waiting-on-bors, A-cli, A-unstable

#12922 Update link in environment-variables.md
  src/doc/src/reference/environment-variables.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12923 Bug 12920
  src/cargo/util/semver_ext.rs
  tests/testsuite/update.rs
Labels: S-waiting-on-bors, A-semver

#12865 Add better error message when it can not find the search section
  src/cargo/util/toml_mut/manifest.rs
  tests/testsuite/cargo_remove/invalid_dep/stderr.log
  tests/testsuite/cargo_remove/invalid_section/stderr.log
  tests/testsuite/cargo_remove/invalid_section_dep/stderr.log
  tests/testsuite/cargo_remove/invalid_target/stderr.log
  tests/testsuite/cargo_remove/invalid_target_dep/stderr.log
Labels: A-documenting-cargo-itself, A-manifest, S-waiting-on-bors, A-cli, Command-remove

#12929 Fix some broken links in the man pages
  src/doc/man/cargo-add.md
  src/doc/man/cargo-install.md
  src/doc/man/generated_txt/cargo-add.txt
  src/doc/man/generated_txt/cargo-install.txt
  src/doc/src/commands/cargo-add.md
  src/doc/src/commands/cargo-install.md
  src/etc/man/cargo-add.1
  src/etc/man/cargo-install.1
Labels: A-documenting-cargo-itself, S-waiting-on-bors, A-cli-help

#12924 fix: Report more detailed semver errors
  Cargo.lock
  crates/xtask-bump-check/Cargo.toml
  crates/xtask-bump-check/src/xtask.rs
  src/bin/cargo/commands/install.rs
  src/cargo/core/package_id.rs
  src/cargo/sources/registry/index.rs
  src/cargo/util/mod.rs
  src/cargo/util/to_semver.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/install_upgrade.rs
  triagebot.toml
Labels: Command-install, A-registries, A-manifest, S-waiting-on-bors, A-cli, A-semver, A-infrastructure

#12934 fix(timings): unnecessary backslash when error happens
  src/cargo/core/compiler/timings.rs
Labels: S-waiting-on-bors, A-timings

#12928 Do not allow empty feature name
  src/cargo/core/summary.rs
  tests/testsuite/features.rs
Labels: S-waiting-on-bors

#12889 feat: Make browser links out of HTML file paths
  Cargo.lock
  Cargo.toml
  src/cargo/core/compiler/timings.rs
  src/cargo/core/shell.rs
  src/cargo/ops/cargo_doc.rs
  src/cargo/util/config/mod.rs
  src/cargo/util/hostname.rs
  src/cargo/util/mod.rs
  src/doc/src/reference/config.md
Labels: A-documenting-cargo-itself, Command-doc, A-configuration, T-cargo, A-console-output, final-comment-period, disposition-merge, S-waiting-on-bors, A-timings

#12926 refactor(util): Prepare for splitting out semver logic
  src/bin/cargo/commands/install.rs
  src/cargo/core/package_id_spec.rs
  src/cargo/ops/cargo_compile/mod.rs
  src/cargo/ops/common_for_install_and_uninstall.rs
  src/cargo/util/mod.rs
  src/cargo/util/semver_ext.rs
  src/cargo/util/toml/mod.rs
Labels: Command-install, A-manifest, S-waiting-on-bors, A-cli, A-semver

#12939 Fix the invalidate feature name message
  src/cargo/core/summary.rs
  tests/testsuite/features.rs
Labels: S-waiting-on-bors

#12940 refactor(util): Pull out `mod util_semver`
  src/bin/cargo/commands/install.rs
  src/cargo/core/package_id_spec.rs
  src/cargo/core/resolver/errors.rs
  src/cargo/lib.rs
  src/cargo/util/mod.rs
  src/cargo/util/semver_ext.rs
  src/cargo/util_semver.rs
Labels: Command-install, A-dependency-resolution, S-waiting-on-bors, A-cli, A-semver

#12949 Filter `cargo-credential-*` dependencies by OS
  Cargo.toml
  src/cargo/util/auth/mod.rs
Labels: S-waiting-on-bors, A-registry-authentication

#12948 refactor(toml): Simplify code to make schema split easier
  src/cargo/ops/cargo_package.rs
  src/cargo/util/command_prelude.rs
  src/cargo/util/config/mod.rs
  src/cargo/util/restricted_names.rs
  src/cargo/util/toml/embedded.rs
  src/cargo/util/toml/mod.rs
  src/cargo/util/toml/schema.rs
  src/cargo/util/toml/targets.rs
Labels: A-configuration, Command-package, A-manifest, S-waiting-on-bors, A-cli

#12930 refactor(resolver): Consolidate logic in `VersionPreferences`
  crates/resolver-tests/src/lib.rs
  src/cargo/core/resolver/dep_cache.rs
  src/cargo/core/resolver/mod.rs
  src/cargo/core/resolver/version_prefs.rs
  src/cargo/ops/resolve.rs
Labels: A-dependency-resolution, S-waiting-on-bors

#12951 fix: preserve jobserver file descriptors on rustc invocation in `fix_exec_rustc`
  src/cargo/ops/fix.rs
Labels: Command-fix, S-waiting-on-bors

#12953 credential: include license files in all published crates
  credential/cargo-credential-1password/LICENSE-APACHE
  credential/cargo-credential-1password/LICENSE-MIT
  credential/cargo-credential-libsecret/LICENSE-APACHE
  credential/cargo-credential-libsecret/LICENSE-MIT
  credential/cargo-credential-macos-keychain/LICENSE-APACHE
  credential/cargo-credential-macos-keychain/LICENSE-MIT
  credential/cargo-credential-wincred/LICENSE-APACHE
  credential/cargo-credential-wincred/LICENSE-MIT
  credential/cargo-credential/LICENSE-APACHE
  credential/cargo-credential/LICENSE-MIT
Labels: S-waiting-on-bors, A-credential-provider

#12938 refactor(source): Prepare for new PackageIDSpec syntax
  src/cargo/core/package_id_spec.rs
  src/cargo/core/source_id.rs
Labels: S-waiting-on-bors

#12956 Fix typo
  src/doc/src/reference/profiles.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12954 refactor(toml): Improve consistency
  src/cargo/util/toml/mod.rs
  src/cargo/util/toml/schema.rs
  src/cargo/util/toml/targets.rs
Labels: A-manifest, S-waiting-on-bors

#12634 Add cache garbage collection
  Cargo.lock
  Cargo.toml
  benches/README.md
  benches/benchsuite/Cargo.toml
  benches/benchsuite/benches/global_cache_tracker.rs
  benches/benchsuite/global-cache-tracker/global-cache-sample
  benches/benchsuite/global-cache-tracker/random-sample
  benches/benchsuite/src/bin/capture-last-use.rs
  crates/cargo-test-support/Cargo.toml
  crates/cargo-test-support/src/paths.rs
  crates/cargo-util/Cargo.toml
  crates/cargo-util/src/du.rs
  crates/cargo-util/src/lib.rs
  src/bin/cargo/commands/clean.rs
  src/bin/cargo/commands/config.rs
  src/cargo/core/features.rs
  src/cargo/core/gc.rs
  src/cargo/core/global_cache_tracker.rs
  src/cargo/core/mod.rs
  src/cargo/core/package.rs
  src/cargo/ops/cargo_clean.rs
  src/cargo/ops/cargo_compile/mod.rs
  src/cargo/ops/cargo_fetch.rs
  src/cargo/ops/mod.rs
  src/cargo/ops/resolve.rs
  src/cargo/sources/git/source.rs
  src/cargo/sources/registry/download.rs
  src/cargo/sources/registry/http_remote.rs
  src/cargo/sources/registry/mod.rs
  src/cargo/sources/registry/remote.rs
  src/cargo/util/config/mod.rs
  src/cargo/util/mod.rs
  src/cargo/util/sqlite.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/clean.rs
  tests/testsuite/global_cache_tracker.rs
  tests/testsuite/main.rs
Labels: A-documenting-cargo-itself, A-git, A-configuration, Command-clean, Command-publish, A-interacts-with-crates.io, Command-fetch, Command-generate-lockfile, Command-package, A-registries, A-testing-cargo-itself, S-waiting-on-bors, A-cli, A-filesystem, A-unstable, A-future-incompat, Command-add, A-sparse-registry, A-infrastructure

#12958 Fix non-deterministic behavior in last-use repopulation
  src/cargo/core/global_cache_tracker.rs
Labels: S-waiting-on-bors

#12961 refactor(toml): Remove unused method
  src/cargo/util/toml/mod.rs
Labels: A-manifest, S-waiting-on-bors

#12960 refactor(toml): Consistently lead with 'Toml' prefix
  src/cargo/util/toml/mod.rs
  src/cargo/util/toml/schema.rs
Labels: A-manifest, S-waiting-on-bors

#12963 make some debug assertion failures more informative
  src/cargo/util/rustc.rs
Labels: S-waiting-on-bors, A-cache-messages

#12962 Improve about information of `cargo search`
  src/bin/cargo/commands/search.rs
  src/doc/man/cargo-search.md
  src/doc/man/generated_txt/cargo-search.txt
  src/doc/src/commands/cargo-search.md
  src/etc/man/cargo-search.1
  tests/testsuite/cargo_search/help/stdout.log
Labels: A-documenting-cargo-itself, Command-search, S-waiting-on-bors, A-cli, A-cli-help

#12966 Bump to 0.77.0; update changelog
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#12965 fix: do not panic when failed to parse rustc commit-hash
  src/cargo/util/rustc.rs
Labels: S-waiting-on-bors, A-cache-messages

#12972 Ignore changing_spec_relearns_crate_types on windows-gnu
  tests/testsuite/custom_target.rs
Labels: S-waiting-on-bors

#12944 Only filter out target if its in the package root
  src/cargo/sources/path.rs
  tests/testsuite/package.rs
Labels: S-waiting-on-bors

#12973 fix error message for duplicate links
  src/cargo/core/resolver/errors.rs
  tests/testsuite/build_script.rs
Labels: A-dependency-resolution, S-waiting-on-bors

#12950 fix(resolver): Prefer MSRV, rather than ignore incompatible
  src/cargo/core/resolver/version_prefs.rs
  tests/testsuite/cargo_add/rust_version_ignore/mod.rs
  tests/testsuite/cargo_add/rust_version_ignore/stderr.log
  tests/testsuite/rust_version.rs
Labels: A-dependency-resolution, S-waiting-on-bors

#12977 If the only path is a loop then counted as the shortest path.
  src/cargo/util/graph.rs
  tests/testsuite/test.rs
Labels: S-waiting-on-bors

#12981 Switch from AtomicU64 to Mutex.
  Cargo.lock
  crates/cargo-util/Cargo.toml
  crates/cargo-util/src/du.rs
Labels: S-waiting-on-bors

#12976 docs(ref): Find a place to comment on --cap-lints
  src/doc/src/reference/manifest.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12982 Fix some test output validation.
  tests/testsuite/artifact_dep.rs
  tests/testsuite/build.rs
  tests/testsuite/build_script.rs
  tests/testsuite/clean.rs
  tests/testsuite/doc.rs
  tests/testsuite/features.rs
  tests/testsuite/fetch.rs
  tests/testsuite/freshness.rs
  tests/testsuite/generate_lockfile.rs
  tests/testsuite/git.rs
  tests/testsuite/package.rs
  tests/testsuite/path.rs
  tests/testsuite/publish_lockfile.rs
  tests/testsuite/registry.rs
  tests/testsuite/replace.rs
  tests/testsuite/rustflags.rs
  tests/testsuite/test.rs
Labels: S-waiting-on-bors

#12987 Fix a rustflags test using a wrong buildfile name
  tests/testsuite/rustflags.rs
Labels: S-waiting-on-bors

#12986 cargo-credential-1password: Fix README
  Cargo.lock
  credential/cargo-credential-1password/Cargo.toml
  credential/cargo-credential-1password/README.md
  src/doc/src/reference/registry-authentication.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors, A-credential-provider

#12178 chore: dogfood Cargo `-Zlints` table feature
  .github/workflows/main.yml
  Cargo.lock
  Cargo.toml
  benches/benchsuite/Cargo.toml
  benches/benchsuite/src/lib.rs
  benches/capture/Cargo.toml
  benches/capture/src/main.rs
  crates/cargo-platform/Cargo.toml
  crates/cargo-platform/examples/matches.rs
  crates/cargo-test-macro/Cargo.toml
  crates/cargo-test-support/Cargo.toml
  crates/cargo-test-support/build.rs
  crates/cargo-test-support/src/lib.rs
  crates/cargo-util/Cargo.toml
  crates/cargo-util/src/lib.rs
  crates/crates-io/Cargo.toml
  crates/crates-io/lib.rs
  crates/home/Cargo.toml
  crates/home/src/lib.rs
  crates/mdman/Cargo.toml
  crates/mdman/src/main.rs
  crates/mdman/tests/compare.rs
  crates/resolver-tests/Cargo.toml
  crates/resolver-tests/src/lib.rs
  crates/semver-check/Cargo.toml
  crates/semver-check/src/main.rs
  crates/xtask-build-man/Cargo.toml
  crates/xtask-build-man/src/main.rs
  crates/xtask-bump-check/Cargo.toml
  crates/xtask-stale-label/Cargo.toml
  crates/xtask-stale-label/src/main.rs
  credential/cargo-credential-1password/Cargo.toml
  credential/cargo-credential-1password/src/main.rs
  credential/cargo-credential-libsecret/Cargo.toml
  credential/cargo-credential-macos-keychain/Cargo.toml
  credential/cargo-credential-macos-keychain/src/lib.rs
  credential/cargo-credential-wincred/Cargo.toml
  credential/cargo-credential/Cargo.toml
  credential/cargo-credential/examples/stdout-redirected.rs
  credential/cargo-credential/src/lib.rs
  src/bin/cargo/main.rs
  src/cargo/lib.rs
  src/cargo/util/errors.rs
  tests/build-std/main.rs
  tests/testsuite/main.rs
Labels: A-building-cargo-itself, A-interacts-with-crates.io, A-dependency-resolution, A-environment-variables, A-testing-cargo-itself, S-waiting-on-bors, A-cli, A-cfg-expr, A-semver, A-cli-help, A-credential-provider, A-registry-authentication, A-infrastructure, A-lints-table, A-home

#12985 cargo-credential-1password: Add missing `--account` argument to `op signin` command
  credential/cargo-credential-1password/src/main.rs
Labels: S-waiting-on-bors, A-credential-provider

#12988 chore(ci): Catch naive use of AtomicU64 early
  clippy.toml
Labels: S-waiting-on-bors, A-infrastructure

#12990 Link to rustc lint levels
  src/doc/src/reference/manifest.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12991 refactor: log when loading config from file
  src/cargo/util/config/mod.rs
Labels: A-configuration, S-waiting-on-bors

#12992 feat(cli): add color output for `cargo --list`
  src/bin/cargo/cli.rs
Labels: S-waiting-on-bors, A-cli

#12994 [beta 1.75] Backport 1password fixes
  Cargo.lock
  credential/cargo-credential-1password/Cargo.toml
  credential/cargo-credential-1password/README.md
  credential/cargo-credential-1password/src/main.rs
  src/doc/src/reference/registry-authentication.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors, A-credential-provider

#12993 docs: Recommend a wider selection of libsecret-compatible password managers
  src/doc/src/reference/registry-authentication.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12971 refactor(toml): Clean up workspace inheritance
  src/cargo/core/mod.rs
  src/cargo/core/workspace.rs
  src/cargo/util/toml/mod.rs
  src/cargo/util/toml/schema.rs
Labels: A-workspaces, A-manifest, S-waiting-on-bors

#12975 fix(resolver): Don't do git fetches when updating workspace members
  src/cargo/ops/cargo_generate_lockfile.rs
  tests/testsuite/update.rs
Labels: Command-generate-lockfile, S-waiting-on-bors

#12999 Fix clippy-wrapper test race condition.
  crates/cargo-test-support/src/lib.rs
  crates/cargo-test-support/src/tools.rs
  tests/testsuite/check.rs
  tests/testsuite/fix.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors

#12968 Respect `rust-lang/rust`'s `omit-git-hash`
  build.rs
Labels: S-waiting-on-bors, A-infrastructure

#13008 Add more resources to the contrib docs.
  src/doc/contrib/src/team.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#13006 contrib docs: Update now that credential crates are published.
  src/doc/contrib/src/process/release.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#13004 [stable-1.74] chore: bump `cargo-credential-*` crates as e58b84d broke stuff
  .github/workflows/main.yml
  Cargo.lock
  Cargo.toml
  credential/cargo-credential-libsecret/Cargo.toml
  credential/cargo-credential-macos-keychain/Cargo.toml
  credential/cargo-credential-wincred/Cargo.toml
  src/cargo/core/resolver/context.rs
  tests/testsuite/cross_compile.rs
  tests/testsuite/main.rs
  tests/testsuite/plugins.rs
  tests/testsuite/proc_macro.rs
Labels: A-dependency-resolution, S-waiting-on-bors, A-credential-provider, A-infrastructure

#13009 [beta-1.75.0] chore: bump `cargo-credential-*` crates as e58b84d broke stuff
  Cargo.lock
  Cargo.toml
  credential/cargo-credential-libsecret/Cargo.toml
  credential/cargo-credential-macos-keychain/Cargo.toml
  credential/cargo-credential-wincred/Cargo.toml
Labels: S-waiting-on-bors, A-credential-provider

#13010 chore: bump `cargo-credential-*` crates as e58b84d broke stuff
  Cargo.lock
  Cargo.toml
  credential/cargo-credential-libsecret/Cargo.toml
  credential/cargo-credential-macos-keychain/Cargo.toml
  credential/cargo-credential-wincred/Cargo.toml
Labels: S-waiting-on-bors, A-credential-provider

#13015 [stable 1.74] Bump cargo patch version
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#13011 Fix `--check-cfg` invocations with zero features
  src/cargo/core/compiler/mod.rs
  tests/testsuite/check_cfg.rs
Labels: A-build-execution, S-waiting-on-bors

#13000 refactor(toml): Further clean up inheritance
  src/cargo/util/toml/mod.rs
  src/cargo/util/toml/schema.rs
Labels: A-manifest, S-waiting-on-bors

#13016 Handle $message_type in JSON diagnostics
  crates/cargo-test-support/src/compare.rs
  tests/testsuite/doc.rs
  tests/testsuite/metabuild.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors

#13019 typo: rusc -> rustc
  src/cargo/core/compiler/job_queue/mod.rs
Labels: A-build-execution, S-waiting-on-bors

#13005 Migrate rustfix to the cargo repo
  Cargo.lock
  Cargo.toml
  crates/rustfix/Cargo.toml
  crates/rustfix/Changelog.md
  crates/rustfix/LICENSE-APACHE
  crates/rustfix/LICENSE-MIT
  crates/rustfix/Readme.md
  crates/rustfix/examples/fix-json.rs
  crates/rustfix/proptest-regressions/replace.txt
  crates/rustfix/src/diagnostics.rs
  crates/rustfix/src/lib.rs
  crates/rustfix/src/replace.rs
  crates/rustfix/tests/edge-cases/empty.json
  crates/rustfix/tests/edge-cases/empty.rs
  crates/rustfix/tests/edge-cases/indented_whitespace.json
  crates/rustfix/tests/edge-cases/no_main.json
  crates/rustfix/tests/edge-cases/no_main.rs
  crates/rustfix/tests/edge-cases/out_of_bounds.recorded.json
  crates/rustfix/tests/edge-cases/utf8_idents.recorded.json
  crates/rustfix/tests/edge_cases.rs
  crates/rustfix/tests/edition/.gitignore
  crates/rustfix/tests/everything/.gitignore
  crates/rustfix/tests/everything/E0178.fixed.rs
  crates/rustfix/tests/everything/E0178.json
  crates/rustfix/tests/everything/E0178.rs
  crates/rustfix/tests/everything/closure-immutable-outer-variable.fixed.rs
  crates/rustfix/tests/everything/closure-immutable-outer-variable.json
  crates/rustfix/tests/everything/closure-immutable-outer-variable.rs
  crates/rustfix/tests/everything/handle-insert-only.fixed.rs
  crates/rustfix/tests/everything/handle-insert-only.json
  crates/rustfix/tests/everything/handle-insert-only.rs
  crates/rustfix/tests/everything/lt-generic-comp.fixed.rs
  crates/rustfix/tests/everything/lt-generic-comp.json
  crates/rustfix/tests/everything/lt-generic-comp.rs
  crates/rustfix/tests/everything/multiple-solutions.fixed.rs
  crates/rustfix/tests/everything/multiple-solutions.json
  crates/rustfix/tests/everything/multiple-solutions.rs
  crates/rustfix/tests/everything/replace-only-one-char.fixed.rs
  crates/rustfix/tests/everything/replace-only-one-char.json
  crates/rustfix/tests/everything/replace-only-one-char.rs
  crates/rustfix/tests/everything/str-lit-type-mismatch.fixed.rs
  crates/rustfix/tests/everything/str-lit-type-mismatch.json
  crates/rustfix/tests/everything/str-lit-type-mismatch.rs
  crates/rustfix/tests/parse_and_replace.rs
  crates/xtask-bump-check/src/xtask.rs
  publish.py
  src/doc/contrib/src/issues.md
  triagebot.toml
Labels: A-documenting-cargo-itself, S-waiting-on-bors, A-infrastructure

#12997 cargo-test-support: Add features to the default Cargo.toml file
  crates/cargo-test-support/src/registry.rs
  tests/testsuite/cargo_remove/update_lock_file/in/Cargo.lock
  tests/testsuite/cargo_remove/update_lock_file/out/Cargo.lock
Labels: A-testing-cargo-itself, S-waiting-on-bors

#13021 refactor(toml): Better abstract inheritance details
  src/cargo/util/toml/mod.rs
Labels: A-manifest, S-waiting-on-bors

#13042 try running on windows
  crates/rustfix/tests/parse_and_replace.rs
Labels: Command-fix, S-waiting-on-bors

#12995 Exited with hard error when custom build file no existence or not in package
  src/cargo/ops/cargo_package.rs
  tests/testsuite/package.rs
Labels: Command-package, S-waiting-on-bors

#12996 feat: Add `CARGO_RUSTC_CURRENT_DIR` (unstable)
  src/cargo/core/compiler/mod.rs
  src/doc/src/reference/environment-variables.md
  tests/testsuite/build.rs
Labels: A-documenting-cargo-itself, A-build-execution, S-waiting-on-bors

#13048 docs: add doc comments for rustfix
  crates/rustfix/src/diagnostics.rs
  crates/rustfix/src/lib.rs
  crates/rustfix/src/replace.rs
  src/cargo/lib.rs
Labels: Command-fix, S-waiting-on-bors

#13047 review and remove ignored tests in rustfix
  crates/rustfix/src/replace.rs
  crates/rustfix/tests/edition/.gitignore
  crates/rustfix/tests/parse_and_replace.rs
Labels: Command-fix, S-waiting-on-bors

#13056 docs: Provide pointers for MSRV
  src/doc/src/guide/continuous-integration.md
  src/doc/src/reference/manifest.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#13055 Add more doc comments for gc changes.
  src/cargo/core/global_cache_tracker.rs
  src/cargo/sources/git/source.rs
  src/cargo/sources/registry/http_remote.rs
  src/cargo/sources/registry/mod.rs
  src/cargo/sources/registry/remote.rs
  src/cargo/util/config/mod.rs
Labels: A-git, A-configuration, A-registries, S-waiting-on-bors, A-sparse-registry

#13057 docs: link to the packages lint table from the related workspace table
  src/doc/src/reference/workspaces.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#13066 fix(resolver): De-prioritize no-rust-version in MSRV resolver
  src/cargo/core/resolver/version_prefs.rs
Labels: A-dependency-resolution, S-waiting-on-bors

#13070 docs: remove review capacity notice in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: S-waiting-on-bors, A-infrastructure

#13072 remove jobserver env var in some tests
  tests/testsuite/fix.rs
Labels: S-waiting-on-bors

#13065 fix: reorder `--remap-path-prefix` flags for `-Zbuild-std`
  src/cargo/core/compiler/mod.rs
  tests/build-std/main.rs
  tests/testsuite/profile_trim_paths.rs
Labels: A-build-execution, S-waiting-on-bors, Z-build-std, Z-trim-paths

#12484 Fixes error count display is different when there's only one error left
  src/cargo/core/compiler/mod.rs
  tests/testsuite/build.rs
  tests/testsuite/build_script.rs
  tests/testsuite/check.rs
  tests/testsuite/fix.rs
  tests/testsuite/install.rs
  tests/testsuite/messages.rs
  tests/testsuite/replace.rs
Labels: A-build-execution, S-waiting-on-bors, S-blocked-external

#13036 fix(resolver): Remove unused public-deps error handling
  crates/resolver-tests/src/lib.rs
  crates/resolver-tests/tests/resolve.rs
  src/cargo/core/resolver/context.rs
  src/cargo/core/resolver/mod.rs
  src/cargo/ops/resolve.rs
Labels: A-dependency-resolution, S-waiting-on-bors

#13076 Remove the outdated comment
  src/cargo/ops/cargo_add/crate_spec.rs
Labels: S-waiting-on-bors, Command-add

#13077 Don't filter on workspace members when scraping doc examples
  src/cargo/core/compiler/mod.rs
  tests/testsuite/docscrape.rs
Labels: A-build-execution, S-waiting-on-bors
