Repository rust-lang/cargo, pull requests merged in 2023-08, with the labels that each got.

#12420 Display crate version on timings graph
  src/cargo/core/compiler/timings.js
Labels: S-waiting-on-bors, A-timings

#12428 fix(update): Tweak CLI behavior
  src/bin/cargo/commands/update.rs
  tests/testsuite/cargo_update/help/stdout.log
  tests/testsuite/update.rs
Labels: Command-update, S-waiting-on-bors, A-cli

#12395 ci: rewrite bump check and respect semver
  .cargo/config.toml
  .github/workflows/main.yml
  Cargo.lock
  ci/validate-version-bump.sh
  crates/xtask-bump-check/Cargo.toml
  crates/xtask-bump-check/src/main.rs
  crates/xtask-bump-check/src/xtask.rs
  crates/xtask-unpublished/src/xtask.rs
Labels: S-waiting-on-bors, A-infrastructure

#12429 `#[allow(internal_features)]` in RUSTC_BOOTSTRAP test
  tests/testsuite/build_script_env.rs
Labels: S-waiting-on-bors

#12435 replace `master` branch by default branch in documentation
  src/doc/src/guide/cargo-toml-vs-cargo-lock.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12440 Don't attempt to read a token from stdin if a cmdline token is provided
  src/cargo/ops/registry/login.rs
Labels: A-interacts-with-crates.io, Command-login, S-waiting-on-bors

#12443 Fix CVE-2023-38497 for master
  src/cargo/sources/registry/mod.rs
  src/cargo/util/mod.rs
  tests/testsuite/registry.rs
  tests/testsuite/vendor.rs
Labels: A-registries, S-waiting-on-bors

#12442 Fix CVE-2023-38497 for beta 1.72.0
  Cargo.lock
  Cargo.toml
  src/cargo/sources/registry/mod.rs
  src/cargo/util/mod.rs
  tests/testsuite/bench.rs
  tests/testsuite/install.rs
  tests/testsuite/registry.rs
  tests/testsuite/test.rs
  tests/testsuite/vendor.rs
Labels: A-registries, S-waiting-on-bors

#12444 Remove build metadata from libgit2-sys dependency
  Cargo.toml
Labels: S-waiting-on-bors

#12445 Update pretty_env_logger to 0.5
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#12450 Add allow(internal_features)
  tests/testsuite/cargo_features.rs
  tests/testsuite/custom_target.rs
  tests/testsuite/doc.rs
Labels: S-waiting-on-bors

#12451 Rustfmt a let-else statement
  src/cargo/util/errors.rs
Labels: S-waiting-on-bors

#12453 Update windows dependencies
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#12439 Fix printing multiple warning messages for unused fields in [registries] table
  src/cargo/util/auth/mod.rs
  src/cargo/util/config/mod.rs
  tests/testsuite/alt_registry.rs
Labels: A-configuration, S-waiting-on-bors, A-registry-authentication

#12461 docs: add example for cargo-credential
  Cargo.lock
  credential/cargo-credential/Cargo.toml
  credential/cargo-credential/examples/file-provider.rs
  credential/cargo-credential/src/lib.rs
  credential/cargo-credential/tests/examples.rs
Labels: S-waiting-on-bors, A-registry-authentication

#12462 Bump cargo library to 0.72.2 for CVE patches
  Cargo.lock
  Cargo.toml
  src/cargo/sources/git/known_hosts.rs
  tests/testsuite/bench.rs
  tests/testsuite/build_script_env.rs
  tests/testsuite/cargo_features.rs
  tests/testsuite/custom_target.rs
  tests/testsuite/doc.rs
  tests/testsuite/install.rs
  tests/testsuite/test.rs
Labels: A-git, S-waiting-on-bors

#12447 fix: preserve jobserver file descriptors on rustc invocation to get `TargetInfo`
  src/cargo/core/compiler/build_context/target_info.rs
Labels: S-waiting-on-bors, A-cfg-expr

#12468 Fix panic when enabling http.debug for certain strings
  src/cargo/util/network/http.rs
Labels: A-networking, S-waiting-on-bors

#12466 chore(gh): Expand update window
  .github/renovate.json5
Labels: S-waiting-on-bors, A-infrastructure

#12454 Fix cargo remove incorrectly removing used patches
  src/bin/cargo/commands/remove.rs
  tests/testsuite/cargo_remove/avoid_empty_tables/stderr.log
  tests/testsuite/cargo_remove/build/stderr.log
  tests/testsuite/cargo_remove/dev/stderr.log
  tests/testsuite/cargo_remove/gc_keep_used_patch/in/Cargo.toml
  tests/testsuite/cargo_remove/gc_keep_used_patch/in/serde/Cargo.toml
  tests/testsuite/cargo_remove/gc_keep_used_patch/in/serde/src/lib.rs
  tests/testsuite/cargo_remove/gc_keep_used_patch/in/serde_derive/Cargo.toml
  tests/testsuite/cargo_remove/gc_keep_used_patch/in/serde_derive/src/lib.rs
  tests/testsuite/cargo_remove/gc_keep_used_patch/mod.rs
  tests/testsuite/cargo_remove/gc_keep_used_patch/out/Cargo.toml
  tests/testsuite/cargo_remove/gc_keep_used_patch/out/serde/Cargo.toml
  tests/testsuite/cargo_remove/gc_keep_used_patch/out/serde/src/lib.rs
  tests/testsuite/cargo_remove/gc_keep_used_patch/out/serde_derive/Cargo.toml
  tests/testsuite/cargo_remove/gc_keep_used_patch/out/serde_derive/src/lib.rs
  tests/testsuite/cargo_remove/gc_keep_used_patch/stderr.log
  tests/testsuite/cargo_remove/gc_keep_used_patch/stdout.log
  tests/testsuite/cargo_remove/gc_patch/mod.rs
  tests/testsuite/cargo_remove/gc_patch/out/Cargo.lock
  tests/testsuite/cargo_remove/gc_patch/stderr.log
  tests/testsuite/cargo_remove/gc_profile/stderr.log
  tests/testsuite/cargo_remove/gc_replace/stderr.log
  tests/testsuite/cargo_remove/mod.rs
  tests/testsuite/cargo_remove/multiple_deps/stderr.log
  tests/testsuite/cargo_remove/multiple_dev/stderr.log
  tests/testsuite/cargo_remove/optional_dep_feature/stderr.log
  tests/testsuite/cargo_remove/optional_feature/stderr.log
  tests/testsuite/cargo_remove/package/stderr.log
  tests/testsuite/cargo_remove/remove_basic/stderr.log
  tests/testsuite/cargo_remove/target/stderr.log
  tests/testsuite/cargo_remove/target_build/stderr.log
  tests/testsuite/cargo_remove/target_dev/stderr.log
  tests/testsuite/cargo_remove/update_lock_file/stderr.log
  tests/testsuite/cargo_remove/workspace/stderr.log
  tests/testsuite/cargo_remove/workspace_non_virtual/stderr.log
  tests/testsuite/cargo_remove/workspace_preserved/stderr.log
Labels: S-waiting-on-bors, A-cli, Command-remove

#12469 cargo-credential: reset stdin & stdout to the Console
  Cargo.lock
  credential/cargo-credential-1password/src/lib.rs
  credential/cargo-credential/Cargo.toml
  credential/cargo-credential/examples/stdout-redirected.rs
  credential/cargo-credential/src/lib.rs
  credential/cargo-credential/src/stdio.rs
  credential/cargo-credential/tests/examples.rs
Labels: S-waiting-on-bors, Z-credential-process, A-registry-authentication

#12463 prompt the use of `--nocapture` flag if `cargo test` process is terminated via a signal.
  src/cargo/ops/cargo_test.rs
  tests/testsuite/test.rs
Labels: Command-test, A-errors, S-waiting-on-bors

#12475 Fix elided lifetime in associated const
  src/cargo/sources/registry/mod.rs
Labels: A-registries, S-waiting-on-bors

#12479 doc: note the backward compatible `.cargo/credential` file exists
  src/doc/src/reference/config.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12482 docs: make the env var source of rerun-if-env-changed clearer
  src/doc/src/reference/build-scripts.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12483 chore: window-sys should be a platform-specific dependency
  credential/cargo-credential/Cargo.toml
Labels: S-waiting-on-bors, A-registry-authentication

#12478 feat: remove `--keep-going` from `cargo test/bench`
  src/bin/cargo/commands/bench.rs
  src/bin/cargo/commands/test.rs
  src/cargo/util/command_prelude.rs
  src/doc/man/cargo-test.md
  src/doc/man/generated_txt/cargo-test.txt
  src/doc/src/commands/cargo-test.md
  src/etc/_cargo
  src/etc/cargo.bashcomp.sh
  src/etc/man/cargo-test.1
  tests/testsuite/bench.rs
  tests/testsuite/cargo_bench/help/stdout.log
  tests/testsuite/cargo_test/help/stdout.log
  tests/testsuite/test.rs
Labels: A-documenting-cargo-itself, Command-test, Command-bench, S-waiting-on-bors, A-completions, A-cli, A-cli-help

#12491 test: bypass `rustc --test` impl details for `-Zfuture-incompat-test`
  tests/testsuite/future_incompat_report.rs
Labels: S-waiting-on-bors

#12490 Update cargo-yank.md
  src/doc/man/cargo-yank.md
  src/doc/man/generated_txt/cargo-yank.txt
  src/doc/src/commands/cargo-yank.md
  src/etc/man/cargo-yank.1
Labels: A-documenting-cargo-itself, S-waiting-on-bors, A-cli-help

#12492 doc(unstable): `cargo test` does not provide `--keep-going`
  src/doc/src/reference/unstable.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12500 test: relax assertions of panic message (again)
  tests/testsuite/bench.rs
  tests/testsuite/test.rs
Labels: S-waiting-on-bors

#12501 fix(lints): Doctest extraction should respect `[lints]`
  src/cargo/ops/cargo_test.rs
  tests/testsuite/lints.rs
Labels: Command-test, S-waiting-on-bors

#11447 Crate checksum lookup query should match on semver build metadata
  src/cargo/sources/registry/index.rs
  src/cargo/sources/registry/mod.rs
  tests/testsuite/registry.rs
Labels: A-registries, S-waiting-on-bors

#12504 Update hermit-abi
  Cargo.lock
Labels: S-waiting-on-bors

#12505 [beta-1.72.0] bump cargo-util to 0.2.5
  Cargo.lock
  Cargo.toml
  crates/cargo-util/Cargo.toml
  tests/testsuite/cargo_features.rs
  tests/testsuite/custom_target.rs
  tests/testsuite/doc.rs
  tests/testsuite/future_incompat_report.rs
Labels: S-waiting-on-bors

#12508 ci: use pull request head commit whenever possible
  .github/workflows/main.yml
Labels: S-waiting-on-bors, A-infrastructure

#12513 fix(xtask-bump-check): query by package name to detect changes
  crates/xtask-bump-check/src/xtask.rs
Labels: S-waiting-on-bors, A-infrastructure

#12512 credential: rename cargo:basic to cargo:token-from-stdout
  src/cargo/util/auth/mod.rs
  src/cargo/util/credential/adaptor.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/credential_process.rs
Labels: A-documenting-cargo-itself, S-waiting-on-bors, A-registry-authentication

#12517 chore(cargo-util): bump version to 0.2.6
  Cargo.lock
  Cargo.toml
  crates/cargo-util/Cargo.toml
Labels: S-waiting-on-bors

#12498 Print environment variables for `cargo run` in extra verbose mode
  src/cargo/ops/cargo_run.rs
  src/cargo/ops/cargo_test.rs
  tests/testsuite/bench.rs
  tests/testsuite/profile_targets.rs
  tests/testsuite/run.rs
  tests/testsuite/test.rs
Labels: Command-test, Command-run, S-waiting-on-bors

#12507 credential-providers: make 1password no longer built-in
  Cargo.lock
  Cargo.toml
  credential/cargo-credential-1password/src/main.rs
  src/cargo/util/auth/mod.rs
  src/doc/src/reference/unstable.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors, Z-credential-process, A-registry-authentication

#12518 cargo-credential-gnome-secret: dynamically load libsecret
  Cargo.lock
  Cargo.toml
  credential/cargo-credential-gnome-secret/Cargo.toml
  credential/cargo-credential-gnome-secret/build.rs
  credential/cargo-credential-gnome-secret/src/libsecret.rs
Labels: S-waiting-on-bors, A-registry-authentication

#12499 login: allow passing additional args to provider
  src/bin/cargo/commands/login.rs
  src/cargo/ops/registry/login.rs
  src/cargo/util/auth/mod.rs
  src/cargo/util/credential/paseto.rs
  tests/testsuite/cargo_login/help/stdout.log
  tests/testsuite/credential_process.rs
  tests/testsuite/login.rs
Labels: A-interacts-with-crates.io, Command-login, S-waiting-on-bors, A-cli, A-registry-authentication

#12521 Make cargo-credential-gnome-secret built-in as cargo:libsecret
  Cargo.lock
  Cargo.toml
  crates/xtask-bump-check/src/xtask.rs
  credential/cargo-credential-gnome-secret/src/libsecret.rs
  credential/cargo-credential-gnome-secret/src/main.rs
  credential/cargo-credential-libsecret/Cargo.toml
  credential/cargo-credential-libsecret/README.md
  credential/cargo-credential-libsecret/src/lib.rs
  deny.toml
  src/cargo/util/auth/mod.rs
  src/doc/src/reference/unstable.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors, Z-credential-process, A-registry-authentication, A-infrastructure

#12169 Document layout SemVer compatibility.
  crates/semver-check/src/main.rs
  src/doc/src/reference/semver.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors, A-semver

#12522 Fix typo: "use" -> "used"
  src/cargo/core/compiler/context/compilation_files.rs
Labels: S-waiting-on-bors, A-layout

#12526 Improve error message for when no credential providers are available
  src/cargo/util/auth/mod.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/credential_process.rs
Labels: A-documenting-cargo-itself, S-waiting-on-bors, A-registry-authentication

#12528 chore: Downgrade serde below the binary blob
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#12538 docs: Remove redundant explicit link
  src/cargo/ops/cargo_compile/mod.rs
Labels: S-waiting-on-bors

#12382 fix: Change the defaults to always check-in `Cargo.lock`
  src/cargo/ops/cargo_new.rs
  src/doc/src/faq.md
  src/doc/src/guide/cargo-toml-vs-cargo-lock.md
  src/doc/src/guide/continuous-integration.md
  tests/testsuite/cargo_init/auto_git/out/.gitignore
  tests/testsuite/cargo_init/fossil_autodetect/out/.fossil-settings/clean-glob
  tests/testsuite/cargo_init/fossil_autodetect/out/.fossil-settings/ignore-glob
  tests/testsuite/cargo_init/git_autodetect/out/.gitignore
  tests/testsuite/cargo_init/git_ignore_exists_no_conflicting_entries/out/.gitignore
  tests/testsuite/cargo_init/inferred_lib_with_git/out/.gitignore
  tests/testsuite/cargo_init/mercurial_autodetect/out/.hgignore
  tests/testsuite/cargo_init/pijul_autodetect/out/.ignore
  tests/testsuite/cargo_init/simple_git/out/.gitignore
  tests/testsuite/cargo_init/simple_git_ignore_exists/out/.gitignore
  tests/testsuite/cargo_init/simple_hg/out/.hgignore
  tests/testsuite/cargo_init/simple_hg_ignore_exists/out/.hgignore
  tests/testsuite/new.rs
Labels: A-documenting-cargo-itself, Command-new, S-waiting-on-bors

#12539 Bump to 0.75.0; update changelog
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#12541 docs(guide): Generalize over VCSs
  src/doc/src/guide/cargo-toml-vs-cargo-lock.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12529 refactor: Use clap to suggest alternative argument for unsupported arguments
  Cargo.lock
  Cargo.toml
  src/bin/cargo/commands/bench.rs
  src/bin/cargo/commands/build.rs
  src/bin/cargo/commands/check.rs
  src/bin/cargo/commands/doc.rs
  src/bin/cargo/commands/fix.rs
  src/bin/cargo/commands/install.rs
  src/bin/cargo/commands/package.rs
  src/bin/cargo/commands/publish.rs
  src/bin/cargo/commands/run.rs
  src/bin/cargo/commands/rustc.rs
  src/bin/cargo/commands/rustdoc.rs
  src/bin/cargo/commands/test.rs
  src/bin/cargo/commands/vendor.rs
  src/cargo/util/command_prelude.rs
  tests/testsuite/bench.rs
  tests/testsuite/cargo_bench/mod.rs
  tests/testsuite/cargo_bench/no_keep_going/in/Cargo.toml
  tests/testsuite/cargo_bench/no_keep_going/in/src/lib.rs
  tests/testsuite/cargo_bench/no_keep_going/mod.rs
  tests/testsuite/cargo_bench/no_keep_going/stderr.log
  tests/testsuite/cargo_bench/no_keep_going/stdout.log
  tests/testsuite/cargo_test/mod.rs
  tests/testsuite/cargo_test/no_keep_going/in/Cargo.toml
  tests/testsuite/cargo_test/no_keep_going/in/src/lib.rs
  tests/testsuite/cargo_test/no_keep_going/mod.rs
  tests/testsuite/cargo_test/no_keep_going/stderr.log
  tests/testsuite/cargo_test/no_keep_going/stdout.log
  tests/testsuite/test.rs
Labels: Command-doc, Command-test, Command-run, Command-publish, Command-install, Command-check, Command-bench, Command-build, Command-package, Command-rustc, Command-rustdoc, Command-fix, S-waiting-on-bors, Command-vendor, A-cli

#12540 ci: test `resolver-tests` in a separate job
  .github/workflows/main.yml
Labels: S-waiting-on-bors, A-infrastructure

#12515 config: merge lists in precedence order
  src/cargo/util/config/mod.rs
  src/cargo/util/config/value.rs
  src/doc/src/reference/config.md
  tests/testsuite/cargo_config/mod.rs
  tests/testsuite/config.rs
  tests/testsuite/config_cli.rs
Labels: A-documenting-cargo-itself, A-configuration, relnotes, T-cargo, final-comment-period, disposition-merge, S-waiting-on-bors

#12542 fix(log): Use a more compact relative-time format
  crates/xtask-bump-check/src/main.rs
  src/bin/cargo/main.rs
Labels: S-waiting-on-bors, A-cli, A-infrastructure

#12548 use AND search when having multiple terms
  src/doc/book.toml
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12537 doc: fix two links to tracing docs
  src/doc/contrib/src/implementation/debugging.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12381 fix: Set MSRV for internal packages
  .github/renovate.json5
  Cargo.lock
  Cargo.toml
  benches/benchsuite/Cargo.toml
  benches/capture/Cargo.toml
  crates/cargo-test-macro/Cargo.toml
  crates/cargo-test-support/Cargo.toml
  crates/cargo-util/Cargo.toml
  crates/crates-io/Cargo.toml
  crates/mdman/Cargo.toml
  crates/resolver-tests/Cargo.toml
  crates/semver-check/Cargo.toml
  crates/xtask-build-man/Cargo.toml
  crates/xtask-bump-check/Cargo.toml
  crates/xtask-stale-label/Cargo.toml
Labels: A-interacts-with-crates.io, A-dependency-resolution, T-cargo, A-environment-variables, A-testing-cargo-itself, finished-final-comment-period, disposition-merge, S-waiting-on-bors, A-cfg-expr, A-semver, A-cli-help, to-announce, A-registry-authentication, A-infrastructure

#12547 refactor(install): Move value parsing to clap
  src/bin/cargo/commands/install.rs
  src/cargo/ops/cargo_install.rs
  tests/testsuite/install.rs
  tests/testsuite/install_upgrade.rs
Labels: Command-install, S-waiting-on-bors, A-cli

#12551 Create dedicated unstable flag for asymmetric-token
  src/cargo/core/features.rs
  src/cargo/util/auth/mod.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/credential_process.rs
  tests/testsuite/login.rs
  tests/testsuite/owner.rs
  tests/testsuite/publish.rs
  tests/testsuite/registry_auth.rs
  tests/testsuite/yank.rs
Labels: A-documenting-cargo-itself, S-waiting-on-bors, A-unstable, A-registry-authentication

#12556 fix(toml): Improve parse errors
  src/cargo/ops/lockfile.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/bad_config.rs
  tests/testsuite/build.rs
  tests/testsuite/cargo_add/invalid_manifest/stderr.log
  tests/testsuite/cargo_alias_config.rs
  tests/testsuite/cargo_features.rs
  tests/testsuite/config.rs
  tests/testsuite/git.rs
  tests/testsuite/inheritable_workspace_fields.rs
  tests/testsuite/metadata.rs
  tests/testsuite/workspaces.rs
Labels: A-manifest, S-waiting-on-bors, A-lockfile

#12421 Support dependencies from registries for artifact dependencies, take 2
  Cargo.lock
  Cargo.toml
  benches/benchsuite/benches/resolve.rs
  crates/cargo-test-support/src/registry.rs
  crates/crates-io/Cargo.toml
  crates/crates-io/lib.rs
  src/cargo/core/compiler/build_context/target_info.rs
  src/cargo/core/compiler/standard_lib.rs
  src/cargo/core/dependency.rs
  src/cargo/core/resolver/features.rs
  src/cargo/ops/cargo_compile/mod.rs
  src/cargo/ops/cargo_fetch.rs
  src/cargo/ops/cargo_output_metadata.rs
  src/cargo/ops/fix.rs
  src/cargo/ops/registry/publish.rs
  src/cargo/ops/resolve.rs
  src/cargo/ops/tree/mod.rs
  src/cargo/sources/registry/index.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/artifact_dep.rs
Labels: Command-publish, Command-metadata, A-interacts-with-crates.io, A-crate-dependencies, Command-fetch, A-dependency-resolution, A-registries, A-manifest, A-testing-cargo-itself, Command-fix, S-waiting-on-bors, A-cfg-expr, A-features2, Command-tree

#12487 Contrib: Add process for security responses.
  src/doc/contrib/src/SUMMARY.md
  src/doc/contrib/src/process/security.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12553 refactor: Pull out cargo-add MSRV code for reuse
  crates/resolver-tests/src/lib.rs
  src/cargo/core/compiler/compilation.rs
  src/cargo/core/manifest.rs
  src/cargo/core/package.rs
  src/cargo/core/resolver/version_prefs.rs
  src/cargo/core/summary.rs
  src/cargo/ops/cargo_add/mod.rs
  src/cargo/ops/cargo_compile/mod.rs
  src/cargo/ops/registry/publish.rs
  src/cargo/sources/registry/index.rs
  src/cargo/util/mod.rs
  src/cargo/util/semver_ext.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/rust_version.rs
Labels: Command-publish, A-interacts-with-crates.io, A-build-execution, A-dependency-resolution, A-registries, A-manifest, S-waiting-on-bors, A-semver, Command-add

#12559 string leek is stable
  src/cargo/util/interning.rs
Labels: S-waiting-on-bors

#12563 chore: add missing `windows-sys` features back
  Cargo.toml
Labels: S-waiting-on-bors, beta-nominated

#12565 [stable-1.72.0] add missing `windows-sys` features back
  Cargo.lock
  Cargo.toml
  crates/xtask-stale-label/src/main.rs
  src/cargo/ops/cargo_compile/mod.rs
  src/cargo/sources/git/known_hosts.rs
  src/cargo/sources/registry/http_remote.rs
  src/cargo/sources/registry/mod.rs
  src/cargo/util/auth/asymmetric.rs
  src/cargo/util/toml/embedded.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/bench.rs
  tests/testsuite/test.rs
Labels: A-git, A-registries, A-manifest, S-waiting-on-bors, A-sparse-registry, A-registry-authentication, A-infrastructure

#12564 [beta-1.73.0] add missing `windows-sys` features back
  Cargo.toml
  src/cargo/ops/cargo_compile/mod.rs
Labels: S-waiting-on-bors

#12569 Update serde
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#12570 Define {{command}} for use in src/doc/man/includes
  src/doc/man/cargo-add.md
  src/doc/man/cargo-bench.md
  src/doc/man/cargo-build.md
  src/doc/man/cargo-check.md
  src/doc/man/cargo-clean.md
  src/doc/man/cargo-doc.md
  src/doc/man/cargo-fetch.md
  src/doc/man/cargo-fix.md
  src/doc/man/cargo-install.md
  src/doc/man/cargo-package.md
  src/doc/man/cargo-publish.md
  src/doc/man/cargo-remove.md
  src/doc/man/cargo-run.md
  src/doc/man/cargo-rustc.md
  src/doc/man/cargo-rustdoc.md
  src/doc/man/cargo-test.md
  src/doc/man/cargo-tree.md
  src/doc/src/commands/cargo-add.md
  src/doc/src/commands/cargo-bench.md
  src/doc/src/commands/cargo-build.md
  src/doc/src/commands/cargo-check.md
  src/doc/src/commands/cargo-clean.md
  src/doc/src/commands/cargo-doc.md
  src/doc/src/commands/cargo-fetch.md
  src/doc/src/commands/cargo-fix.md
  src/doc/src/commands/cargo-install.md
  src/doc/src/commands/cargo-package.md
  src/doc/src/commands/cargo-publish.md
  src/doc/src/commands/cargo-remove.md
  src/doc/src/commands/cargo-run.md
  src/doc/src/commands/cargo-rustc.md
  src/doc/src/commands/cargo-rustdoc.md
  src/doc/src/commands/cargo-test.md
  src/doc/src/commands/cargo-tree.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12568 Stabilize `--keep-going`
  src/cargo/util/command_prelude.rs
  src/doc/man/cargo-bench.md
  src/doc/man/cargo-test.md
  src/doc/man/generated_txt/cargo-bench.txt
  src/doc/man/generated_txt/cargo-build.txt
  src/doc/man/generated_txt/cargo-check.txt
  src/doc/man/generated_txt/cargo-doc.txt
  src/doc/man/generated_txt/cargo-fix.txt
  src/doc/man/generated_txt/cargo-install.txt
  src/doc/man/generated_txt/cargo-package.txt
  src/doc/man/generated_txt/cargo-publish.txt
  src/doc/man/generated_txt/cargo-run.txt
  src/doc/man/generated_txt/cargo-rustc.txt
  src/doc/man/generated_txt/cargo-rustdoc.txt
  src/doc/man/generated_txt/cargo-test.txt
  src/doc/man/includes/options-keep-going.md
  src/doc/src/commands/cargo-bench.md
  src/doc/src/commands/cargo-build.md
  src/doc/src/commands/cargo-check.md
  src/doc/src/commands/cargo-doc.md
  src/doc/src/commands/cargo-fix.md
  src/doc/src/commands/cargo-install.md
  src/doc/src/commands/cargo-package.md
  src/doc/src/commands/cargo-publish.md
  src/doc/src/commands/cargo-run.md
  src/doc/src/commands/cargo-rustc.md
  src/doc/src/commands/cargo-rustdoc.md
  src/doc/src/commands/cargo-test.md
  src/doc/src/reference/unstable.md
  src/etc/man/cargo-bench.1
  src/etc/man/cargo-build.1
  src/etc/man/cargo-check.1
  src/etc/man/cargo-doc.1
  src/etc/man/cargo-fix.1
  src/etc/man/cargo-install.1
  src/etc/man/cargo-package.1
  src/etc/man/cargo-publish.1
  src/etc/man/cargo-run.1
  src/etc/man/cargo-rustc.1
  src/etc/man/cargo-rustdoc.1
  src/etc/man/cargo-test.1
  tests/testsuite/cargo_build/help/stdout.log
  tests/testsuite/cargo_check/help/stdout.log
  tests/testsuite/cargo_doc/help/stdout.log
  tests/testsuite/cargo_fix/help/stdout.log
  tests/testsuite/cargo_install/help/stdout.log
  tests/testsuite/cargo_package/help/stdout.log
  tests/testsuite/cargo_publish/help/stdout.log
  tests/testsuite/cargo_run/help/stdout.log
  tests/testsuite/cargo_rustc/help/stdout.log
  tests/testsuite/cargo_rustdoc/help/stdout.log
  tests/testsuite/check.rs
Labels: A-documenting-cargo-itself, S-waiting-on-bors, A-cli, A-cli-help

#12573 Improve resolver version mismatch warning
  src/cargo/core/workspace.rs
  tests/testsuite/features2.rs
Labels: A-workspaces, S-waiting-on-bors

#12574 Improve deserialization errors of untagged enums
  Cargo.lock
  Cargo.toml
  src/cargo/util/config/mod.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/bad_config.rs
  tests/testsuite/lints.rs
Labels: A-configuration, A-manifest, S-waiting-on-bors

#12270 Explain how `version` works for `git` dependencies
  src/doc/src/reference/specifying-dependencies.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12560 feat(resolver): **Very** preliminary MSRV resolver support
  benches/benchsuite/benches/resolve.rs
  crates/resolver-tests/src/lib.rs
  src/cargo/core/compiler/standard_lib.rs
  src/cargo/core/resolver/dep_cache.rs
  src/cargo/core/resolver/mod.rs
  src/cargo/core/workspace.rs
  src/cargo/ops/cargo_compile/mod.rs
  src/cargo/ops/cargo_generate_lockfile.rs
  src/cargo/ops/cargo_output_metadata.rs
  src/cargo/ops/cargo_package.rs
  src/cargo/ops/fix.rs
  src/cargo/ops/resolve.rs
  src/cargo/ops/tree/mod.rs
  src/cargo/util/semver_ext.rs
  tests/testsuite/cargo_add/rust_version_ignore/mod.rs
  tests/testsuite/cargo_add/rust_version_ignore/stderr.log
  tests/testsuite/rust_version.rs
Labels: Command-metadata, Command-generate-lockfile, Command-package, A-workspaces, A-dependency-resolution, A-testing-cargo-itself, Command-fix, S-waiting-on-bors, A-semver, Command-tree

#12583 Retry docs
  src/cargo/util/network/retry.rs
  src/cargo/util/network/sleep.rs
Labels: A-networking, S-waiting-on-bors

#12582 Set tracing target for networking messages.
  src/cargo/core/package.rs
  src/cargo/sources/registry/http_remote.rs
  src/cargo/util/network/http.rs
  src/cargo/util/network/mod.rs
  src/doc/contrib/src/implementation/debugging.md
  src/doc/src/reference/config.md
Labels: A-documenting-cargo-itself, A-dependency-resolution, A-registries, A-networking, S-waiting-on-bors, A-sparse-registry

#12545 fix(update): Make `-p` more convenient by being positional
  src/bin/cargo/commands/update.rs
  src/cargo/ops/cargo_compile/mod.rs
  src/cargo/ops/resolve.rs
  src/cargo/sources/registry/mod.rs
  src/doc/man/cargo-update.md
  src/doc/man/generated_txt/cargo-update.txt
  src/doc/src/commands/cargo-update.md
  src/doc/src/guide/cargo-toml-vs-cargo-lock.md
  src/doc/src/reference/overriding-dependencies.md
  src/doc/src/reference/resolver.md
  src/doc/src/reference/specifying-dependencies.md
  src/etc/_cargo
  src/etc/man/cargo-update.1
  tests/testsuite/cargo_update/help/stdout.log
  tests/testsuite/cargo_update/mod.rs
  tests/testsuite/cargo_update/toolchain_pkgname/in/Cargo.toml
  tests/testsuite/cargo_update/toolchain_pkgname/in/src/main.rs
  tests/testsuite/cargo_update/toolchain_pkgname/mod.rs
  tests/testsuite/cargo_update/toolchain_pkgname/stderr.log
  tests/testsuite/cargo_update/toolchain_pkgname/stdout.log
  tests/testsuite/future_incompat_report.rs
  tests/testsuite/git.rs
  tests/testsuite/offline.rs
  tests/testsuite/patch.rs
  tests/testsuite/registry.rs
  tests/testsuite/replace.rs
  tests/testsuite/rust_version.rs
  tests/testsuite/update.rs
Labels: A-documenting-cargo-itself, Command-update, A-registries, T-cargo, final-comment-period, disposition-merge, S-waiting-on-bors, A-completions, A-cli, A-cli-help

#12586 fix(update): Remove references to -p in help
  src/bin/cargo/commands/update.rs
  tests/testsuite/cargo_update/help/stdout.log
Labels: Command-update, S-waiting-on-bors, A-cli

#12587 Improve logout message for asymmetric tokens
  src/cargo/util/credential/paseto.rs
  tests/testsuite/logout.rs
Labels: S-waiting-on-bors

#12588 chore: remove unstable-options for logout
  tests/testsuite/logout.rs
Labels: S-waiting-on-bors

#12575 cargo install: suggest --git when package name is url
  src/bin/cargo/commands/install.rs
  tests/testsuite/install.rs
Labels: Command-install, S-waiting-on-bors, A-cli

#12584 fix(lints): Fail when overriding inherited lints
  src/cargo/util/toml/mod.rs
  tests/testsuite/lints.rs
Labels: A-manifest, S-waiting-on-bors

#12594 fix(help): Remove redundant information from new/init
  src/cargo/util/command_prelude.rs
  tests/testsuite/cargo_init/help/stdout.log
  tests/testsuite/cargo_new/help/stdout.log
Labels: S-waiting-on-bors, A-cli

#12592 fix(help): Explain --explain
  src/bin/cargo/cli.rs
  tests/testsuite/cargo/help/stdout.log
Labels: S-waiting-on-bors, A-cli

#12590 fix: add error for unsupported credential provider version
  Cargo.lock
  credential/cargo-credential/Cargo.toml
  credential/cargo-credential/src/lib.rs
  src/cargo/util/credential/process.rs
  tests/testsuite/credential_process.rs
Labels: S-waiting-on-bors, Z-credential-process, A-registry-authentication

#12601 docs(changelog): Clarify language for Cargo.lock policy
  CHANGELOG.md
Labels: S-waiting-on-bors

#12544 fix(update): Clarify meaning of --aggressive as --recursive
  src/bin/cargo/commands/update.rs
  src/cargo/ops/cargo_generate_lockfile.rs
  src/doc/man/cargo-update.md
  src/doc/man/generated_txt/cargo-update.txt
  src/doc/src/commands/cargo-update.md
  src/doc/src/reference/resolver.md
  src/etc/_cargo
  src/etc/cargo.bashcomp.sh
  src/etc/man/cargo-update.1
  tests/testsuite/cargo_update/help/stdout.log
  tests/testsuite/git.rs
  tests/testsuite/update.rs
Labels: A-documenting-cargo-itself, Command-generate-lockfile, Command-update, T-cargo, final-comment-period, disposition-merge, S-waiting-on-bors, A-completions, A-cli, A-cli-help

#12604 Fewer temporary needless strings
  credential/cargo-credential/src/error.rs
  src/cargo/core/compiler/custom_build.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/core/package.rs
  src/cargo/core/resolver/dep_cache.rs
  src/cargo/core/resolver/types.rs
  src/cargo/util/toml/mod.rs
Labels: A-build-execution, A-build-scripts, A-dependency-resolution, A-manifest, S-waiting-on-bors, A-registry-authentication

#12607 fix(cli): Help users know possible `--target` values
  src/bin/cargo/cli.rs
  src/bin/cargo/commands/clean.rs
  src/bin/cargo/commands/fetch.rs
  src/bin/cargo/commands/package.rs
  src/bin/cargo/commands/publish.rs
  src/bin/cargo/commands/tree.rs
  src/cargo/util/command_prelude.rs
  src/cargo/util/mod.rs
  tests/testsuite/cargo_bench/help/stdout.log
  tests/testsuite/cargo_build/help/stdout.log
  tests/testsuite/cargo_check/help/stdout.log
  tests/testsuite/cargo_clean/help/stdout.log
  tests/testsuite/cargo_doc/help/stdout.log
  tests/testsuite/cargo_fetch/help/stdout.log
  tests/testsuite/cargo_fix/help/stdout.log
  tests/testsuite/cargo_install/help/stdout.log
  tests/testsuite/cargo_package/help/stdout.log
  tests/testsuite/cargo_publish/help/stdout.log
  tests/testsuite/cargo_run/help/stdout.log
  tests/testsuite/cargo_rustc/help/stdout.log
  tests/testsuite/cargo_rustdoc/help/stdout.log
  tests/testsuite/cargo_test/help/stdout.log
  tests/testsuite/cargo_tree/help/stdout.log
  tests/testsuite/list_availables.rs
Labels: Command-clean, Command-publish, Command-fetch, Command-package, S-waiting-on-bors, A-cli, Command-tree

#12581 refactor: Use more serde_untagged
  src/cargo/util/interning.rs
  src/cargo/util/semver_ext.rs
  src/cargo/util/toml/mod.rs
Labels: A-manifest, S-waiting-on-bors, A-semver

#12591 Prepare for partial-version package specs
  src/bin/cargo/commands/install.rs
  src/cargo/util/semver_ext.rs
  src/cargo/util/to_semver.rs
  tests/testsuite/install_upgrade.rs
  tests/testsuite/pkgid.rs
  tests/testsuite/rust_version.rs
Labels: Command-install, S-waiting-on-bors, A-cli, A-semver
