Repository rust-lang/cargo, pull requests merged in 2023-05, with the labels that each got.

#12065 Fix warning with unused mut
  src/cargo/core/compiler/unit_dependencies.rs
Labels: S-waiting-on-bors

#12073 docs(commands): add missed preposition
  src/doc/man/cargo-install.md
  src/doc/man/generated_txt/cargo-install.txt
  src/doc/src/commands/cargo-install.md
  src/etc/man/cargo-install.1
Labels: A-documenting-cargo-itself, S-waiting-on-bors, A-cli-help

#10877 Document that adding `#[non_exhaustive]` on existing items is breaking.
  src/doc/src/reference/semver.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12067 Remove repeated definite articles
  crates/home/src/env.rs
  crates/mdman/doc/mdman.md
  crates/mdman/doc/out/mdman.1
  crates/mdman/doc/out/mdman.md
  crates/mdman/doc/out/mdman.txt
  src/doc/src/reference/semver.md
  src/doc/src/reference/unstable.md
Labels: A-documenting-cargo-itself, A-environment-variables, S-waiting-on-bors, A-cli-help

#12068 docs(registry): Further specify owner-remove response (#12056)
  src/doc/src/reference/registry-web-api.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12015 Build by PackageIdSpec, not name, to avoid ambiguity
  src/cargo/ops/cargo_install.rs
  tests/testsuite/install.rs
Labels: Command-install, S-waiting-on-bors

#11840 support for shallow clones and fetches with `gitoxide`
  Cargo.lock
  Cargo.toml
  src/cargo/sources/git/mod.rs
  src/cargo/sources/git/oxide.rs
  src/cargo/sources/git/source.rs
  src/cargo/sources/git/utils.rs
  src/cargo/sources/registry/mod.rs
  src/cargo/sources/registry/remote.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/git.rs
  tests/testsuite/git_shallow.rs
  tests/testsuite/main.rs
  tests/testsuite/offline.rs
  tests/testsuite/patch.rs
Labels: A-documenting-cargo-itself, A-git, A-registries, T-cargo, final-comment-period, disposition-merge, S-waiting-on-bors

#11862 doc: clarify implications of `cargo-yank`
  src/doc/man/cargo-yank.md
  src/doc/man/generated_txt/cargo-yank.txt
  src/doc/src/commands/cargo-yank.md
  src/etc/man/cargo-yank.1
Labels: A-documenting-cargo-itself, S-waiting-on-bors, A-cli-help

#11978 feat(cargo-metadata): add `workspace_default_members`
  src/cargo/ops/cargo_output_metadata.rs
  src/doc/man/cargo-metadata.md
  src/doc/man/generated_txt/cargo-metadata.txt
  src/doc/src/commands/cargo-metadata.md
  src/etc/man/cargo-metadata.1
  tests/testsuite/alt_registry.rs
  tests/testsuite/features_namespaced.rs
  tests/testsuite/git.rs
  tests/testsuite/metadata.rs
  tests/testsuite/update.rs
Labels: A-documenting-cargo-itself, Command-metadata, A-workspaces, S-waiting-on-bors, A-cli-help

#12055 fix: doc-test failures
  crates/cargo-test-support/src/install.rs
  crates/cargo-test-support/src/lib.rs
  crates/cargo-test-support/src/registry.rs
  crates/crates-io/lib.rs
Labels: A-interacts-with-crates.io, A-testing-cargo-itself, S-waiting-on-bors

#11917 Optimize usage under rustup.
  src/cargo/util/config/mod.rs
  tests/testsuite/main.rs
  tests/testsuite/rustup.rs
Labels: A-configuration, S-waiting-on-bors, A-rustup

#12088 fix: hack around `libsysroot` instead of `libtest`
  src/cargo/core/compiler/standard_lib.rs
  tests/testsuite/mock-std/library/sysroot/Cargo.toml
  tests/testsuite/mock-std/library/sysroot/src/lib.rs
  tests/testsuite/mock-std/library/test/Cargo.toml
Labels: S-waiting-on-bors

#12085 xtask-unpublished: output a markdown table
  benches/capture/Cargo.toml
  crates/cargo-test-macro/Cargo.toml
  crates/cargo-test-support/Cargo.toml
  crates/xtask-unpublished/src/xtask.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors, A-infrastructure

#12083 do not try an exponential number of package names
  src/cargo/sources/registry/index.rs
  src/cargo/sources/registry/mod.rs
  tests/testsuite/registry.rs
Labels: A-registries, S-waiting-on-bors

#12096 Update git2
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#12097 Fix self_signed_should_fail for macOS.
  tests/testsuite/https.rs
Labels: S-waiting-on-bors

#12095 Fix redacting tokens in http debug.
  src/cargo/ops/registry.rs
  tests/testsuite/registry_auth.rs
Labels: A-interacts-with-crates.io, S-waiting-on-bors

#12101 Disallow RUSTUP_HOME in the [env] table.
  src/cargo/util/config/mod.rs
  tests/testsuite/cargo_env_config.rs
Labels: A-configuration, S-waiting-on-bors

#12107 Disallow RUSTUP_TOOLCHAIN in the [env] table.
  src/cargo/util/config/mod.rs
  tests/testsuite/cargo_env_config.rs
Labels: A-configuration, S-waiting-on-bors

#12086 changelog: move registry query fixes to the right place
  CHANGELOG.md
Labels: S-waiting-on-bors

#12110 Add more documentation for artifact-dependencies.
  src/doc/src/reference/unstable.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12116 Semver: Note that it is not a breaking change to make an unsafe function safe
  src/doc/src/reference/semver.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12117 Update the semver-check script to be able to run in any directory.
  crates/semver-check/src/main.rs
  src/doc/README.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors, A-semver

#12098 Update libc to 0.2.144
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#12119 changelog: add entries of some behavior changes
  CHANGELOG.md
Labels: S-waiting-on-bors

#12130 Fix dep/feat syntax with hidden implicit optional dependencies
  src/cargo/core/resolver/dep_cache.rs
  src/cargo/core/resolver/features.rs
  tests/testsuite/features_namespaced.rs
Labels: A-dependency-resolution, S-waiting-on-bors, A-features2

#12136 Remove useless drop of copy type
  crates/cargo-test-support/src/lib.rs
  src/cargo/core/compiler/job_queue/mod.rs
  src/cargo/core/features.rs
Labels: A-build-execution, A-testing-cargo-itself, S-waiting-on-bors, A-unstable

#12010 Add Cargo team charter.
  src/doc/contrib/src/SUMMARY.md
  src/doc/contrib/src/process/index.md
  src/doc/contrib/src/team.md
Labels: A-documenting-cargo-itself, T-cargo, proposed-final-comment-period, disposition-merge, S-waiting-on-bors

#12133 doc: intra-doc links and doc comments for build script
  src/cargo/core/compiler/custom_build.rs
Labels: A-build-scripts, S-waiting-on-bors

#12143 Fixes: Incorrect document link
  src/doc/src/faq.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12122 docs(ref): Clarify MSRV is generally minor
  src/doc/src/reference/semver.md
Labels: A-documenting-cargo-itself, T-cargo, final-comment-period, disposition-merge, S-waiting-on-bors

#12146 docs: Clarify that crates.io doesn't link to docs.rs right away.
  src/doc/src/reference/manifest.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12153 docs(source): doc comments for `Source` and friends
  src/cargo/core/source/mod.rs
  src/cargo/sources/directory.rs
  src/cargo/sources/mod.rs
  src/cargo/sources/replaced.rs
Labels: A-overrides, A-source-replacement, S-waiting-on-bors, A-directory-source

#12159 docs(source): doc comments for Source and its impls
  src/cargo/core/source/mod.rs
  src/cargo/core/source/source_id.rs
  src/cargo/sources/config.rs
  src/cargo/sources/path.rs
Labels: S-waiting-on-bors

#12157 Tweak build help to clarify role of --bin
  src/bin/cargo/cli.rs
  src/cargo/util/command_prelude.rs
Labels: S-waiting-on-bors, A-cli

#12165 fix: pass `-C debuginfo` after weakening if explicitly set
  src/cargo/core/profiles.rs
  tests/testsuite/build.rs
  tests/testsuite/profile_targets.rs
Labels: A-profiles, S-waiting-on-bors

#12126 ci: check if any version bump needed for member crates
  .github/workflows/main.yml
  ci/validate-version-bump.sh
  crates/xtask-unpublished/src/xtask.rs
Labels: S-waiting-on-bors, A-infrastructure

#12168 fix(lints): Switch to -Zlints so stable projects can experiment
  src/cargo/core/features.rs
  src/cargo/util/toml/mod.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/lints.rs
Labels: A-documenting-cargo-itself, A-manifest, S-waiting-on-bors, A-unstable

#12078 Consider rust-version when selecting packages for cargo add
  src/bin/cargo/commands/add.rs
  src/cargo/ops/cargo_add/mod.rs
  src/doc/man/cargo-add.md
  src/doc/man/generated_txt/cargo-add.txt
  src/doc/src/commands/cargo-add.md
  src/etc/man/cargo-add.1
  tests/testsuite/cargo_add/mod.rs
  tests/testsuite/cargo_add/rust_version_ignore/in/Cargo.toml
  tests/testsuite/cargo_add/rust_version_ignore/in/src/lib.rs
  tests/testsuite/cargo_add/rust_version_ignore/mod.rs
  tests/testsuite/cargo_add/rust_version_ignore/out/Cargo.toml
  tests/testsuite/cargo_add/rust_version_ignore/out/src/lib.rs
  tests/testsuite/cargo_add/rust_version_ignore/stderr.log
  tests/testsuite/cargo_add/rust_version_ignore/stdout.log
  tests/testsuite/cargo_add/rust_version_incompatible/in/Cargo.toml
  tests/testsuite/cargo_add/rust_version_incompatible/in/src/lib.rs
  tests/testsuite/cargo_add/rust_version_incompatible/mod.rs
  tests/testsuite/cargo_add/rust_version_incompatible/out/Cargo.toml
  tests/testsuite/cargo_add/rust_version_incompatible/out/src/lib.rs
  tests/testsuite/cargo_add/rust_version_incompatible/stderr.log
  tests/testsuite/cargo_add/rust_version_incompatible/stdout.log
  tests/testsuite/cargo_add/rust_version_latest/in/Cargo.toml
  tests/testsuite/cargo_add/rust_version_latest/in/src/lib.rs
  tests/testsuite/cargo_add/rust_version_latest/mod.rs
  tests/testsuite/cargo_add/rust_version_latest/out/Cargo.toml
  tests/testsuite/cargo_add/rust_version_latest/out/src/lib.rs
  tests/testsuite/cargo_add/rust_version_latest/stderr.log
  tests/testsuite/cargo_add/rust_version_latest/stdout.log
  tests/testsuite/cargo_add/rust_version_older/in/Cargo.toml
  tests/testsuite/cargo_add/rust_version_older/in/src/lib.rs
  tests/testsuite/cargo_add/rust_version_older/mod.rs
  tests/testsuite/cargo_add/rust_version_older/out/Cargo.toml
  tests/testsuite/cargo_add/rust_version_older/out/src/lib.rs
  tests/testsuite/cargo_add/rust_version_older/stderr.log
  tests/testsuite/cargo_add/rust_version_older/stdout.log
Labels: A-documenting-cargo-itself, S-waiting-on-bors, A-cli, A-cli-help, Command-add

#12022 Test that the new `debuginfo` options match between cargo and rustc
  tests/testsuite/profiles.rs
Labels: S-waiting-on-bors

#12174 Automatically inherit workspace lints when running cargo new/init
  src/cargo/ops/cargo_new.rs
  tests/testsuite/cargo_new/inherit_workspace_lints/in/Cargo.toml
  tests/testsuite/cargo_new/inherit_workspace_lints/in/src/lib.rs
  tests/testsuite/cargo_new/inherit_workspace_lints/mod.rs
  tests/testsuite/cargo_new/inherit_workspace_lints/out/Cargo.toml
  tests/testsuite/cargo_new/inherit_workspace_lints/out/crates/foo/Cargo.toml
  tests/testsuite/cargo_new/inherit_workspace_lints/out/crates/foo/src/main.rs
  tests/testsuite/cargo_new/inherit_workspace_lints/out/src/lib.rs
  tests/testsuite/cargo_new/inherit_workspace_lints/stderr.log
  tests/testsuite/cargo_new/inherit_workspace_lints/stdout.log
  tests/testsuite/cargo_new/mod.rs
Labels: Command-new, S-waiting-on-bors

#12176 deps: remove unused features from windows-sys
  Cargo.toml
Labels: S-waiting-on-bors

#11968 fix: AIX searches dynamic libraries in `LIBPATH`.
  crates/cargo-util/src/paths.rs
  src/doc/src/reference/environment-variables.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12180 chore(ci): remove temporary fix for rustup 1.24.1
  .github/workflows/main.yml
Labels: S-waiting-on-bors, A-infrastructure

#12184 refactor(tests): Reduce cargo-remove setup load
  tests/testsuite/cargo_remove/avoid_empty_tables/mod.rs
  tests/testsuite/cargo_remove/build/mod.rs
  tests/testsuite/cargo_remove/dev/mod.rs
  tests/testsuite/cargo_remove/dry_run/mod.rs
  tests/testsuite/cargo_remove/gc_patch/mod.rs
  tests/testsuite/cargo_remove/gc_profile/mod.rs
  tests/testsuite/cargo_remove/gc_replace/mod.rs
  tests/testsuite/cargo_remove/invalid_arg/mod.rs
  tests/testsuite/cargo_remove/invalid_dep/mod.rs
  tests/testsuite/cargo_remove/invalid_package/mod.rs
  tests/testsuite/cargo_remove/invalid_package_multiple/mod.rs
  tests/testsuite/cargo_remove/invalid_section/mod.rs
  tests/testsuite/cargo_remove/invalid_section_dep/mod.rs
  tests/testsuite/cargo_remove/invalid_target/mod.rs
  tests/testsuite/cargo_remove/invalid_target_dep/mod.rs
  tests/testsuite/cargo_remove/mod.rs
  tests/testsuite/cargo_remove/multiple_deps/mod.rs
  tests/testsuite/cargo_remove/multiple_dev/mod.rs
  tests/testsuite/cargo_remove/no_arg/mod.rs
  tests/testsuite/cargo_remove/offline/mod.rs
  tests/testsuite/cargo_remove/optional_dep_feature/mod.rs
  tests/testsuite/cargo_remove/optional_feature/mod.rs
  tests/testsuite/cargo_remove/package/mod.rs
  tests/testsuite/cargo_remove/remove_basic/mod.rs
  tests/testsuite/cargo_remove/target/mod.rs
  tests/testsuite/cargo_remove/target_build/mod.rs
  tests/testsuite/cargo_remove/target_dev/mod.rs
  tests/testsuite/cargo_remove/update_lock_file/mod.rs
  tests/testsuite/cargo_remove/workspace/mod.rs
  tests/testsuite/cargo_remove/workspace_non_virtual/mod.rs
  tests/testsuite/cargo_remove/workspace_preserved/mod.rs
Labels: S-waiting-on-bors

#10910 Warn when an edition 2021 crate is in a virtual workspace with default resolver
  src/cargo/core/workspace.rs
  tests/testsuite/cargo_new/inherit_workspace_lints/in/Cargo.toml
  tests/testsuite/cargo_new/inherit_workspace_lints/out/Cargo.toml
  tests/testsuite/cargo_new/inherit_workspace_package_table.in/Cargo.toml
  tests/testsuite/cargo_new/inherit_workspace_package_table/out/Cargo.toml
  tests/testsuite/cargo_new/inherit_workspace_package_table_with_edition/out/Cargo.toml
  tests/testsuite/cargo_new/inherit_workspace_package_table_with_registry/out/Cargo.toml
  tests/testsuite/features2.rs
Labels: A-workspaces, S-waiting-on-bors

#12185 Add a description of `Cargo.lock` conflicts in the Cargo FAQ
  src/doc/src/faq.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12188 test(add): Remove expensive test
  tests/testsuite/cargo_add/invalid_git_external/in
  tests/testsuite/cargo_add/invalid_git_external/mod.rs
  tests/testsuite/cargo_add/invalid_git_external/out/Cargo.toml
  tests/testsuite/cargo_add/invalid_git_external/stderr.log
  tests/testsuite/cargo_add/invalid_git_external/stdout.log
  tests/testsuite/cargo_add/mod.rs
Labels: S-waiting-on-bors

#12191 fix(add): Reduce the chance we re-format the user's `[features]` table
  src/cargo/util/toml_mut/manifest.rs
  tests/testsuite/cargo_add/mod.rs
  tests/testsuite/cargo_add/preserve_features_table/in/Cargo.toml
  tests/testsuite/cargo_add/preserve_features_table/in/src/lib.rs
  tests/testsuite/cargo_add/preserve_features_table/mod.rs
  tests/testsuite/cargo_add/preserve_features_table/out/Cargo.toml
  tests/testsuite/cargo_add/preserve_features_table/stderr.log
  tests/testsuite/cargo_add/preserve_features_table/stdout.log
Labels: A-manifest, S-waiting-on-bors

#12194 test: set retry sleep to 1ms for all tests
  crates/cargo-test-support/src/lib.rs
  src/cargo/util/network/retry.rs
Labels: A-testing-cargo-itself, A-networking, S-waiting-on-bors

#12192 docs: add doc comments for git source and friends
  src/cargo/sources/git/known_hosts.rs
  src/cargo/sources/git/mod.rs
  src/cargo/sources/git/oxide.rs
  src/cargo/sources/git/source.rs
  src/cargo/sources/git/utils.rs
  src/cargo/sources/path.rs
Labels: A-git, S-waiting-on-bors

#12199 Re-enable code_generation test on Windows
  tests/testsuite/build_script.rs
Labels: S-waiting-on-bors

#12203 refactor: de-depulicate `make_dep_prefix` implementation
  src/cargo/sources/registry/mod.rs
Labels: A-registries, S-waiting-on-bors

#12181 chore: detect the channel a PR wants to merge into
  .github/workflows/main.yml
  ci/matrix.json
  ci/which-channel.sh
Labels: S-waiting-on-bors, A-infrastructure

#12205 Don't distinguish `Debuginfo::None` and `Debuginfo::Explicit(None)`
  src/cargo/core/compiler/mod.rs
  src/cargo/core/profiles.rs
  tests/testsuite/build.rs
  tests/testsuite/profile_config.rs
  tests/testsuite/profile_targets.rs
  tests/testsuite/profiles.rs
Labels: A-build-execution, A-profiles, S-waiting-on-bors

#12204 Revert "chore: detect the channel a PR wants to merge into"
  .github/workflows/main.yml
  ci/matrix.json
  ci/which-channel.sh
Labels: S-waiting-on-bors, A-infrastructure

#11442 fix: use `remove_dir_all` in `cargo clean` to resolve race condition
  crates/cargo-util/src/paths.rs
  src/cargo/ops/cargo_clean.rs
Labels: Command-clean, S-waiting-on-bors
