Repository rust-lang/cargo, pull requests merged in 2023-10, with the labels that each got.

#12754 Add more missing `strip` info to docs.
  src/doc/src/reference/config.md
  src/doc/src/reference/profiles.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12763 Disable custom_target::custom_bin_target on windows-gnu
  tests/testsuite/custom_target.rs
Labels: S-waiting-on-bors

#12767 Prep for automating MSRV management
  .github/workflows/main.yml
  Cargo.lock
  crates/home/Cargo.toml
  crates/home/src/lib.rs
Labels: A-environment-variables, S-waiting-on-bors, A-infrastructure, A-home

#12755 Add unsupported short suggestion for --out-dir flag
  src/bin/cargo/commands/build.rs
  src/cargo/util/command_prelude.rs
  tests/testsuite/out_dir.rs
Labels: Command-build, S-waiting-on-bors, A-cli

#12770 Bump to 0.76.0; update changelog
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#12765 chore: Specify all of toml_edit's features
  Cargo.toml
Labels: S-waiting-on-bors

#12768 refactor(toml): Make manifest file layout more consitent
  src/cargo/util/toml/mod.rs
Labels: A-manifest, S-waiting-on-bors

#12771 feat: Add `Edition2024`
  src/cargo/core/features.rs
  src/cargo/util/toml/mod.rs
  src/doc/man/generated_txt/cargo-init.txt
  src/doc/man/generated_txt/cargo-new.txt
  src/doc/man/includes/options-new.md
  src/doc/src/commands/cargo-init.md
  src/doc/src/commands/cargo-new.md
  src/doc/src/reference/unstable.md
  src/etc/man/cargo-init.1
  src/etc/man/cargo-new.1
  tests/testsuite/cargo_init/help/stdout.log
  tests/testsuite/cargo_new/help/stdout.log
  tests/testsuite/package.rs
Labels: A-documenting-cargo-itself, A-manifest, S-waiting-on-bors, A-cli-help, A-unstable

#12773 Fix typo
  src/doc/src/reference/publishing.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12774 docs(changelog): Highlight 1.73's minor incompat with build.rs
  CHANGELOG.md
Labels: S-waiting-on-bors

#12777 Add test for unsupported short config flag
  src/bin/cargo/cli.rs
  src/cargo/util/command_prelude.rs
  tests/testsuite/build.rs
Labels: S-waiting-on-bors, A-cli

#12781 cargo/targets: fix error-message typo
  src/cargo/util/toml/targets.rs
  tests/testsuite/build.rs
Labels: S-waiting-on-bors

#12782 crates-io: Add doc comment for `NewCrate` struct
  Cargo.lock
  crates/crates-io/Cargo.toml
  crates/crates-io/lib.rs
Labels: A-interacts-with-crates.io, S-waiting-on-bors

#12791 [stable 1.73] Update serde
  Cargo.lock
Labels: S-waiting-on-bors

#12792 [stable 1.73] backport publish script fixes
  publish.py
Labels: S-waiting-on-bors, A-infrastructure

#12654 Set and verify all MSRVs in CI
  .github/renovate.json5
  .github/workflows/main.yml
  Cargo.lock
  Cargo.toml
  crates/cargo-platform/Cargo.toml
  crates/home/Cargo.toml
  credential/cargo-credential-1password/Cargo.toml
  credential/cargo-credential-libsecret/Cargo.toml
  credential/cargo-credential-macos-keychain/Cargo.toml
  credential/cargo-credential-wincred/Cargo.toml
  credential/cargo-credential/Cargo.toml
Labels: A-environment-variables, S-waiting-on-bors, A-cfg-expr, A-credential-provider, A-registry-authentication, A-infrastructure, A-home

#12795 ci: bump cargo-semver-checks to 0.24.0
  .github/workflows/main.yml
  crates/xtask-bump-check/src/xtask.rs
Labels: S-waiting-on-bors, A-infrastructure

#12706 Add new package cache lock modes
  crates/cargo-test-support/src/compare.rs
  crates/cargo-test-support/src/lib.rs
  crates/xtask-bump-check/src/xtask.rs
  src/cargo/core/compiler/context/mod.rs
  src/cargo/core/compiler/future_incompat.rs
  src/cargo/core/compiler/layout.rs
  src/cargo/core/package.rs
  src/cargo/ops/cargo_add/mod.rs
  src/cargo/ops/cargo_generate_lockfile.rs
  src/cargo/ops/cargo_package.rs
  src/cargo/ops/common_for_install_and_uninstall.rs
  src/cargo/ops/lockfile.rs
  src/cargo/ops/registry/mod.rs
  src/cargo/ops/registry/publish.rs
  src/cargo/ops/resolve.rs
  src/cargo/sources/git/source.rs
  src/cargo/sources/registry/download.rs
  src/cargo/sources/registry/http_remote.rs
  src/cargo/sources/registry/index.rs
  src/cargo/sources/registry/mod.rs
  src/cargo/sources/registry/remote.rs
  src/cargo/util/cache_lock.rs
  src/cargo/util/config/mod.rs
  src/cargo/util/flock.rs
  src/cargo/util/mod.rs
  tests/testsuite/cache_lock.rs
  tests/testsuite/config.rs
  tests/testsuite/main.rs
  tests/testsuite/search.rs
Labels: A-git, A-configuration, Command-publish, A-interacts-with-crates.io, Command-generate-lockfile, Command-package, A-registries, A-testing-cargo-itself, S-waiting-on-bors, A-lockfile, A-filesystem, A-layout, A-future-incompat, Command-add, A-sparse-registry, A-infrastructure

#12785 refactor(core): Clean up deserialization of PackageId
  src/cargo/core/package_id.rs
Labels: S-waiting-on-bors

#12788 Add unsupported lowercase `-z` flag suggestion for `-Z` flag
  src/bin/cargo/cli.rs
  src/cargo/util/command_prelude.rs
  tests/testsuite/build.rs
Labels: S-waiting-on-bors, A-cli

#12800 rustdoc: remove the word "Version" from test cases
  tests/testsuite/doc.rs
  tests/testsuite/rustdocflags.rs
Labels: S-waiting-on-bors

#12798 fix(install): Suggest an alternative version on MSRV failure
  src/cargo/ops/cargo_install.rs
  src/cargo/ops/cargo_uninstall.rs
  src/cargo/ops/common_for_install_and_uninstall.rs
  tests/testsuite/install.rs
Labels: Command-install, Command-uninstall, S-waiting-on-bors, A-cli

#12803 chore: Sort dependency tables
  Cargo.lock
  Cargo.toml
  crates/cargo-util/Cargo.toml
Labels: S-waiting-on-bors

#12804 test(build): generalize test assertion for non-rustup env
  tests/testsuite/build.rs
Labels: S-waiting-on-bors

#12805 Add unsupported short flag suggestion for `--target` and `--exclude` flags
  src/cargo/util/command_prelude.rs
  tests/testsuite/build.rs
Labels: S-waiting-on-bors, A-cli

#12796 Do not call it "Downgrading" when difference is only build metadata
  Cargo.lock
  Cargo.toml
  src/cargo/core/package_id.rs
  src/cargo/ops/cargo_generate_lockfile.rs
  src/cargo/sources/registry/index.rs
  src/cargo/util/semver_ext.rs
  tests/testsuite/update.rs
Labels: Command-generate-lockfile, A-registries, A-testing-cargo-itself, S-waiting-on-bors, A-semver

#12799 feat: add package name and version to warning messages
  src/cargo/core/compiler/job_queue/mod.rs
  tests/testsuite/build_script.rs
  tests/testsuite/build_script_env.rs
  tests/testsuite/build_script_extra_link_arg.rs
  tests/testsuite/features2.rs
  tests/testsuite/warn_on_failure.rs
Labels: A-build-execution, S-waiting-on-bors

#12809 [beta 1.74] Update curl-sys to pull in curl 8.4.0
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#12808 Update curl-sys to pull in curl 8.4.0
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#12813 contrib doc: remove extraneous word
  src/doc/contrib/src/process/working-on-cargo.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12814 contrib docs: update rfc and roadmap links
  src/doc/contrib/src/process/index.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12811 Better suggestion for unsupported `--path` flag
  src/bin/cargo/commands/add.rs
  src/cargo/util/command_prelude.rs
  tests/testsuite/build.rs
Labels: S-waiting-on-bors, A-cli, Command-add

#12812 contrib docs: add some conveniences
  src/doc/contrib/book.toml
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12815 Update rustix to 0.38.18
  Cargo.lock
Labels: S-waiting-on-bors

#12820 add detailed message when target folder path is invalid
  crates/cargo-util/src/paths.rs
Labels: S-waiting-on-bors

#12822 Add test for `-V` short argument
  tests/testsuite/version.rs
Labels: S-waiting-on-bors

#12827 update SPDX License info
  src/doc/src/reference/manifest.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12830 changelog: add compat notice for `cargo login -- <arg>`
  CHANGELOG.md
Labels: S-waiting-on-bors

#12832 doc(cargo-login): mention args after `--` in manpage
  src/doc/man/cargo-login.md
  src/doc/man/generated_txt/cargo-login.txt
  src/doc/src/commands/cargo-login.md
  src/etc/man/cargo-login.1
Labels: A-documenting-cargo-itself, S-waiting-on-bors, A-cli-help

#12823 Clarify flag behavior in `cargo remove --help`
  src/bin/cargo/commands/remove.rs
  tests/testsuite/cargo_remove/help/stdout.log
Labels: S-waiting-on-bors, A-cli, Command-remove

#12834 ci/contrib: do not fail on missing gh-pages
  .github/workflows/contrib.yml
Labels: S-waiting-on-bors, A-infrastructure

#12835 ci/contrib: use separate concurrency group
  .github/workflows/contrib.yml
Labels: S-waiting-on-bors, A-infrastructure

#12836 docs(contrib): Policy on manifest editing
  src/doc/contrib/src/SUMMARY.md
  src/doc/contrib/src/implementation/formatting.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12840 fix(cli): Suggest cargo-search on bad commands
  src/bin/cargo/main.rs
  tests/testsuite/cargo_command.rs
  tests/testsuite/script.rs
Labels: S-waiting-on-bors, A-cli

#12829 Print environment variables for build script executions with `-vv`
  src/cargo/core/compiler/custom_build.rs
  tests/testsuite/build_script_env.rs
Labels: A-build-scripts, S-waiting-on-bors

#12845 Adjust `-Zcheck-cfg` for new rustc syntax and behavior
  src/cargo/core/compiler/custom_build.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/core/features.rs
  src/cargo/util/config/target.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/check_cfg.rs
Labels: A-documenting-cargo-itself, A-build-execution, A-build-scripts, S-waiting-on-bors, A-unstable

#12841 fix(help):Clarify install's positional
  src/bin/cargo/commands/bench.rs
  src/bin/cargo/commands/init.rs
  src/bin/cargo/commands/install.rs
  src/bin/cargo/commands/login.rs
  src/bin/cargo/commands/new.rs
  src/bin/cargo/commands/owner.rs
  src/bin/cargo/commands/pkgid.rs
  src/bin/cargo/commands/run.rs
  src/bin/cargo/commands/rustc.rs
  src/bin/cargo/commands/rustdoc.rs
  src/bin/cargo/commands/search.rs
  src/bin/cargo/commands/test.rs
  src/bin/cargo/commands/uninstall.rs
  src/bin/cargo/commands/yank.rs
  tests/testsuite/cargo_bench/help/stdout.log
  tests/testsuite/cargo_bench/no_keep_going/stderr.log
  tests/testsuite/cargo_init/help/stdout.log
  tests/testsuite/cargo_init/unknown_flags/stderr.log
  tests/testsuite/cargo_install/help/stdout.log
  tests/testsuite/cargo_login/help/stdout.log
  tests/testsuite/cargo_new/help/stdout.log
  tests/testsuite/cargo_owner/help/stdout.log
  tests/testsuite/cargo_pkgid/help/stdout.log
  tests/testsuite/cargo_run/help/stdout.log
  tests/testsuite/cargo_rustc/help/stdout.log
  tests/testsuite/cargo_rustdoc/help/stdout.log
  tests/testsuite/cargo_search/help/stdout.log
  tests/testsuite/cargo_test/help/stdout.log
  tests/testsuite/cargo_test/no_keep_going/stderr.log
  tests/testsuite/cargo_uninstall/help/stdout.log
  tests/testsuite/cargo_yank/help/stdout.log
  tests/testsuite/install.rs
  tests/testsuite/new.rs
  tests/testsuite/run.rs
Labels: Command-test, Command-run, Command-new, Command-install, Command-bench, Command-init, Command-login, Command-owner, Command-pkgid, Command-rustc, Command-rustdoc, Command-search, Command-uninstall, Command-yank, S-waiting-on-bors, A-cli

#12842 docs: remove review capacity notice
  CONTRIBUTING.md
  src/doc/contrib/src/process/index.md
  src/doc/contrib/src/process/working-on-cargo.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12846 docs(contrib): generate redirection HTML pages in CI
  .github/workflows/contrib.yml
  ci/generate.py
Labels: S-waiting-on-bors, A-infrastructure

#12847 [beta-1.74.0] Partial-version spec support
  src/cargo/core/package_id_spec.rs
  src/cargo/core/resolver/dep_cache.rs
  src/cargo/util/semver_ext.rs
  tests/testsuite/doc.rs
  tests/testsuite/replace.rs
  tests/testsuite/rustdocflags.rs
Labels: A-dependency-resolution, S-waiting-on-bors, A-semver

#12850 docs(cargo-bench): `--bench` is passed in unconditionally to bench harnesses
  src/doc/man/cargo-bench.md
  src/doc/man/generated_txt/cargo-bench.txt
  src/doc/src/commands/cargo-bench.md
  src/etc/man/cargo-bench.1
Labels: A-documenting-cargo-itself, S-waiting-on-bors, A-cli-help

#12853 ci: big ⚠️ to ensure the CNAME file is always there
  .github/workflows/contrib.yml
  ci/generate.py
Labels: S-waiting-on-bors, A-infrastructure

#12838 fix(add): Preserve more comments
  src/cargo/util/toml_mut/dependency.rs
  src/cargo/util/toml_mut/manifest.rs
  tests/testsuite/cargo_add/mod.rs
  tests/testsuite/cargo_add/preserve_dep_std_table/in/Cargo.toml
  tests/testsuite/cargo_add/preserve_dep_std_table/in/src/lib.rs
  tests/testsuite/cargo_add/preserve_dep_std_table/mod.rs
  tests/testsuite/cargo_add/preserve_dep_std_table/out/Cargo.toml
  tests/testsuite/cargo_add/preserve_dep_std_table/stderr.log
  tests/testsuite/cargo_add/preserve_dep_std_table/stdout.log
Labels: A-manifest, S-waiting-on-bors

#12856 chore(triagebot): auto label when PR review state changes
  triagebot.toml
Labels: S-waiting-on-bors, A-infrastructure

#12844 docs: fix typo
  src/doc/man/cargo-rustc.md
  src/doc/man/generated_txt/cargo-bench.txt
  src/doc/man/generated_txt/cargo-build.txt
  src/doc/man/generated_txt/cargo-check.txt
  src/doc/man/generated_txt/cargo-doc.txt
  src/doc/man/generated_txt/cargo-fix.txt
  src/doc/man/generated_txt/cargo-install.txt
  src/doc/man/generated_txt/cargo-run.txt
  src/doc/man/generated_txt/cargo-rustc.txt
  src/doc/man/generated_txt/cargo-rustdoc.txt
  src/doc/man/generated_txt/cargo-test.txt
  src/doc/man/includes/options-profile-legacy-check.md
  src/doc/man/includes/options-profile.md
  src/doc/src/commands/cargo-bench.md
  src/doc/src/commands/cargo-build.md
  src/doc/src/commands/cargo-check.md
  src/doc/src/commands/cargo-doc.md
  src/doc/src/commands/cargo-fix.md
  src/doc/src/commands/cargo-install.md
  src/doc/src/commands/cargo-run.md
  src/doc/src/commands/cargo-rustc.md
  src/doc/src/commands/cargo-rustdoc.md
  src/doc/src/commands/cargo-test.md
  src/etc/man/cargo-bench.1
  src/etc/man/cargo-build.1
  src/etc/man/cargo-check.1
  src/etc/man/cargo-doc.1
  src/etc/man/cargo-fix.1
  src/etc/man/cargo-install.1
  src/etc/man/cargo-run.1
  src/etc/man/cargo-rustc.1
  src/etc/man/cargo-rustdoc.1
  src/etc/man/cargo-test.1
Labels: A-documenting-cargo-itself, S-waiting-on-bors, A-cli-help

#12837 fix(remove): Preserve feature comments
  src/cargo/util/toml_mut/manifest.rs
  tests/testsuite/cargo_remove/mod.rs
  tests/testsuite/cargo_remove/multiple_dev/out/Cargo.toml
  tests/testsuite/cargo_remove/optional_dep_feature/out/Cargo.toml
  tests/testsuite/cargo_remove/optional_dep_feature_formatting/in/Cargo.toml
  tests/testsuite/cargo_remove/optional_dep_feature_formatting/in/src/lib.rs
  tests/testsuite/cargo_remove/optional_dep_feature_formatting/mod.rs
  tests/testsuite/cargo_remove/optional_dep_feature_formatting/out/Cargo.toml
  tests/testsuite/cargo_remove/optional_dep_feature_formatting/stderr.log
  tests/testsuite/cargo_remove/optional_dep_feature_formatting/stdout.log
Labels: A-manifest, S-waiting-on-bors

#12857 fix(cli): Provide next steps for bad -Z flag
  src/cargo/core/features.rs
  tests/testsuite/cargo_features.rs
Labels: Command-doc, A-testing-cargo-itself, S-waiting-on-bors, A-unstable

#12772 If there's a version in the lock file only use that exact version
  src/cargo/core/registry.rs
  src/cargo/sources/registry/index.rs
  src/cargo/util/semver_ext.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/registry.rs
Labels: A-registries, A-manifest, S-waiting-on-bors, A-semver

#12860 refactor: centralize logic of getting max resolve version
  src/cargo/core/resolver/resolve.rs
  src/cargo/ops/lockfile.rs
Labels: A-dependency-resolution, S-waiting-on-bors, A-lockfile

#12876 Fix unused_imports warning
  src/cargo/core/resolver/context.rs
Labels: A-dependency-resolution, S-waiting-on-bors

#12749 move up looking at index summary enum
  src/cargo/sources/registry/index.rs
  src/cargo/sources/registry/mod.rs
  src/cargo/util/semver_ext.rs
Labels: A-registries, S-waiting-on-bors, A-semver

#12878 docs(contrib): Describe how to add a new package
  src/doc/contrib/src/SUMMARY.md
  src/doc/contrib/src/implementation/packages.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12879 docs(ref): Link to docs.rs metadata table
  src/doc/src/reference/manifest.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12880 refactor(shell): Write at once rather than in fragments
  src/cargo/core/shell.rs
  src/cargo/ops/cargo_add/mod.rs
  src/cargo/ops/registry/search.rs
Labels: A-interacts-with-crates.io, Command-search, A-console-output, S-waiting-on-bors, Command-add

#12868 Remove duplicate binaries during install
  src/bin/cargo/commands/install.rs
  tests/testsuite/install.rs
Labels: Command-install, S-waiting-on-bors, A-cli

#12884 Remove outdated option to `-Zcheck-cfg` warnings
  src/cargo/core/compiler/custom_build.rs
  src/cargo/util/config/target.rs
  tests/testsuite/check_cfg.rs
Labels: A-build-scripts, S-waiting-on-bors

#12786 feat(toml): Allow version-less manifests
  src/cargo/ops/registry/publish.rs
  src/cargo/util/toml/embedded.rs
  src/cargo/util/toml/mod.rs
  src/doc/src/reference/manifest.md
  src/doc/src/reference/unstable.md
  tests/testsuite/check.rs
  tests/testsuite/metadata.rs
  tests/testsuite/package.rs
  tests/testsuite/publish.rs
Labels: A-documenting-cargo-itself, Command-publish, A-interacts-with-crates.io, T-cargo, A-manifest, finished-final-comment-period, disposition-merge, S-waiting-on-bors, to-announce

#12859 feat(doc): Print the generated docs links
  crates/cargo-test-support/src/compare.rs
  src/cargo/ops/cargo_doc.rs
  tests/testsuite/artifact_dep.rs
  tests/testsuite/build_script.rs
  tests/testsuite/check_cfg.rs
  tests/testsuite/collisions.rs
  tests/testsuite/doc.rs
  tests/testsuite/docscrape.rs
  tests/testsuite/features2.rs
  tests/testsuite/glob_targets.rs
  tests/testsuite/multitarget.rs
  tests/testsuite/profile_targets.rs
  tests/testsuite/rustdoc.rs
  tests/testsuite/rustdocflags.rs
Labels: Command-doc, A-testing-cargo-itself, S-waiting-on-bors

#12881 refactor(toml): Decouple parsing from interning system
  src/bin/cargo/commands/remove.rs
  src/cargo/core/package_id_spec.rs
  src/cargo/core/profiles.rs
  src/cargo/core/workspace.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/config.rs
Labels: A-workspaces, A-profiles, A-manifest, S-waiting-on-bors, A-cli, Command-remove

#12890 Improve the margin calculation for the search command's UI
  src/cargo/ops/registry/search.rs
Labels: A-interacts-with-crates.io, Command-search, S-waiting-on-bors

#12625 feat: implement RFC 3127 `-Ztrim-paths`
  src/cargo/core/compiler/mod.rs
  src/cargo/core/features.rs
  src/cargo/core/profiles.rs
  src/cargo/util/rustc.rs
  src/cargo/util/toml/mod.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/bad_config.rs
  tests/testsuite/config.rs
  tests/testsuite/main.rs
  tests/testsuite/profile_trim_paths.rs
Labels: A-documenting-cargo-itself, A-build-execution, A-profiles, A-manifest, S-waiting-on-bors, A-cache-messages, A-unstable, Z-trim-paths

#12902 refactor(toml): Cleanup noticed on the way to #12801
  src/cargo/util/toml/mod.rs
Labels: A-manifest, S-waiting-on-bors

#12903 docs(ref): Highlight commands to answer dep resolution questions
  src/doc/src/reference/resolver.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#12904 docs(ref): Fix open-semver-range issue link
  src/doc/src/reference/specifying-dependencies.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors
