Repository rust-lang/cargo, pull requests merged in 2024-05, with the labels that each got.

#13833 fix(lint): Warn not Error on unsupported lint tool
  src/cargo/util/toml/mod.rs
  tests/testsuite/lints_table.rs
Labels: A-manifest, S-waiting-on-bors

#13805 Error when unstable lints are specified but not enabled
  src/cargo/core/features.rs
  src/cargo/core/workspace.rs
  src/cargo/util/lints.rs
  tests/testsuite/lints_table.rs
Labels: A-workspaces, S-waiting-on-bors, A-unstable

#13836 fix(toml): Don't lose 'public' when inheriting a dep
  src/cargo/util/toml/mod.rs
Labels: A-manifest, S-waiting-on-bors

#13791 fix(resolver): Treat unset MSRV as compatible
  src/cargo/core/resolver/version_prefs.rs
Labels: A-dependency-resolution, S-waiting-on-bors

#13840 chore(ci): Ignore openssl deps
  .github/renovate.json5
Labels: S-waiting-on-bors, A-infrastructure

#13839 fix(toml): On 2024 Edition, disallow ignored `default-features` when inheriting
  crates/cargo-util-schemas/src/manifest/mod.rs
  src/cargo/ops/fix.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/fix.rs
  tests/testsuite/inheritable_workspace_fields.rs
Labels: A-manifest, Command-fix, S-waiting-on-bors

#13841 fix(toml): Validate crates_types/proc-macro for bin like others
  src/cargo/util/toml/mod.rs
  src/cargo/util/toml/targets.rs
  tests/testsuite/bad_config.rs
Labels: A-manifest, S-waiting-on-bors

#13818 Clean package perf improvements
  src/cargo/ops/cargo_clean.rs
Labels: Command-clean, S-waiting-on-bors

#13850 Update continuous-integration.md: Include CircleCI reference
  src/doc/src/guide/continuous-integration.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#13849 perf(toml): Avoid inferring when targets are known
  src/cargo/util/toml/targets.rs
Labels: S-waiting-on-bors

#13851 refactor: remove unnecessary branch for link binary on macOS
  crates/cargo-test-support/src/lib.rs
  crates/cargo-util/src/paths.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors

#13852 fix(lints): Prevent inheritance from bring exposed for published packages
  src/cargo/core/workspace.rs
  src/cargo/util/lints.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/lints_table.rs
Labels: A-workspaces, A-manifest, S-waiting-on-bors, beta-nominated

#13853 [beta-1.79] Prevent inheritance from bring exposed for published packages
  src/cargo/core/workspace.rs
  src/cargo/util/lints.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/lints_table.rs
Labels: A-workspaces, A-manifest, S-waiting-on-bors

#13571 Stabilize `-Zcheck-cfg` as always enabled
  src/cargo/core/compiler/build_context/target_info.rs
  src/cargo/core/compiler/build_runner/mod.rs
  src/cargo/core/compiler/custom_build.rs
  src/cargo/core/compiler/fingerprint/mod.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/core/features.rs
  src/cargo/util/context/target.rs
  src/doc/src/reference/build-script-examples.md
  src/doc/src/reference/build-scripts.md
  src/doc/src/reference/unstable.md
  tests/testsuite/build_script.rs
  tests/testsuite/cargo/z_help/stdout.term.svg
  tests/testsuite/check_cfg.rs
  tests/testsuite/features_namespaced.rs
  tests/testsuite/package_features.rs
  tests/testsuite/profiles.rs
  tests/testsuite/rustc.rs
  tests/testsuite/rustflags.rs
  tests/testsuite/weak_dep_features.rs
Labels: A-documenting-cargo-itself, A-build-execution, A-rebuild-detection, A-build-scripts, S-waiting-on-bors, A-cfg-expr, A-unstable

#13860 Fix global_cache_tracker::max_download_size test flakiness
  tests/testsuite/global_cache_tracker.rs
Labels: S-waiting-on-bors

#13865 style(test): Remove check-cfg warning
  crates/cargo-test-support/build.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors

#13864 Update UI example code in contributor guide
  src/doc/contrib/src/tests/writing.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#13861 fix(toml): Remove unstable rejrected frontmatter syntax for cargo script
  src/cargo/util/toml/embedded.rs
  tests/testsuite/script.rs
Labels: S-waiting-on-bors

#13869 Add more documentation to `cargo::rustc-check-cfg`
  src/doc/src/reference/build-scripts.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#13872 docs: add missing CARGO_MAKEFLAGS env for plugins
  src/doc/src/reference/environment-variables.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#13842 Fix: Build only the specified artifact library when multiple types are available
  src/cargo/core/compiler/unit_dependencies.rs
  tests/testsuite/artifact_dep.rs
Labels: S-waiting-on-bors

#13878 docs(ref): Correct heading level of `[lints]` documentation
  src/doc/src/reference/manifest.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#13879 test: clean up unnecessary uses of `match_exact`
  tests/testsuite/artifact_dep.rs
  tests/testsuite/config.rs
  tests/testsuite/config_cli.rs
Labels: S-waiting-on-bors

#13881 chore: Add cargo-lints to unstable docs
  src/doc/src/reference/unstable.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#13882 docs(changelog): also mention `--message-format=json`
  CHANGELOG.md
Labels: S-waiting-on-bors

#13884 Add local-only build scripts example in check-cfg docs
  src/doc/src/reference/build-scripts.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#13874 Old syntax suggestion
  src/cargo/core/compiler/custom_build.rs
  tests/testsuite/build_script.rs
Labels: A-build-scripts, S-waiting-on-bors

#13880 Refactor cargo lint tests
  tests/testsuite/lints/error/mod.rs
  tests/testsuite/lints/error/stderr.term.svg
  tests/testsuite/lints/implicit_features.rs
  tests/testsuite/lints/implicit_features/edition_2021/stderr.term.svg
  tests/testsuite/lints/implicit_features/edition_2021_warn/stderr.term.svg
  tests/testsuite/lints/implicit_features/edition_2024/mod.rs
  tests/testsuite/lints/implicit_features/edition_2024/stderr.term.svg
  tests/testsuite/lints/implicit_features/mod.rs
  tests/testsuite/lints/inherited/mod.rs
  tests/testsuite/lints/inherited/stderr.term.svg
  tests/testsuite/lints/mod.rs
  tests/testsuite/lints/unknown_lints.rs
  tests/testsuite/lints/unknown_lints/default/mod.rs
  tests/testsuite/lints/unknown_lints/mod.rs
  tests/testsuite/lints/unused_optional_dependencies.rs
  tests/testsuite/lints/unused_optional_dependencies/edition_2021/mod.rs
  tests/testsuite/lints/unused_optional_dependencies/edition_2021/stderr.term.svg
  tests/testsuite/lints/unused_optional_dependencies/edition_2024/mod.rs
  tests/testsuite/lints/unused_optional_dependencies/edition_2024/stderr.term.svg
  tests/testsuite/lints/unused_optional_dependencies/mod.rs
  tests/testsuite/lints/unused_optional_dependencies/renamed_deps/mod.rs
  tests/testsuite/lints/unused_optional_dependencies/renamed_deps/stderr.term.svg
  tests/testsuite/lints/warning/mod.rs
  tests/testsuite/lints/warning/stderr.term.svg
  tests/testsuite/lints_table.rs
Labels: S-waiting-on-bors

#13893 Fix docs for unstable script feature
  src/doc/src/reference/unstable.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#13901 Update benchmark formatting for new nightly
  tests/testsuite/bench.rs
Labels: S-waiting-on-bors

#13898 Preserve file permissions on unix during `write_atomic`
  crates/cargo-util/src/paths.rs
Labels: S-waiting-on-bors

#13917 refactor: misc refactors for `ops::resolve`
  src/cargo/core/resolver/resolve.rs
  src/cargo/ops/resolve.rs
Labels: A-dependency-resolution, S-waiting-on-bors

#13920 test: set safe.directory for git repo in apache container
  crates/cargo-test-support/containers/apache/Dockerfile
  crates/cargo-test-support/containers/sshd/Dockerfile
Labels: A-testing-cargo-itself, S-waiting-on-bors

#13924 refactor: more comments and variable rename
  src/cargo/core/registry.rs
Labels: A-registries, S-waiting-on-bors

#13913 Add special `check-cfg` lint config for the `unexpected_cfgs` lint
  crates/cargo-util-schemas/src/manifest/mod.rs
  src/cargo/core/compiler/build_runner/mod.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/util/toml/mod.rs
  src/doc/src/reference/build-scripts.md
  tests/testsuite/check_cfg.rs
  tests/testsuite/lints_table.rs
Labels: A-documenting-cargo-itself, A-build-execution, T-cargo, A-manifest, final-comment-period, disposition-merge, S-waiting-on-bors

#13931 Temporarily fix standard_lib tests on linux.
  tests/testsuite/standard_lib.rs
Labels: S-waiting-on-bors

#13572 Fix: Make path dependencies with the same name stays locked
  src/cargo/core/resolver/encode.rs
  tests/testsuite/patch.rs
  tests/testsuite/path.rs
Labels: A-dependency-resolution, S-waiting-on-bors, A-lockfile

#13930 Fix warning output in build_with_symlink_to_path_dependency_with_build_script_in_git
  tests/testsuite/build.rs
Labels: S-waiting-on-bors

#13929 Silence warnings running embedded unittests.
  src/cargo/util/toml/embedded.rs
Labels: S-waiting-on-bors

#13935 Make `git::use_the_cli` test truly locale independent
  tests/testsuite/git.rs
Labels: S-waiting-on-bors

#13937 docs(ref): Simplify check-cfg build.rs docs
  src/doc/src/reference/build-scripts.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#13927 Load `libsecret` by its `SONAME`, `libsecret-1.so.0`
  credential/cargo-credential-libsecret/src/lib.rs
Labels: S-waiting-on-bors, A-credential-provider

#13907 fix: support IPv6-only network for cargo fix
  src/cargo/util/diagnostic_server.rs
  src/cargo/util/lockserver.rs
  src/cargo/util/network/mod.rs
Labels: Command-fix, A-networking, S-waiting-on-bors

#13946 fetch specific commits even if the github fast path fails
  src/cargo/sources/git/utils.rs
Labels: A-git, S-waiting-on-bors

#13939 Use `i32` rather than `usize` as "default integer" in library template
  src/cargo/ops/cargo_new.rs
  tests/testsuite/cargo_init/auto_git/out/src/lib.rs
  tests/testsuite/cargo_init/formats_source/out/src/lib.rs
  tests/testsuite/cargo_init/fossil_autodetect/out/src/lib.rs
  tests/testsuite/cargo_init/git_autodetect/out/src/lib.rs
  tests/testsuite/cargo_init/git_ignore_exists_no_conflicting_entries/out/src/lib.rs
  tests/testsuite/cargo_init/ignores_failure_to_format_source/out/src/lib.rs
  tests/testsuite/cargo_init/inherit_workspace_package_table/in/src/lib.rs
  tests/testsuite/cargo_init/inherit_workspace_package_table/out/src/lib.rs
  tests/testsuite/cargo_init/mercurial_autodetect/out/src/lib.rs
  tests/testsuite/cargo_init/pijul_autodetect/out/src/lib.rs
  tests/testsuite/cargo_init/simple_git/out/src/lib.rs
  tests/testsuite/cargo_init/simple_git_ignore_exists/out/src/lib.rs
  tests/testsuite/cargo_init/simple_hg/out/src/lib.rs
  tests/testsuite/cargo_init/simple_hg_ignore_exists/out/src/lib.rs
  tests/testsuite/cargo_init/simple_lib/out/src/lib.rs
  tests/testsuite/cargo_new/add_members_to_non_workspace/out/bar/src/lib.rs
  tests/testsuite/cargo_new/add_members_to_workspace_with_exclude_list/in/src/lib.rs
  tests/testsuite/cargo_new/add_members_to_workspace_without_members/out/bar/src/lib.rs
  tests/testsuite/cargo_new/inherit_workspace_lints/in/src/lib.rs
  tests/testsuite/cargo_new/inherit_workspace_lints/out/src/lib.rs
  tests/testsuite/cargo_new/inherit_workspace_package_table.in/src/lib.rs
  tests/testsuite/cargo_new/inherit_workspace_package_table/out/src/lib.rs
  tests/testsuite/cargo_new/inherit_workspace_package_table_with_edition/out/src/lib.rs
  tests/testsuite/cargo_new/inherit_workspace_package_table_with_registry/out/src/lib.rs
  tests/testsuite/cargo_new/inherit_workspace_package_table_without_version/in/src/lib.rs
  tests/testsuite/cargo_new/inherit_workspace_package_table_without_version/out/src/lib.rs
  tests/testsuite/cargo_new/not_inherit_workspace_package_table_if_not_members/in/src/lib.rs
  tests/testsuite/cargo_new/not_inherit_workspace_package_table_if_not_members/out/src/lib.rs
  tests/testsuite/new.rs
  tests/testsuite/test.rs
Labels: Command-new, S-waiting-on-bors

#13925 [beta-1.79] fix(toml): Don't warn on lints.rust.unexpected_cfgs.check-cfg
  .github/workflows/main.yml
  Cargo.lock
  Cargo.toml
  crates/cargo-test-support/build.rs
  crates/cargo-test-support/containers/apache/Dockerfile
  crates/cargo-test-support/containers/sshd/Dockerfile
  crates/rustfix/Cargo.toml
  crates/rustfix/tests/everything/multiple-solutions.nightly.fixed.rs
  crates/rustfix/tests/everything/multiple-solutions.nightly.json
  crates/rustfix/tests/everything/multiple-solutions.nightly.rs
  crates/rustfix/tests/parse_and_replace.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/bench.rs
  tests/testsuite/check_cfg.rs
  tests/testsuite/standard_lib.rs
Labels: A-manifest, A-testing-cargo-itself, Command-fix, S-waiting-on-bors, A-infrastructure

#13948 upgrade gix from 0.62 to 0.63
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors, beta-nominated

#13950 [beta-1.79] upgrade gix from 0.62 to 0.63
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#13951 Add more high level traces
  src/cargo/core/compiler/build_context/target_info.rs
  src/cargo/core/package.rs
Labels: S-waiting-on-bors, A-cfg-expr

#13957 Fix wrong type of rustc-flags in documentation
  src/doc/src/reference/config.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#13956 Improve error description when deserializing partial field struct
  src/cargo/util/context/de.rs
  src/cargo/util/context/mod.rs
  tests/testsuite/config.rs
  tests/testsuite/progress.rs
Labels: A-configuration, S-waiting-on-bors

#13964 test: switch from `drop` to `let _` due to nightly rustc change
  tests/testsuite/fix.rs
Labels: S-waiting-on-bors

#13969 fix: check if rev is full commit sha for github fast path
  src/cargo/sources/git/source.rs
  src/cargo/sources/git/utils.rs
Labels: A-git, S-waiting-on-bors

#13973 feat(test): Auto-redact elapsed time
  Cargo.lock
  Cargo.toml
  crates/cargo-test-support/Cargo.toml
  crates/cargo-test-support/src/compare.rs
  tests/testsuite/lints/warning/stderr.term.svg
Labels: A-testing-cargo-itself, S-waiting-on-bors

#13958 Include `lints.rust.unexpected_cfgs.check-cfg` in the fingerprint
  src/cargo/core/compiler/fingerprint/mod.rs
  tests/testsuite/check_cfg.rs
Labels: A-rebuild-detection, S-waiting-on-bors

#13976 Update openssl-src to 111.28.2+1.1.1w
  Cargo.lock
Labels: S-waiting-on-bors

#13974 feat: stabilize `cargo update --precise <yanked>`
  src/cargo/sources/registry/mod.rs
  src/doc/man/cargo-update.md
  src/doc/man/generated_txt/cargo-update.txt
  src/doc/src/commands/cargo-update.md
  src/etc/man/cargo-update.1
  tests/testsuite/update.rs
Labels: A-documenting-cargo-itself, A-registries, T-cargo, final-comment-period, disposition-merge, S-waiting-on-bors, A-cli-help

#13984 doc(cargo-package): explain no guarantee of vcs provenance
  src/doc/man/cargo-package.md
  src/doc/man/generated_txt/cargo-package.txt
  src/doc/src/commands/cargo-package.md
  src/etc/man/cargo-package.1
Labels: A-documenting-cargo-itself, S-waiting-on-bors, A-cli-help

#13989 fix(toml): Ensure targets are in a deterministic order
  src/cargo/util/toml/mod.rs
Labels: A-manifest, S-waiting-on-bors

#13970 fix: adjust custom err from cert-check due to libgit2 1.8 change
  src/cargo/sources/git/known_hosts.rs
  src/cargo/sources/git/utils.rs
  tests/testsuite/https.rs
Labels: A-git, S-waiting-on-bors

#13987 fix(new): Dont say were adding to a workspace when a regular package is in root
  src/cargo/ops/cargo_new.rs
  tests/testsuite/cargo_new/add_members_to_non_workspace/stderr.term.svg
Labels: Command-new, S-waiting-on-bors

#13992 fix(config): Ensure `--config net.git-fetch-with-cli=true` is respected
  src/cargo/util/context/mod.rs
  tests/testsuite/cargo/z_help/stdout.term.svg
  tests/testsuite/config_cli.rs
Labels: A-configuration, S-waiting-on-bors
