Repository rust-lang/cargo, pull requests merged in 2024-01, with the labels that each got.

#13220 Fix fix::fix_in_dependency to not rely on rustc
  tests/testsuite/fix.rs
Labels: S-waiting-on-bors

#13226 rustfix: Support inserting new lines.
  Cargo.lock
  Cargo.toml
  crates/rustfix/Cargo.toml
  crates/rustfix/src/lib.rs
  crates/rustfix/tests/everything/use-insert.fixed.rs
  crates/rustfix/tests/everything/use-insert.json
  crates/rustfix/tests/everything/use-insert.rs
  crates/rustfix/tests/parse_and_replace.rs
Labels: Command-fix, S-waiting-on-bors

#13237 Contrib: Fix team HackMD links
  src/doc/contrib/src/team.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#13239 chore: tracing be compat with rustc_log
  Cargo.toml
Labels: S-waiting-on-bors

#13242 [beta-1.76.0] chore: tracing be compat with rustc_log
  Cargo.toml
Labels: S-waiting-on-bors

#13243 `cargo fix`: Call rustc fewer times.
  crates/rustfix/src/lib.rs
  src/cargo/ops/fix.rs
  src/cargo/util/diagnostic_server.rs
  tests/testsuite/fix.rs
  tests/testsuite/fix_n_times.rs
  tests/testsuite/main.rs
Labels: A-diagnostics, Command-fix, S-waiting-on-bors

#13245 test: support publish package with a `public` field.
  crates/cargo-test-support/src/registry.rs
  tests/testsuite/pub_priv.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors

#13244 chore: update auto labels
  triagebot.toml
Labels: S-waiting-on-bors, A-infrastructure

#13241 feat(embedded): Add multiple experimental manifest syntaxes
  Cargo.lock
  Cargo.toml
  src/cargo/util/toml/embedded.rs
Labels: S-waiting-on-bors

#13248 Deprecate rustc plugin support in cargo
  src/cargo/util/toml/targets.rs
  tests/testsuite/cross_compile.rs
  tests/testsuite/proc_macro.rs
Labels: S-waiting-on-bors

#13249 Update dependency handlebars to v5 for mdman.
  Cargo.lock
  Cargo.toml
  crates/mdman/src/hbs.rs
Labels: S-waiting-on-bors, A-cli-help

#13255 chore: Add dependency dashboard
  .github/renovate.json5
Labels: S-waiting-on-bors, A-infrastructure

#13260 docs(changelog): Call out cargo-new lockfile change
  CHANGELOG.md
Labels: S-waiting-on-bors

#13263 test(manifest): Verify we warn on unused workspace.package fields
  tests/testsuite/inheritable_workspace_fields.rs
Labels: S-waiting-on-bors

#13262 fix(manifest): Provide unused key warnings for lints table
  crates/cargo-util-schemas/src/manifest.rs
  tests/testsuite/lints.rs
Labels: A-manifest, S-waiting-on-bors

#13204 fix: set OUT_DIR for all units with build scripts
  crates/cargo-test-support/src/lib.rs
  src/cargo/core/compiler/context/mod.rs
  tests/testsuite/test.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors

#13265 chore(ci): Shot-in-the-dark fix for MSRV updating
  .github/renovate.json5
Labels: S-waiting-on-bors, A-infrastructure

#13268 chore(ci): Fix MSRV:3 updates
  .github/renovate.json5
Labels: S-waiting-on-bors, A-infrastructure

#13267 refactor(toml): Make it more obvious to update package-dependent fields
  crates/cargo-util-schemas/src/manifest.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/workspaces.rs
Labels: A-manifest, S-waiting-on-bors

#13269 feat(cli): add colors to `-Zhelp` console output
  src/bin/cargo/cli.rs
  tests/testsuite/cargo/mod.rs
  tests/testsuite/cargo/z_help/mod.rs
  tests/testsuite/cargo/z_help/stderr.log
  tests/testsuite/cargo/z_help/stdout.log
  tests/testsuite/help.rs
Labels: S-waiting-on-bors, A-cli

#13261 fix: only inherit workspace package table if the new package is a member
  src/cargo/ops/cargo_new.rs
  tests/testsuite/cargo_new/not_inherit_workspace_package_table_if_not_members/in/Cargo.toml
  tests/testsuite/cargo_new/not_inherit_workspace_package_table_if_not_members/mod.rs
  tests/testsuite/cargo_new/not_inherit_workspace_package_table_if_not_members/out/Cargo.toml
  tests/testsuite/cargo_new/not_inherit_workspace_package_table_if_not_members/out/bar/Cargo.toml
  tests/testsuite/cargo_new/not_inherit_workspace_package_table_if_not_members/out/bar/src/main.rs
  tests/testsuite/cargo_new/not_inherit_workspace_package_table_if_not_members/out/foo/Cargo.toml
  tests/testsuite/cargo_new/not_inherit_workspace_package_table_if_not_members/stderr.log
Labels: Command-new, S-waiting-on-bors

#13264 crates-io: Set `Content-Type: application/json` only for requests with a body payload
  Cargo.lock
  Cargo.toml
  crates/crates-io/Cargo.toml
  crates/crates-io/lib.rs
  src/doc/src/reference/registry-web-api.md
Labels: A-documenting-cargo-itself, A-interacts-with-crates.io, S-waiting-on-bors

#13274 docs(unstable): doc comments for items and fields
  src/bin/cargo/cli.rs
  src/cargo/core/features.rs
  tests/testsuite/cargo/z_help/stdout.log
Labels: S-waiting-on-bors, A-cli, A-unstable

#13275 refactor: replace `iter_join` with `itertools::join`
  src/cargo/core/compiler/future_incompat.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/core/features.rs
  src/cargo/util/mod.rs
  tests/testsuite/clean.rs
Labels: A-build-execution, S-waiting-on-bors, A-unstable, A-future-incompat

#13273 Document why `du` function uses mutex
  Cargo.lock
  crates/cargo-util/Cargo.toml
  crates/cargo-util/src/du.rs
Labels: S-waiting-on-bors

#13172 feat: Add `rustc` style errors for manifest parsing
  Cargo.lock
  Cargo.toml
  src/cargo/util/toml/mod.rs
  tests/testsuite/alt_registry.rs
  tests/testsuite/bad_config.rs
  tests/testsuite/build.rs
  tests/testsuite/cargo_add/invalid_manifest/stderr.log
  tests/testsuite/cargo_features.rs
  tests/testsuite/features.rs
  tests/testsuite/features_namespaced.rs
  tests/testsuite/git.rs
  tests/testsuite/inheritable_workspace_fields.rs
  tests/testsuite/install.rs
  tests/testsuite/lints.rs
  tests/testsuite/member_errors.rs
  tests/testsuite/metadata.rs
  tests/testsuite/profile_custom.rs
  tests/testsuite/rust_version.rs
  tests/testsuite/workspaces.rs
Labels: A-diagnostics, A-manifest, S-waiting-on-bors

#12252 Add unstable `--output-format` option to `cargo rustdoc`
  src/bin/cargo/commands/doc.rs
  src/bin/cargo/commands/rustdoc.rs
  src/cargo/core/compiler/build_config.rs
  src/cargo/core/compiler/context/compilation_files.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/core/compiler/rustdoc.rs
  src/cargo/core/compiler/unit_dependencies.rs
  src/cargo/ops/cargo_compile/mod.rs
  src/cargo/ops/cargo_doc.rs
  src/cargo/ops/mod.rs
  src/doc/man/cargo-rustdoc.md
  src/doc/man/generated_txt/cargo-rustdoc.txt
  src/doc/man/includes/options-output-format.md
  src/doc/src/commands/cargo-rustdoc.md
  src/etc/man/cargo-rustdoc.1
  tests/testsuite/cargo_rustdoc/help/stdout.log
  tests/testsuite/rustdoc.rs
Labels: A-documenting-cargo-itself, Command-doc, A-build-execution, Command-rustdoc, S-waiting-on-bors, A-cli, A-layout, A-cli-help

#13286 More docs on prerelease compat
  src/doc/src/reference/resolver.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#13272 doc: add `public` info in `cargo-add` man page.
  src/bin/cargo/commands/add.rs
  src/doc/man/cargo-add.md
  src/doc/man/generated_txt/cargo-add.txt
  src/doc/src/commands/cargo-add.md
  src/etc/man/cargo-add.1
  tests/testsuite/cargo_add/help/stdout.log
Labels: A-documenting-cargo-itself, S-waiting-on-bors, A-cli, A-cli-help, Command-add

#13284 Add documentation entry for unstable `--output-format` flag
  src/doc/src/reference/unstable.md
Labels: A-documenting-cargo-itself, Command-rustdoc, S-waiting-on-bors

#13252 Implementation of shallow libgit2 fetches behind an unstable flag
  src/cargo/core/features.rs
  src/cargo/sources/git/mod.rs
  src/cargo/sources/git/oxide.rs
  src/cargo/sources/git/source.rs
  src/cargo/sources/git/utils.rs
  src/cargo/sources/registry/mod.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/cargo/z_help/stdout.log
  tests/testsuite/git_shallow.rs
  tests/testsuite/offline.rs
  tests/testsuite/patch.rs
Labels: A-documenting-cargo-itself, A-git, A-registries, S-waiting-on-bors, A-unstable

#13287 fix(resolver): do not panic when sorting empty summaries
  src/cargo/core/resolver/version_prefs.rs
Labels: A-dependency-resolution, S-waiting-on-bors

#13236 Clarify the function of the test options
  src/bin/cargo/commands/test.rs
  tests/testsuite/cargo_test/help/stdout.log
Labels: Command-test, S-waiting-on-bors, A-cli

#13293 Add guidance on setting homepage in manifest
  src/doc/src/reference/manifest.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#13292 Delete sentence about parentheses being unsupported in license
  src/doc/src/reference/manifest.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#13296 Introduce `-Zprecise-pre-release` unstable flag
  src/cargo/core/features.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/cargo/z_help/stdout.log
  tests/testsuite/main.rs
  tests/testsuite/precise_pre_release.rs
Labels: A-documenting-cargo-itself, S-waiting-on-bors, A-unstable

#12914 fix(metadata): Stabilize id format as PackageIDSpec
  src/cargo/core/package.rs
  src/cargo/ops/cargo_output_metadata.rs
  src/doc/man/cargo-metadata.md
  src/doc/man/generated_txt/cargo-metadata.txt
  src/doc/src/commands/cargo-metadata.md
  src/etc/man/cargo-metadata.1
  tests/testsuite/alt_registry.rs
  tests/testsuite/features_namespaced.rs
  tests/testsuite/git.rs
  tests/testsuite/metadata.rs
  tests/testsuite/read_manifest.rs
  tests/testsuite/script.rs
  tests/testsuite/update.rs
Labels: A-documenting-cargo-itself, Command-metadata, T-cargo, finished-final-comment-period, disposition-merge, S-waiting-on-bors, A-cli-help, to-announce

#13298 docs: add more links to pkgid spec chapter
  src/doc/man/cargo-metadata.md
  src/doc/man/cargo-pkgid.md
  src/doc/man/generated_txt/cargo-metadata.txt
  src/doc/man/generated_txt/cargo-pkgid.txt
  src/doc/src/commands/cargo-metadata.md
  src/doc/src/commands/cargo-pkgid.md
  src/etc/man/cargo-metadata.1
  src/etc/man/cargo-pkgid.1
Labels: A-documenting-cargo-itself, S-waiting-on-bors, A-cli-help

#13301 Update ahash dependency to 0.8.7
  Cargo.lock
Labels: S-waiting-on-bors

#13257 Strip debuginfo when debuginfo is not requested
  src/cargo/core/compiler/mod.rs
  src/cargo/core/profiles.rs
  src/cargo/ops/cargo_compile/mod.rs
  tests/testsuite/profiles.rs
  tests/testsuite/run.rs
  tests/testsuite/unit_graph.rs
Labels: relnotes, A-build-execution, A-profiles, S-waiting-on-bors

#13250 fix(cargo-update): `--precise` accept arbitrary git revisions
  src/cargo/core/source_id.rs
  src/cargo/ops/cargo_generate_lockfile.rs
  src/cargo/sources/git/source.rs
  src/cargo/sources/git/utils.rs
  tests/testsuite/git.rs
  tests/testsuite/update.rs
Labels: A-git, Command-generate-lockfile, S-waiting-on-bors

#13305 doc: add a heading to highlight "How to find features enabled on dependencies"
  src/doc/src/reference/resolver.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#13307 doc(features): Highlight the non-blocking feature gating technique
  src/cargo/core/features.rs
Labels: S-waiting-on-bors, A-unstable

#13311 fix(json-msg): use pkgid spec in in JSON messages
  src/cargo/core/compiler/custom_build.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/core/compiler/timings.rs
  src/cargo/util/machine_message.rs
  src/doc/man/cargo-metadata.md
  src/doc/man/cargo-pkgid.md
  src/doc/man/generated_txt/cargo-metadata.txt
  src/doc/man/generated_txt/cargo-pkgid.txt
  src/doc/src/commands/cargo-metadata.md
  src/doc/src/commands/cargo-pkgid.md
  src/doc/src/reference/external-tools.md
  src/etc/man/cargo-metadata.1
  src/etc/man/cargo-pkgid.1
  tests/testsuite/bench.rs
  tests/testsuite/binary_name.rs
  tests/testsuite/build.rs
  tests/testsuite/doc.rs
  tests/testsuite/install.rs
  tests/testsuite/metabuild.rs
  tests/testsuite/test.rs
Labels: A-documenting-cargo-itself, A-build-execution, A-build-scripts, A-console-output, S-waiting-on-bors, A-timings, A-cli-help

#13315 fix(`--package`): accept `?` if it's a valid pkgid spec
  src/cargo/ops/cargo_compile/packages.rs
  tests/testsuite/check.rs
Labels: S-waiting-on-bors

#13316 Go back to passing an empty `values()` when no features are declared
  src/cargo/core/compiler/mod.rs
  tests/testsuite/check_cfg.rs
Labels: A-build-execution, S-waiting-on-bors

#13318 [beta-1.76.0] fix(`--package`): accept `?` if it's a valid pkgid spec
  src/cargo/ops/cargo_compile/packages.rs
  tests/testsuite/check.rs
  tests/testsuite/fix.rs
Labels: S-waiting-on-bors

#13317 Improve GitHub Actions CI config
  .github/workflows/main.yml
Labels: S-waiting-on-bors, A-infrastructure

#13322 test(pkgid): keep package ID format in sync
  tests/testsuite/pkgid.rs
Labels: S-waiting-on-bors

#13320 Fix precise-prerelease tracking link.
  src/doc/src/reference/unstable.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#13324 chore: Make MSRV=N-2 the workspace default
  Cargo.lock
  Cargo.toml
  benches/benchsuite/Cargo.toml
  benches/capture/Cargo.toml
  crates/cargo-platform/Cargo.toml
  crates/cargo-test-macro/Cargo.toml
  crates/cargo-test-support/Cargo.toml
  crates/cargo-util-schemas/Cargo.toml
  crates/cargo-util/Cargo.toml
  crates/crates-io/Cargo.toml
  crates/home/Cargo.toml
  crates/mdman/Cargo.toml
  crates/resolver-tests/Cargo.toml
  crates/rustfix/Cargo.toml
  crates/semver-check/Cargo.toml
  crates/xtask-build-man/Cargo.toml
  crates/xtask-bump-check/Cargo.toml
  crates/xtask-stale-label/Cargo.toml
  credential/cargo-credential-1password/Cargo.toml
  credential/cargo-credential-libsecret/Cargo.toml
  credential/cargo-credential-macos-keychain/Cargo.toml
  credential/cargo-credential-wincred/Cargo.toml
  credential/cargo-credential/Cargo.toml
Labels: A-interacts-with-crates.io, A-dependency-resolution, A-environment-variables, A-testing-cargo-itself, Command-fix, S-waiting-on-bors, A-cfg-expr, A-semver, A-cli-help, A-credential-provider, A-infrastructure, A-home

#13325 fix(cargo-rustdoc): use same path by output format logic everywhere
  src/cargo/ops/cargo_doc.rs
  tests/testsuite/rustdoc.rs
Labels: Command-doc, S-waiting-on-bors

#13210 fix(trim-paths): remap common prefix only
  src/cargo/core/compiler/mod.rs
  tests/testsuite/profile_trim_paths.rs
Labels: A-build-execution, S-waiting-on-bors

#13329 Fix static_mut_ref warning.
  crates/cargo-test-macro/src/lib.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors

#12776 feat: inherit jobserver from env for all kinds of runner
  src/cargo/core/compiler/compilation.rs
  tests/testsuite/jobserver.rs
Labels: Command-test, Command-run, A-build-execution, S-waiting-on-bors

#13342 Fix typo in test
  tests/testsuite/profiles.rs
Labels: S-waiting-on-bors

#13344 fix list option description starting with uppercase
  src/bin/cargo/commands/install.rs
  tests/testsuite/cargo_install/help/stdout.log
Labels: Command-install, S-waiting-on-bors, A-cli

#13346 fix(cli): Improve errors related to cargo script
  src/bin/cargo/commands/run.rs
  src/bin/cargo/main.rs
  tests/testsuite/script.rs
Labels: Command-run, S-waiting-on-bors, A-cli

#13349 fix(config): Deprecate non-extension files
  crates/cargo-test-support/src/registry.rs
  src/cargo/util/config/mod.rs
  tests/testsuite/alt_registry.rs
  tests/testsuite/bad_config.rs
  tests/testsuite/build.rs
  tests/testsuite/build_script.rs
  tests/testsuite/cargo_alias_config.rs
  tests/testsuite/cargo_env_config.rs
  tests/testsuite/cargo_features.rs
  tests/testsuite/check_cfg.rs
  tests/testsuite/config.rs
  tests/testsuite/config_cli.rs
  tests/testsuite/config_include.rs
  tests/testsuite/credential_process.rs
  tests/testsuite/cross_compile.rs
  tests/testsuite/directory.rs
  tests/testsuite/freshness.rs
  tests/testsuite/git.rs
  tests/testsuite/git_auth.rs
  tests/testsuite/help.rs
  tests/testsuite/install.rs
  tests/testsuite/local_registry.rs
  tests/testsuite/login.rs
  tests/testsuite/metabuild.rs
  tests/testsuite/net_config.rs
  tests/testsuite/new.rs
  tests/testsuite/offline.rs
  tests/testsuite/old_cargos.rs
  tests/testsuite/out_dir.rs
  tests/testsuite/path.rs
  tests/testsuite/paths.rs
  tests/testsuite/profile_config.rs
  tests/testsuite/progress.rs
  tests/testsuite/publish.rs
  tests/testsuite/registry.rs
  tests/testsuite/run.rs
  tests/testsuite/rustdoc_extern_html.rs
  tests/testsuite/rustdocflags.rs
  tests/testsuite/rustflags.rs
  tests/testsuite/script.rs
  tests/testsuite/source_replacement.rs
  tests/testsuite/test.rs
  tests/testsuite/tool_paths.rs
  tests/testsuite/vendor.rs
  tests/testsuite/version.rs
Labels: A-configuration, A-testing-cargo-itself, S-waiting-on-bors

#13357 fix typo of rustbuild, instead of rustuild
  src/cargo/version.rs
Labels: S-waiting-on-bors

#13351 docs(ref): Try to improve reg auth docs
  src/doc/src/reference/config.md
  src/doc/src/reference/registry-authentication.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#13362 test: data layout fix for `x86_64-unknown-none-gnu`
  tests/build-std/main.rs
  tests/testsuite/custom_target.rs
Labels: S-waiting-on-bors

#13366 doc: Replace version with `latest` for jobserver link
  crates/cargo-util/src/process_builder.rs
Labels: S-waiting-on-bors

#13361 refactor: remove unnecessary Option in `Freshness::Dirty`
  src/cargo/core/compiler/custom_build.rs
  src/cargo/core/compiler/fingerprint/dirty_reason.rs
  src/cargo/core/compiler/fingerprint/mod.rs
  src/cargo/core/compiler/job_queue/job.rs
  src/cargo/core/compiler/job_queue/mod.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/ops/common_for_install_and_uninstall.rs
Labels: A-build-execution, A-rebuild-detection, A-build-scripts, S-waiting-on-bors

#13333 feat(cargo-update): `--precise` to allow yanked versions
  src/cargo/sources/registry/mod.rs
  src/cargo/util/semver_ext.rs
  src/doc/man/cargo-update.md
  src/doc/man/generated_txt/cargo-update.txt
  src/doc/src/commands/cargo-update.md
  src/doc/src/reference/resolver.md
  src/etc/man/cargo-update.1
  tests/testsuite/update.rs
Labels: A-documenting-cargo-itself, A-registries, S-waiting-on-bors, A-semver, A-cli-help

#13368 refactor(shell): Use new fancy anstyle API
  Cargo.lock
  src/bin/cargo/cli.rs
  src/cargo/core/shell.rs
  src/cargo/ops/cargo_add/mod.rs
  src/cargo/ops/registry/search.rs
Labels: A-interacts-with-crates.io, Command-search, A-console-output, S-waiting-on-bors, A-cli, Command-add

#13335 fix: use spec id instead of name to match package
  src/cargo/ops/cargo_compile/packages.rs
  tests/testsuite/run.rs
Labels: S-waiting-on-bors

#13367 fix(new): Print a 'Creating', rather than 'Created' status
  crates/cargo-test-support/src/compare.rs
  src/bin/cargo/commands/init.rs
  src/bin/cargo/commands/new.rs
  src/cargo/ops/cargo_new.rs
  tests/testsuite/bad_config.rs
  tests/testsuite/cargo_init/auto_git/stderr.log
  tests/testsuite/cargo_init/bin_already_exists_explicit/stderr.log
  tests/testsuite/cargo_init/bin_already_exists_explicit_nosrc/stderr.log
  tests/testsuite/cargo_init/bin_already_exists_implicit/stderr.log
  tests/testsuite/cargo_init/bin_already_exists_implicit_namenosrc/stderr.log
  tests/testsuite/cargo_init/bin_already_exists_implicit_namesrc/stderr.log
  tests/testsuite/cargo_init/bin_already_exists_implicit_nosrc/stderr.log
  tests/testsuite/cargo_init/cant_create_library_when_both_binlib_present/stderr.log
  tests/testsuite/cargo_init/creates_binary_when_both_binlib_present/stderr.log
  tests/testsuite/cargo_init/creates_binary_when_instructed_and_has_lib_file/stderr.log
  tests/testsuite/cargo_init/creates_library_when_instructed_and_has_bin_file/stderr.log
  tests/testsuite/cargo_init/explicit_bin_with_git/stderr.log
  tests/testsuite/cargo_init/formats_source/stderr.log
  tests/testsuite/cargo_init/fossil_autodetect/stderr.log
  tests/testsuite/cargo_init/git_autodetect/stderr.log
  tests/testsuite/cargo_init/git_ignore_exists_no_conflicting_entries/stderr.log
  tests/testsuite/cargo_init/ignores_failure_to_format_source/stderr.log
  tests/testsuite/cargo_init/inferred_bin_with_git/stderr.log
  tests/testsuite/cargo_init/inferred_lib_with_git/stderr.log
  tests/testsuite/cargo_init/inherit_workspace_package_table/stderr.log
  tests/testsuite/cargo_init/invalid_dir_name/stderr.log
  tests/testsuite/cargo_init/lib_already_exists_nosrc/stderr.log
  tests/testsuite/cargo_init/lib_already_exists_src/stderr.log
  tests/testsuite/cargo_init/mercurial_autodetect/stderr.log
  tests/testsuite/cargo_init/path_contains_separator/stderr.log
  tests/testsuite/cargo_init/pijul_autodetect/stderr.log
  tests/testsuite/cargo_init/reserved_name/stderr.log
  tests/testsuite/cargo_init/simple_bin/stderr.log
  tests/testsuite/cargo_init/simple_git/stderr.log
  tests/testsuite/cargo_init/simple_git_ignore_exists/stderr.log
  tests/testsuite/cargo_init/simple_hg/stderr.log
  tests/testsuite/cargo_init/simple_hg_ignore_exists/stderr.log
  tests/testsuite/cargo_init/simple_lib/stderr.log
  tests/testsuite/cargo_init/with_argument/stderr.log
  tests/testsuite/cargo_init/workspace_add_member/stderr.log
  tests/testsuite/cargo_new/add_members_to_workspace_format_previous_items/stderr.log
  tests/testsuite/cargo_new/add_members_to_workspace_format_sorted/stderr.log
  tests/testsuite/cargo_new/add_members_to_workspace_with_absolute_package_path/stderr.log
  tests/testsuite/cargo_new/add_members_to_workspace_with_empty_members/stderr.log
  tests/testsuite/cargo_new/add_members_to_workspace_with_exclude_list/stderr.log
  tests/testsuite/cargo_new/add_members_to_workspace_with_members_glob/stderr.log
  tests/testsuite/cargo_new/empty_name/stderr.log
  tests/testsuite/cargo_new/inherit_workspace_lints/stderr.log
  tests/testsuite/cargo_new/inherit_workspace_package_table/stderr.log
  tests/testsuite/cargo_new/inherit_workspace_package_table_with_edition/stderr.log
  tests/testsuite/cargo_new/inherit_workspace_package_table_with_registry/stderr.log
  tests/testsuite/cargo_new/inherit_workspace_package_table_without_version/stderr.log
  tests/testsuite/cargo_new/not_inherit_workspace_package_table_if_not_members/stderr.log
  tests/testsuite/new.rs
  tests/testsuite/workspaces.rs
Labels: Command-new, Command-init, A-testing-cargo-itself, S-waiting-on-bors, A-cli

#12852 feat: stabilize lockfile v4
  src/cargo/core/resolver/encode.rs
  src/cargo/core/resolver/resolve.rs
  src/cargo/core/source_id.rs
  src/cargo/sources/git/source.rs
  src/cargo/util/toml_mut/dependency.rs
  tests/testsuite/lockfile_compat.rs
Labels: A-git, A-dependency-resolution, T-cargo, A-manifest, finished-final-comment-period, disposition-merge, S-waiting-on-bors, A-lockfile, to-announce

#13364 doc: Hide `cargo-fetch` description in offline man page
  src/doc/man/generated_txt/cargo-fetch.txt
  src/doc/man/includes/options-locked.md
  src/doc/src/commands/cargo-fetch.md
  src/etc/man/cargo-fetch.1
Labels: A-documenting-cargo-itself, Command-fetch, S-waiting-on-bors, A-cli, A-cli-help

#13375 fix(diagnostic): Don't panic on empty spans
  src/cargo/util/toml/mod.rs
  tests/testsuite/diagnostics.rs
  tests/testsuite/main.rs
Labels: A-manifest, S-waiting-on-bors

#13376 fix(toml): Improve map/sequence error message
  Cargo.lock
  Cargo.toml
  tests/testsuite/diagnostics.rs
Labels: S-waiting-on-bors

#13377 chore(ci): enable m1 runner
  .github/workflows/main.yml
Labels: S-waiting-on-bors, A-infrastructure
