Repository rust-lang/cargo, pull requests merged in 2024-03, with the labels that each got.

#13506 refactor: Clarify more Config -> Context
  crates/xtask-bump-check/src/main.rs
  src/bin/cargo/cli.rs
  src/cargo/core/compiler/build_config.rs
  src/cargo/core/compiler/build_context/mod.rs
  src/cargo/core/compiler/build_context/target_info.rs
  src/cargo/core/compiler/compilation.rs
  src/cargo/core/features.rs
  src/cargo/core/profiles.rs
  src/cargo/core/resolver/mod.rs
  src/cargo/core/source_id.rs
  src/cargo/core/workspace.rs
  src/cargo/lib.rs
  src/cargo/ops/cargo_compile/mod.rs
  src/cargo/ops/cargo_config.rs
  src/cargo/ops/cargo_doc.rs
  src/cargo/ops/cargo_fetch.rs
  src/cargo/ops/cargo_generate_lockfile.rs
  src/cargo/ops/cargo_package.rs
  src/cargo/ops/registry/mod.rs
  src/cargo/ops/registry/publish.rs
  src/cargo/ops/registry/yank.rs
  src/cargo/sources/config.rs
  src/cargo/sources/git/known_hosts.rs
  src/cargo/sources/git/oxide.rs
  src/cargo/util/auth/mod.rs
  src/cargo/util/command_prelude.rs
  src/cargo/util/context/de.rs
  src/cargo/util/context/environment.rs
  src/cargo/util/context/key.rs
  src/cargo/util/context/mod.rs
  src/cargo/util/context/path.rs
  src/cargo/util/context/target.rs
  src/cargo/util/context/value.rs
  src/cargo/util/credential/paseto.rs
  src/cargo/util/credential/token.rs
  src/cargo/util/mod.rs
  src/cargo/util/network/http.rs
  src/cargo/util/network/proxy.rs
  src/cargo/util/progress.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/config.rs
  tests/testsuite/config_cli.rs
  tests/testsuite/member_discovery.rs
  tests/testsuite/member_errors.rs
  triagebot.toml
Labels: A-git, Command-doc, Command-publish, A-interacts-with-crates.io, A-build-execution, Command-fetch, Command-generate-lockfile, Command-package, Command-yank, A-workspaces, A-profiles, A-dependency-resolution, A-console-output, A-manifest, A-networking, S-waiting-on-bors, A-cli, A-cfg-expr, A-unstable, A-registry-authentication, A-infrastructure

#13512 [docs]: Clarify vendored sources as read-only and way to modify
  src/doc/man/cargo-vendor.md
  src/doc/man/generated_txt/cargo-vendor.txt
  src/doc/src/commands/cargo-vendor.md
  src/etc/man/cargo-vendor.1
Labels: A-documenting-cargo-itself, S-waiting-on-bors, A-cli-help

#13515 refactor: abstract `std::fs` away from on-disk index cache
  src/cargo/sources/registry/index/cache.rs
  src/cargo/sources/registry/index/mod.rs
Labels: A-registries, S-waiting-on-bors

#13514 fix(msrv): Report all incompatible packages, not just a random one
  src/cargo/ops/cargo_compile/mod.rs
  tests/testsuite/rust_version.rs
Labels: S-waiting-on-bors

#13505 feat(toml): Warn on unset Edition
  src/cargo/core/features.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/bench.rs
  tests/testsuite/check_cfg.rs
  tests/testsuite/custom_target.rs
  tests/testsuite/docscrape.rs
  tests/testsuite/edition.rs
  tests/testsuite/https.rs
  tests/testsuite/profile_trim_paths.rs
  tests/testsuite/ssh.rs
Labels: A-manifest, S-waiting-on-bors, A-unstable

#13520 feat: Use consistent colors when testing
  Cargo.toml
  tests/testsuite/cargo_add/invalid_manifest/stderr.term.svg
Labels: S-waiting-on-bors

#13517 chore: update pulldown-cmark to 0.10.0
  Cargo.lock
  Cargo.toml
  crates/mdman/src/format/man.rs
  crates/mdman/src/format/text.rs
  crates/mdman/src/lib.rs
  crates/mdman/src/util.rs
  crates/mdman/tests/compare/expected/tables.md
  crates/mdman/tests/compare/tables.md
  src/doc/src/commands/cargo-add.md
  src/doc/src/commands/cargo-bench.md
  src/doc/src/commands/cargo-build.md
  src/doc/src/commands/cargo-check.md
  src/doc/src/commands/cargo-doc.md
  src/doc/src/commands/cargo-fix.md
  src/doc/src/commands/cargo-install.md
  src/doc/src/commands/cargo-metadata.md
  src/doc/src/commands/cargo-package.md
  src/doc/src/commands/cargo-test.md
  src/doc/src/commands/cargo-tree.md
  src/etc/man/cargo-add.1
  src/etc/man/cargo-bench.1
  src/etc/man/cargo-build.1
  src/etc/man/cargo-check.1
  src/etc/man/cargo-doc.1
  src/etc/man/cargo-fix.1
  src/etc/man/cargo-install.1
  src/etc/man/cargo-metadata.1
  src/etc/man/cargo-package.1
  src/etc/man/cargo-publish.1
  src/etc/man/cargo-run.1
  src/etc/man/cargo-rustc.1
  src/etc/man/cargo-rustdoc.1
  src/etc/man/cargo-test.1
  src/etc/man/cargo-tree.1
Labels: A-documenting-cargo-itself, S-waiting-on-bors, A-cli-help

#13532 fix(cli): Trace core cargo operations
  src/bin/cargo/cli.rs
  src/bin/cargo/main.rs
  src/cargo/core/compiler/build_runner/mod.rs
  src/cargo/core/compiler/custom_build.rs
  src/cargo/core/compiler/fingerprint/mod.rs
  src/cargo/core/compiler/job_queue/mod.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/core/compiler/unit_dependencies.rs
  src/cargo/core/global_cache_tracker.rs
  src/cargo/core/package.rs
  src/cargo/core/resolver/features.rs
  src/cargo/core/resolver/mod.rs
  src/cargo/ops/cargo_compile/mod.rs
  src/cargo/ops/lockfile.rs
  src/cargo/ops/resolve.rs
  src/cargo/util/command_prelude.rs
  src/cargo/util/context/mod.rs
  src/cargo/util/rustc.rs
  src/cargo/util/toml/mod.rs
Labels: A-configuration, A-build-execution, A-rebuild-detection, A-build-scripts, A-dependency-resolution, A-manifest, S-waiting-on-bors, A-cli, A-lockfile, A-cache-messages, A-features2

#13533 fix(toml): Don't warn on unset Edition if only 2015 is compatible
  src/cargo/util/toml/mod.rs
  tests/testsuite/edition.rs
Labels: A-manifest, S-waiting-on-bors

#13538 fix(log): Trace parameters to align with profile
  src/cargo/core/compiler/fingerprint/mod.rs
  src/cargo/core/global_cache_tracker.rs
Labels: A-rebuild-detection, S-waiting-on-bors

#13399 feat(cli): Allow logging to chrome traces
  Cargo.lock
  Cargo.toml
  src/bin/cargo/main.rs
  src/cargo/core/compiler/build_runner/mod.rs
  src/cargo/core/compiler/custom_build.rs
  src/cargo/core/compiler/fingerprint/mod.rs
  src/cargo/core/compiler/job_queue/mod.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/core/global_cache_tracker.rs
  src/cargo/core/resolver/features.rs
  src/cargo/core/resolver/mod.rs
  src/cargo/ops/cargo_compile/mod.rs
  src/cargo/ops/resolve.rs
  src/cargo/util/mod.rs
  src/cargo/util/profile.rs
  src/cargo/util/rustc.rs
  src/doc/contrib/src/tests/profiling.md
Labels: A-documenting-cargo-itself, A-configuration, A-build-execution, A-rebuild-detection, A-build-scripts, A-dependency-resolution, A-manifest, S-waiting-on-bors, A-cli, A-lockfile, A-cache-messages, A-features2

#13341 doc: Edits for git/path dependency sections
  src/doc/src/reference/specifying-dependencies.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#13536 test: Add test for packaging a public dependency
  tests/testsuite/package.rs
Labels: S-waiting-on-bors

#13544 fix(rustdoc-map): dedup `--extern-html-too-url` for same unit
  src/cargo/core/compiler/rustdoc.rs
  tests/testsuite/rustdoc_extern_html.rs
Labels: S-waiting-on-bors

#13545 fix(cli): Add traces to clarify where time is going
  src/cargo/core/resolver/encode.rs
  src/cargo/core/summary.rs
  src/cargo/ops/lockfile.rs
  src/cargo/util/toml/mod.rs
  src/cargo/util/toml/targets.rs
Labels: A-dependency-resolution, A-manifest, S-waiting-on-bors, A-lockfile

#13550 chore: downgrade to openssl v1.1.1 (again)
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#13551 fix(cli): Skip tracing-chrome for platforms without 64bit atomics
  Cargo.toml
  src/bin/cargo/main.rs
Labels: S-waiting-on-bors, A-cli

#13547 docs: add link to the exported_private_dependencies lint
  src/doc/src/reference/unstable.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#13556 doc: Add doc for -Zpublic-dependency
  src/cargo/util/toml/mod.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/pub_priv.rs
Labels: A-documenting-cargo-itself, A-manifest, S-waiting-on-bors

#13557 fix(doc): Collapse down Generated statuses without --verbose
  src/cargo/ops/cargo_doc.rs
  tests/testsuite/collisions.rs
  tests/testsuite/doc.rs
Labels: Command-doc, S-waiting-on-bors

#13562 refactor(shell): Use alternate to close links
  src/cargo/core/compiler/job_queue/mod.rs
  src/cargo/core/compiler/timings.rs
  src/cargo/core/shell.rs
  src/cargo/ops/cargo_doc.rs
Labels: Command-doc, A-build-execution, A-console-output, S-waiting-on-bors, A-timings

#13537 fix: Consistently compare MSRVs
  crates/cargo-util-schemas/src/manifest/mod.rs
  crates/cargo-util-schemas/src/manifest/rust_version.rs
  src/cargo/core/resolver/version_prefs.rs
  src/cargo/ops/cargo_add/mod.rs
  src/cargo/ops/cargo_compile/mod.rs
  src/cargo/ops/cargo_install.rs
  src/cargo/ops/common_for_install_and_uninstall.rs
  src/cargo/ops/resolve.rs
  src/cargo/util/toml/mod.rs
  triagebot.toml
Labels: Command-install, A-dependency-resolution, A-manifest, S-waiting-on-bors, Command-add, A-infrastructure

#13548 util/network/http: Use `cargo/1.2.3` user-agent header
  src/cargo/util/network/http.rs
  src/doc/src/reference/registry-web-api.md
Labels: A-documenting-cargo-itself, A-networking, S-waiting-on-bors

#13567 test: Add tests for using worktrees and sparse checkouts
  tests/testsuite/git.rs
Labels: S-waiting-on-bors

#13564 refactor(lockfile): Make diffing/printing more reusable
  src/cargo/ops/cargo_generate_lockfile.rs
Labels: Command-generate-lockfile, S-waiting-on-bors

#13575 chore: remove repetitive word
  src/cargo/util/context/mod.rs
Labels: A-configuration, S-waiting-on-bors

#13581 fix(ci): bump check error when PR is behind master
  crates/xtask-bump-check/src/xtask.rs
Labels: S-waiting-on-bors, A-infrastructure

#13518 fix: strip feature dep when dep is dev dep
  src/cargo/ops/registry/publish.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/publish.rs
Labels: Command-publish, A-interacts-with-crates.io, A-manifest, S-waiting-on-bors

#13589 refactor(toml): Flatten manifest parsing
  Cargo.lock
  Cargo.toml
  crates/cargo-util-schemas/Cargo.toml
  crates/cargo-util-schemas/src/manifest/mod.rs
  crates/xtask-stale-label/src/main.rs
  src/bin/cargo/commands/remove.rs
  src/cargo/core/manifest.rs
  src/cargo/core/package.rs
  src/cargo/core/workspace.rs
  src/cargo/ops/cargo_new.rs
  src/cargo/ops/cargo_package.rs
  src/cargo/ops/cargo_read_manifest.rs
  src/cargo/ops/registry/publish.rs
  src/cargo/ops/vendor.rs
  src/cargo/sources/path.rs
  src/cargo/util/context/mod.rs
  src/cargo/util/toml/mod.rs
  src/cargo/util/toml_mut/manifest.rs
  tests/testsuite/build.rs
Labels: A-configuration, Command-publish, Command-new, A-interacts-with-crates.io, Command-package, Command-read-manifest, A-workspaces, A-manifest, S-waiting-on-bors, Command-vendor, A-cli, Command-remove, A-infrastructure

#13337 feat(tree): Control `--charset` via auto-detecting config value
  Cargo.lock
  Cargo.toml
  src/bin/cargo/commands/tree.rs
  src/cargo/core/shell.rs
  src/cargo/ops/tree/mod.rs
  src/cargo/util/context/mod.rs
  src/doc/man/cargo-tree.md
  src/doc/man/generated_txt/cargo-tree.txt
  src/doc/src/commands/cargo-tree.md
  src/doc/src/reference/config.md
  src/etc/man/cargo-tree.1
  tests/testsuite/cargo_tree/help/stdout.term.svg
Labels: A-documenting-cargo-itself, A-configuration, T-cargo, A-console-output, final-comment-period, disposition-merge, S-waiting-on-bors, A-cli, A-cli-help, Command-tree

#13593 refactor: Expose source/spans to Manifest for emitting lints
  src/cargo/core/manifest.rs
  src/cargo/ops/cargo_package.rs
  src/cargo/util/toml/mod.rs
Labels: Command-package, A-manifest, S-waiting-on-bors

#13591 feat: Add 'open-namespaces' feature
  crates/cargo-util-schemas/src/manifest/mod.rs
  crates/cargo-util-schemas/src/restricted_names.rs
  src/cargo/core/features.rs
  src/cargo/util/toml/mod.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/build.rs
  tests/testsuite/main.rs
  tests/testsuite/open_namespaces.rs
Labels: A-documenting-cargo-itself, A-manifest, S-waiting-on-bors, A-unstable

#12783 cargo: prevent dashes in lib.name
  src/cargo/core/compiler/artifact.rs
  src/cargo/core/manifest.rs
  src/cargo/util/toml/targets.rs
  tests/testsuite/artifact_dep.rs
  tests/testsuite/collisions.rs
  tests/testsuite/doc.rs
  tests/testsuite/metadata.rs
  tests/testsuite/test.rs
Labels: T-cargo, A-manifest, finished-final-comment-period, disposition-merge, S-waiting-on-bors, to-announce

#13604 Bump to 0.80.0; update changelog
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#13606 cargo/init: avoid target.name assignments if possible
  src/cargo/ops/cargo_new.rs
  tests/testsuite/cargo_init/creates_binary_when_both_binlib_present/out/Cargo.toml
  tests/testsuite/cargo_init/creates_library_when_instructed_and_has_bin_file/out/Cargo.toml
  tests/testsuite/cargo_init/inferred_lib_with_git/out/Cargo.toml
  tests/testsuite/cargo_init/lib_already_exists_nosrc/out/Cargo.toml
Labels: Command-new, S-waiting-on-bors

#13603 refactor(toml): Expose surce/spans for VirtualManifests
  Cargo.lock
  crates/cargo-util-schemas/Cargo.toml
  crates/cargo-util-schemas/src/manifest/mod.rs
  src/cargo/core/compiler/standard_lib.rs
  src/cargo/core/features.rs
  src/cargo/core/manifest.rs
  src/cargo/util/toml/mod.rs
Labels: A-manifest, S-waiting-on-bors, A-unstable

#13610 refactor(vendor): tiny not important refactors
  src/cargo/ops/vendor.rs
Labels: S-waiting-on-bors, Command-vendor

#13609 Update annotate snippets
  Cargo.lock
  Cargo.toml
  src/cargo/util/toml/mod.rs
Labels: A-manifest, S-waiting-on-bors

#13613 fix(alias): dont panic when resolving an empty alias
  src/bin/cargo/main.rs
  tests/testsuite/cargo_alias_config.rs
Labels: S-waiting-on-bors, A-cli

#13614 Fix publish script due to crates.io CDN change
  publish.py
Labels: S-waiting-on-bors, A-infrastructure

#13616 [beta 1.78] Fix publish script due to crates.io CDN change
  publish.py
Labels: S-waiting-on-bors, A-infrastructure

#13619 refactor(toml): Push diagnostic complexity on annotate-snippets
  Cargo.lock
  Cargo.toml
  src/cargo/util/toml/mod.rs
Labels: A-manifest, S-waiting-on-bors

#13618 Fix debuginfo strip when using `--target`
  src/cargo/ops/cargo_compile/mod.rs
  tests/testsuite/profiles.rs
Labels: S-waiting-on-bors

#13627 refactor(testsuite): Rename lints to lints_table
  tests/testsuite/lints_table.rs
  tests/testsuite/main.rs
Labels: S-waiting-on-bors

#13631 docs: remove untrue TODO for `native_dirs`
  src/cargo/core/compiler/compilation.rs
Labels: A-build-execution, S-waiting-on-bors

#13621 feat: Add a basic linting system
  Cargo.lock
  Cargo.toml
  src/cargo/core/features.rs
  src/cargo/core/workspace.rs
  src/cargo/util/lints.rs
  src/cargo/util/mod.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/cargo/z_help/stdout.term.svg
  tests/testsuite/lints/implicit_features/edition_2021/mod.rs
  tests/testsuite/lints/implicit_features/edition_2021_warn/mod.rs
  tests/testsuite/lints/implicit_features/edition_2021_warn/stderr.term.svg
  tests/testsuite/lints/implicit_features/edition_2024/mod.rs
  tests/testsuite/lints/implicit_features/edition_2024/stderr.term.svg
  tests/testsuite/lints/implicit_features/mod.rs
  tests/testsuite/lints/implicit_features/warn/mod.rs
  tests/testsuite/lints/implicit_features/warn/stderr.term.svg
  tests/testsuite/lints/mod.rs
  tests/testsuite/lints/rust_2024_compatibility/edition_2021/mod.rs
  tests/testsuite/lints/rust_2024_compatibility/edition_2021_warn/mod.rs
  tests/testsuite/lints/rust_2024_compatibility/edition_2021_warn/stderr.term.svg
  tests/testsuite/lints/rust_2024_compatibility/edition_2024/mod.rs
  tests/testsuite/lints/rust_2024_compatibility/edition_2024/stderr.term.svg
  tests/testsuite/lints/rust_2024_compatibility/mod.rs
  tests/testsuite/lints/rust_2024_compatibility/warn/mod.rs
  tests/testsuite/lints/rust_2024_compatibility/warn/stderr.term.svg
  tests/testsuite/lints_table.rs
  tests/testsuite/main.rs
Labels: A-workspaces, A-manifest, S-waiting-on-bors, A-unstable

#13632 fix: Warn on -Zlints
  src/cargo/core/features.rs
  tests/testsuite/cargo/z_help/stdout.term.svg
Labels: S-waiting-on-bors, A-unstable

#13592 Use `gitoxide` for `list_files_git`
  .github/renovate.json5
  Cargo.lock
  Cargo.toml
  src/cargo/core/features.rs
  src/cargo/sources/path.rs
  tests/testsuite/package.rs
Labels: S-waiting-on-bors, A-unstable, A-infrastructure

#13637 Remove unnecessary test
  tests/testsuite/check.rs
Labels: S-waiting-on-bors

#13635 refactor: Make lint names snake_case
  src/cargo/core/workspace.rs
  src/cargo/util/lints.rs
  tests/testsuite/lints_table.rs
Labels: A-workspaces, S-waiting-on-bors

#13640 Fix doc collision for lib/bin with a dash in the inferred name.
  src/cargo/ops/cargo_compile/unit_generator.rs
  tests/testsuite/doc.rs
Labels: S-waiting-on-bors, A-cargo-targets

#13630 Do not strip debuginfo by default for MSVC
  src/cargo/ops/cargo_compile/mod.rs
  tests/testsuite/profiles.rs
  tests/testsuite/run.rs
Labels: S-waiting-on-bors, beta-nominated

#13647 fix: do not borrow shell across registry query
  src/cargo/ops/cargo_generate_lockfile.rs
Labels: Command-generate-lockfile, S-waiting-on-bors

#13418 Publish test crates
  Cargo.lock
  Cargo.toml
  crates/cargo-test-macro/Cargo.toml
  crates/cargo-test-macro/LICENSE-APACHE
  crates/cargo-test-macro/LICENSE-MIT
  crates/cargo-test-macro/README.md
  crates/cargo-test-macro/src/lib.rs
  crates/cargo-test-support/Cargo.toml
  crates/cargo-test-support/LICENSE-APACHE
  crates/cargo-test-support/LICENSE-MIT
  crates/cargo-test-support/README.md
  crates/cargo-test-support/src/lib.rs
  crates/xtask-bump-check/src/xtask.rs
  publish.py
  src/doc/contrib/src/process/release.md
Labels: A-documenting-cargo-itself, A-testing-cargo-itself, S-waiting-on-bors, A-infrastructure

#13651 test: Add asserts to catch BorrowMutError's
  src/cargo/core/registry.rs
  src/cargo/util/flock.rs
Labels: A-registries, S-waiting-on-bors, A-filesystem

#13654 [stable-1.77] Do not strip debuginfo by default for MSVC
  Cargo.lock
  Cargo.toml
  src/cargo/ops/cargo_compile/mod.rs
  tests/testsuite/profiles.rs
  tests/testsuite/run.rs
Labels: S-waiting-on-bors

#13653 [beta-1.78] Do not strip debuginfo by default for MSVC
  src/cargo/ops/cargo_compile/mod.rs
  tests/testsuite/profiles.rs
  tests/testsuite/run.rs
Labels: S-waiting-on-bors

#13657 fix(generate-lockfile): hold lock before querying index
  src/cargo/ops/cargo_generate_lockfile.rs
  src/cargo/ops/mod.rs
  src/cargo/ops/resolve.rs
  tests/testsuite/generate_lockfile.rs
Labels: Command-generate-lockfile, S-waiting-on-bors

#13655 fix(add): Preserve comments when updating simple deps
  src/cargo/util/toml_mut/dependency.rs
  tests/testsuite/cargo_add/overwrite_default_features/in/Cargo.toml
  tests/testsuite/cargo_add/overwrite_default_features/out/Cargo.toml
  tests/testsuite/cargo_add/overwrite_default_features_with_no_default_features/in/Cargo.toml
  tests/testsuite/cargo_add/overwrite_default_features_with_no_default_features/out/Cargo.toml
  tests/testsuite/cargo_add/overwrite_features/in/Cargo.toml
  tests/testsuite/cargo_add/overwrite_features/out/Cargo.toml
  tests/testsuite/cargo_add/overwrite_inline_features/in/Cargo.toml
  tests/testsuite/cargo_add/overwrite_inline_features/out/Cargo.toml
  tests/testsuite/cargo_add/overwrite_name_dev_noop/in/Cargo.toml
  tests/testsuite/cargo_add/overwrite_name_dev_noop/out/Cargo.toml
  tests/testsuite/cargo_add/overwrite_name_noop/in/Cargo.toml
  tests/testsuite/cargo_add/overwrite_name_noop/out/Cargo.toml
  tests/testsuite/cargo_add/overwrite_no_default_features/in/Cargo.toml
  tests/testsuite/cargo_add/overwrite_no_default_features/out/Cargo.toml
  tests/testsuite/cargo_add/overwrite_no_default_features_with_default_features/in/Cargo.toml
  tests/testsuite/cargo_add/overwrite_no_default_features_with_default_features/out/Cargo.toml
  tests/testsuite/cargo_add/overwrite_no_optional/in/Cargo.toml
  tests/testsuite/cargo_add/overwrite_no_optional/out/Cargo.toml
  tests/testsuite/cargo_add/overwrite_no_optional_with_optional/in/Cargo.toml
  tests/testsuite/cargo_add/overwrite_no_optional_with_optional/out/Cargo.toml
  tests/testsuite/cargo_add/overwrite_no_public/in/Cargo.toml
  tests/testsuite/cargo_add/overwrite_no_public/out/Cargo.toml
  tests/testsuite/cargo_add/overwrite_no_public_with_public/in/Cargo.toml
  tests/testsuite/cargo_add/overwrite_no_public_with_public/out/Cargo.toml
  tests/testsuite/cargo_add/overwrite_optional/in/Cargo.toml
  tests/testsuite/cargo_add/overwrite_optional/out/Cargo.toml
  tests/testsuite/cargo_add/overwrite_optional_with_no_optional/in/Cargo.toml
  tests/testsuite/cargo_add/overwrite_optional_with_no_optional/out/Cargo.toml
  tests/testsuite/cargo_add/overwrite_optional_with_optional/in/Cargo.toml
  tests/testsuite/cargo_add/overwrite_optional_with_optional/out/Cargo.toml
  tests/testsuite/cargo_add/overwrite_path_noop/in/Cargo.toml
  tests/testsuite/cargo_add/overwrite_path_noop/out/Cargo.toml
  tests/testsuite/cargo_add/overwrite_preserves_inline_table/in/Cargo.toml
  tests/testsuite/cargo_add/overwrite_preserves_inline_table/out/Cargo.toml
  tests/testsuite/cargo_add/overwrite_public/in/Cargo.toml
  tests/testsuite/cargo_add/overwrite_public/out/Cargo.toml
  tests/testsuite/cargo_add/overwrite_public_with_no_public/in/Cargo.toml
  tests/testsuite/cargo_add/overwrite_public_with_no_public/out/Cargo.toml
  tests/testsuite/cargo_add/overwrite_rename_with_no_rename/in/Cargo.toml
  tests/testsuite/cargo_add/overwrite_rename_with_no_rename/out/Cargo.toml
  tests/testsuite/cargo_add/overwrite_rename_with_rename/in/Cargo.toml
  tests/testsuite/cargo_add/overwrite_rename_with_rename/out/Cargo.toml
  tests/testsuite/cargo_add/overwrite_rename_with_rename_noop/in/Cargo.toml
  tests/testsuite/cargo_add/overwrite_rename_with_rename_noop/out/Cargo.toml
  tests/testsuite/cargo_add/overwrite_version_with_git/in/Cargo.toml
  tests/testsuite/cargo_add/overwrite_version_with_git/out/Cargo.toml
  tests/testsuite/cargo_add/overwrite_with_rename/in/Cargo.toml
  tests/testsuite/cargo_add/overwrite_with_rename/out/Cargo.toml
Labels: A-manifest, S-waiting-on-bors

#13648 RUSTC_WORKSPACE_WRAPPER: clarify docs
  src/doc/src/reference/config.md
  src/doc/src/reference/environment-variables.md
  tests/testsuite/build.rs
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#13664 fix(toml): Warn on unused workspace.dependencies keys on virtual workspaces
  src/cargo/core/manifest.rs
  src/cargo/ops/cargo_package.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/build_script.rs
Labels: Command-package, A-manifest, S-waiting-on-bors

#13666 refactor(package): Simplify getting of published Manifest
  src/cargo/core/manifest.rs
  src/cargo/core/package.rs
  src/cargo/ops/cargo_package.rs
  src/cargo/ops/vendor.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/artifact_dep.rs
  tests/testsuite/features2.rs
  tests/testsuite/features_namespaced.rs
  tests/testsuite/inheritable_workspace_fields.rs
  tests/testsuite/package.rs
  tests/testsuite/publish.rs
  tests/testsuite/weak_dep_features.rs
Labels: Command-package, A-manifest, S-waiting-on-bors, Command-vendor
