Repository rust-lang/cargo, pull requests merged in 2024-08, with the labels that each got.

#14339 fix: also build manpage for cargo.md
  crates/xtask-build-man/src/main.rs
  src/doc/man/cargo.md
  src/doc/man/generated_txt/cargo.txt
  src/doc/src/commands/cargo.md
  src/etc/man/cargo.1
Labels: A-documenting-cargo-itself, S-waiting-on-bors, A-cli-help, A-infrastructure

#14341 Change tests to support `rustc` wording changes
  tests/testsuite/check.rs
Labels: S-waiting-on-bors

#14343 Fix a typo in 1.81 changes
  CHANGELOG.md
Labels: S-waiting-on-bors

#14344 docs(unstable): Improve nightly link
  src/doc/src/reference/unstable.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#14336 faq: rephrase offline usage.
  src/doc/src/faq.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#14342 refactor(toml): Rename 'resolved' to 'normalized'
  Cargo.lock
  Cargo.toml
  crates/cargo-util-schemas/Cargo.toml
  crates/cargo-util-schemas/src/manifest/mod.rs
  src/cargo/core/compiler/fingerprint/mod.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/core/manifest.rs
  src/cargo/core/workspace.rs
  src/cargo/ops/cargo_package.rs
  src/cargo/ops/fix.rs
  src/cargo/ops/registry/publish.rs
  src/cargo/ops/vendor.rs
  src/cargo/sources/path.rs
  src/cargo/util/lints.rs
  src/cargo/util/toml/mod.rs
  src/cargo/util/toml/targets.rs
Labels: Command-publish, A-interacts-with-crates.io, A-build-execution, Command-package, A-workspaces, A-rebuild-detection, A-manifest, Command-fix, S-waiting-on-bors, Command-vendor

#14351 Backport publishing workflow to 1.80.0
  .github/workflows/release.yml
  publish.py
Labels: S-waiting-on-bors, A-infrastructure

#14358 fix(build-std): remove hack on creating virtual std workspace
  src/cargo/core/compiler/standard_lib.rs
  src/cargo/core/workspace.rs
  tests/build-std/main.rs
  tests/testsuite/mock-std/Cargo.toml
  tests/testsuite/mock-std/library/Cargo.toml
Labels: A-workspaces, S-waiting-on-bors

#14357 Don't specify the depedency name in the `cargo add` inferred name test
  tests/testsuite/cargo_add/path_inferred_name/mod.rs
Labels: S-waiting-on-bors

#14367 fix(vendor): Strip excluded build targets
  src/cargo/ops/vendor.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/vendor.rs
Labels: A-manifest, S-waiting-on-review, Command-vendor, beta-nominated

#14368 [beta-1.81] fix(vendor): Strip excluded build targets
  src/cargo/ops/vendor.rs
  src/cargo/util/toml/mod.rs
  tests/build-std/main.rs
  tests/testsuite/check.rs
  tests/testsuite/vendor.rs
Labels: A-manifest, S-waiting-on-bors, Command-vendor

#14370 fix: std Cargo.lock moved to `library` dir
  src/cargo/core/compiler/standard_lib.rs
  tests/testsuite/standard_lib.rs
Labels: S-waiting-on-bors, Z-build-std

#14359 Fix: `cargo package` failed on bare commit git repo.
  src/cargo/ops/cargo_package.rs
  tests/testsuite/package.rs
Labels: Command-package, T-cargo, S-waiting-on-bors, beta-nominated

#14377 Use context instead of with_context
  crates/rustfix/tests/parse_and_replace.rs
  src/cargo/core/compiler/build_runner/mod.rs
  src/cargo/core/compiler/custom_build.rs
  src/cargo/core/compiler/future_incompat.rs
  src/cargo/core/compiler/job_queue/mod.rs
  src/cargo/core/compiler/timings.rs
  src/cargo/core/global_cache_tracker.rs
  src/cargo/core/package.rs
  src/cargo/core/registry.rs
  src/cargo/ops/cargo_add/mod.rs
  src/cargo/ops/cargo_package.rs
  src/cargo/ops/common_for_install_and_uninstall.rs
  src/cargo/ops/vendor.rs
  src/cargo/sources/git/oxide.rs
  src/cargo/sources/registry/http_remote.rs
  src/cargo/sources/registry/mod.rs
  src/cargo/util/cache_lock.rs
  src/cargo/util/context/mod.rs
  src/cargo/util/diagnostic_server.rs
  src/cargo/util/lockserver.rs
  src/cargo/util/toml/mod.rs
  src/cargo/util/toml/targets.rs
Labels: A-git, A-configuration, A-build-execution, Command-package, A-build-scripts, A-registries, A-manifest, Command-fix, S-waiting-on-bors, Command-vendor, A-timings, A-future-incompat, Command-add, A-sparse-registry

#14382 CI: Switch macos aarch64 to nightly
  .github/workflows/main.yml
Labels: S-waiting-on-bors, A-infrastructure

#14380 Use longhand gitoxide path-spec patterns
  src/cargo/sources/path.rs
  tests/testsuite/build_script.rs
Labels: S-waiting-on-bors

#14389 feat(trim-paths): rustdoc supports trim-paths for diagnostics
  src/cargo/core/compiler/mod.rs
  tests/testsuite/profile_trim_paths.rs
Labels: A-build-execution, S-waiting-on-bors, Z-trim-paths

#14391 chore: downgrade to openssl v1.1.1 (again)
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#14366 [beta-1.81] Revert "fix: Ensure dep/feature activates the dependency on 2024"
  src/cargo/util/toml/mod.rs
  tests/build-std/main.rs
  tests/testsuite/build.rs
  tests/testsuite/features.rs
Labels: A-manifest, S-waiting-on-bors

#14397 doc: convert comments to rustdoc in workspace
  src/cargo/core/workspace.rs
Labels: A-workspaces, S-waiting-on-bors

#14360 Implement base paths (RFC 3529) 1/n: path dep and patch support
  crates/cargo-util-schemas/src/manifest/mod.rs
  crates/cargo-util-schemas/src/restricted_names.rs
  src/cargo/core/features.rs
  src/cargo/util/toml/mod.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/patch.rs
  tests/testsuite/path.rs
Labels: A-documenting-cargo-itself, A-manifest, S-waiting-on-bors, A-unstable

#14402 test: Migrate some json tests to snapbox
  Cargo.lock
  Cargo.toml
  tests/testsuite/doc.rs
  tests/testsuite/metabuild.rs
Labels: S-waiting-on-bors

#14413 Correct diagnostic for `TomlDebugInfo`
  crates/cargo-util-schemas/src/manifest/mod.rs
  tests/testsuite/bad_config.rs
Labels: A-manifest, S-waiting-on-bors

#14410 test: Migrate old_cargos to snapbox
  tests/testsuite/old_cargos.rs
Labels: S-waiting-on-bors

#14401 feat(update): Report when incompatible-rust-version packages are selected
  src/cargo/ops/cargo_update.rs
  tests/testsuite/rust_version.rs
Labels: Command-update, S-waiting-on-bors

#14417 Lockfile path tests (follow-up)
  tests/testsuite/lockfile_path.rs
Labels: S-waiting-on-bors

#14418 fix: remove list owners feature of info subcommand
  src/cargo/ops/registry/info/mod.rs
  src/cargo/ops/registry/info/view.rs
  tests/testsuite/cargo_info/features_activated_over_limit_verbose/stderr.term.svg
  tests/testsuite/cargo_info/specify_version_within_ws_and_match_with_lockfile/stderr.term.svg
  tests/testsuite/cargo_info/transitive_dependency_within_ws/ws-stderr.term.svg
  tests/testsuite/cargo_info/verbose/stderr.term.svg
  tests/testsuite/cargo_info/within_ws/stderr.term.svg
  tests/testsuite/cargo_info/within_ws_without_lockfile/stderr.term.svg
Labels: A-interacts-with-crates.io, S-waiting-on-bors

#14423 doc: add lockfile-path unstable doc section
  src/doc/src/reference/unstable.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#14422 chore: update label trigger for Command-info
  triagebot.toml
Labels: S-waiting-on-bors, A-infrastructure

#14430 test: add a regression test for Issue 14409
  tests/testsuite/cargo_info/mod.rs
  tests/testsuite/cargo_info/without_requiring_registry_auth/in/.cargo/config.toml
  tests/testsuite/cargo_info/without_requiring_registry_auth/in/Cargo.lock
  tests/testsuite/cargo_info/without_requiring_registry_auth/in/Cargo.toml
  tests/testsuite/cargo_info/without_requiring_registry_auth/in/src/lib.rs
  tests/testsuite/cargo_info/without_requiring_registry_auth/mod.rs
  tests/testsuite/cargo_info/without_requiring_registry_auth/out/.cargo/config.toml
  tests/testsuite/cargo_info/without_requiring_registry_auth/out/Cargo.lock
  tests/testsuite/cargo_info/without_requiring_registry_auth/out/Cargo.toml
  tests/testsuite/cargo_info/without_requiring_registry_auth/out/src/lib.rs
  tests/testsuite/cargo_info/without_requiring_registry_auth/stderr.term.svg
  tests/testsuite/cargo_info/without_requiring_registry_auth/stdout.term.svg
Labels: S-waiting-on-bors

#14412 fix: Limiting pre-release match semantics to use only on `OptVersionReq::Req`
  src/cargo/util/semver_ext.rs
Labels: S-waiting-on-bors, A-semver

#14408 Be more permissive while packaging unpublishable crates.
  src/cargo/ops/cargo_package.rs
  src/cargo/ops/registry/mod.rs
  tests/testsuite/package.rs
Labels: A-interacts-with-crates.io, Command-package, S-waiting-on-bors

#14425 fix: doctest respects Cargo's color options
  src/cargo/ops/cargo_test.rs
  tests/testsuite/build_script.rs
  tests/testsuite/lto.rs
  tests/testsuite/test.rs
Labels: Command-test, A-interacts-with-crates.io, S-waiting-on-bors, Command-info

#14428 [mdman] Normalize newlines when rendering options
  crates/mdman/src/hbs.rs
  crates/mdman/tests/compare/expected/options.1
  crates/mdman/tests/compare/expected/options.md
  crates/mdman/tests/compare/expected/options.txt
  crates/mdman/tests/compare/includes/options-common.md
Labels: S-waiting-on-bors, A-cli-help

#14431 [beta-1.81] chore(deps): update rust crate gix to 0.64.0
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#14432 fix: -Cmetadata includes whether extra rustflags is same as host
  src/cargo/core/compiler/build_runner/compilation_files.rs
  tests/testsuite/rustflags.rs
Labels: S-waiting-on-bors, A-layout

#14441 Tests rely on absence of RUST_BACKTRACE
  crates/cargo-test-support/src/lib.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors

#14440 refactor(update): Prepare for smarter update messages
  src/cargo/ops/cargo_update.rs
  tests/testsuite/global_cache_tracker.rs
Labels: Command-update, S-waiting-on-bors

#14305 feat: Add matches_prerelease semantic
  src/cargo/util/mod.rs
  src/cargo/util/semver_eval_ext.rs
  src/cargo/util/semver_ext.rs
  tests/testsuite/precise_pre_release.rs
Labels: A-manifest, S-waiting-on-bors, A-semver

#14436 More helpful missing feature error message
  src/cargo/core/workspace.rs
  tests/testsuite/package_features.rs
Labels: A-workspaces, S-waiting-on-bors

#14453 Log details of failure if no errors were seen
  src/cargo/core/compiler/mod.rs
Labels: A-build-execution, S-waiting-on-bors

#14457 fix(resolve): Report incompatible packages with precise Rust version
  src/cargo/ops/cargo_update.rs
  tests/testsuite/rust_version.rs
Labels: Command-update, S-waiting-on-bors

#14459 feat(resolve): Report incompatible-with-rustc when MSRV-resolver is disabled
  src/cargo/ops/cargo_update.rs
  tests/testsuite/cargo_add/rustc_ignore/stderr.term.svg
  tests/testsuite/rust_version.rs
Labels: Command-update, S-waiting-on-bors

#14467 fix(pkgid): Allow open namespaces in PackageIdSpec's
  crates/cargo-util-schemas/src/core/package_id_spec.rs
  tests/testsuite/open_namespaces.rs
Labels: S-waiting-on-bors

#14461 fix(resolve): With `latest` message, differentiate actionable updates
  src/cargo/ops/cargo_update.rs
  src/cargo/util/semver_ext.rs
  tests/testsuite/direct_minimal_versions.rs
  tests/testsuite/minimal_versions.rs
  tests/testsuite/rust_version.rs
  tests/testsuite/update.rs
  tests/testsuite/workspaces.rs
Labels: Command-update, S-waiting-on-bors, A-semver
