Repository rust-lang/cargo, pull requests merged in 2024-06, with the labels that each got.

#14000 Fix: Skip deserialization of unrelated fields with overlapping name
  src/cargo/util/context/de.rs
  tests/testsuite/config.rs
Labels: S-waiting-on-bors

#13980 refactor: Transition direct assertions from cargo-test-support to snapbox
  Cargo.lock
  Cargo.toml
  crates/cargo-test-support/src/compare.rs
  crates/cargo-test-support/src/lib.rs
  tests/testsuite/alt_registry.rs
  tests/testsuite/artifact_dep.rs
  tests/testsuite/build.rs
  tests/testsuite/build_script.rs
  tests/testsuite/check.rs
  tests/testsuite/config.rs
  tests/testsuite/config_cli.rs
  tests/testsuite/config_include.rs
  tests/testsuite/dep_info.rs
  tests/testsuite/fix.rs
  tests/testsuite/install.rs
  tests/testsuite/lockfile_compat.rs
  tests/testsuite/pkgid.rs
  tests/testsuite/profile_trim_paths.rs
  tests/testsuite/registry_auth.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors

#13687 Allows the default git/gitoxide configuration to be obtained from the ENV and config
  src/cargo/core/features.rs
  src/cargo/util/context/de.rs
  tests/testsuite/config.rs
Labels: A-git, S-waiting-on-bors, A-unstable

#13997 [beta-1.79] fix(config): Ensure `--config net.git-fetch-with-cli=true` is respected
  src/cargo/util/context/mod.rs
  tests/testsuite/cargo/z_help/stdout.term.svg
  tests/testsuite/config_cli.rs
  tests/testsuite/fix.rs
Labels: A-configuration, S-waiting-on-bors

#13977 doc: Add README for resolver-tests
  crates/resolver-tests/README.md
  crates/resolver-tests/src/lib.rs
Labels: A-dependency-resolution, S-waiting-on-bors

#13993 refactor(source): Split `RecursivePathSource` out of `PathSource`
  src/cargo/core/workspace.rs
  src/cargo/ops/resolve.rs
  src/cargo/sources/git/source.rs
  src/cargo/sources/mod.rs
  src/cargo/sources/path.rs
Labels: A-git, A-workspaces, S-waiting-on-bors

#14006 fix(add): Avoid escaping double-quotes by using string literals
  Cargo.lock
  Cargo.toml
  tests/testsuite/bad_config.rs
  tests/testsuite/cargo_add/target_cfg/mod.rs
  tests/testsuite/cargo_add/target_cfg/out/Cargo.toml
  tests/testsuite/cargo_add/target_cfg/stderr.term.svg
  tests/testsuite/cargo_config/mod.rs
Labels: S-waiting-on-bors

#14004 fix(vendor): Ensure sort happens for vendor
  src/cargo/util/toml/mod.rs
  src/cargo/util/toml/targets.rs
  tests/testsuite/package.rs
  tests/testsuite/required_features.rs
  tests/testsuite/vendor.rs
Labels: A-manifest, S-waiting-on-bors

#13886 Silence the warning about forgetting the vendoring
  src/cargo/sources/replaced.rs
  src/cargo/sources/source.rs
  tests/testsuite/registry.rs
Labels: A-overrides, A-source-replacement, S-waiting-on-bors

#14013 test(semver): track the behavior of `--precise <prerelease>`
  src/cargo/util/semver_ext.rs
Labels: S-waiting-on-bors, A-semver

#14014 docs(contrib): Suggest atomic commits with separate test commits
  src/doc/contrib/src/process/working-on-cargo.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#14024 fix(lints): Add unknown_lints to lints list
  src/cargo/util/lints.rs
Labels: S-waiting-on-bors

#13809 Rename --out-dir to --artifact-dir
  src/bin/cargo/commands/build.rs
  src/cargo/core/compiler/build_config.rs
  src/cargo/core/compiler/build_runner/compilation_files.rs
  src/cargo/core/compiler/build_runner/mod.rs
  src/cargo/util/command_prelude.rs
  src/cargo/util/context/mod.rs
  src/doc/man/cargo-build.md
  src/doc/man/generated_txt/cargo-build.txt
  src/doc/src/commands/cargo-build.md
  src/doc/src/reference/unstable.md
  src/etc/man/cargo-build.1
  tests/testsuite/artifact_dir.rs
  tests/testsuite/cargo_build/help/stdout.term.svg
  tests/testsuite/collisions.rs
  tests/testsuite/main.rs
Labels: A-documenting-cargo-itself, A-configuration, A-build-execution, Command-build, Command-fix, S-waiting-on-bors, A-cli, A-layout, A-semver, A-cli-help

#14025 Add tooling to document lints
  .cargo/config.toml
  .github/workflows/main.yml
  Cargo.lock
  crates/xtask-lint-docs/Cargo.toml
  crates/xtask-lint-docs/src/main.rs
  src/cargo/util/lints.rs
  src/doc/src/SUMMARY.md
  src/doc/src/reference/index.md
  src/doc/src/reference/lints.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors, A-infrastructure

#13979 Add `cargo update --breaking`
  benches/benchsuite/benches/resolve.rs
  crates/cargo-test-support/src/compare.rs
  src/bin/cargo/commands/add.rs
  src/bin/cargo/commands/remove.rs
  src/bin/cargo/commands/update.rs
  src/cargo/core/compiler/standard_lib.rs
  src/cargo/core/summary.rs
  src/cargo/ops/cargo_clean.rs
  src/cargo/ops/cargo_compile/mod.rs
  src/cargo/ops/cargo_fetch.rs
  src/cargo/ops/cargo_install.rs
  src/cargo/ops/cargo_output_metadata.rs
  src/cargo/ops/cargo_package.rs
  src/cargo/ops/cargo_update.rs
  src/cargo/ops/fix.rs
  src/cargo/ops/mod.rs
  src/cargo/ops/resolve.rs
  src/cargo/ops/tree/mod.rs
  src/cargo/ops/vendor.rs
  src/cargo/util/toml_mut/manifest.rs
  src/cargo/util/toml_mut/mod.rs
  src/cargo/util/toml_mut/upgrade.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/cargo_update/help/stdout.term.svg
  tests/testsuite/update.rs
  triagebot.toml
Labels: A-documenting-cargo-itself, Command-clean, Command-new, Command-install, Command-metadata, Command-fetch, Command-package, Command-update, A-dependency-resolution, A-manifest, A-testing-cargo-itself, Command-fix, S-waiting-on-bors, Command-vendor, A-cli, Command-tree, Command-add, Command-remove, A-infrastructure

#14028 test(lints): Ensure unused optional dep fires for shadowed dep
  tests/testsuite/lints/unused_optional_dependencies.rs
Labels: S-waiting-on-bors

#14030 Keep lints updated
  src/cargo/util/lints.rs
Labels: S-waiting-on-bors

#13921 fix(toml): Convert warnings that `licence` and `readme` files do not exist into errors
  src/cargo/ops/cargo_package.rs
  tests/testsuite/package.rs
  tests/testsuite/publish.rs
  tests/testsuite/registry.rs
Labels: Command-package, S-waiting-on-bors

#13971 fix: using `--release/debug` and `--profile` together becomes an error
  src/bin/cargo/commands/bench.rs
  src/bin/cargo/commands/clean.rs
  src/bin/cargo/commands/install.rs
  src/bin/cargo/commands/test.rs
  src/cargo/util/command_prelude.rs
  tests/testsuite/check.rs
  tests/testsuite/profile_custom.rs
Labels: Command-test, Command-clean, Command-install, Command-bench, S-waiting-on-bors, A-cli

#13902 fix(toml): remove `lib.plugin` key support and make it warning
  crates/cargo-util-schemas/src/manifest/mod.rs
  src/cargo/core/manifest.rs
  src/cargo/util/toml/targets.rs
  src/doc/src/reference/cargo-targets.md
  src/doc/src/reference/environment-variables.md
  tests/testsuite/build_script.rs
  tests/testsuite/cross_compile.rs
  tests/testsuite/proc_macro.rs
  tests/testsuite/rustflags.rs
Labels: A-documenting-cargo-itself, A-manifest, S-waiting-on-bors

#14036 fix: remove `__CARGO_GITOXIDE_DISABLE_LIST_FILES` env var
  src/cargo/sources/path.rs
Labels: S-waiting-on-bors

#14037 chore(deps): update rust crate pulldown-cmark to 0.11.0
  Cargo.lock
  Cargo.toml
  crates/mdman/src/format/man.rs
  crates/mdman/src/format/text.rs
Labels: S-waiting-on-bors, A-cli-help

#14038 chore: Bump cargo-util-schemas to 0.5
  Cargo.lock
  Cargo.toml
  crates/cargo-util-schemas/Cargo.toml
Labels: S-waiting-on-bors

#13892 fix: proc-macro example from dep no longer affects feature resolution
  src/cargo/core/resolver/features.rs
  tests/testsuite/features2.rs
Labels: A-dependency-resolution, S-waiting-on-bors, A-features2, A-proc-macro

#14040 Bump to 0.82.0; update changelog
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#14041 test: migrate binary_name to snapbox
  crates/cargo-test-support/src/compare.rs
  tests/testsuite/binary_name.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors

#14042 docs(change): Don't mention non-existent workspace.badges
  CHANGELOG.md
Labels: S-waiting-on-bors

#13926 Add local registry overlays
  crates/cargo-test-support/src/lib.rs
  crates/cargo-test-support/src/registry.rs
  crates/xtask-bump-check/src/xtask.rs
  src/cargo/core/registry.rs
  src/cargo/core/workspace.rs
  src/cargo/ops/cargo_add/mod.rs
  src/cargo/ops/cargo_package.rs
  src/cargo/ops/cargo_update.rs
  src/cargo/ops/resolve.rs
  src/cargo/sources/config.rs
  src/cargo/sources/mod.rs
  src/cargo/sources/overlay.rs
  tests/testsuite/main.rs
  tests/testsuite/registry_overlay.rs
Labels: A-configuration, Command-package, Command-update, A-workspaces, A-registries, A-testing-cargo-itself, S-waiting-on-bors, Command-add, A-infrastructure

#14047 docs: Iterate on --breaking docs
  src/bin/cargo/commands/update.rs
  src/doc/man/cargo-update.md
  src/doc/man/generated_txt/cargo-update.txt
  src/doc/src/commands/cargo-update.md
  src/doc/src/reference/unstable.md
  src/etc/man/cargo-update.1
  tests/testsuite/cargo_update/help/stdout.term.svg
Labels: A-documenting-cargo-itself, Command-update, S-waiting-on-bors, A-cli, A-cli-help

#14044 test: migrate build_script_env to snapbox
  tests/testsuite/build_script_env.rs
Labels: S-waiting-on-bors

#14054 Add assert redactions
  crates/cargo-test-support/src/compare.rs
  crates/cargo-test-support/src/cross_compile.rs
  tests/testsuite/cargo_add/target/mod.rs
  tests/testsuite/cargo_add/target/out/Cargo.toml
  tests/testsuite/cargo_add/target/stderr.term.svg
  tests/testsuite/cargo_remove/invalid_target/out/Cargo.toml
  tests/testsuite/cargo_remove/invalid_target/stderr.term.svg
  tests/testsuite/cargo_remove/invalid_target_dep/mod.rs
  tests/testsuite/cargo_remove/invalid_target_dep/out/Cargo.toml
  tests/testsuite/cargo_remove/invalid_target_dep/stderr.term.svg
  tests/testsuite/cargo_remove/remove-target.in/Cargo.toml
  tests/testsuite/cargo_remove/target/mod.rs
  tests/testsuite/cargo_remove/target/out/Cargo.toml
  tests/testsuite/cargo_remove/target/stderr.term.svg
  tests/testsuite/cargo_remove/target_build/mod.rs
  tests/testsuite/cargo_remove/target_build/out/Cargo.toml
  tests/testsuite/cargo_remove/target_build/stderr.term.svg
  tests/testsuite/cargo_remove/target_dev/mod.rs
  tests/testsuite/cargo_remove/target_dev/out/Cargo.toml
  tests/testsuite/cargo_remove/target_dev/stderr.term.svg
Labels: A-testing-cargo-itself, S-waiting-on-bors

#14051 test: migrate features_are_quoted to snapbox
  tests/testsuite/shell_quoting.rs
Labels: S-waiting-on-bors

#14061 Revert #13630 as rustc ignores `-C strip` on MSVC
  src/cargo/ops/cargo_compile/mod.rs
  tests/testsuite/profiles.rs
  tests/testsuite/run.rs
Labels: S-waiting-on-bors

#14062 chore(ci): Upgrade cargo-semver-checks
  .github/workflows/main.yml
Labels: S-waiting-on-bors, A-infrastructure

#14048 Migrate a few test files to snapbox
  tests/testsuite/artifact_dep.rs
  tests/testsuite/artifact_dir.rs
  tests/testsuite/bad_config.rs
  tests/testsuite/bad_manifest_path.rs
  tests/testsuite/bench.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors

#14064 test: Redact conditional compile-fail warning
  tests/testsuite/artifact_dep.rs
Labels: S-waiting-on-bors

#14066 Fix some documentation misspellings
  src/doc/man/cargo-bench.md
  src/doc/man/cargo-metadata.md
  src/doc/man/cargo-vendor.md
  src/doc/man/generated_txt/cargo-bench.txt
  src/doc/man/generated_txt/cargo-metadata.txt
  src/doc/man/generated_txt/cargo-vendor.txt
  src/doc/src/commands/cargo-bench.md
  src/doc/src/commands/cargo-metadata.md
  src/doc/src/commands/cargo-vendor.md
  src/doc/src/reference/unstable.md
  src/etc/man/cargo-bench.1
  src/etc/man/cargo-metadata.1
  src/etc/man/cargo-vendor.1
Labels: A-documenting-cargo-itself, S-waiting-on-bors, A-cli-help

#14067 Update git2 for libgit2 1.8.1
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#14074 Change verification order during packaging.
  src/cargo/ops/cargo_package.rs
  src/cargo/ops/registry/publish.rs
  tests/testsuite/alt_registry.rs
  tests/testsuite/cargo_features.rs
  tests/testsuite/cross_publish.rs
  tests/testsuite/features_namespaced.rs
  tests/testsuite/inheritable_workspace_fields.rs
  tests/testsuite/package.rs
  tests/testsuite/publish.rs
  tests/testsuite/publish_lockfile.rs
  tests/testsuite/registry.rs
  tests/testsuite/source_replacement.rs
  tests/testsuite/weak_dep_features.rs
Labels: Command-publish, A-interacts-with-crates.io, Command-package, S-waiting-on-bors

#14075 Use `std::fs::absolute` instead of reimplementing it
  src/cargo/util/mod.rs
Labels: S-waiting-on-bors

#14079 test: Migrate tests/testsuite/co*.rs to snapbox
  tests/testsuite/collisions.rs
  tests/testsuite/concurrent.rs
  tests/testsuite/config.rs
  tests/testsuite/config_cli.rs
  tests/testsuite/config_include.rs
  tests/testsuite/corrupt_git.rs
Labels: S-waiting-on-bors

#14060 test: migrate help to snapbox
  tests/testsuite/help.rs
Labels: S-waiting-on-bors

#14078 Remove `run_expect_error` to avoid tests incorrectly passing
  crates/cargo-test-support/src/lib.rs
  tests/testsuite/check_cfg.rs
  tests/testsuite/freshness.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors

#14080 test: migrate minimal_versions to snapbox
  tests/testsuite/minimal_versions.rs
Labels: S-waiting-on-bors

#14082 test: migrate timings_works to snapbox
  tests/testsuite/member_discovery.rs
  tests/testsuite/timings.rs
Labels: S-waiting-on-bors

#14087 test: migrate `git_(gc|shallow)` to snapbox
  tests/testsuite/git_gc.rs
  tests/testsuite/git_shallow.rs
Labels: S-waiting-on-bors

#14088 refactor: 1.79 cleanup
  Cargo.lock
  Cargo.toml
  crates/cargo-test-macro/Cargo.toml
  crates/cargo-test-support/Cargo.toml
  crates/xtask-bump-check/src/xtask.rs
  tests/testsuite/check_cfg.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors, A-infrastructure

#14018 fix(fix): Address problems with implicit -> explicit feature migration
  src/cargo/ops/fix.rs
  tests/testsuite/fix.rs
Labels: Command-fix, S-waiting-on-bors

#14090 remove some legacy public dependency code from the resolver
  src/cargo/core/resolver/conflict_cache.rs
  src/cargo/core/resolver/errors.rs
  src/cargo/core/resolver/mod.rs
  src/cargo/core/resolver/types.rs
Labels: A-dependency-resolution, S-waiting-on-bors

#14094 test: migrate tree and tree_graph_features to snapbox
  tests/testsuite/tree.rs
  tests/testsuite/tree_graph_features.rs
Labels: S-waiting-on-bors

#14099 test: prefer raw string for regex reduction
  crates/cargo-test-support/src/compare.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors

#14098 test: migrate rustdoc and rustdocflags to snapbox
  tests/testsuite/rustdoc.rs
  tests/testsuite/rustdocflags.rs
Labels: S-waiting-on-bors

#14103 test: Migrate `pub_priv.rs` to snapshot
  tests/testsuite/pub_priv.rs
Labels: S-waiting-on-bors

#14089 Simplify checking for dependency cycles
  src/cargo/core/resolver/mod.rs
  src/cargo/core/resolver/resolve.rs
  src/cargo/util/graph.rs
Labels: A-dependency-resolution, S-waiting-on-bors

#14093 test: migrate `cargo_alias_config&cargo_config/mod` to snapbox
  tests/testsuite/cargo_alias_config.rs
  tests/testsuite/cargo_config/mod.rs
Labels: S-waiting-on-bors

#14092 Add `CodeFix::apply_solution` and impl `Clone`
  Cargo.lock
  crates/rustfix/Cargo.toml
  crates/rustfix/src/lib.rs
Labels: Command-fix, S-waiting-on-bors

#14110 fix(toml): Warn when edition is unuset, even when MSRV is unset
  src/cargo/util/toml/mod.rs
  tests/testsuite/artifact_dep.rs
  tests/testsuite/edition.rs
  tests/testsuite/shell_quoting.rs
Labels: A-manifest, S-waiting-on-bors

#14107 Make `-Cmetadata` consistent across platforms
  src/cargo/core/compiler/build_runner/compilation_files.rs
Labels: S-waiting-on-bors, A-layout

#14091 test: migrate testsuites to snapbox
  tests/testsuite/death.rs
  tests/testsuite/message_format.rs
  tests/testsuite/precise_pre_release.rs
  tests/testsuite/verify_project.rs
  tests/testsuite/version.rs
Labels: S-waiting-on-bors

#14106 Simplify checking feature syntax
  src/cargo/core/summary.rs
Labels: S-waiting-on-bors

#14104 test: migrate lints_table and lints/(mod|unknown_lints) to snapbox
  tests/testsuite/lints/mod.rs
  tests/testsuite/lints/unknown_lints.rs
  tests/testsuite/lints_table.rs
Labels: S-waiting-on-bors

#14121 test: Auto-redact file number
  crates/cargo-test-support/src/compare.rs
  tests/testsuite/alt_registry.rs
  tests/testsuite/artifact_dep.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors

#14123 fix(test): Un-redact Packaged files
  crates/cargo-test-support/src/compare.rs
  tests/testsuite/alt_registry.rs
  tests/testsuite/artifact_dep.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors

#14119 test: migrate unit_graph, update and vendor to snapbox
  tests/testsuite/unit_graph.rs
  tests/testsuite/update.rs
  tests/testsuite/vendor.rs
Labels: S-waiting-on-bors

#14068 test: migrate build to snapbox
  tests/testsuite/build.rs
Labels: S-waiting-on-bors

#14124 test: Add auto-redaction for not found error
  crates/cargo-test-support/src/compare.rs
  tests/testsuite/config_include.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors

#14100 test: migrate features and features(2|_namespaced) to snapbox
  tests/testsuite/features.rs
  tests/testsuite/features2.rs
  tests/testsuite/features_namespaced.rs
Labels: S-waiting-on-bors

#14111 test: migrate weak_dep_features, workspaces and yank to snapbox
  tests/testsuite/weak_dep_features.rs
  tests/testsuite/workspaces.rs
  tests/testsuite/yank.rs
Labels: S-waiting-on-bors

#14127 test: migrate rename_deps, replace, required_features and run to snapbox
  tests/testsuite/rename_deps.rs
  tests/testsuite/replace.rs
  tests/testsuite/required_features.rs
  tests/testsuite/run.rs
Labels: S-waiting-on-bors

#14126 test: migrate rustflags, rustup and script to snapbox
  crates/cargo-test-support/src/compare.rs
  tests/testsuite/rustflags.rs
  tests/testsuite/rustup.rs
  tests/testsuite/script.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors

#14109 test: migrate path and paths to snapbox
  tests/testsuite/path.rs
  tests/testsuite/paths.rs
Labels: S-waiting-on-bors

#14128 test: migrate profile* to snapbox
  tests/testsuite/profile_config.rs
  tests/testsuite/profile_custom.rs
  tests/testsuite/profile_overrides.rs
  tests/testsuite/profile_targets.rs
  tests/testsuite/profile_trim_paths.rs
  tests/testsuite/profiles.rs
Labels: S-waiting-on-bors

#14122 deps: dont use tracing-attributes for workspace, use for cargo only
  Cargo.toml
Labels: S-waiting-on-bors

#14135 Change tests to support `rustc` wording changes
  tests/testsuite/check.rs
  tests/testsuite/message_format.rs
  tests/testsuite/metabuild.rs
  tests/testsuite/replace.rs
Labels: S-waiting-on-bors

#14133 docs: remove stray comment
  src/cargo/core/resolver/encode.rs
Labels: A-dependency-resolution, S-waiting-on-bors, A-lockfile

#14138 test: migrate offline, open_namespaces and owner to snapbox
  tests/testsuite/offline.rs
  tests/testsuite/open_namespaces.rs
  tests/testsuite/owner.rs
Labels: S-waiting-on-bors

#14142 test: omit target-dir name
  tests/testsuite/publish_lockfile.rs
Labels: S-waiting-on-bors

#14144 Docs: Fix curly quotes in config docs.
  src/doc/src/reference/config.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#14146 Docs: Remove duplicate `strip` section.
  src/doc/src/reference/config.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#14143 test: migrate `dep_info/diagnostics/direct_minimal_versions` to snapbox
  tests/testsuite/dep_info.rs
  tests/testsuite/diagnostics.rs
  tests/testsuite/direct_minimal_versions.rs
Labels: S-waiting-on-bors

#14145 Docs: Update config summary to include missing keys.
  src/doc/src/reference/config.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#14151 test: migrate search, source_replacement and standard_lib to snapbox
  tests/testsuite/search.rs
  tests/testsuite/source_replacement.rs
  tests/testsuite/standard_lib.rs
Labels: S-waiting-on-bors

#14153 Allow `unexpected_builtin_cfgs` lint in `user_specific_cfgs` test
  tests/testsuite/build.rs
Labels: S-waiting-on-bors

#14096 test: migrate clean to snapbox
  tests/testsuite/clean.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors

#14049 More `update --breaking` tests
  src/cargo/ops/cargo_update.rs
  src/cargo/util/toml_mut/upgrade.rs
  tests/testsuite/update.rs
Labels: Command-update, A-manifest, S-waiting-on-bors

#14130 test: migrate package* and publish* to snapbox
  crates/cargo-test-support/src/compare.rs
  tests/testsuite/package.rs
  tests/testsuite/package_features.rs
  tests/testsuite/publish.rs
  tests/testsuite/publish_lockfile.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors

#14160 gix: remove `revision` feature from cargo
  Cargo.toml
Labels: S-waiting-on-bors

#14149 test: migrate registry and registry_auth to snapbox
  tests/testsuite/registry.rs
  tests/testsuite/registry_auth.rs
Labels: S-waiting-on-bors

#14158 test: migrate some files to snapbox
  tests/testsuite/local_registry.rs
  tests/testsuite/locate_project.rs
  tests/testsuite/lockfile_compat.rs
  tests/testsuite/login.rs
  tests/testsuite/logout.rs
Labels: S-waiting-on-bors

#14159 test: Migrate git to snapbox
  crates/cargo-test-support/src/compare.rs
  tests/testsuite/git.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors

#14164 Document `CARGO_CFG_TARGET_ABI`
  src/doc/src/reference/environment-variables.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#14165 Make it clear that `CARGO_CFG_TARGET_FAMILY` is multi-valued
  src/doc/src/reference/environment-variables.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#14166 test: replace glob with explicit unordered calls
  tests/testsuite/features.rs
Labels: S-waiting-on-bors

#14167 test: fix several assertions
  tests/testsuite/git.rs
  tests/testsuite/publish_lockfile.rs
Labels: S-waiting-on-bors

#14132 test: Migrate some files to snapbox
  tests/testsuite/credential_process.rs
  tests/testsuite/cross_compile.rs
  tests/testsuite/cross_publish.rs
  tests/testsuite/custom_target.rs
Labels: S-waiting-on-bors
