Repository rust-lang/cargo, pull requests merged in 2024-11, with the labels that each got.

#14750 fix(util): Respect all `..`s in `normalize_path`
  crates/cargo-util/src/paths.rs
Labels: S-waiting-on-bors

#14765 test(rustfix): switch to a simpler case for dedup-suggestions
  crates/rustfix/tests/everything/dedup-suggestions.fixed.rs
  crates/rustfix/tests/everything/dedup-suggestions.json
  crates/rustfix/tests/everything/dedup-suggestions.rs
  tests/testsuite/fix.rs
Labels: Command-fix, S-waiting-on-bors

#14761 Add more metadata to `rustc_fingerprint`
  src/cargo/util/rustc.rs
Labels: S-waiting-on-bors, A-cache-messages

#14772 chore: update handlebars to v6, fix build error
  Cargo.lock
  Cargo.toml
  crates/mdman/src/hbs.rs
Labels: S-waiting-on-bors, A-cli-help

#14773 doc: fix `GlobalContext` reference
  src/doc/contrib/src/implementation/console.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#14747 Add transactional semantics to `rustfix`
  Cargo.lock
  Cargo.toml
  crates/rustfix/Cargo.toml
  crates/rustfix/src/error.rs
  crates/rustfix/src/lib.rs
  crates/rustfix/src/replace.rs
Labels: Command-fix, S-waiting-on-bors

#14777 Enable transfer feature in triagebot
  triagebot.toml
Labels: S-waiting-on-bors, A-infrastructure

#14781 test: Update some emaining unordered tests to snapbox
  tests/testsuite/clean.rs
  tests/testsuite/freshness.rs
  tests/testsuite/freshness_checksum.rs
Labels: S-waiting-on-bors

#14782 rustfix: replace special-case duplicate handling with error
  crates/rustfix/src/error.rs
  crates/rustfix/src/lib.rs
  crates/rustfix/src/replace.rs
  src/cargo/ops/fix.rs
Labels: Command-fix, S-waiting-on-bors

#14497 Normalize the `target` paths
  src/cargo/util/toml/mod.rs
  src/cargo/util/toml/targets.rs
  tests/testsuite/binary_name.rs
Labels: A-manifest, S-waiting-on-bors, Command-vendor

#14785 test(gc): Update remaining unordered tests to snapbox
  crates/cargo-test-support/src/compare.rs
  crates/cargo-test-support/src/diff.rs
  crates/cargo-test-support/src/lib.rs
  tests/testsuite/global_cache_tracker.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors

#14790 fix(test): Make redactions consistent with snapbox
  Cargo.lock
  Cargo.toml
  crates/cargo-test-support/src/compare.rs
  crates/cargo-test-support/src/lib.rs
  tests/testsuite/artifact_dep.rs
  tests/testsuite/check_cfg.rs
  tests/testsuite/test.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors

#14793 docs(test): Document Execs assertions based on port effort
  crates/cargo-test-support/src/compare.rs
  crates/cargo-test-support/src/lib.rs
  tests/testsuite/artifact_dep.rs
  tests/testsuite/build.rs
  tests/testsuite/build_script.rs
  tests/testsuite/build_script_extra_link_arg.rs
  tests/testsuite/cache_messages.rs
  tests/testsuite/cargo_command.rs
  tests/testsuite/check.rs
  tests/testsuite/check_cfg.rs
  tests/testsuite/collisions.rs
  tests/testsuite/features2.rs
  tests/testsuite/fetch.rs
  tests/testsuite/fix.rs
  tests/testsuite/future_incompat_report.rs
  tests/testsuite/git_auth.rs
  tests/testsuite/install.rs
  tests/testsuite/lto.rs
  tests/testsuite/message_format.rs
  tests/testsuite/metabuild.rs
  tests/testsuite/offline.rs
  tests/testsuite/package.rs
  tests/testsuite/package_features.rs
  tests/testsuite/profile_config.rs
  tests/testsuite/profile_overrides.rs
  tests/testsuite/profile_targets.rs
  tests/testsuite/profile_trim_paths.rs
  tests/testsuite/profiles.rs
  tests/testsuite/progress.rs
  tests/testsuite/publish.rs
  tests/testsuite/rustc.rs
  tests/testsuite/rustc_info_cache.rs
  tests/testsuite/rustdoc_extern_html.rs
  tests/testsuite/search.rs
  tests/testsuite/standard_lib.rs
  tests/testsuite/test.rs
  tests/testsuite/warn_on_failure.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors

#14718 Switch CI from bors to merge queue
  .github/workflows/main.yml
Labels: S-waiting-on-review, A-infrastructure

#14799 Revert "feat: Add `CARGO_RUSTC_CURRENT_DIR`"
  src/cargo/core/compiler/mod.rs
  src/doc/src/reference/environment-variables.md
  tests/testsuite/build.rs
Labels: A-documenting-cargo-itself, A-build-execution, S-waiting-on-review

#14388 feat(warnings): add build.warnings option
  src/cargo/core/compiler/compilation.rs
  src/cargo/core/compiler/job_queue/mod.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/core/features.rs
  src/cargo/ops/cargo_compile/mod.rs
  src/cargo/util/context/mod.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/cargo/z_help/stdout.term.svg
  tests/testsuite/main.rs
  tests/testsuite/warning_override.rs
Labels: A-documenting-cargo-itself, A-configuration, A-build-execution, A-workspaces, S-waiting-on-review, A-unstable

#14803 test: adjust `cargo_test_env` to unblock rust submodule update
  tests/testsuite/test.rs
Labels: S-waiting-on-review

#14805 fix(docs): typo in cargo-fmt.md
  src/doc/src/commands/cargo-fmt.md
Labels: A-documenting-cargo-itself, S-waiting-on-review

#14808 refactor: clone-on-write when needed for InternedString
  src/cargo/util/interning.rs
Labels: S-waiting-on-review

#14605 git: do not validate submodules of fresh checkouts
  src/cargo/sources/git/utils.rs
  tests/testsuite/git.rs
Labels: A-git, S-waiting-on-review

#14796 chore(ci): Check for clippy `correctness`
  Cargo.toml
  crates/cargo-util-schemas/src/manifest/mod.rs
  crates/rustfix/src/replace.rs
  src/cargo/core/resolver/dep_cache.rs
  src/cargo/util/mod.rs
  src/cargo/util/toml/mod.rs
Labels: A-dependency-resolution, A-manifest, Command-fix, S-waiting-on-review

#14786 Migrate build-rs to the Cargo repo
  Cargo.lock
  Cargo.toml
  crates/build-rs-test-lib/Cargo.toml
  crates/build-rs-test-lib/build.rs
  crates/build-rs-test-lib/src/lib.rs
  crates/build-rs/Cargo.toml
  crates/build-rs/README.md
  crates/build-rs/src/allow_use.rs
  crates/build-rs/src/ident.rs
  crates/build-rs/src/input.rs
  crates/build-rs/src/lib.rs
  crates/build-rs/src/output.rs
  crates/xtask-bump-check/src/xtask.rs
  src/doc/contrib/src/team.md
Labels: A-documenting-cargo-itself, S-waiting-on-review, A-infrastructure

#14812 feat(rustdoc): diplay env vars in extra verbose mode
  src/cargo/core/compiler/compilation.rs
  tests/testsuite/profile_targets.rs
Labels: A-build-execution, S-waiting-on-review

#14817 fix(build-rs)!: Updates from an audit
  crates/build-rs-test-lib/build.rs
  crates/build-rs/src/allow_use.rs
  crates/build-rs/src/input.rs
  crates/build-rs/src/output.rs
Labels: S-waiting-on-review

#14815 Always include Cargo.lock in published crates
  src/cargo/core/package.rs
  src/cargo/ops/cargo_package.rs
  src/cargo/sources/path.rs
  tests/testsuite/artifact_dep.rs
  tests/testsuite/cargo_features.rs
  tests/testsuite/credential_process.rs
  tests/testsuite/features2.rs
  tests/testsuite/features_namespaced.rs
  tests/testsuite/git.rs
  tests/testsuite/package.rs
  tests/testsuite/publish.rs
  tests/testsuite/publish_lockfile.rs
  tests/testsuite/registry_auth.rs
  tests/testsuite/source_replacement.rs
  tests/testsuite/weak_dep_features.rs
Labels: Command-package, S-waiting-on-review

#14754 feat(resolver): Stabilize resolver v3
  src/cargo/util/toml/mod.rs
  src/doc/src/reference/config.md
  src/doc/src/reference/resolver.md
  tests/testsuite/rust_version.rs
Labels: A-documenting-cargo-itself, relnotes, T-cargo, A-manifest, finished-final-comment-period, disposition-merge, S-waiting-on-review, to-announce

#14825 Simplify English used in guide
  src/doc/src/guide/dependencies.md
  src/doc/src/guide/why-cargo-exists.md
Labels: A-documenting-cargo-itself, S-waiting-on-review

#14827 docs(unstable): Move -Zwarnings from stable to unstable section
  src/doc/src/reference/unstable.md
Labels: A-documenting-cargo-itself, S-waiting-on-review

#14792 fix(toml): Update frontmatter parser for RFC 3503
  src/cargo/util/toml/embedded.rs
Labels: S-waiting-on-review

#14826 refactor(fingerprint): Track the intent for each use of `UnitHash`
  src/cargo/core/compiler/build_runner/compilation_files.rs
  src/cargo/core/compiler/build_runner/mod.rs
  src/cargo/core/compiler/compilation.rs
  src/cargo/core/compiler/custom_build.rs
  src/cargo/core/compiler/job_queue/mod.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/ops/cargo_test.rs
Labels: Command-test, A-build-execution, A-build-scripts, S-waiting-on-review, A-layout

#14829 you we distinction
  src/doc/src/guide/cargo-toml-vs-cargo-lock.md
  src/doc/src/guide/creating-a-new-project.md
  src/doc/src/guide/dependencies.md
  src/doc/src/guide/tests.md
  src/doc/src/guide/why-cargo-exists.md
Labels: A-documenting-cargo-itself, S-waiting-on-review

#14806 fix(): error context for git_fetch refspec not found
  src/cargo/sources/git/utils.rs
  tests/testsuite/git.rs
Labels: A-git, A-diagnostics, S-waiting-on-review

#14836 docs(unstable): Link to -Zwarnings issue, tracking issue
  src/doc/src/reference/unstable.md
Labels: A-documenting-cargo-itself, S-waiting-on-review

#14839 Docs for optional registry JSON fields
  src/doc/src/reference/registry-index.md
Labels: A-documenting-cargo-itself, S-waiting-on-review

#14842 Clarify how `cargo::metadata` env var is selected
  src/doc/src/reference/build-scripts.md
Labels: A-documenting-cargo-itself, S-waiting-on-review

#14845 chore: remove bors mentions
  .github/PULL_REQUEST_TEMPLATE.md
  ci/validate-version-bump.sh
  src/doc/contrib/src/process/index.md
  src/doc/contrib/src/process/working-on-cargo.md
  src/doc/contrib/src/team.md
Labels: A-documenting-cargo-itself, S-waiting-on-review, A-infrastructure

#14846 test(rustflags): Verify -Cmetadata directly, not through -Cextra-filename
  crates/cargo-test-support/src/lib.rs
  tests/testsuite/build.rs
  tests/testsuite/build_script.rs
  tests/testsuite/config.rs
  tests/testsuite/future_incompat_report.rs
  tests/testsuite/metadata.rs
  tests/testsuite/open_namespaces.rs
  tests/testsuite/package.rs
  tests/testsuite/pkgid.rs
  tests/testsuite/precise_pre_release.rs
  tests/testsuite/pub_priv.rs
  tests/testsuite/registry.rs
  tests/testsuite/rustflags.rs
  tests/testsuite/test.rs
Labels: A-testing-cargo-itself, S-waiting-on-review

#14848 test: Switch from 'exec_with_output' to 'run'
  tests/testsuite/build.rs
  tests/testsuite/cache_messages.rs
  tests/testsuite/cargo_command.rs
  tests/testsuite/check.rs
  tests/testsuite/freshness.rs
  tests/testsuite/freshness_checksum.rs
  tests/testsuite/future_incompat_report.rs
  tests/testsuite/git.rs
  tests/testsuite/help.rs
  tests/testsuite/lto.rs
  tests/testsuite/package.rs
  tests/testsuite/pkgid.rs
  tests/testsuite/registry_auth.rs
  tests/testsuite/vendor.rs
Labels: S-waiting-on-review

#14847 fix(publish): Allow dry-run of a non-bumped workspace
  src/cargo/sources/overlay.rs
  tests/testsuite/package.rs
  tests/testsuite/registry_overlay.rs
Labels: S-waiting-on-review

#14183 Check build target supports std when building with -Zbuild-std=std
  src/cargo/core/compiler/build_context/target_info.rs
  src/cargo/core/compiler/standard_lib.rs
  tests/testsuite/standard_lib.rs
Labels: S-waiting-on-review, Z-build-std, A-cfg-expr

#14853 chore: move supports-unicode to workspace deps
  Cargo.toml
Labels: S-waiting-on-review

#14855 test: address test output nondeterminism
  tests/testsuite/freshness.rs
  tests/testsuite/freshness_checksum.rs
  tests/testsuite/registry_overlay.rs
Labels: S-waiting-on-review

#14854 Improve error handling when PathSource is relative
  src/cargo/util/toml_mut/dependency.rs
Labels: A-manifest, S-waiting-on-review

#14850 fix(build-std): always link to std when testing proc-macros
  src/cargo/core/compiler/compilation.rs
  tests/build-std/main.rs
Labels: A-build-execution, S-waiting-on-review, Z-build-std, A-proc-macro

#14860 git-fetch-with-cli: Set `GIT_DIR` for bare repository compatibility
  src/cargo/sources/git/utils.rs
Labels: A-git, S-waiting-on-review

#14859 test(pgo): ensure PGO works
  tests/testsuite/main.rs
  tests/testsuite/pgo.rs
Labels: S-waiting-on-review

#14861 test(build-std): download deps first
  tests/build-std/main.rs
Labels: S-waiting-on-review

#14671 Add future-incompat warning against keywords in cfgs and add raw-idents
  Cargo.lock
  Cargo.toml
  crates/cargo-platform/Cargo.toml
  crates/cargo-platform/src/cfg.rs
  crates/cargo-platform/src/lib.rs
  crates/cargo-platform/tests/test_cfg.rs
  src/cargo/core/compiler/custom_build.rs
  src/cargo/util/context/target.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/cfg.rs
Labels: A-build-scripts, T-cargo, A-manifest, finished-final-comment-period, disposition-merge, S-waiting-on-review, A-cfg-expr, to-announce

#14864 fix(fix): Migrate cargo script manifests across editions
  src/cargo/ops/fix.rs
  tests/testsuite/edition.rs
  tests/testsuite/fix.rs
  tests/testsuite/publish.rs
Labels: Command-fix, S-waiting-on-review

#14875 test: `requires` attribute accepts string literals for cmds
  Cargo.lock
  Cargo.toml
  crates/cargo-test-macro/Cargo.toml
  crates/cargo-test-macro/src/lib.rs
  tests/testsuite/cargo_init/simple_hg/mod.rs
  tests/testsuite/git.rs
  tests/testsuite/git_gc.rs
  tests/testsuite/new.rs
  tests/testsuite/profile_trim_paths.rs
Labels: A-testing-cargo-itself, S-waiting-on-review
