Repository rust-lang/cargo, pull requests merged in 2024-02, with the labels that each got.

#13382 Change tests to support changes to suggestion
  tests/testsuite/fix.rs
  tests/testsuite/messages.rs
Labels: S-waiting-on-bors

#13383 Add `docsrs` cfg as a well known `--check-cfg`
  src/cargo/core/compiler/mod.rs
  tests/testsuite/check_cfg.rs
Labels: A-build-execution, S-waiting-on-bors

#13385 Ensure `nonzero_exit_code` test isn't affected by developers `RUST_BACKTRACE` setting
  tests/testsuite/test.rs
Labels: S-waiting-on-bors

#13387 Don't print rustdoc command lines on failure by default
  src/cargo/core/compiler/mod.rs
  tests/testsuite/doc.rs
Labels: A-build-execution, S-waiting-on-bors

#13388 Apply `-Zpanic-abort-tests` to doctests too
  src/cargo/ops/cargo_test.rs
  tests/testsuite/test.rs
Labels: Command-test, S-waiting-on-bors

#13390 doc: `[package]` doesn't require `version` field
  src/doc/src/reference/manifest.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#13392 Bump to 0.79.0; update changelog
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#13393 [beta-1.77.0] Fix panic on empty spans when parsing Cargo.toml
  Cargo.lock
  Cargo.toml
  src/cargo/util/toml/mod.rs
  tests/build-std/main.rs
  tests/testsuite/custom_target.rs
  tests/testsuite/diagnostics.rs
  tests/testsuite/main.rs
Labels: A-manifest, S-waiting-on-bors

#13396 docs(changelog): Slight cleanup
  CHANGELOG.md
Labels: S-waiting-on-bors

#13372 feat(update): Tell users when they are still behind
  crates/cargo-test-support/src/compare.rs
  src/cargo/ops/cargo_generate_lockfile.rs
  tests/testsuite/git.rs
  tests/testsuite/local_registry.rs
  tests/testsuite/patch.rs
  tests/testsuite/registry.rs
  tests/testsuite/replace.rs
  tests/testsuite/update.rs
Labels: Command-generate-lockfile, A-testing-cargo-itself, S-waiting-on-bors

#13398 Remove `package.documentation` from the “before publishing” list.
  src/doc/src/reference/publishing.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#13400 Fix markdown line break in cargo-add
  src/doc/man/cargo-add.md
  src/doc/src/commands/cargo-add.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#13391 Don't add the new package to workspace.members if there is no existing workspace in Cargo.toml.
  src/cargo/ops/cargo_new.rs
  tests/testsuite/cargo_new/add_members_to_non_workspace/in/Cargo.toml
  tests/testsuite/cargo_new/add_members_to_non_workspace/in/src/main.rs
  tests/testsuite/cargo_new/add_members_to_non_workspace/mod.rs
  tests/testsuite/cargo_new/add_members_to_non_workspace/out/Cargo.toml
  tests/testsuite/cargo_new/add_members_to_non_workspace/out/bar/Cargo.toml
  tests/testsuite/cargo_new/add_members_to_non_workspace/out/bar/src/lib.rs
  tests/testsuite/cargo_new/add_members_to_non_workspace/out/src/main.rs
  tests/testsuite/cargo_new/add_members_to_non_workspace/stderr.log
  tests/testsuite/cargo_new/add_members_to_non_workspace/stdout.log
  tests/testsuite/cargo_new/add_members_to_workspace_without_members/in/Cargo.toml
  tests/testsuite/cargo_new/add_members_to_workspace_without_members/in/src/main.rs
  tests/testsuite/cargo_new/add_members_to_workspace_without_members/mod.rs
  tests/testsuite/cargo_new/add_members_to_workspace_without_members/out/Cargo.toml
  tests/testsuite/cargo_new/add_members_to_workspace_without_members/out/bar/Cargo.toml
  tests/testsuite/cargo_new/add_members_to_workspace_without_members/out/bar/src/lib.rs
  tests/testsuite/cargo_new/add_members_to_workspace_without_members/out/src/main.rs
  tests/testsuite/cargo_new/add_members_to_workspace_without_members/stderr.log
  tests/testsuite/cargo_new/add_members_to_workspace_without_members/stdout.log
  tests/testsuite/cargo_new/mod.rs
Labels: Command-new, S-waiting-on-bors

#13410 fix: Switch more notes/warnings to lowercase
  src/cargo/core/compiler/fingerprint/dirty_reason.rs
  src/cargo/ops/cargo_compile/unit_generator.rs
  src/cargo/ops/cargo_package.rs
  src/cargo/ops/registry/publish.rs
  src/cargo/util/config/mod.rs
  tests/testsuite/alt_registry.rs
  tests/testsuite/artifact_dep.rs
  tests/testsuite/cargo_features.rs
  tests/testsuite/cargo_targets.rs
  tests/testsuite/config.rs
  tests/testsuite/credential_process.rs
  tests/testsuite/cross_publish.rs
  tests/testsuite/features_namespaced.rs
  tests/testsuite/inheritable_workspace_fields.rs
  tests/testsuite/publish.rs
  tests/testsuite/registry_auth.rs
  tests/testsuite/required_features.rs
  tests/testsuite/source_replacement.rs
  tests/testsuite/tool_paths.rs
  tests/testsuite/weak_dep_features.rs
Labels: A-configuration, Command-publish, A-interacts-with-crates.io, Command-package, A-rebuild-detection, S-waiting-on-bors, A-cargo-targets

#13412 Update git2
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#13416 test: disable lldb test as it requires privileges to run on macOS
  tests/testsuite/profile_trim_paths.rs
Labels: S-waiting-on-bors

#13415 Relax a test to permit warnings to be emitted, too.
  tests/testsuite/fix.rs
Labels: S-waiting-on-bors

#13402 fix: Don't duplicate comments when editing TOML
  Cargo.lock
  Cargo.toml
  src/cargo/util/config/mod.rs
Labels: A-configuration, S-waiting-on-bors

#13417 [Beta-1.77] Update libgit2
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#13411 feat: Add hint for adding members to workspace
  src/cargo/ops/cargo_new.rs
  tests/testsuite/cargo_init/workspace_add_member/stderr.log
  tests/testsuite/cargo_new/add_members_to_non_workspace/stderr.log
  tests/testsuite/cargo_new/add_members_to_workspace_format_previous_items/stderr.log
  tests/testsuite/cargo_new/add_members_to_workspace_format_sorted/stderr.log
  tests/testsuite/cargo_new/add_members_to_workspace_with_absolute_package_path/stderr.log
  tests/testsuite/cargo_new/add_members_to_workspace_with_empty_members/stderr.log
  tests/testsuite/cargo_new/add_members_to_workspace_without_members/stderr.log
  tests/testsuite/workspaces.rs
Labels: Command-new, S-waiting-on-bors

#13419 chore: update to `jobserver` 0.1.28
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#13421 chore(bump-check): include rustfix and cargo-util-schemas
  crates/xtask-bump-check/src/xtask.rs
Labels: S-waiting-on-bors, A-infrastructure

#13424 fix(test-support): remove special case for `$message_type`
  crates/cargo-test-support/src/compare.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors

#13425 docs(changelog): Clarify lints in virtual workspace error
  CHANGELOG.md
Labels: S-waiting-on-bors

#13429 Enable edition migration for 2024
  src/cargo/core/features.rs
Labels: S-waiting-on-bors, A-unstable

#13433 Fix confusing error messages for sparse index replaced source
  src/cargo/sources/replaced.rs
  tests/testsuite/credential_process.rs
  tests/testsuite/registry.rs
Labels: A-overrides, A-source-replacement, S-waiting-on-bors

#13435 Fix old_cargos tests
  tests/testsuite/old_cargos.rs
Labels: S-waiting-on-bors

#13436 docs: Minor clarification of build script metadata.
  src/doc/src/reference/build-scripts.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#13444 Update tests for changes in latest nightly
  tests/build-std/main.rs
  tests/testsuite/custom_target.rs
  tests/testsuite/future_incompat_report.rs
Labels: S-waiting-on-bors

#13434 fix(add): Ensure users know a feature is being created
  src/cargo/ops/cargo_add/mod.rs
  tests/testsuite/cargo_add/change_rename_target/stderr.log
  tests/testsuite/cargo_add/detect_workspace_inherit_optional/stderr.log
  tests/testsuite/cargo_add/optional/stderr.log
  tests/testsuite/cargo_add/overwrite_git_with_path/stderr.log
  tests/testsuite/cargo_add/overwrite_inherit_optional_noop/stderr.log
  tests/testsuite/cargo_add/overwrite_name_noop/stderr.log
  tests/testsuite/cargo_add/overwrite_no_optional_with_optional/stderr.log
  tests/testsuite/cargo_add/overwrite_optional/stderr.log
  tests/testsuite/cargo_add/overwrite_path_noop/stderr.log
  tests/testsuite/cargo_add/overwrite_path_with_version/stderr.log
  tests/testsuite/cargo_add/overwrite_rename_with_rename_noop/stderr.log
  tests/testsuite/cargo_add/overwrite_version_with_git/stderr.log
  tests/testsuite/cargo_add/overwrite_version_with_path/stderr.log
Labels: S-waiting-on-bors, Command-add

#13442 chore(ci): Drop MSRV:1 patch field
  .github/renovate.json5
Labels: S-waiting-on-bors, A-infrastructure

#13448 fix(test): Suggest `--` for libtest arguments
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#13449 chore(deps): update openssl to 3.2.1 again
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#13452 [beta-1.77] chore: update jobserver to 0.1.28
  Cargo.lock
  Cargo.toml
  tests/build-std/main.rs
  tests/testsuite/custom_target.rs
  tests/testsuite/fix.rs
  tests/testsuite/future_incompat_report.rs
  tests/testsuite/messages.rs
Labels: S-waiting-on-bors

#13455 Remove unnecessary `use` statement in metabuild
  src/cargo/core/compiler/custom_build.rs
Labels: A-build-scripts, S-waiting-on-bors

#13459 chore(ci): bump CI tools
  .github/workflows/contrib.yml
  .github/workflows/main.yml
Labels: S-waiting-on-bors, A-infrastructure

#12861 feat: respect `rust-version` when generating lockfile
  benches/benchsuite/benches/resolve.rs
  crates/cargo-util-schemas/src/manifest.rs
  crates/resolver-tests/src/lib.rs
  src/cargo/core/compiler/standard_lib.rs
  src/cargo/core/resolver/mod.rs
  src/cargo/core/resolver/resolve.rs
  src/cargo/ops/cargo_compile/mod.rs
  src/cargo/ops/cargo_generate_lockfile.rs
  src/cargo/ops/cargo_output_metadata.rs
  src/cargo/ops/cargo_package.rs
  src/cargo/ops/fix.rs
  src/cargo/ops/lockfile.rs
  src/cargo/ops/resolve.rs
  src/cargo/ops/tree/mod.rs
  tests/testsuite/lockfile_compat.rs
Labels: Command-metadata, Command-generate-lockfile, Command-package, A-dependency-resolution, T-cargo, A-manifest, A-testing-cargo-itself, Command-fix, finished-final-comment-period, disposition-merge, S-waiting-on-bors, A-lockfile, Command-tree, to-announce

#13464 Fix redundant imports.
  Cargo.lock
  crates/cargo-test-support/src/lib.rs
  crates/cargo-test-support/src/paths.rs
  crates/resolver-tests/src/lib.rs
  crates/rustfix/Cargo.toml
  crates/rustfix/tests/edge_cases.rs
  src/bin/cargo/cli.rs
  src/bin/cargo/commands/help.rs
  src/bin/cargo/main.rs
  src/cargo/ops/fix.rs
  src/cargo/ops/registry/mod.rs
  src/cargo/sources/git/utils.rs
  src/cargo/util/machine_message.rs
  src/cargo/util/toml_mut/dependency.rs
Labels: A-git, A-interacts-with-crates.io, A-dependency-resolution, A-console-output, A-manifest, A-testing-cargo-itself, Command-fix, S-waiting-on-bors, A-cli

#13469 Fix unused imports on Windows.
  tests/testsuite/profile_trim_paths.rs
Labels: S-waiting-on-bors

#13197 feat: support `target.<triple>.rustdocflags` officially
  src/cargo/core/compiler/build_context/target_info.rs
  src/cargo/util/config/target.rs
  src/doc/src/reference/config.md
  tests/testsuite/rustdocflags.rs
Labels: A-documenting-cargo-itself, S-waiting-on-bors, A-cfg-expr

#13468 fix: remove unused `sysroot_host_libdir`
  src/cargo/core/compiler/build_context/target_info.rs
  src/cargo/core/compiler/compilation.rs
Labels: A-build-execution, S-waiting-on-bors, A-cfg-expr

#13470 Fix missing brackets
  src/cargo/ops/cargo_compile/mod.rs
Labels: S-waiting-on-bors

#13463 fix(cli): Control clap colors through config
  src/bin/cargo/cli.rs
  src/bin/cargo/commands/help.rs
  src/bin/cargo/main.rs
  src/cargo/core/shell.rs
  src/cargo/util/config/mod.rs
Labels: A-configuration, A-console-output, S-waiting-on-bors, A-cli

#13467 Add global_cache_tracker stability tests.
  .github/workflows/main.yml
  crates/cargo-test-macro/src/lib.rs
  crates/cargo-test-support/src/lib.rs
  src/cargo/core/global_cache_tracker.rs
  tests/testsuite/global_cache_tracker.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors, A-infrastructure

#13478 [docs]:Add missing jump links
  src/cargo/core/compiler/fingerprint/mod.rs
Labels: A-rebuild-detection, S-waiting-on-bors

#13281 fix(add): Improve error when adding registry packages while vendored
  crates/resolver-tests/src/lib.rs
  src/cargo/core/resolver/errors.rs
  src/cargo/ops/cargo_add/mod.rs
  src/cargo/sources/directory.rs
  src/cargo/sources/path.rs
  src/cargo/sources/registry/mod.rs
  src/cargo/sources/source.rs
  tests/testsuite/cargo_add/add_no_vendored_package_with_alter_registry/in/.cargo/config.toml
  tests/testsuite/cargo_add/add_no_vendored_package_with_alter_registry/in/Cargo.toml
  tests/testsuite/cargo_add/add_no_vendored_package_with_alter_registry/in/src/lib.rs
  tests/testsuite/cargo_add/add_no_vendored_package_with_alter_registry/in/vendor/aa/.cargo-checksum.json
  tests/testsuite/cargo_add/add_no_vendored_package_with_alter_registry/in/vendor/aa/Cargo.toml
  tests/testsuite/cargo_add/add_no_vendored_package_with_alter_registry/in/vendor/aa/src/lib.rs
  tests/testsuite/cargo_add/add_no_vendored_package_with_alter_registry/mod.rs
  tests/testsuite/cargo_add/add_no_vendored_package_with_alter_registry/out/Cargo.toml
  tests/testsuite/cargo_add/add_no_vendored_package_with_alter_registry/stderr.log
  tests/testsuite/cargo_add/add_no_vendored_package_with_alter_registry/stdout.log
  tests/testsuite/cargo_add/add_no_vendored_package_with_vendor/in/.cargo/config.toml
  tests/testsuite/cargo_add/add_no_vendored_package_with_vendor/in/Cargo.toml
  tests/testsuite/cargo_add/add_no_vendored_package_with_vendor/in/src/lib.rs
  tests/testsuite/cargo_add/add_no_vendored_package_with_vendor/in/vendor/aa/.cargo-checksum.json
  tests/testsuite/cargo_add/add_no_vendored_package_with_vendor/in/vendor/aa/Cargo.toml
  tests/testsuite/cargo_add/add_no_vendored_package_with_vendor/in/vendor/aa/src/lib.rs
  tests/testsuite/cargo_add/add_no_vendored_package_with_vendor/mod.rs
  tests/testsuite/cargo_add/add_no_vendored_package_with_vendor/out/Cargo.toml
  tests/testsuite/cargo_add/add_no_vendored_package_with_vendor/stderr.log
  tests/testsuite/cargo_add/add_no_vendored_package_with_vendor/stdout.log
  tests/testsuite/cargo_add/mod.rs
Labels: A-dependency-resolution, A-registries, A-manifest, S-waiting-on-bors, A-directory-source, Command-add

#13480 Error messages when collecting workspace members now mention the workspace root location
  src/cargo/core/workspace.rs
  tests/testsuite/workspaces.rs
Labels: A-workspaces, S-waiting-on-bors

#13479 fix(cli): Respect CARGO_TERM_COLOR in '--list' and '-Zhelp'
  src/bin/cargo/cli.rs
  src/cargo/util/config/mod.rs
Labels: A-configuration, S-waiting-on-bors, A-cli

#13486 refactor: clean up for `GlobalContext` rename
  crates/mdman/src/hbs.rs
  src/bin/cargo/cli.rs
  src/bin/cargo/commands/install.rs
  src/cargo/core/compiler/job_queue/job_state.rs
  src/cargo/core/gc.rs
  src/cargo/core/global_cache_tracker.rs
  src/cargo/core/resolver/errors.rs
  src/cargo/ops/cargo_clean.rs
  src/cargo/sources/config.rs
  src/cargo/util/cache_lock.rs
  src/cargo/util/config/de.rs
  src/cargo/util/config/environment.rs
  src/cargo/util/config/mod.rs
  src/cargo/util/toml/mod.rs
  src/doc/contrib/src/implementation/console.md
  tests/testsuite/config.rs
Labels: A-documenting-cargo-itself, A-configuration, Command-clean, Command-install, A-build-execution, A-dependency-resolution, A-environment-variables, A-manifest, S-waiting-on-bors, A-cli, A-cli-help

#13488 test: relax help text assertion
  tests/testsuite/cargo/help/stdout.term.svg
Labels: S-waiting-on-bors

#13489 chore: fixed a typo(two->too)
  src/cargo/core/resolver/types.rs
Labels: A-dependency-resolution, S-waiting-on-bors

#13490 fix(doctest): search native libs in build script outputs
  src/cargo/core/compiler/compilation.rs
  tests/testsuite/test.rs
Labels: A-build-execution, S-waiting-on-bors, A-doctests

#13494 chore: bump baseline version requirement of sub crates
  Cargo.toml
Labels: S-waiting-on-bors

#13492 Stabilize global cache data tracking.
  src/cargo/core/global_cache_tracker.rs
  tests/testsuite/global_cache_tracker.rs
Labels: T-cargo, S-waiting-on-bors, Z-gc

#13340 feat: Add "-Zpublic-dependency" for public-dependency feature.
  src/cargo/core/compiler/mod.rs
  src/cargo/core/features.rs
  src/cargo/ops/cargo_package.rs
  src/cargo/util/toml/mod.rs
  tests/build-std/main.rs
  tests/testsuite/cargo/z_help/stdout.term.svg
  tests/testsuite/pub_priv.rs
Labels: A-documenting-cargo-itself, A-build-execution, Command-package, A-workspaces, A-manifest, S-waiting-on-bors, A-unstable

#13438 Silently ignore `cargo::rustc-check-cfg` to avoid MSRV annoyance when stabilizing `-Zcheck-cfg`
  src/cargo/core/compiler/custom_build.rs
  src/cargo/util/config/target.rs
  tests/testsuite/check_cfg.rs
Labels: A-build-scripts, S-waiting-on-bors

#13500 [beta-1.77] Backport ignore `cargo::rustc-check-cfg`
  src/cargo/core/compiler/custom_build.rs
  src/cargo/util/config/target.rs
  tests/testsuite/check_cfg.rs
Labels: A-build-scripts, S-waiting-on-bors

#13499 fix(rustc): Always pass --edition to rustc
  src/cargo/core/features.rs
  tests/testsuite/artifact_dep.rs
  tests/testsuite/build.rs
  tests/testsuite/build_script.rs
  tests/testsuite/build_script_extra_link_arg.rs
  tests/testsuite/cache_messages.rs
  tests/testsuite/check.rs
  tests/testsuite/cross_compile.rs
  tests/testsuite/doc.rs
  tests/testsuite/features2.rs
  tests/testsuite/freshness.rs
  tests/testsuite/git.rs
  tests/testsuite/glob_targets.rs
  tests/testsuite/lto.rs
  tests/testsuite/profile_overrides.rs
  tests/testsuite/profile_targets.rs
  tests/testsuite/profiles.rs
  tests/testsuite/publish_lockfile.rs
  tests/testsuite/run.rs
  tests/testsuite/rustc.rs
  tests/testsuite/rustdoc.rs
  tests/testsuite/test.rs
Labels: S-waiting-on-bors, A-unstable

#13481 Add all unit's children recursively for `doc.extern-map` option
  src/cargo/core/compiler/rustdoc.rs
  tests/testsuite/rustdoc_extern_html.rs
Labels: S-waiting-on-bors
