Repository rust-lang/cargo, pull requests merged in 2024-04, with the labels that each got.

#13678 Remove useless parameters
  src/cargo/ops/cargo_add/mod.rs
Labels: S-waiting-on-bors, Command-add

#13685 CI: Update macos images to macos-13
  .github/workflows/main.yml
Labels: S-waiting-on-bors, A-infrastructure

#13686 fix: bash completion fallback in `nounset` mode
  src/etc/cargo.bashcomp.sh
Labels: S-waiting-on-bors, A-completions

#13692 Update `der` crate
  Cargo.lock
Labels: S-waiting-on-bors

#13682 Maintain sorting of dependency features
  src/cargo/util/toml_mut/dependency.rs
  tests/testsuite/cargo_add/mod.rs
  tests/testsuite/cargo_add/overwrite_inline_features/out/Cargo.toml
  tests/testsuite/cargo_add/preserve_features_sorted/in/Cargo.toml
  tests/testsuite/cargo_add/preserve_features_sorted/in/src/lib.rs
  tests/testsuite/cargo_add/preserve_features_sorted/mod.rs
  tests/testsuite/cargo_add/preserve_features_sorted/out/Cargo.toml
  tests/testsuite/cargo_add/preserve_features_sorted/stderr.term.svg
  tests/testsuite/cargo_add/preserve_features_unsorted/in/Cargo.toml
  tests/testsuite/cargo_add/preserve_features_unsorted/in/src/lib.rs
  tests/testsuite/cargo_add/preserve_features_unsorted/mod.rs
  tests/testsuite/cargo_add/preserve_features_unsorted/out/Cargo.toml
  tests/testsuite/cargo_add/preserve_features_unsorted/stderr.term.svg
Labels: A-manifest, S-waiting-on-bors

#13693 refactor(toml): Split out an explicit step to resolve `Cargo.toml`
  crates/cargo-util-schemas/src/manifest/mod.rs
  src/cargo/core/features.rs
  src/cargo/core/workspace.rs
  src/cargo/util/toml/mod.rs
Labels: A-workspaces, A-manifest, S-waiting-on-bors, A-unstable

#13626 Allow precise update to prerelease.
  src/cargo/core/dependency.rs
  src/cargo/core/features.rs
  src/cargo/sources/registry/mod.rs
  src/cargo/util/semver_ext.rs
  src/doc/man/cargo-update.md
  src/doc/man/generated_txt/cargo-update.txt
  src/doc/src/commands/cargo-update.md
  src/doc/src/reference/unstable.md
  src/etc/man/cargo-update.1
  tests/testsuite/cargo/z_help/stdout.term.svg
  tests/testsuite/precise_pre_release.rs
Labels: A-documenting-cargo-itself, A-crate-dependencies, A-registries, S-waiting-on-bors, A-semver, A-cli-help, A-unstable

#13696 Switch to using gitoxide by default for listing files
  src/cargo/core/features.rs
  src/cargo/ops/cargo_package.rs
  src/cargo/sources/path.rs
  tests/testsuite/package.rs
Labels: Command-package, T-cargo, final-comment-period, disposition-merge, S-waiting-on-bors, A-unstable

#13698 doc: comments on `PackageRegistry`
  src/cargo/core/registry.rs
Labels: A-registries, S-waiting-on-bors

#13704 fix: adjust tracing verbosity in list_files_git
  src/cargo/sources/path.rs
Labels: S-waiting-on-bors

#13703 test(metadata): Show behavior with TOML-specific types
  tests/testsuite/metadata.rs
Labels: S-waiting-on-bors

#13706 Don't depend on `?` affecting type inference in weird ways
  crates/cargo-util/src/paths.rs
Labels: S-waiting-on-bors

#13701 refactor(toml): Decouple target discovery from Target creation
  src/cargo/util/toml/mod.rs
  src/cargo/util/toml/targets.rs
  tests/testsuite/package.rs
Labels: A-manifest, S-waiting-on-bors

#13714 chore: fix some typos
  src/cargo/core/compiler/mod.rs
  src/cargo/core/features.rs
  src/cargo/lib.rs
  src/cargo/ops/cargo_add/mod.rs
  src/cargo/sources/git/source.rs
  src/doc/src/reference/unstable.md
Labels: A-documenting-cargo-itself, A-git, A-build-execution, S-waiting-on-bors, A-unstable, Command-add

#13715 doc(semver): remove mention of deprecated tool rust-semverver
  src/doc/src/reference/semver.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#13717 Add release notes for 1.77.1
  CHANGELOG.md
Labels: S-waiting-on-bors

#13718 Fix github fast path redirect.
  src/cargo/sources/git/utils.rs
Labels: A-git, S-waiting-on-bors

#13608 feat(add): Stabilize MSRV-aware version req selection
  src/bin/cargo/commands/add.rs
  src/cargo/ops/cargo_add/mod.rs
  src/doc/man/cargo-add.md
  src/doc/man/generated_txt/cargo-add.txt
  src/doc/src/commands/cargo-add.md
  src/doc/src/reference/unstable.md
  src/etc/_cargo
  src/etc/cargo.bashcomp.sh
  src/etc/man/cargo-add.1
  tests/testsuite/cargo_add/help/stdout.term.svg
Labels: A-documenting-cargo-itself, T-cargo, finished-final-comment-period, disposition-merge, S-waiting-on-bors, A-completions, A-cli, A-cli-help, to-announce, Command-add

#13729 fix(package): Normalize paths in `Cargo.toml`
  src/cargo/util/toml/mod.rs
  tests/testsuite/package.rs
Labels: A-manifest, S-waiting-on-bors

#13727 refactor: make `resolve_with_previous` clearer
  src/cargo/core/registry.rs
  src/cargo/ops/cargo_generate_lockfile.rs
  src/cargo/ops/resolve.rs
Labels: Command-generate-lockfile, A-registries, S-waiting-on-bors

#13728 fix(cargo-fix): dont apply same suggestion twice
  crates/rustfix/src/lib.rs
  crates/rustfix/tests/everything/dedup-suggestions.fixed.rs
  crates/rustfix/tests/everything/dedup-suggestions.json
  crates/rustfix/tests/everything/dedup-suggestions.rs
  src/cargo/ops/fix.rs
  tests/testsuite/fix.rs
Labels: Command-fix, S-waiting-on-bors

#13731 chore: downgrade to openssl v1.1.1 (again)
  .github/renovate.json5
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors, A-infrastructure

#13740 refactor: Remove `rust_2024_compatibility` lint group
  src/cargo/util/lints.rs
  tests/testsuite/lints/mod.rs
  tests/testsuite/lints/rust_2024_compatibility/edition_2021/mod.rs
  tests/testsuite/lints/rust_2024_compatibility/edition_2021_warn/mod.rs
  tests/testsuite/lints/rust_2024_compatibility/edition_2021_warn/stderr.term.svg
  tests/testsuite/lints/rust_2024_compatibility/edition_2024/mod.rs
  tests/testsuite/lints/rust_2024_compatibility/edition_2024/stderr.term.svg
  tests/testsuite/lints/rust_2024_compatibility/mod.rs
  tests/testsuite/lints/rust_2024_compatibility/warn/mod.rs
  tests/testsuite/lints/rust_2024_compatibility/warn/stderr.term.svg
Labels: S-waiting-on-bors

#13738 feat(reslve): Respect '--ignore-rust-version'
  src/cargo/core/workspace.rs
  src/cargo/ops/resolve.rs
  src/cargo/util/command_prelude.rs
  tests/testsuite/rust_version.rs
Labels: A-workspaces, S-waiting-on-bors, A-cli

#13744 test: don't compress test registry crates
  crates/cargo-test-support/src/registry.rs
  tests/testsuite/alt_registry.rs
  tests/testsuite/cargo_add/locked_unchanged/in/Cargo.lock
  tests/testsuite/cargo_add/lockfile_updated/in/Cargo.lock
  tests/testsuite/cargo_add/lockfile_updated/out/Cargo.lock
  tests/testsuite/cargo_remove/update_lock_file/in/Cargo.lock
  tests/testsuite/cargo_remove/update_lock_file/out/Cargo.lock
Labels: A-testing-cargo-itself, S-waiting-on-bors

#13735 `cargo package -p no-exist` emitt error when the -p `package` not found
  src/cargo/ops/cargo_package.rs
  tests/testsuite/package.rs
Labels: Command-package, S-waiting-on-bors

#13742 feat(cli): Add --ignore-rust-version to update/generate-lockfile
  src/bin/cargo/commands/generate_lockfile.rs
  src/bin/cargo/commands/update.rs
  src/cargo/util/command_prelude.rs
  src/doc/man/cargo-generate-lockfile.md
  src/doc/man/cargo-update.md
  src/doc/man/generated_txt/cargo-generate-lockfile.txt
  src/doc/man/generated_txt/cargo-update.txt
  src/doc/src/commands/cargo-generate-lockfile.md
  src/doc/src/commands/cargo-update.md
  src/etc/man/cargo-generate-lockfile.1
  src/etc/man/cargo-update.1
  tests/testsuite/cargo_generate_lockfile/help/stdout.term.svg
  tests/testsuite/cargo_update/help/stdout.term.svg
  tests/testsuite/rust_version.rs
Labels: A-documenting-cargo-itself, Command-doc, Command-test, Command-run, Command-check, Command-bench, Command-build, Command-generate-lockfile, Command-rustc, Command-rustdoc, Command-update, A-workspaces, Command-fix, S-waiting-on-bors, A-cli, A-cli-help, Command-add

#13743 feat(resolve): Fallback to 'rustc -V' for MSRV resolving
  src/cargo/ops/resolve.rs
  tests/testsuite/rust_version.rs
Labels: A-documenting-cargo-itself, Command-doc, Command-test, Command-run, Command-check, Command-bench, Command-build, Command-generate-lockfile, Command-rustc, Command-rustdoc, Command-update, A-workspaces, Command-fix, S-waiting-on-bors, A-cli, A-cli-help, Command-add

#13750 test: Remove add/remove death tests
  tests/testsuite/death.rs
Labels: S-waiting-on-bors

#13748 refactor(config): Consistently use kebab-case
  src/cargo/ops/cargo_new.rs
  src/cargo/sources/directory.rs
  src/cargo/sources/registry/mod.rs
  src/cargo/util/context/mod.rs
Labels: A-configuration, Command-new, A-registries, S-waiting-on-bors, A-directory-source

#13751 docs(ref): Update unstable docs for msrv-policy
  src/doc/src/reference/unstable.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#13753 Reword sentence describing workspace toml for clarity
  src/doc/src/reference/workspaces.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#13756 Recategorize cargo test's `--doc` flag under "Target Selection"
  src/bin/cargo/commands/test.rs
  tests/testsuite/cargo_test/help/stdout.term.svg
Labels: Command-test, S-waiting-on-bors, A-cli

#13659 Make sure to also wrap the initial `-vV` invocation
  src/cargo/core/compiler/mod.rs
  src/cargo/util/rustc.rs
  tests/testsuite/build.rs
  tests/testsuite/cargo_env_config.rs
Labels: A-build-execution, S-waiting-on-bors, A-cache-messages

#13761 test(schemas): Ensure tests cover the correct case
  crates/cargo-util-schemas/src/core/package_id_spec.rs
Labels: S-waiting-on-bors

#13759 feat(update): Include a Locking message
  src/cargo/ops/cargo_generate_lockfile.rs
  tests/testsuite/artifact_dep.rs
  tests/testsuite/git.rs
  tests/testsuite/global_cache_tracker.rs
  tests/testsuite/local_registry.rs
  tests/testsuite/offline.rs
  tests/testsuite/patch.rs
  tests/testsuite/registry.rs
  tests/testsuite/replace.rs
  tests/testsuite/rust_version.rs
  tests/testsuite/update.rs
Labels: Command-generate-lockfile, S-waiting-on-bors

#13747 fix(toml): Error on `[project]` in Edition 2024
  src/bin/cargo/commands/fix.rs
  src/cargo/core/workspace.rs
  src/cargo/ops/fix.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/check.rs
  tests/testsuite/fix.rs
Labels: A-workspaces, T-cargo, A-manifest, Command-fix, final-comment-period, disposition-merge, S-waiting-on-bors, A-cli

#13764 feat(install): Including Locking message
  src/cargo/ops/resolve.rs
  tests/testsuite/directory.rs
  tests/testsuite/install.rs
  tests/testsuite/publish_lockfile.rs
  tests/testsuite/required_features.rs
Labels: S-waiting-on-bors

#13767 test(msrv): Re-organize MSRV tests
  tests/testsuite/rust_version.rs
Labels: S-waiting-on-bors

#13770 fix(credential): trim newlines in tokens from stdin
  src/cargo/ops/registry/login.rs
  tests/testsuite/credential_process.rs
  tests/testsuite/login.rs
Labels: A-interacts-with-crates.io, Command-login, S-waiting-on-bors

#13769 fix(msrv): Put MSRV-aware resolver behind a config
  src/cargo/core/workspace.rs
  src/cargo/util/context/mod.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/cargo_add/rust_version_ignore/mod.rs
  tests/testsuite/cargo_add/rust_version_incompatible/mod.rs
  tests/testsuite/cargo_add/rust_version_latest/mod.rs
  tests/testsuite/cargo_add/rust_version_older/mod.rs
  tests/testsuite/cargo_add/rustc_ignore/mod.rs
  tests/testsuite/cargo_add/rustc_incompatible/mod.rs
  tests/testsuite/cargo_add/rustc_latest/mod.rs
  tests/testsuite/cargo_add/rustc_older/mod.rs
  tests/testsuite/rust_version.rs
Labels: A-documenting-cargo-itself, A-configuration, A-workspaces, S-waiting-on-bors

#13775 fix(toml)!: Disallow source-less dependencies
  src/cargo/util/toml/mod.rs
  tests/testsuite/bad_config.rs
  tests/testsuite/cargo_add/empty_dep_table/in/Cargo.toml
  tests/testsuite/cargo_add/empty_dep_table/in/src/lib.rs
  tests/testsuite/cargo_add/empty_dep_table/mod.rs
  tests/testsuite/cargo_add/empty_dep_table/out/Cargo.toml
  tests/testsuite/cargo_add/empty_dep_table/stderr.term.svg
  tests/testsuite/cargo_add/mod.rs
  tests/testsuite/inheritable_workspace_fields.rs
Labels: A-manifest, S-waiting-on-bors

#13780 fix(toml): Don't crash on parse errors that point to multi-byte character
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#13777 fix 13773 - 'cargo build' fails when list_files() with gix is triggered
  Cargo.lock
  crates/cargo-test-support/src/git.rs
  tests/testsuite/build.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors

#13776 feat(resolver): Add v3 resolver for MSRV-aware resolving
  src/cargo/core/resolver/features.rs
  src/cargo/core/resolver/types.rs
  src/cargo/core/workspace.rs
  src/cargo/util/toml/mod.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/rust_version.rs
Labels: A-documenting-cargo-itself, A-workspaces, A-dependency-resolution, A-manifest, S-waiting-on-bors, A-features2

#13783 fix(toml): Report `_` fied variants (e.g. `dev_dependencies`) as deprecated
  src/cargo/util/toml/mod.rs
  src/cargo/util/toml/targets.rs
  tests/testsuite/bad_config.rs
  tests/testsuite/bench.rs
  tests/testsuite/build.rs
  tests/testsuite/cross_compile.rs
  tests/testsuite/features.rs
  tests/testsuite/proc_macro.rs
  tests/testsuite/profiles.rs
  tests/testsuite/run.rs
  tests/testsuite/test.rs
Labels: A-manifest, S-waiting-on-bors

#13789 Fix 2 tests for offline execution
  tests/testsuite/alt_registry.rs
  tests/testsuite/install.rs
Labels: S-waiting-on-bors

#13785 feat(resolver): Add default Edition2024 to resolver v3
  src/cargo/core/features.rs
  src/cargo/core/workspace.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/lints/implicit_features/edition_2024/stderr.term.svg
  tests/testsuite/rust_version.rs
Labels: A-documenting-cargo-itself, A-workspaces, S-waiting-on-bors, A-unstable

#13782 gate some libc usages under cfg(unix), drop os_info features
  Cargo.lock
  Cargo.toml
  crates/cargo-util/Cargo.toml
  credential/cargo-credential/Cargo.toml
Labels: S-waiting-on-bors, A-credential-provider

#13790 fix(install): Don't respect MSRV for non-local installs
  src/bin/cargo/commands/fix.rs
  src/cargo/core/workspace.rs
  src/cargo/ops/cargo_install.rs
  src/cargo/ops/fix.rs
  src/cargo/util/command_prelude.rs
  tests/testsuite/rust_version.rs
Labels: Command-install, A-workspaces, Command-fix, S-waiting-on-bors, A-cli

#13797 Cleanup linting system
  crates/cargo-util-schemas/src/manifest/mod.rs
  src/cargo/core/workspace.rs
  src/cargo/util/lints.rs
  tests/testsuite/lints/unused_optional_dependencies/edition_2024/mod.rs
  tests/testsuite/lints/unused_optional_dependencies/renamed_deps/mod.rs
  tests/testsuite/lints_table.rs
Labels: A-workspaces, A-manifest, S-waiting-on-bors

#13793 Fix warning suppression for config.toml vs config compat symlinks
  Cargo.toml
  src/cargo/util/context/mod.rs
  tests/testsuite/config.rs
Labels: A-configuration, S-waiting-on-bors

#13798 fix(toml): Be more forceful with underscore/dash redundancy
  src/cargo/util/toml/mod.rs
  tests/testsuite/bad_config.rs
Labels: A-manifest, S-waiting-on-bors

#13800 fix(toml): Don't double-warn when underscore is used in workspace dep
  src/cargo/util/toml/mod.rs
  tests/testsuite/bad_config.rs
Labels: A-manifest, S-waiting-on-bors

#13801 Add where lint was set
  src/cargo/core/workspace.rs
  src/cargo/util/lints.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/lints/implicit_features/edition_2021_warn/stderr.term.svg
  tests/testsuite/lints/unused_optional_dependencies/edition_2024/stderr.term.svg
  tests/testsuite/lints/unused_optional_dependencies/renamed_deps/stderr.term.svg
  tests/testsuite/lints_table.rs
Labels: A-workspaces, A-manifest, S-waiting-on-bors

#13802 refactor(toml): extract dependency-to-source-id to function
  src/cargo/util/toml/mod.rs
Labels: A-manifest, S-waiting-on-bors

#13794 docs(ref): Index differences between virtual / real manifests
  src/doc/src/reference/workspaces.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#13804 fix(toml): Remove underscore field support in 2024
  src/cargo/ops/fix.rs
  src/cargo/util/toml/mod.rs
  src/cargo/util/toml/targets.rs
  tests/testsuite/bad_config.rs
  tests/testsuite/fix.rs
Labels: A-manifest, Command-fix, S-waiting-on-bors

#13811 Update SleepTraker returns_in_order unit test
  src/cargo/util/network/sleep.rs
Labels: A-networking, S-waiting-on-bors

#13812 fix(cargo-lints): Don't always inherit workspace lints
  src/cargo/core/workspace.rs
  src/cargo/util/lints.rs
  tests/testsuite/lints_table.rs
Labels: A-workspaces, S-waiting-on-bors

#13816 Add failing test: artifact_dep_target_specified
  tests/testsuite/artifact_dep.rs
Labels: S-waiting-on-bors

#13817 Fix target entry in .gitignore
  .gitignore
Labels: S-waiting-on-bors

#13788 fix(toml)!: Remove support for inheriting badges
  Cargo.lock
  Cargo.toml
  crates/cargo-util-schemas/Cargo.toml
  crates/cargo-util-schemas/src/manifest/mod.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/inheritable_workspace_fields.rs
Labels: T-cargo, A-manifest, final-comment-period, disposition-merge, S-waiting-on-bors

#13829 test(cargo-lints): Add a test to ensure cap-lints works
  tests/testsuite/lints_table.rs
Labels: S-waiting-on-bors

#13713 fix(toml): Warn, rather than fail publish, if a target is excluded
  crates/cargo-util-schemas/src/manifest/mod.rs
  src/cargo/core/manifest.rs
  src/cargo/ops/cargo_package.rs
  src/cargo/util/toml/mod.rs
  src/cargo/util/toml/targets.rs
  tests/testsuite/artifact_dep.rs
  tests/testsuite/features2.rs
  tests/testsuite/features_namespaced.rs
  tests/testsuite/inheritable_workspace_fields.rs
  tests/testsuite/package.rs
  tests/testsuite/publish.rs
  tests/testsuite/weak_dep_features.rs
Labels: Command-package, T-cargo, A-manifest, final-comment-period, disposition-merge, S-waiting-on-bors

#13830 fix(toml): Improve granularity of traces
  src/cargo/util/toml/targets.rs
Labels: S-waiting-on-bors

#13831 docs: fix several typos found by `typos-cli`
  CHANGELOG.md
  src/cargo/core/features.rs
  src/cargo/sources/registry/mod.rs
  src/cargo/util/cache_lock.rs
  src/doc/man/cargo-update.md
  src/doc/man/generated_txt/cargo-update.txt
  src/doc/src/commands/cargo-update.md
  src/etc/man/cargo-update.1
Labels: A-documenting-cargo-itself, A-registries, S-waiting-on-bors, A-cli-help, A-unstable

#13813 refactor: Move diagnostic printing to Shell
  src/cargo/core/shell.rs
  src/cargo/util/lints.rs
  src/cargo/util/toml/mod.rs
Labels: A-configuration, A-console-output, A-manifest, S-waiting-on-bors

#13792 fix(cargo-fix): dont fix into standard library
  src/cargo/ops/fix.rs
  tests/testsuite/fix.rs
Labels: Command-fix, S-waiting-on-bors
