Repository rust-lang/cargo, pull requests merged in 2024-07, with the labels that each got.

#14169 refactor(source): Clean up after PathSource/RecursivePathSource split
  src/cargo/ops/cargo_add/mod.rs
  src/cargo/ops/cargo_install.rs
  src/cargo/ops/cargo_package.rs
  src/cargo/ops/cargo_uninstall.rs
  src/cargo/ops/resolve.rs
  src/cargo/sources/directory.rs
  src/cargo/sources/git/source.rs
  src/cargo/sources/path.rs
  src/cargo/sources/registry/mod.rs
Labels: A-git, Command-install, Command-package, Command-uninstall, A-registries, S-waiting-on-bors, A-directory-source, Command-add

#14173 test: mirgate fix* and future_incompat_report to snapbox
  tests/testsuite/fix.rs
  tests/testsuite/fix_n_times.rs
  tests/testsuite/future_incompat_report.rs
Labels: S-waiting-on-bors

#14177 test: migrate rust_version and rustc* to snapbox
  tests/testsuite/rust_version.rs
  tests/testsuite/rustc.rs
  tests/testsuite/rustc_info_cache.rs
Labels: S-waiting-on-bors

#14172 test: Migrate git_auth to snapbox
  tests/testsuite/git_auth.rs
Labels: S-waiting-on-bors

#14171 test：migrate `doc/directory/docscrape` to snapbox
  crates/cargo-test-support/src/compare.rs
  tests/testsuite/directory.rs
  tests/testsuite/doc.rs
  tests/testsuite/docscrape.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors

#14026 fix: improve message for inactive weak optional feature with edition2024 through unused dep collection
  src/cargo/core/summary.rs
  src/cargo/util/context/mod.rs
  src/cargo/util/lints.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/features.rs
  tests/testsuite/lints/unused_optional_dependencies.rs
Labels: A-configuration, A-dependency-resolution, A-registries, A-manifest, S-waiting-on-bors

#14182 chore: fix some typos
  src/doc/contrib/src/process/unstable.md
  src/doc/src/reference/build-scripts.md
  src/doc/src/reference/registry-index.md
  src/doc/src/reference/resolver.md
  src/doc/src/reference/semver.md
  src/doc/src/reference/unstable.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#14161 test: Auto-redact `... after last build at ...`; Migrate `freshness` to Snapbox
  crates/cargo-test-support/src/compare.rs
  tests/testsuite/freshness.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors

#14113 test: migrate some files to snapbox
  tests/testsuite/cargo_command.rs
  tests/testsuite/cargo_env_config.rs
  tests/testsuite/cargo_features.rs
  tests/testsuite/cargo_targets.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors

#14187 test: Migrate network tests to snapbox
  tests/testsuite/https.rs
  tests/testsuite/ssh.rs
Labels: S-waiting-on-bors

#13900 Pass rustflags to artifacts built with implicit targets when using target-applies-to-host
  src/cargo/core/compiler/build_context/mod.rs
  src/cargo/core/compiler/build_context/target_info.rs
  src/cargo/core/compiler/build_runner/mod.rs
  src/cargo/core/compiler/custom_build.rs
  src/cargo/core/compiler/fingerprint/mod.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/core/compiler/standard_lib.rs
  src/cargo/core/compiler/unit.rs
  src/cargo/core/compiler/unit_dependencies.rs
  src/cargo/ops/cargo_compile/mod.rs
  src/cargo/ops/cargo_compile/unit_generator.rs
  tests/testsuite/rustflags.rs
Labels: A-build-execution, A-rebuild-detection, A-build-scripts, S-waiting-on-bors, A-cfg-expr, A-cargo-targets, Z-target-applies-to-host

#14170 test: migrate install* and inheritable_workspace_fields to snapbox
  tests/testsuite/inheritable_workspace_fields.rs
  tests/testsuite/install.rs
  tests/testsuite/install_upgrade.rs
Labels: S-waiting-on-bors

#14185 test: migrate cfg and check to snapbox
  tests/testsuite/cfg.rs
  tests/testsuite/check.rs
Labels: S-waiting-on-bors

#14193 test: migrate build_plan and build_script to snapbox
  tests/testsuite/build_plan.rs
  tests/testsuite/build_script.rs
Labels: S-waiting-on-bors

#14191 test: Migrate jobserver to snapbox
  tests/testsuite/jobserver.rs
Labels: S-waiting-on-bors

#14181 test: migrate patch, pkgid, proc_macro and progress to snapbox
  tests/testsuite/patch.rs
  tests/testsuite/pkgid.rs
  tests/testsuite/proc_macro.rs
  tests/testsuite/progress.rs
Labels: S-waiting-on-bors

#14198 fix(test): Restore `does_not_contain` for check
  tests/testsuite/check.rs
Labels: S-waiting-on-bors

#14196 Allow enabling `config-include` feature in config
  src/cargo/util/context/mod.rs
  tests/testsuite/config_include.rs
Labels: A-configuration, S-waiting-on-bors

#14201 Add rustdocflags to Unit's Debug impl
  src/cargo/core/compiler/unit.rs
Labels: S-waiting-on-bors

#14180 test: migrate serveral files to snapbox
  tests/testsuite/read_manifest.rs
  tests/testsuite/rustdoc_extern_html.rs
  tests/testsuite/tool_paths.rs
  tests/testsuite/warn_on_failure.rs
Labels: S-waiting-on-bors

#14207 use "bootstrap" instead of "rustbuild"
  src/cargo/core/compiler/build_context/target_info.rs
  src/cargo/version.rs
Labels: S-waiting-on-bors, A-cfg-expr

#14203 test: relax redactions for rust-lang/rust
  tests/testsuite/cfg.rs
  tests/testsuite/git_auth.rs
Labels: S-waiting-on-bors

#14162 test: migrate metabuild, metadata and net_config to snapbox
  tests/testsuite/metabuild.rs
  tests/testsuite/metadata.rs
  tests/testsuite/net_config.rs
Labels: S-waiting-on-bors

#14212 Fix compatible_with_older_cargo test.
  tests/testsuite/global_cache_tracker.rs
Labels: S-waiting-on-bors

#14211 dont make new constant InternedString in hot path
  src/cargo/core/resolver/dep_cache.rs
  src/cargo/core/resolver/features.rs
  src/cargo/ops/tree/graph.rs
  src/cargo/util/interning.rs
Labels: A-dependency-resolution, S-waiting-on-bors, A-features2, Command-tree

#14213 test: Ensure --list test works with cargo-bloat
  tests/testsuite/cargo_command.rs
Labels: S-waiting-on-bors

#14200 test: migrate generate_lockfile and glob_targets to snapbox
  tests/testsuite/generate_lockfile.rs
  tests/testsuite/glob_targets.rs
Labels: S-waiting-on-bors

#14210 test: migrate member_errors, multitarget and new to snapbox
  tests/testsuite/member_errors.rs
  tests/testsuite/multitarget.rs
  tests/testsuite/new.rs
Labels: S-waiting-on-bors

#14215 fix: rename to `rustdoc::broken_intra_doc_links`
  tests/testsuite/doc.rs
Labels: S-waiting-on-bors

#14218 refactor: move get_source_id out of registry
  src/cargo/ops/registry/login.rs
  src/cargo/ops/registry/mod.rs
  src/cargo/ops/registry/owner.rs
  src/cargo/ops/registry/publish.rs
  src/cargo/ops/registry/search.rs
  src/cargo/ops/registry/yank.rs
Labels: Command-publish, A-interacts-with-crates.io, Command-login, Command-owner, Command-search, Command-yank, S-waiting-on-bors

#14217 fix(test): Reduce over-prescription to the caller
  tests/testsuite/build_script.rs
  tests/testsuite/fix_n_times.rs
  tests/testsuite/registry.rs
Labels: S-waiting-on-bors

#14223 test(progress): Resolve flakiness
  tests/testsuite/progress.rs
Labels: S-waiting-on-bors

#14224 docs(ref): Note MSRV for features in the docs
  src/doc/src/reference/build-scripts.md
  src/doc/src/reference/external-tools.md
  src/doc/src/reference/manifest.md
  src/doc/src/reference/profiles.md
  src/doc/src/reference/workspaces.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#14222 docs(contrib): Document things I look for in RFCs
  src/doc/contrib/src/SUMMARY.md
  src/doc/contrib/src/process/index.md
  src/doc/contrib/src/process/rfc.md
  src/doc/contrib/src/process/unstable.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#14228 chore(docs): update index of reference
  src/doc/src/reference/index.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#14221 fix: Ensure dep/feature activates the dependency on 2024
  src/cargo/util/toml/mod.rs
  tests/testsuite/features.rs
Labels: A-manifest, S-waiting-on-bors

#14209 test: Migrate lto tests to snapbox
  tests/testsuite/lto.rs
Labels: S-waiting-on-bors

#14233 fix(test): Redact elapsed time in the minutes time frame
  crates/cargo-test-support/src/compare.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors

#14234 fix(overrides): Don't warn on duplicate packages from using '..'
  src/cargo/ops/resolve.rs
  tests/testsuite/path.rs
Labels: S-waiting-on-bors

#14238 Add more profiling traces
  src/cargo/core/global_cache_tracker.rs
  src/cargo/core/registry.rs
  src/cargo/core/workspace.rs
  src/cargo/ops/cargo_read_manifest.rs
  src/cargo/ops/resolve.rs
  src/cargo/sources/git/utils.rs
Labels: A-git, Command-read-manifest, A-workspaces, A-registries, S-waiting-on-bors

#14231 refactor(source): More RecursivePathSource clean up
  src/cargo/ops/cargo_read_manifest.rs
  src/cargo/ops/mod.rs
  src/cargo/sources/path.rs
Labels: Command-read-manifest, S-waiting-on-bors

#14235 test: migrate check_cfg to snapbox
  tests/testsuite/check_cfg.rs
Labels: S-waiting-on-bors

#14241 test: migrate build-std/main to snapbox
  tests/build-std/main.rs
Labels: S-waiting-on-bors

#14245 test: migrate implicit_features to snapbox
  tests/testsuite/lints/implicit_features.rs
Labels: S-waiting-on-bors

#14202 Add workflow to publish Cargo automatically
  .github/workflows/release.yml
  publish.py
Labels: S-waiting-on-bors, A-infrastructure

#14239 fix(source): Don't warn about unreferenced duplicate packages
  src/cargo/sources/path.rs
  tests/testsuite/git.rs
Labels: S-waiting-on-bors

#14252 perf(source): Don't `du` on every git source load
  src/cargo/core/global_cache_tracker.rs
  src/cargo/sources/git/source.rs
Labels: A-git, S-waiting-on-bors

#14254 chore: downgrade to jobserver@0.1.28
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#14214 test: migrate fetch and list_availables to snapbox
  tests/testsuite/fetch.rs
  tests/testsuite/list_availables.rs
Labels: S-waiting-on-bors

#14257 chore(ci): bump CI tools
  .github/workflows/contrib.yml
  .github/workflows/main.yml
  src/doc/book.toml
Labels: A-documenting-cargo-itself, S-waiting-on-bors, A-infrastructure

#14255 [beta-1.80.0] chore: downgrade to jobserver@0.1.28
  Cargo.lock
  Cargo.toml
  tests/testsuite/global_cache_tracker.rs
Labels: S-waiting-on-bors

#14260 make summary sync by using Arc not Rc
  src/cargo/core/dependency.rs
  src/cargo/core/summary.rs
Labels: A-crate-dependencies, S-waiting-on-bors

#14244 Migrate global_cache_tracker snapbox
  crates/cargo-test-support/src/compare.rs
  tests/testsuite/global_cache_tracker.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors

#14261 fix(toml): Improve error on missing package and workspace
  src/cargo/util/toml/mod.rs
  tests/testsuite/build.rs
  tests/testsuite/metadata.rs
Labels: A-manifest, S-waiting-on-bors

#14205 Fix passing of links-overrides with target-applies-to-host and an implicit target
  src/cargo/core/compiler/build_context/target_info.rs
  src/cargo/core/compiler/custom_build.rs
  src/cargo/core/compiler/standard_lib.rs
  src/cargo/core/compiler/unit.rs
  src/cargo/core/compiler/unit_dependencies.rs
  src/cargo/ops/cargo_compile/mod.rs
  src/cargo/ops/cargo_compile/unit_generator.rs
  src/cargo/util/context/target.rs
  tests/testsuite/build_script.rs
Labels: A-build-scripts, S-waiting-on-bors, A-cfg-expr, A-cargo-targets, Z-target-applies-to-host

#14266 fix(test): Move path2url to CargoPathExt::to_url
  crates/cargo-test-support/src/git.rs
  crates/cargo-test-support/src/lib.rs
  crates/cargo-test-support/src/paths.rs
  tests/testsuite/bench.rs
  tests/testsuite/build.rs
  tests/testsuite/build_script.rs
  tests/testsuite/cache_lock.rs
  tests/testsuite/cargo_command.rs
  tests/testsuite/check.rs
  tests/testsuite/clean.rs
  tests/testsuite/dep_info.rs
  tests/testsuite/doc.rs
  tests/testsuite/features.rs
  tests/testsuite/features2.rs
  tests/testsuite/fix.rs
  tests/testsuite/freshness.rs
  tests/testsuite/git.rs
  tests/testsuite/global_cache_tracker.rs
  tests/testsuite/install.rs
  tests/testsuite/install_upgrade.rs
  tests/testsuite/local_registry.rs
  tests/testsuite/login.rs
  tests/testsuite/logout.rs
  tests/testsuite/old_cargos.rs
  tests/testsuite/owner.rs
  tests/testsuite/package.rs
  tests/testsuite/path.rs
  tests/testsuite/profile_config.rs
  tests/testsuite/profile_custom.rs
  tests/testsuite/registry.rs
  tests/testsuite/required_features.rs
  tests/testsuite/run.rs
  tests/testsuite/rustc_info_cache.rs
  tests/testsuite/rustup.rs
  tests/testsuite/test.rs
  tests/testsuite/weak_dep_features.rs
  tests/testsuite/yank.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors

#14268 feat(test): Re-export ProcessBuilder
  crates/cargo-test-support/src/lib.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors

#14269 fix(test)!: Clarify extension trait role with rename
  crates/cargo-test-support/src/lib.rs
  tests/testsuite/cargo_bench/no_keep_going/mod.rs
  tests/testsuite/cargo_init/inherit_workspace_package_table/mod.rs
  tests/testsuite/cargo_new/add_members_to_non_workspace/mod.rs
  tests/testsuite/cargo_new/add_members_to_workspace_format_previous_items/mod.rs
  tests/testsuite/cargo_new/add_members_to_workspace_format_sorted/mod.rs
  tests/testsuite/cargo_new/add_members_to_workspace_with_absolute_package_path/mod.rs
  tests/testsuite/cargo_new/add_members_to_workspace_with_empty_members/mod.rs
  tests/testsuite/cargo_new/add_members_to_workspace_with_exclude_list/mod.rs
  tests/testsuite/cargo_new/add_members_to_workspace_with_members_glob/mod.rs
  tests/testsuite/cargo_new/add_members_to_workspace_without_members/mod.rs
  tests/testsuite/cargo_new/empty_name/mod.rs
  tests/testsuite/cargo_new/inherit_workspace_lints/mod.rs
  tests/testsuite/cargo_new/inherit_workspace_package_table/mod.rs
  tests/testsuite/cargo_new/inherit_workspace_package_table_with_edition/mod.rs
  tests/testsuite/cargo_new/inherit_workspace_package_table_with_registry/mod.rs
  tests/testsuite/cargo_new/inherit_workspace_package_table_without_version/mod.rs
  tests/testsuite/cargo_new/not_inherit_workspace_package_table_if_not_members/mod.rs
  tests/testsuite/cargo_remove/avoid_empty_tables/mod.rs
  tests/testsuite/cargo_remove/build/mod.rs
  tests/testsuite/cargo_remove/dev/mod.rs
  tests/testsuite/cargo_remove/dry_run/mod.rs
  tests/testsuite/cargo_remove/gc_keep_used_patch/mod.rs
  tests/testsuite/cargo_remove/gc_patch/mod.rs
  tests/testsuite/cargo_remove/gc_profile/mod.rs
  tests/testsuite/cargo_remove/gc_replace/mod.rs
  tests/testsuite/cargo_remove/invalid_arg/mod.rs
  tests/testsuite/cargo_remove/invalid_dep/mod.rs
  tests/testsuite/cargo_remove/invalid_package/mod.rs
  tests/testsuite/cargo_remove/invalid_package_multiple/mod.rs
  tests/testsuite/cargo_remove/invalid_section/mod.rs
  tests/testsuite/cargo_remove/invalid_section_dep/mod.rs
  tests/testsuite/cargo_remove/invalid_target/mod.rs
  tests/testsuite/cargo_remove/invalid_target_dep/mod.rs
  tests/testsuite/cargo_remove/multiple_deps/mod.rs
  tests/testsuite/cargo_remove/multiple_dev/mod.rs
  tests/testsuite/cargo_remove/no_arg/mod.rs
  tests/testsuite/cargo_remove/offline/mod.rs
  tests/testsuite/cargo_remove/optional_dep_feature/mod.rs
  tests/testsuite/cargo_remove/optional_dep_feature_formatting/mod.rs
  tests/testsuite/cargo_remove/optional_feature/mod.rs
  tests/testsuite/cargo_remove/package/mod.rs
  tests/testsuite/cargo_remove/remove_basic/mod.rs
  tests/testsuite/cargo_remove/skip_gc_glob_profile/mod.rs
  tests/testsuite/cargo_remove/target/mod.rs
  tests/testsuite/cargo_remove/target_build/mod.rs
  tests/testsuite/cargo_remove/target_dev/mod.rs
  tests/testsuite/cargo_remove/update_lock_file/mod.rs
  tests/testsuite/cargo_remove/workspace/mod.rs
  tests/testsuite/cargo_remove/workspace_non_virtual/mod.rs
  tests/testsuite/cargo_remove/workspace_preserved/mod.rs
  tests/testsuite/cargo_test/no_keep_going/mod.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors

#14270 fix(test): Move 'cargo_home' from 'install' to 'paths'
  crates/cargo-test-support/src/install.rs
  crates/cargo-test-support/src/lib.rs
  crates/cargo-test-support/src/paths.rs
  crates/cargo-test-support/src/registry.rs
  tests/testsuite/binary_name.rs
  tests/testsuite/build_script.rs
  tests/testsuite/concurrent.rs
  tests/testsuite/features2.rs
  tests/testsuite/install.rs
  tests/testsuite/install_upgrade.rs
  tests/testsuite/jobserver.rs
  tests/testsuite/member_discovery.rs
  tests/testsuite/member_errors.rs
  tests/testsuite/metadata.rs
  tests/testsuite/registry.rs
  tests/testsuite/required_features.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors

#14271 Add `TomlPackage::new`, `Default` for `TomlWorkspace`
  Cargo.lock
  crates/cargo-util-schemas/Cargo.toml
  crates/cargo-util-schemas/src/manifest/mod.rs
Labels: A-manifest, S-waiting-on-bors

#14273 Use `Rc` instead of `Arc` for storing rustflags
  src/cargo/core/compiler/build_context/target_info.rs
  src/cargo/core/compiler/unit.rs
Labels: S-waiting-on-bors, A-cfg-expr

#14282 test: Fix some test based on rustc version
  tests/testsuite/build.rs
  tests/testsuite/lints/implicit_features.rs
Labels: S-waiting-on-bors

#14272 docs(test): Expand documentation of cargo-test-support
  crates/cargo-test-macro/src/lib.rs
  crates/cargo-test-support/Cargo.toml
  crates/cargo-test-support/src/compare.rs
  crates/cargo-test-support/src/git.rs
  crates/cargo-test-support/src/install.rs
  crates/cargo-test-support/src/lib.rs
  crates/cargo-test-support/src/paths.rs
  crates/cargo-test-support/src/publish.rs
  crates/cargo-test-support/src/registry.rs
  src/doc/contrib/src/tests/writing.md
Labels: A-documenting-cargo-itself, A-testing-cargo-itself, S-waiting-on-bors

#14279 Improved error message when `update --breaking` invalid spec.
  src/cargo/ops/cargo_update.rs
  tests/testsuite/update.rs
Labels: Command-update, S-waiting-on-bors, A-cli

#14285 Bump to 0.83.0; update changelog
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#14286 chore: bump cargo-test-support to 0.4.0
  Cargo.lock
  Cargo.toml
  crates/cargo-test-support/Cargo.toml
Labels: A-testing-cargo-itself, S-waiting-on-bors

#14295 Revert "fix: Ensure dep/feature activates the dependency on 2024"
  src/cargo/util/toml/mod.rs
  tests/testsuite/features.rs
Labels: A-manifest, S-waiting-on-bors

#14293 test: Migrate some json tests to snapbox
  Cargo.lock
  Cargo.toml
  crates/cargo-test-support/src/lib.rs
  tests/testsuite/alt_registry.rs
  tests/testsuite/bad_manifest_path.rs
  tests/testsuite/bench.rs
  tests/testsuite/binary_name.rs
  tests/testsuite/build_plan.rs
  tests/testsuite/cargo_config/mod.rs
  tests/testsuite/doc.rs
  tests/testsuite/features_namespaced.rs
  tests/testsuite/git.rs
  tests/testsuite/install.rs
  tests/testsuite/locate_project.rs
  tests/testsuite/metabuild.rs
  tests/testsuite/metadata.rs
  tests/testsuite/open_namespaces.rs
  tests/testsuite/pkgid.rs
  tests/testsuite/read_manifest.rs
  tests/testsuite/script.rs
  tests/testsuite/test.rs
  tests/testsuite/unit_graph.rs
  tests/testsuite/update.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors

#14250 Don't downgrade on prerelease `VersionReq` when update with --breaking.
  src/cargo/util/toml_mut/upgrade.rs
  tests/testsuite/update.rs
Labels: A-manifest, S-waiting-on-bors

#14297 Misc test clean up
  crates/cargo-test-support/src/lib.rs
  tests/testsuite/test.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors

#14299 chore: Update dependencies
  Cargo.lock
  Cargo.toml
  crates/rustfix/Cargo.toml
Labels: Command-fix, S-waiting-on-bors

#14242 test: migrate messages to snapbox
  tests/testsuite/messages.rs
Labels: S-waiting-on-bors

#13947 Package workspaces
  src/bin/cargo/commands/package.rs
  src/cargo/core/features.rs
  src/cargo/ops/cargo_package.rs
  src/cargo/ops/registry/mod.rs
  src/cargo/ops/registry/publish.rs
  src/cargo/sources/registry/index/mod.rs
  src/cargo/sources/registry/mod.rs
  src/doc/man/cargo-package.md
  src/doc/man/generated_txt/cargo-package.txt
  src/doc/src/commands/cargo-package.md
  src/etc/_cargo
  src/etc/cargo.bashcomp.sh
  src/etc/man/cargo-package.1
  tests/testsuite/cargo/z_help/stdout.term.svg
  tests/testsuite/cargo_package/help/stdout.term.svg
  tests/testsuite/package.rs
  tests/testsuite/publish_lockfile.rs
Labels: A-documenting-cargo-itself, A-git, A-configuration, Command-publish, Command-install, A-interacts-with-crates.io, Command-package, Command-uninstall, Command-update, A-dependency-resolution, A-registries, A-manifest, A-testing-cargo-itself, S-waiting-on-bors, A-completions, A-cli, A-lockfile, A-directory-source, A-cli-help, A-unstable, Command-add

#14315 Fix warnings building tests on Windows
  tests/testsuite/open_namespaces.rs
  tests/testsuite/profile_trim_paths.rs
Labels: S-waiting-on-bors

#14319 Partial revert of 3085b548ecbd7d29d40c6180609ea3c224bad857
  tests/testsuite/doc.rs
Labels: S-waiting-on-bors

#14318 dont call wrap in a no-op source_id::with*
  src/cargo/core/source_id.rs
Labels: S-waiting-on-bors

#14324 chore: Update toml
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#14325 fix(publish): Don't strip non-dev features
  src/cargo/ops/cargo_package.rs
  src/cargo/ops/registry/publish.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/inheritable_workspace_fields.rs
  tests/testsuite/publish.rs
Labels: Command-publish, A-interacts-with-crates.io, Command-package, A-manifest, S-waiting-on-bors, beta-nominated

#14323 Use gmake on AIX
  tests/testsuite/jobserver.rs
Labels: S-waiting-on-bors

#14327 test(publish): More dev-dep stripping cases
  tests/testsuite/publish.rs
Labels: S-waiting-on-bors

#14329 fix(toml): Resolve regression from toml_edit 0.22.18
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#14328 [beta-1.81] fix(publish): Don't strip non-dev features
  src/cargo/ops/cargo_package.rs
  src/cargo/ops/registry/publish.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/inheritable_workspace_fields.rs
  tests/testsuite/lints/implicit_features.rs
  tests/testsuite/publish.rs
Labels: Command-publish, A-interacts-with-crates.io, Command-package, A-manifest, S-waiting-on-bors

#14296 fix(config): Adjust MSRV resolve config field name / values
  src/cargo/core/workspace.rs
  src/cargo/util/context/mod.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/cargo_add/rust_version_ignore/mod.rs
  tests/testsuite/cargo_add/rust_version_incompatible/mod.rs
  tests/testsuite/cargo_add/rust_version_latest/mod.rs
  tests/testsuite/cargo_add/rust_version_older/mod.rs
  tests/testsuite/cargo_add/rustc_ignore/mod.rs
  tests/testsuite/cargo_add/rustc_incompatible/mod.rs
  tests/testsuite/cargo_add/rustc_latest/mod.rs
  tests/testsuite/cargo_add/rustc_older/mod.rs
  tests/testsuite/rust_version.rs
Labels: A-documenting-cargo-itself, A-configuration, A-workspaces, S-waiting-on-bors
