Repository rust-lang/cargo, pull requests merged in 2024-09, with the labels that each got.

#14487 Fix elided lifetime
  src/cargo/core/workspace.rs
  tests/testsuite/lints/implicit_features.rs
Labels: A-workspaces, S-waiting-on-bors

#14488 Don't automatically include the current crate when packaging
  src/cargo/ops/cargo_package.rs
  tests/testsuite/package.rs
Labels: Command-package, S-waiting-on-bors

#14471 feat(resolve): Report MSRV compatible version instead of incomptible
  src/cargo/ops/cargo_update.rs
  tests/testsuite/cargo_add/default_features/stderr.term.svg
  tests/testsuite/cargo_add/list_features_path/stderr.term.svg
  tests/testsuite/cargo_add/list_features_path_no_default/stderr.term.svg
  tests/testsuite/cargo_add/namever/stderr.term.svg
  tests/testsuite/cargo_add/no_default_features/stderr.term.svg
  tests/testsuite/cargo_add/overwrite_default_features/stderr.term.svg
  tests/testsuite/cargo_add/overwrite_default_features_with_no_default_features/stderr.term.svg
  tests/testsuite/cargo_add/overwrite_no_default_features/stderr.term.svg
  tests/testsuite/cargo_add/overwrite_no_default_features_with_default_features/stderr.term.svg
  tests/testsuite/cargo_add/overwrite_path_with_version/stderr.term.svg
  tests/testsuite/cargo_add/overwrite_rename_with_no_rename/stderr.term.svg
  tests/testsuite/cargo_add/overwrite_rename_with_rename/stderr.term.svg
  tests/testsuite/cargo_add/overwrite_rename_with_rename_noop/stderr.term.svg
  tests/testsuite/cargo_add/overwrite_with_rename/stderr.term.svg
  tests/testsuite/cargo_add/preserve_sorted/stderr.term.svg
  tests/testsuite/cargo_add/preserve_unsorted/stderr.term.svg
  tests/testsuite/cargo_add/rust_version_older/stderr.term.svg
  tests/testsuite/cargo_add/rustc_latest/stderr.term.svg
  tests/testsuite/cargo_add/rustc_older/stderr.term.svg
  tests/testsuite/cargo_add/sorted_table_with_dotted_item/stderr.term.svg
  tests/testsuite/cargo_info/within_ws_without_lockfile/stderr.term.svg
  tests/testsuite/cfg.rs
  tests/testsuite/collisions.rs
  tests/testsuite/direct_minimal_versions.rs
  tests/testsuite/directory.rs
  tests/testsuite/install.rs
  tests/testsuite/minimal_versions.rs
  tests/testsuite/patch.rs
  tests/testsuite/paths.rs
  tests/testsuite/registry_overlay.rs
  tests/testsuite/replace.rs
  tests/testsuite/rust_version.rs
  tests/testsuite/tree.rs
  tests/testsuite/update.rs
  tests/testsuite/workspaces.rs
Labels: Command-update, S-waiting-on-bors

#13765 Fix cargo add behaving different when translating package name
  src/cargo/ops/cargo_add/mod.rs
  tests/testsuite/cargo_add/add_workspace_non_fuzzy/in/Cargo.lock
  tests/testsuite/cargo_add/add_workspace_non_fuzzy/in/Cargo.toml
  tests/testsuite/cargo_add/add_workspace_non_fuzzy/in/fuzzy_name/Cargo.toml
  tests/testsuite/cargo_add/add_workspace_non_fuzzy/in/fuzzy_name/src/lib.rs
  tests/testsuite/cargo_add/add_workspace_non_fuzzy/in/primary/Cargo.toml
  tests/testsuite/cargo_add/add_workspace_non_fuzzy/in/primary/src/lib.rs
  tests/testsuite/cargo_add/add_workspace_non_fuzzy/mod.rs
  tests/testsuite/cargo_add/add_workspace_non_fuzzy/out/Cargo.toml
  tests/testsuite/cargo_add/add_workspace_non_fuzzy/out/primary/Cargo.toml
  tests/testsuite/cargo_add/add_workspace_non_fuzzy/out/primary/src/lib.rs
  tests/testsuite/cargo_add/add_workspace_non_fuzzy/stderr.term.svg
  tests/testsuite/cargo_add/detect_workspace_inherit_fuzzy/in/Cargo.toml
  tests/testsuite/cargo_add/detect_workspace_inherit_fuzzy/in/primary/Cargo.toml
  tests/testsuite/cargo_add/detect_workspace_inherit_fuzzy/in/primary/src/lib.rs
  tests/testsuite/cargo_add/detect_workspace_inherit_fuzzy/mod.rs
  tests/testsuite/cargo_add/detect_workspace_inherit_fuzzy/out/Cargo.toml
  tests/testsuite/cargo_add/detect_workspace_inherit_fuzzy/out/primary/Cargo.toml
  tests/testsuite/cargo_add/detect_workspace_inherit_fuzzy/out/primary/src/lib.rs
  tests/testsuite/cargo_add/detect_workspace_inherit_fuzzy/stderr.term.svg
  tests/testsuite/cargo_add/features_fuzzy/in/Cargo.toml
  tests/testsuite/cargo_add/features_fuzzy/in/src/lib.rs
  tests/testsuite/cargo_add/features_fuzzy/mod.rs
  tests/testsuite/cargo_add/features_fuzzy/out/Cargo.toml
  tests/testsuite/cargo_add/features_fuzzy/stderr.term.svg
  tests/testsuite/cargo_add/mod.rs
Labels: S-waiting-on-bors, Command-add

#14495 Bump to 0.84.0; update changelog
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#14451 uplift windows gnullvm import libraries
  src/cargo/core/compiler/build_context/target_info.rs
Labels: S-waiting-on-bors, A-cfg-expr

#14496 Document -Zpackage-workspace
  src/doc/src/reference/unstable.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#14503 Bump ci's version of cargo-semver-version
  .github/workflows/main.yml
Labels: S-waiting-on-bors, A-infrastructure

#14448 bail before packaging on same version
  src/cargo/ops/registry/login.rs
  src/cargo/ops/registry/mod.rs
  src/cargo/ops/registry/owner.rs
  src/cargo/ops/registry/publish.rs
  src/cargo/ops/registry/search.rs
  src/cargo/ops/registry/yank.rs
  tests/testsuite/credential_process.rs
  tests/testsuite/publish.rs
  tests/testsuite/registry_auth.rs
Labels: Command-publish, A-interacts-with-crates.io, Command-login, Command-owner, Command-search, Command-yank, S-waiting-on-bors

#14507 fix(toml): Don't require MSRV bump for pub/priv
  src/cargo/util/toml/mod.rs
  tests/testsuite/pub_priv.rs
Labels: A-manifest, S-waiting-on-bors

#14515 docs: bin source can be `src/main.rs` and/or in `src/bin/`
  src/doc/src/reference/cargo-targets.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#14519 Remove unnecessary symbols
  src/cargo/sources/registry/index/mod.rs
Labels: A-registries, S-waiting-on-bors

#14504 Include public/private dependency status in `cargo metadata`
  src/bin/cargo/commands/read_manifest.rs
  src/cargo/core/dependency.rs
  src/cargo/core/mod.rs
  src/cargo/core/package.rs
  src/cargo/ops/cargo_output_metadata.rs
  src/doc/man/cargo-metadata.md
  src/doc/man/generated_txt/cargo-metadata.txt
  src/doc/src/commands/cargo-metadata.md
  src/etc/man/cargo-metadata.1
  tests/testsuite/metadata.rs
Labels: A-documenting-cargo-itself, Command-metadata, A-crate-dependencies, Command-read-manifest, S-waiting-on-bors, A-cli, Z-public-dependency, A-cli-help

#14499 Fix parsing of comma separated values in --crate-type flag
  src/bin/cargo/commands/rustc.rs
  tests/testsuite/rustc.rs
Labels: Command-rustc, S-waiting-on-review, A-cli

#14505 fix(new): Add to workspace relative to manifest, not current-dir
  src/cargo/ops/cargo_new.rs
  tests/testsuite/cargo_new/ignore_current_dir_workspace/in/workspace/Cargo.toml
  tests/testsuite/cargo_new/ignore_current_dir_workspace/in/workspace/src/main.rs
  tests/testsuite/cargo_new/ignore_current_dir_workspace/mod.rs
  tests/testsuite/cargo_new/ignore_current_dir_workspace/out/out-of-workspace/Cargo.toml
  tests/testsuite/cargo_new/ignore_current_dir_workspace/out/out-of-workspace/src/lib.rs
  tests/testsuite/cargo_new/ignore_current_dir_workspace/out/workspace/Cargo.toml
  tests/testsuite/cargo_new/ignore_current_dir_workspace/out/workspace/src/main.rs
  tests/testsuite/cargo_new/ignore_current_dir_workspace/stderr.term.svg
  tests/testsuite/cargo_new/mod.rs
Labels: Command-new, S-waiting-on-bors

#14539 Update docs for how cargo is published
  src/doc/contrib/src/process/release.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#14530 fix(vendor): trust crate version only when coming from registries
  src/cargo/ops/vendor.rs
  tests/testsuite/vendor.rs
Labels: S-waiting-on-bors, Command-vendor

#14546 Disable the shell_completions tests
  tests/testsuite/shell_completions.rs
Labels: S-waiting-on-bors

#14547 chore: revert change to Cargo.lock in f25806c
  Cargo.lock
Labels: S-waiting-on-bors

#14533 feat: Add custom completer for completing bin names
  src/cargo/util/command_prelude.rs
Labels: S-waiting-on-bors, A-cli

#14536 feat: Add custom completer for `cargo -Z <TAB>`
  src/bin/cargo/cli.rs
Labels: S-waiting-on-bors, A-cli

#14535 feat: Add custom completer for completing target triple
  src/cargo/util/command_prelude.rs
Labels: S-waiting-on-bors, A-cli

#14537 Suggest `cargo info` command in the `cargo search` result
  src/cargo/ops/registry/search.rs
  tests/testsuite/search.rs
Labels: A-interacts-with-crates.io, Command-search, S-waiting-on-bors, Command-info

#14548 feat: Add custom completer for completing test names
  src/cargo/util/command_prelude.rs
Labels: S-waiting-on-bors, A-cli

#14554 refactor(info): Use the `shell.note` to print the note
  src/cargo/ops/registry/info/view.rs
  tests/testsuite/cargo_info/specify_version_within_ws_and_match_with_lockfile/stderr.term.svg
  tests/testsuite/cargo_info/specify_version_within_ws_and_match_with_lockfile/stdout.term.svg
  tests/testsuite/cargo_info/transitive_dependency_within_ws/direct1-stderr.term.svg
  tests/testsuite/cargo_info/transitive_dependency_within_ws/direct1-stdout.term.svg
  tests/testsuite/cargo_info/transitive_dependency_within_ws/direct2-stderr.term.svg
  tests/testsuite/cargo_info/transitive_dependency_within_ws/direct2-stdout.term.svg
  tests/testsuite/cargo_info/transitive_dependency_within_ws/mod.rs
  tests/testsuite/cargo_info/transitive_dependency_within_ws/transitive1-stderr.term.svg
  tests/testsuite/cargo_info/transitive_dependency_within_ws/transitive1-stdout.term.svg
  tests/testsuite/cargo_info/transitive_dependency_within_ws/transitive2-stderr.term.svg
  tests/testsuite/cargo_info/transitive_dependency_within_ws/transitive2-stdout.term.svg
  tests/testsuite/cargo_info/transitive_dependency_within_ws/ws-stderr.term.svg
  tests/testsuite/cargo_info/transitive_dependency_within_ws/ws-stdout.term.svg
  tests/testsuite/cargo_info/within_ws/stderr.term.svg
  tests/testsuite/cargo_info/within_ws/stdout.term.svg
  tests/testsuite/cargo_info/within_ws_without_lockfile/stderr.term.svg
  tests/testsuite/cargo_info/within_ws_without_lockfile/stdout.term.svg
  tests/testsuite/cargo_info/without_requiring_registry_auth/stderr.term.svg
  tests/testsuite/cargo_info/without_requiring_registry_auth/stdout.term.svg
Labels: A-interacts-with-crates.io, S-waiting-on-bors, Command-info

#14532 feat: Add custom completer for completing benchmark names
  src/cargo/util/command_prelude.rs
Labels: S-waiting-on-bors, A-cli

#14558 fix(complete): Fix problems on my machine
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#14561 remove reference to incomplete crates.io feature from docs
  src/doc/src/reference/manifest.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#14531 feat: Add custom completer for `cargo build --example=<TAB>`
  src/cargo/util/command_prelude.rs
Labels: S-waiting-on-bors, A-cli

#14563 docs(unstable): Expand on completion documentation
  src/doc/src/reference/unstable.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#14557 feat: Add custom completer for `cargo help <TAB>`
  src/bin/cargo/commands/help.rs
Labels: S-waiting-on-bors, A-cli

#14562 Revert "remove reference to incomplete crates.io feature from docs"
  src/doc/src/reference/manifest.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#14564 fix(complete): Harden `--target` completions
  src/cargo/util/command_prelude.rs
Labels: S-waiting-on-bors, A-cli

#14573 feat(complete): Upgrade clap_complete
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-bors

#14568 fix(resolve): Don't list transitive, incompatible dependencies as available
  src/cargo/ops/cargo_update.rs
  tests/testsuite/paths.rs
  tests/testsuite/update.rs
Labels: Command-update, S-waiting-on-bors

#14280 Add a `--dry-run` flag to the `install` command
  src/bin/cargo/commands/install.rs
  src/cargo/core/compiler/build_config.rs
  src/cargo/core/compiler/build_runner/mod.rs
  src/cargo/ops/cargo_compile/mod.rs
  src/cargo/ops/cargo_install.rs
  src/doc/man/cargo-install.md
  src/doc/man/generated_txt/cargo-install.txt
  src/doc/src/commands/cargo-install.md
  src/etc/man/cargo-install.1
  tests/testsuite/cargo_install/help/stdout.term.svg
  tests/testsuite/install.rs
Labels: A-documenting-cargo-itself, Command-install, A-testing-cargo-itself, S-waiting-on-bors, A-cli, A-cli-help

#14585 chore: Bump MSRV to 1.81
  Cargo.lock
  Cargo.toml
  crates/cargo-test-macro/Cargo.toml
  crates/cargo-test-support/Cargo.toml
  crates/cargo-util-schemas/Cargo.toml
  crates/cargo-util/Cargo.toml
  crates/crates-io/Cargo.toml
  credential/cargo-credential-libsecret/Cargo.toml
  credential/cargo-credential-macos-keychain/Cargo.toml
  credential/cargo-credential-wincred/Cargo.toml
Labels: A-interacts-with-crates.io, A-testing-cargo-itself, S-waiting-on-bors, A-credential-provider

#14569 fix(resolve): Improve multi-MSRV workspaces
  src/cargo/core/resolver/version_prefs.rs
  src/cargo/core/workspace.rs
  src/cargo/ops/cargo_update.rs
  src/cargo/ops/lockfile.rs
  src/cargo/ops/registry/info/mod.rs
  src/cargo/ops/resolve.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/rust_version.rs
Labels: A-documenting-cargo-itself, A-interacts-with-crates.io, Command-update, A-workspaces, A-dependency-resolution, S-waiting-on-bors, A-lockfile, Command-info

#14577 test: Migrate remaining with_stdout/with_stderr calls
  Cargo.lock
  Cargo.toml
  crates/cargo-test-support/Cargo.toml
  crates/cargo-test-support/src/compare.rs
  crates/cargo-test-support/src/lib.rs
  crates/cargo-test-support/src/registry.rs
  tests/testsuite/artifact_dep.rs
  tests/testsuite/build.rs
  tests/testsuite/build_script.rs
  tests/testsuite/build_script_extra_link_arg.rs
  tests/testsuite/cache_messages.rs
  tests/testsuite/cargo_command.rs
  tests/testsuite/check.rs
  tests/testsuite/check_cfg.rs
  tests/testsuite/clean.rs
  tests/testsuite/collisions.rs
  tests/testsuite/doc.rs
  tests/testsuite/features2.rs
  tests/testsuite/fetch.rs
  tests/testsuite/fix.rs
  tests/testsuite/freshness.rs
  tests/testsuite/future_incompat_report.rs
  tests/testsuite/git_auth.rs
  tests/testsuite/global_cache_tracker.rs
  tests/testsuite/install.rs
  tests/testsuite/lto.rs
  tests/testsuite/message_format.rs
  tests/testsuite/metabuild.rs
  tests/testsuite/metadata.rs
  tests/testsuite/offline.rs
  tests/testsuite/package.rs
  tests/testsuite/package_features.rs
  tests/testsuite/profile_config.rs
  tests/testsuite/profile_overrides.rs
  tests/testsuite/profile_targets.rs
  tests/testsuite/profile_trim_paths.rs
  tests/testsuite/profiles.rs
  tests/testsuite/progress.rs
  tests/testsuite/publish.rs
  tests/testsuite/rustc.rs
  tests/testsuite/rustc_info_cache.rs
  tests/testsuite/rustdoc_extern_html.rs
  tests/testsuite/search.rs
  tests/testsuite/standard_lib.rs
  tests/testsuite/test.rs
  tests/testsuite/warn_on_failure.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors

#14552 feat: Add support for completing `cargo update <TAB>`
  src/bin/cargo/commands/update.rs
  src/cargo/util/command_prelude.rs
Labels: Command-update, S-waiting-on-bors, A-cli

#14590 test: Remove completion tests
  .github/workflows/main.yml
  Cargo.lock
  Cargo.toml
  tests/testsuite/main.rs
  tests/testsuite/shell_completions.rs
Labels: S-waiting-on-bors, A-infrastructure

#14592 perf: Improve quality of completion performance traces
  src/bin/cargo/main.rs
Labels: S-waiting-on-bors, A-cli

#14595 feat: make lockfile v4 the default
  src/cargo/core/resolver/resolve.rs
  src/cargo/core/source_id.rs
  src/cargo/sources/git/source.rs
  src/cargo/util/toml_mut/dependency.rs
  tests/testsuite/alt_registry.rs
  tests/testsuite/cargo_add/add_workspace_non_fuzzy/in/Cargo.lock
  tests/testsuite/cargo_add/locked_unchanged/in/Cargo.lock
  tests/testsuite/cargo_add/lockfile_updated/in/Cargo.lock
  tests/testsuite/cargo_add/lockfile_updated/out/Cargo.lock
  tests/testsuite/cargo_info/not_found/out/Cargo.lock
  tests/testsuite/cargo_info/path_dependency/in/Cargo.lock
  tests/testsuite/cargo_info/path_dependency/out/Cargo.lock
  tests/testsuite/cargo_info/specify_version_within_ws_and_conflict_with_lockfile/out/Cargo.lock
  tests/testsuite/cargo_info/specify_version_within_ws_and_match_with_lockfile/out/Cargo.lock
  tests/testsuite/cargo_info/with_frozen_within_ws/out/Cargo.lock
  tests/testsuite/cargo_info/with_locked_within_ws/out/Cargo.lock
  tests/testsuite/cargo_info/within_workspace.in/Cargo.lock
  tests/testsuite/cargo_info/within_ws/out/Cargo.lock
  tests/testsuite/cargo_info/within_ws_and_pick_ws_package/in/Cargo.lock
  tests/testsuite/cargo_info/within_ws_and_pick_ws_package/out/Cargo.lock
  tests/testsuite/cargo_info/within_ws_with_alternative_registry/out/Cargo.lock
  tests/testsuite/cargo_info/within_ws_without_lockfile/out/Cargo.lock
  tests/testsuite/cargo_info/without_requiring_registry_auth/in/Cargo.lock
  tests/testsuite/cargo_info/without_requiring_registry_auth/out/Cargo.lock
  tests/testsuite/cargo_remove/gc_patch/out/Cargo.lock
  tests/testsuite/cargo_remove/update_lock_file/in/Cargo.lock
  tests/testsuite/cargo_remove/update_lock_file/out/Cargo.lock
  tests/testsuite/git.rs
  tests/testsuite/lockfile_compat.rs
  tests/testsuite/lockfile_path.rs
  tests/testsuite/package.rs
  tests/testsuite/publish.rs
Labels: A-git, A-dependency-resolution, A-manifest, S-waiting-on-bors, A-lockfile

#14587 fix(cargo-rustc): give trailing flags higher precedence on nightly
  src/cargo/core/compiler/mod.rs
  tests/testsuite/rustc.rs
Labels: A-build-execution, S-waiting-on-bors

#14579 fix(config): Don't double-warn about `$CARGO_HOME/config`
  src/cargo/util/context/mod.rs
  tests/testsuite/config.rs
Labels: A-configuration, S-waiting-on-bors

#14404 feat: add CARGO_MANIFEST_PATH env variable
  src/cargo/core/compiler/compilation.rs
  src/cargo/core/compiler/custom_build.rs
  src/doc/src/reference/environment-variables.md
  src/doc/src/reference/unstable.md
  tests/testsuite/build.rs
  tests/testsuite/script.rs
Labels: A-documenting-cargo-itself, A-build-execution, A-build-scripts, T-cargo, final-comment-period, disposition-merge, S-waiting-on-bors

#14588 feat(timings): support dark color scheme in HTML output
  src/cargo/core/compiler/timings.js
  src/cargo/core/compiler/timings.rs
Labels: A-testing-cargo-itself, S-waiting-on-bors, A-timings

#14602 test: relax panic output assertion
  tests/testsuite/freshness.rs
  tests/testsuite/install.rs
  tests/testsuite/jobserver.rs
  tests/testsuite/test.rs
Labels: S-waiting-on-bors

#14598 fix: correct error count for `cargo check --message-format json`
  src/cargo/core/compiler/mod.rs
  tests/testsuite/build.rs
  tests/testsuite/pkgid.rs
Labels: A-build-execution, S-waiting-on-bors

#14591 feat(toml): Add `autolib`
  Cargo.lock
  Cargo.toml
  crates/cargo-util-schemas/Cargo.toml
  crates/cargo-util-schemas/src/manifest/mod.rs
  src/cargo/util/toml/embedded.rs
  src/cargo/util/toml/mod.rs
  src/cargo/util/toml/targets.rs
  src/doc/src/reference/cargo-targets.md
  src/doc/src/reference/manifest.md
  src/doc/src/reference/unstable.md
  tests/testsuite/artifact_dep.rs
  tests/testsuite/features2.rs
  tests/testsuite/features_namespaced.rs
  tests/testsuite/inheritable_workspace_fields.rs
  tests/testsuite/package.rs
  tests/testsuite/publish.rs
  tests/testsuite/script.rs
  tests/testsuite/vendor.rs
  tests/testsuite/weak_dep_features.rs
Labels: A-documenting-cargo-itself, T-cargo, A-manifest, final-comment-period, disposition-merge, S-waiting-on-bors

#14556 feat: lockfile path implies --locked on cargo install
  src/bin/cargo/commands/install.rs
  src/cargo/core/workspace.rs
  src/cargo/ops/cargo_install.rs
  src/cargo/util/context/mod.rs
  tests/testsuite/cargo_install/help/stdout.term.svg
  tests/testsuite/lockfile_path.rs
Labels: A-configuration, Command-install, A-workspaces, S-waiting-on-bors, A-cli

#14607 Update cc to 1.1.22
  Cargo.lock
Labels: S-waiting-on-bors

#14583 test: add support for features in the sat resolver
  crates/resolver-tests/src/lib.rs
  crates/resolver-tests/tests/resolve.rs
  src/cargo/core/summary.rs
Labels: A-dependency-resolution, S-waiting-on-bors

#14608 refactor(compiler): zero-copy deserialization when possible
  src/cargo/core/compiler/job_queue/job_state.rs
  src/cargo/core/compiler/mod.rs
Labels: A-build-execution, S-waiting-on-bors

#14618 test: relax compiler panic assertions
  tests/build-std/main.rs
  tests/testsuite/artifact_dep.rs
  tests/testsuite/bench.rs
  tests/testsuite/features2.rs
  tests/testsuite/freshness.rs
  tests/testsuite/install.rs
  tests/testsuite/jobserver.rs
  tests/testsuite/rustflags.rs
  tests/testsuite/test.rs
Labels: S-waiting-on-bors

#14312 docs: clarify `target.'cfg(...)'` doesnt respect cfg from build script
  src/doc/src/reference/config.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors

#14619 docs(ref): Clean up language for `package.rust-version`
  src/doc/src/reference/manifest.md
Labels: A-documenting-cargo-itself, S-waiting-on-bors
