Repository rust-lang/cargo, pull requests merged in 2025-08, with the labels that each got.

#15807 chore: bump to 0.92.0; update changelog
  Cargo.lock
  Cargo.toml
  src/doc/src/CHANGELOG.md
Labels: A-documenting-cargo-itself, S-waiting-on-review

#15776 Accessing each build script's `OUT_DIR` and in the correct order
  src/cargo/core/compiler/unit_dependencies.rs
  tests/testsuite/build_scripts_multiple.rs
Labels: S-waiting-on-review

#15822 test(build-std): relax the thread name assertion
  tests/build-std/main.rs
Labels: S-waiting-on-review

#15781 More helpful error for invalid cargo-features = []
  src/cargo/core/features.rs
  tests/testsuite/cargo_features.rs
Labels: S-waiting-on-review, A-unstable

#15783 perf(package): Always reuse the workspace's target-dir
  src/cargo/ops/cargo_package/verify.rs
  tests/testsuite/package.rs
  tests/testsuite/publish.rs
  tests/testsuite/publish_lockfile.rs
Labels: Command-package, S-waiting-on-review

#15831 chore: remove x86_64-apple-darwin from CI and tests
  .github/workflows/main.yml
  crates/cargo-test-support/src/cross_compile.rs
  src/doc/contrib/src/tests/writing.md
  tests/testsuite/utils/cross_compile.rs
Labels: A-documenting-cargo-itself, A-testing-cargo-itself, S-waiting-on-review, A-infrastructure

#15835 make resolve features public for cargo-as-a-library
  src/cargo/core/resolver/features.rs
Labels: A-dependency-resolution, S-waiting-on-review, A-features2

#15840 docs: Formatting and cross-linking to build-dir/target-dir docs
  src/doc/src/appendix/glossary.md
  src/doc/src/reference/build-cache.md
Labels: A-documenting-cargo-itself, S-waiting-on-review

#15800 Clarify that `cargo doc --no-deps` is cumulative and won’t delete prev
  src/doc/man/cargo-doc.md
  src/doc/man/generated_txt/cargo-doc.txt
  src/doc/src/commands/cargo-doc.md
  src/etc/man/cargo-doc.1
Labels: Command-doc, S-waiting-on-review, A-cli-help

#15846 refactor(unstable): group stabilized features
  src/cargo/core/features.rs
Labels: S-waiting-on-review, A-unstable

#15851 chore: downgrade to libc@0.2.174
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-review

#15849 update tests to match lint message changes from rust-lang/rust#140794
  Cargo.lock
  crates/rustfix/Cargo.toml
  crates/rustfix/tests/everything/multiple-solutions.json
  crates/rustfix/tests/everything/replace-only-one-char.json
  tests/testsuite/fix.rs
  tests/testsuite/warning_override.rs
Labels: Command-fix, S-waiting-on-author

#15865 Linting system
  src/cargo/util/lints.rs
  tests/testsuite/lints/unknown_lints.rs
Labels: S-waiting-on-review

#15873 make `UnitGenerator` public in cargo-as-a-library
  src/cargo/ops/cargo_compile/mod.rs
  src/cargo/ops/cargo_compile/unit_generator.rs
  src/cargo/ops/mod.rs
Labels: S-waiting-on-review, A-cargo-targets

#15507 suggest workspace hints for boolean dependencies
  crates/cargo-util-schemas/src/manifest/mod.rs
  tests/testsuite/bad_config.rs
Labels: A-manifest, S-waiting-on-review

#15877 chore: fix some typos in comment
  src/cargo/core/manifest.rs
  src/doc/src/reference/build-cache.md
Labels: A-documenting-cargo-itself, A-manifest, S-waiting-on-review

#15886 test(add): Cover some frontmatter corner cases
  tests/testsuite/cargo_add/mod.rs
  tests/testsuite/cargo_add/script_escape/in/cargo-test-fixture.rs
  tests/testsuite/cargo_add/script_escape/mod.rs
  tests/testsuite/cargo_add/script_escape/out/cargo-test-fixture.rs
  tests/testsuite/cargo_add/script_escape/stderr.term.svg
  tests/testsuite/cargo_add/script_frontmatter_empty/in/cargo-test-fixture.rs
  tests/testsuite/cargo_add/script_frontmatter_empty/mod.rs
  tests/testsuite/cargo_add/script_frontmatter_empty/out/cargo-test-fixture.rs
  tests/testsuite/cargo_add/script_frontmatter_empty/stderr.term.svg
Labels: S-waiting-on-review

#15880 test: avoid hardcoded target spec json
  crates/cargo-test-support/src/lib.rs
  tests/build-std/main.rs
  tests/testsuite/custom_target.rs
  tests/testsuite/rustc.rs
Labels: A-testing-cargo-itself, S-waiting-on-review

#15896 fix(cli): Show the bad manifest path
  src/cargo/util/command_prelude.rs
  tests/testsuite/bad_manifest_path.rs
  tests/testsuite/metadata.rs
  tests/testsuite/read_manifest.rs
  tests/testsuite/script.rs
Labels: S-waiting-on-review, A-cli
