Repository rust-lang/cargo, pull requests merged in 2025-09, with the labels that each got.

#15889 feat: Don't stop at first error when emitting lints and warnings
  src/cargo/core/workspace.rs
Labels: A-workspaces, S-waiting-on-review

#15904 Update dependencies
  Cargo.lock
Labels: S-waiting-on-review

#15909 chore(deps): update rust crate annotate-snippets to 0.12.1
  Cargo.lock
  Cargo.toml
  src/cargo/core/shell.rs
  src/cargo/util/lints.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/alt_registry.rs
  tests/testsuite/bad_config.rs
  tests/testsuite/build.rs
  tests/testsuite/cargo_add/invalid_manifest/stderr.term.svg
  tests/testsuite/cargo_features.rs
  tests/testsuite/diagnostics.rs
  tests/testsuite/features.rs
  tests/testsuite/features_namespaced.rs
  tests/testsuite/git.rs
  tests/testsuite/inheritable_workspace_fields.rs
  tests/testsuite/install.rs
  tests/testsuite/lints/error/stderr.term.svg
  tests/testsuite/lints/inherited/stderr.term.svg
  tests/testsuite/lints/mod.rs
  tests/testsuite/lints/unknown_lints.rs
  tests/testsuite/lints/warning/stderr.term.svg
  tests/testsuite/lints_table.rs
  tests/testsuite/member_errors.rs
  tests/testsuite/metadata.rs
  tests/testsuite/path.rs
  tests/testsuite/profile_custom.rs
  tests/testsuite/rust_version.rs
  tests/testsuite/script/rustc_fixtures/frontmatter-contains-whitespace.stderr
  tests/testsuite/workspaces.rs
Labels: A-console-output, A-manifest, S-waiting-on-review

#15910 fix(publish): Don't generate final artifacts
  src/cargo/ops/cargo_package/mod.rs
  src/doc/src/reference/build-cache.md
  tests/testsuite/build_dir.rs
Labels: A-documenting-cargo-itself, Command-package, S-waiting-on-review

#15914 refactor(frontmatter): Pull out as a dedicated mod
  src/cargo/util/frontmatter.rs
  src/cargo/util/mod.rs
  src/cargo/util/toml/embedded.rs
  src/cargo/util/toml/mod.rs
  src/cargo/util/toml_mut/manifest.rs
Labels: A-manifest, S-waiting-on-review

#15920 refactor(shell): Prepare for `Report`s being generated in more places
  src/cargo/core/shell.rs
  src/cargo/util/lints.rs
  src/cargo/util/toml/mod.rs
Labels: A-console-output, A-manifest, S-waiting-on-review

#15929 test(credential): Switch more expected results to snapshots
  tests/testsuite/credential_process.rs
Labels: S-waiting-on-review

#15923 Render individual compilation sections in `--timings` pipeline graph
  src/cargo/core/compiler/timings.js
  src/cargo/core/compiler/timings.rs
Labels: S-waiting-on-review, A-timings

#15930 fix: Switch from --nocapture to --no-capture
  src/cargo/ops/cargo_test.rs
  src/doc/man/cargo-bench.md
  src/doc/man/cargo-test.md
  src/doc/man/generated_txt/cargo-bench.txt
  src/doc/man/generated_txt/cargo-test.txt
  src/doc/src/commands/cargo-bench.md
  src/doc/src/commands/cargo-test.md
  src/etc/cargo.bashcomp.sh
  src/etc/man/cargo-bench.1
  src/etc/man/cargo-test.1
  tests/testsuite/old_cargos.rs
  tests/testsuite/package.rs
  tests/testsuite/test.rs
Labels: A-documenting-cargo-itself, Command-test, S-waiting-on-review, A-completions, A-cli-help

#15940 test(manifest): Fix test output order
  tests/testsuite/bad_config.rs
Labels: S-waiting-on-review

#15953 Clarify warning for using `features` or `default-features` in `patch`
  src/cargo/core/registry.rs
  src/cargo/ops/resolve.rs
  tests/testsuite/patch.rs
  tests/testsuite/replace.rs
Labels: A-registries, S-waiting-on-review

#15924 Add "Optimizing Build Performance" section to the Cargo book
  src/doc/src/SUMMARY.md
  src/doc/src/guide/build-performance.md
  src/doc/src/guide/index.md
Labels: A-documenting-cargo-itself, S-waiting-on-review

#15976 docs(team): Fixed broken office hours link
  src/doc/contrib/src/team.md
Labels: A-documenting-cargo-itself, S-waiting-on-review

#15977 Adds ghostty as supported terminal for term integration (OSC 9;4)
  src/cargo/core/shell.rs
Labels: A-console-output, S-waiting-on-review

#15980 feat(cargo-util-schemas): Move lockfile schemas
  Cargo.lock
  crates/cargo-util-schemas/Cargo.toml
  crates/cargo-util-schemas/lockfile.schema.json
  crates/cargo-util-schemas/src/lib.rs
  crates/cargo-util-schemas/src/lockfile.rs
  src/cargo/core/resolver/encode.rs
  src/cargo/core/resolver/mod.rs
  src/cargo/core/resolver/resolve.rs
  src/cargo/ops/lockfile.rs
Labels: A-dependency-resolution, S-waiting-on-review, A-lockfile

#15970 Add parallel frontend to the build performance guide
  src/doc/src/guide/build-performance.md
Labels: A-documenting-cargo-itself, S-waiting-on-review

#15967 Make GlobalContext Sync
  src/cargo/core/registry.rs
  src/cargo/core/shell.rs
  src/cargo/core/workspace.rs
  src/cargo/sources/git/utils.rs
  src/cargo/util/cache_lock.rs
  src/cargo/util/context/mod.rs
  src/cargo/util/flock.rs
  src/cargo/util/mod.rs
  src/cargo/util/once.rs
  src/cargo/util/toml/mod.rs
Labels: A-git, A-configuration, A-workspaces, A-registries, A-console-output, A-manifest, S-waiting-on-review, A-filesystem

#16006 test(build-std): move away from panic_immediate_abort
  tests/build-std/main.rs
Labels: S-waiting-on-review

#16003 fix: use `host-tuple` for host target subsitution
  src/cargo/core/compiler/compile_kind.rs
  src/cargo/util/command_prelude.rs
  src/doc/man/generated_txt/cargo-bench.txt
  src/doc/man/generated_txt/cargo-build.txt
  src/doc/man/generated_txt/cargo-check.txt
  src/doc/man/generated_txt/cargo-clean.txt
  src/doc/man/generated_txt/cargo-doc.txt
  src/doc/man/generated_txt/cargo-fetch.txt
  src/doc/man/generated_txt/cargo-fix.txt
  src/doc/man/generated_txt/cargo-install.txt
  src/doc/man/generated_txt/cargo-package.txt
  src/doc/man/generated_txt/cargo-publish.txt
  src/doc/man/generated_txt/cargo-run.txt
  src/doc/man/generated_txt/cargo-rustc.txt
  src/doc/man/generated_txt/cargo-rustdoc.txt
  src/doc/man/generated_txt/cargo-test.txt
  src/doc/man/includes/options-target-triple.md
  src/doc/src/commands/cargo-bench.md
  src/doc/src/commands/cargo-build.md
  src/doc/src/commands/cargo-check.md
  src/doc/src/commands/cargo-clean.md
  src/doc/src/commands/cargo-doc.md
  src/doc/src/commands/cargo-fetch.md
  src/doc/src/commands/cargo-fix.md
  src/doc/src/commands/cargo-install.md
  src/doc/src/commands/cargo-package.md
  src/doc/src/commands/cargo-publish.md
  src/doc/src/commands/cargo-run.md
  src/doc/src/commands/cargo-rustc.md
  src/doc/src/commands/cargo-rustdoc.md
  src/doc/src/commands/cargo-test.md
  src/doc/src/reference/config.md
  src/etc/man/cargo-bench.1
  src/etc/man/cargo-build.1
  src/etc/man/cargo-check.1
  src/etc/man/cargo-clean.1
  src/etc/man/cargo-doc.1
  src/etc/man/cargo-fetch.1
  src/etc/man/cargo-fix.1
  src/etc/man/cargo-install.1
  src/etc/man/cargo-package.1
  src/etc/man/cargo-publish.1
  src/etc/man/cargo-run.1
  src/etc/man/cargo-rustc.1
  src/etc/man/cargo-rustdoc.1
  src/etc/man/cargo-test.1
  tests/testsuite/cross_compile.rs
Labels: A-documenting-cargo-itself, S-waiting-on-review, A-cli, A-cli-help

#15986 docs: update changelog
  src/doc/src/CHANGELOG.md
Labels: A-documenting-cargo-itself, S-waiting-on-review

#16019 fix(shell): Use a distinct style for transient status
  src/cargo/core/shell.rs
  src/cargo/util/progress.rs
  src/cargo/util/style.rs
Labels: A-console-output, S-waiting-on-review

#16016 Add retry for `git fetch` failures in `CARGO_NET_GIT_FETCH_WITH_CLI` path
  src/cargo/sources/git/utils.rs
  src/cargo/util/errors.rs
  src/cargo/util/network/retry.rs
  tests/testsuite/git.rs
Labels: A-git, A-networking, S-waiting-on-review, A-cache-messages

#16025 fix: remove FIXME comment that's no longer a problem
  tests/testsuite/tool_paths.rs
Labels: S-waiting-on-review
