Repository rust-lang/cargo, pull requests merged in 2025-01, with the labels that each got.

#14756 fix: env table config can't trigger rebuild with `rerun-if-env-changed`.
  src/cargo/core/compiler/fingerprint/mod.rs
  tests/testsuite/build_script_env.rs
Labels: A-configuration, A-build-execution, A-rebuild-detection, S-waiting-on-review

#15000 fix(schema): Correct and update the JSON Schema
  .github/workflows/main.yml
  crates/cargo-util-schemas/manifest.schema.json
  crates/cargo-util-schemas/src/manifest/mod.rs
Labels: A-manifest, S-waiting-on-review, A-infrastructure

#15002 test(git): Clean up shallow fetch tests
  crates/cargo-test-support/src/lib.rs
  tests/testsuite/git_shallow.rs
Labels: A-testing-cargo-itself, S-waiting-on-review

#15008 refactor(manifest): Clean up field -> env var handling
  src/cargo/core/manifest.rs
Labels: A-manifest, S-waiting-on-review

#15012 chore: bump gix-lock to remove thiserror@1 from `cargo`
  Cargo.lock
Labels: S-waiting-on-review

#15016 Fix https::self_signed_should_fail for macos
  tests/testsuite/https.rs
Labels: S-waiting-on-review

#15017 Remove condition on RUSTUP_WINDOWS_PATH_ADD_BIN
  crates/cargo-test-macro/src/lib.rs
Labels: A-testing-cargo-itself, S-waiting-on-review

#15018 Update libgit2 to 1.9
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-review

#15022 Bump to 0.87.0; update changelog
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-review

#15026 Setup cargo environment for `cargo rustc --print`
  src/cargo/ops/cargo_compile/mod.rs
  tests/testsuite/rustc.rs
Labels: S-waiting-on-review

#14980 simplify SourceID Ord/Eq
  src/cargo/core/source_id.rs
Labels: T-cargo, final-comment-period, disposition-merge, S-waiting-on-review

#15034 Make `"C"` explicit in `extern "C"`.
  tests/testsuite/build_script.rs
Labels: S-waiting-on-review

#15029 shorten comment on Ord for SourceKind
  Cargo.lock
  crates/cargo-util-schemas/Cargo.toml
  crates/cargo-util-schemas/src/core/source_kind.rs
  src/cargo/core/source_id.rs
Labels: S-waiting-on-review

#15035 fix(schemas): Fix the `[lints]` JSON Schema
  Cargo.lock
  Cargo.toml
  crates/cargo-util-schemas/Cargo.toml
  crates/cargo-util-schemas/manifest.schema.json
  crates/cargo-util-schemas/src/manifest/mod.rs
  crates/cargo-util-schemas/src/schema.rs
Labels: A-manifest, S-waiting-on-review

#15036 fix: emit warnings as warnings when learning rust target info
  .github/workflows/main.yml
  Cargo.lock
  Cargo.toml
  crates/cargo-test-support/Cargo.toml
  crates/cargo-test-support/src/cross_compile.rs
  src/cargo/core/compiler/build_context/target_info.rs
  tests/testsuite/cross_compile.rs
  tests/testsuite/standard_lib.rs
Labels: A-testing-cargo-itself, S-waiting-on-review, A-cfg-expr, A-infrastructure

#15037 docs(contrib): Start guidelines for schema design
  src/doc/contrib/src/SUMMARY.md
  src/doc/contrib/src/implementation/schemas.md
Labels: A-documenting-cargo-itself, S-waiting-on-review

#15042 Remove unnecessary into conversions
  src/cargo/sources/git/known_hosts.rs
  src/cargo/sources/git/utils.rs
Labels: A-git, S-waiting-on-review

#15044 docs(ref): Fix the inverted logic about MSRV
  src/doc/src/reference/resolver.md
Labels: A-documenting-cargo-itself, S-waiting-on-review

#15014 feat: Added warning when failing to update index cache
  src/cargo/sources/registry/index/cache.rs
  tests/testsuite/registry.rs
Labels: A-registries, S-waiting-on-review

#15049 docs(reference): Fix PkgIdSpec kind docs
  src/doc/src/reference/pkgid-spec.md
Labels: A-documenting-cargo-itself, S-waiting-on-review

#15054 Clarify note in example
  src/doc/src/reference/specifying-dependencies.md
Labels: A-documenting-cargo-itself, S-waiting-on-review

#15062 Document that cargo automatically registers variables used in env! macro to trigger rebuilds
  src/doc/src/reference/build-scripts.md
Labels: A-documenting-cargo-itself, A-build-scripts, S-waiting-on-review

#15069 Fix benchsuite issue with newer versions of git
  benches/benchsuite/src/lib.rs
Labels: A-testing-cargo-itself, S-waiting-on-review

#15065 fix(build-std): parse as comma-separated list
  src/cargo/core/features.rs
  tests/testsuite/config.rs
Labels: S-waiting-on-review, Z-build-std, A-unstable

#15067 docs(cargo-package): alwasy include the lockfile
  src/doc/man/cargo-package.md
  src/doc/man/generated_txt/cargo-package.txt
  src/doc/src/commands/cargo-package.md
  src/etc/man/cargo-package.1
Labels: A-documenting-cargo-itself, Command-package, S-waiting-on-review, A-cli-help

#15072 docs(cargo-clippy): correct typo
  src/doc/src/commands/cargo-clippy.md
Labels: A-documenting-cargo-itself, S-waiting-on-review

#15070 fix(publish): Report all unpublishable packages
  src/cargo/ops/registry/publish.rs
  tests/testsuite/publish.rs
Labels: Command-publish, A-interacts-with-crates.io, S-waiting-on-review

#15074 fix: wrong concat and field name
  src/cargo/util/toml/mod.rs
Labels: A-manifest, S-waiting-on-review

#15075 took the functionality of the third party subcommand from the list_commands function
  src/bin/cargo/main.rs
Labels: S-waiting-on-review, A-cli

#15076 created a function for user defined aliases
  src/bin/cargo/main.rs
Labels: S-waiting-on-review, A-cli

#15013 Make --allow-dirty imply --allow-staged
  src/bin/cargo/commands/fix.rs
  src/cargo/ops/fix.rs
  src/doc/man/cargo-fix.md
  src/doc/man/generated_txt/cargo-fix.txt
  src/doc/src/commands/cargo-fix.md
  src/etc/man/cargo-fix.1
  tests/testsuite/cargo_fix/help/stdout.term.svg
  tests/testsuite/fix.rs
Labels: A-documenting-cargo-itself, Command-fix, S-waiting-on-review, A-cli, A-cli-help

#15097 Remove unused `-C link-arg=-fuse-ld=lld`
  tests/testsuite/freshness.rs
  tests/testsuite/freshness_checksum.rs
Labels: S-waiting-on-review

#15103 Fix comment on Ord for SourceId
  src/cargo/core/source_id.rs
Labels: S-waiting-on-review

#15110 Update tests to fix nightly errors
  tests/testsuite/build_script.rs
  tests/testsuite/cross_compile.rs
  tests/testsuite/standard_lib.rs
Labels: S-waiting-on-review

#15057 fix(login): Deprecate CLI token
  src/bin/cargo/commands/login.rs
  src/doc/man/cargo-login.md
  src/doc/man/generated_txt/cargo-login.txt
  src/doc/src/commands/cargo-login.md
  src/etc/man/cargo-login.1
  tests/testsuite/alt_registry.rs
  tests/testsuite/cargo_login/help/stdout.term.svg
  tests/testsuite/credential_process.rs
  tests/testsuite/login.rs
Labels: A-documenting-cargo-itself, Command-login, T-cargo, final-comment-period, disposition-merge, S-waiting-on-review, A-cli, A-cli-help

#15112 Fix warnings on Windows
  tests/testsuite/registry.rs
Labels: S-waiting-on-review

#15111 Fix shared_std_dependency_rebuild running on Windows
  tests/testsuite/standard_lib.rs
Labels: S-waiting-on-review

#15109 fix broken links in the Cargo book
  src/doc/src/guide/build-cache.md
  src/doc/src/guide/index.md
  src/doc/src/reference/index.md
Labels: A-documenting-cargo-itself, S-waiting-on-review

#15007 Conditionally mark the `test` cfg as a well known cfg
  src/cargo/core/compiler/mod.rs
  src/doc/src/reference/cargo-targets.md
  tests/testsuite/check_cfg.rs
  tests/testsuite/test.rs
Labels: A-documenting-cargo-itself, A-build-execution, S-waiting-on-review

#15119 Move the changelog to the cargo book
  .github/workflows/contrib.yml
  .github/workflows/main.yml
  src/doc/book.toml
  src/doc/contrib/src/process/release.md
  src/doc/contrib/src/process/security.md
  src/doc/src/CHANGELOG.md
  src/doc/src/SUMMARY.md
  src/doc/src/index.md
Labels: A-documenting-cargo-itself, S-waiting-on-review, A-infrastructure

#15121 chore: Update clap_complete
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-review

#15124 Don't suggest `cargo login` when using incompatible credental providers
  src/cargo/util/auth/mod.rs
  tests/testsuite/credential_process.rs
Labels: S-waiting-on-review, A-registry-authentication
