Repository rust-lang/cargo, pull requests merged in 2025-10, with the labels that each got.

#16020 [Beta-1.91] fix(shell): Use a distinct style for transient status
  src/cargo/core/shell.rs
  src/cargo/util/progress.rs
  src/cargo/util/style.rs
Labels: A-console-output, S-waiting-on-review

#16002 Public in private manifest errors
  src/cargo/core/compiler/build_context/target_info.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/util/lints.rs
  tests/testsuite/pub_priv.rs
Labels: A-build-execution, S-waiting-on-review, A-cfg-expr

#16027 fix(run): Override arg0 for cargo scripts
  crates/cargo-util/src/process_builder.rs
  src/cargo/ops/cargo_run.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/script/cargo.rs
Labels: A-documenting-cargo-itself, Command-run, S-waiting-on-review

#16035 Convert a multi-part diagnostic to a report
  src/cargo/core/workspace.rs
  tests/testsuite/features2.rs
Labels: A-workspaces, S-waiting-on-review

#16039 Lockfile schemas error cleanup
  crates/cargo-util-schemas/src/lockfile.rs
Labels: S-waiting-on-review

#16036 Fix FileLock path tracking after rename in package operation
  src/cargo/ops/cargo_package/mod.rs
  src/cargo/util/flock.rs
Labels: Command-package, S-waiting-on-review, A-filesystem

#16044 chore(ci): unpin libc
  .github/renovate.json5
  Cargo.lock
Labels: S-waiting-on-review, A-infrastructure

#16026 fix(toml): Prevent non-script fields in Cargo scripts
  src/cargo/util/toml/mod.rs
  tests/testsuite/cargo_remove/script/in/cargo-remove-test-fixture.rs
  tests/testsuite/cargo_remove/script/out/cargo-remove-test-fixture.rs
Labels: A-manifest, S-waiting-on-review

#16048 chore: Disabled `reserved_windows_name` test temporaily
  tests/testsuite/package.rs
Labels: S-waiting-on-review

#16052 test: null-terminated path for reserved windows name detection
  crates/cargo-test-support/src/paths.rs
  tests/testsuite/package.rs
Labels: A-testing-cargo-itself, S-waiting-on-review

#15966 Consider public dependencies when choosing a version in cargo add (#1…
  src/cargo/ops/cargo_add/mod.rs
  src/cargo/util/toml_mut/manifest.rs
  tests/testsuite/cargo_add/mod.rs
  tests/testsuite/cargo_add/public_common_version/in/Cargo.toml
  tests/testsuite/cargo_add/public_common_version/in/src/lib.rs
  tests/testsuite/cargo_add/public_common_version/mod.rs
  tests/testsuite/cargo_add/public_common_version/out/Cargo.toml
  tests/testsuite/cargo_add/public_common_version/stderr.term.svg
Labels: A-manifest, S-waiting-on-review, Command-add
