Repository rust-lang/cargo, pull requests merged in 2025-04, with the labels that each got.

#14439 move modules from kebab-case to snake_case
  src/doc/src/guide/project-layout.md
Labels: A-documenting-cargo-itself, S-waiting-on-review

#15362 rename the `author` field to be `authors` in book.toml
  src/doc/book.toml
Labels: A-documenting-cargo-itself, S-waiting-on-review

#15368 Prevent undeclared public network access
  tests/testsuite/cargo_add/add_no_vendored_package_with_vendor/mod.rs
  tests/testsuite/cargo_add/add_toolchain/mod.rs
  tests/testsuite/cargo_add/dev_existing_path_base/mod.rs
  tests/testsuite/cargo_add/invalid_key_inherit_dependency/mod.rs
  tests/testsuite/cargo_add/invalid_key_overwrite_inherit_dependency/mod.rs
  tests/testsuite/cargo_add/invalid_key_rename_inherit_dependency/mod.rs
  tests/testsuite/cargo_add/merge_activated_features/mod.rs
  tests/testsuite/cargo_add/normalize_name_path_existing/mod.rs
  tests/testsuite/cargo_add/normalize_name_path_existing/stderr.term.svg
  tests/testsuite/cargo_add/path_base/mod.rs
  tests/testsuite/cargo_add/path_base_inferred_name/mod.rs
  tests/testsuite/cargo_add/path_base_missing_base_path/mod.rs
  tests/testsuite/cargo_add/path_base_unstable/mod.rs
  tests/testsuite/cargo_add/unknown_inherited_feature/mod.rs
  tests/testsuite/cargo_info/specify_empty_version_with_url/mod.rs
  tests/testsuite/cargo_info/specify_version_with_url_but_registry_is_not_matched/mod.rs
  tests/testsuite/cargo_info/within_ws_with_alternative_registry/mod.rs
  tests/testsuite/cargo_info/within_ws_with_alternative_registry/stderr.term.svg
  tests/testsuite/package.rs
Labels: S-waiting-on-review

#15377 Added `build_directory` field to cargo metadata output
  src/cargo/ops/cargo_output_metadata.rs
  tests/testsuite/metadata.rs
Labels: Command-metadata, S-waiting-on-review

#15077 chore: add aarch64 linux runner
  .github/workflows/main.yml
  Cargo.lock
  crates/cargo-test-support/Cargo.toml
  crates/cargo-test-support/src/cross_compile.rs
Labels: A-testing-cargo-itself, S-waiting-on-review, A-infrastructure

#15379 docs(changelog): polish changelog items
  src/doc/src/CHANGELOG.md
Labels: A-documenting-cargo-itself, S-waiting-on-review

#15389 chore(ci): restore cargo-util semver check
  crates/xtask-bump-check/src/xtask.rs
Labels: S-waiting-on-review, A-infrastructure

#15397 [stable-1.86] chore: bump cargo-util-schemas to 0.8.0
  .github/workflows/main.yml
  Cargo.lock
  Cargo.toml
  crates/cargo-util-schemas/Cargo.toml
  src/doc/src/reference/semver.md
Labels: A-documenting-cargo-itself, S-waiting-on-review, A-infrastructure

#15403 chore: Bump cargo-util-schemas to 0.8.2
  Cargo.lock
  Cargo.toml
  crates/cargo-util-schemas/Cargo.toml
Labels: S-waiting-on-review

#15402 [beta-1.87] chore: Bump cargo-util-schemas to 0.8.1
  Cargo.lock
  Cargo.toml
  crates/cargo-util-schemas/Cargo.toml
  src/doc/src/reference/semver.md
Labels: A-documenting-cargo-itself, S-waiting-on-review

#15404 docs(ref): Use better example value in `CARGO_CFG_TARGET_ABI`
  src/doc/src/reference/environment-variables.md
Labels: A-documenting-cargo-itself, S-waiting-on-review

#15405 feat: print target and package names formatted as file hyperlinks
  src/cargo/util/workspace.rs
Labels: A-workspaces, S-waiting-on-review

#15400 Added symlink resolution for `workspace-path-hash`
  src/cargo/util/context/mod.rs
  tests/testsuite/build_dir.rs
Labels: A-configuration, A-testing-cargo-itself, S-waiting-on-review

#15416 fix(package): detect dirtiness for symlinks to submodule
  src/cargo/ops/cargo_package/vcs.rs
  tests/testsuite/package.rs
Labels: A-git, Command-package, S-waiting-on-review

#15414 Added validation for unmatched brackets in build-dir template
  src/cargo/util/context/mod.rs
  src/cargo/util/context/path.rs
  tests/testsuite/build_dir.rs
Labels: A-configuration, S-waiting-on-review

#15418 Improved error message when build-dir template var is invalid
  src/cargo/util/context/mod.rs
  tests/testsuite/build_dir.rs
Labels: A-configuration, S-waiting-on-review

#15419 Revert "fix(package): detect dirtiness for symlinks to submodule"
  src/cargo/ops/cargo_package/vcs.rs
  tests/testsuite/package.rs
Labels: A-git, Command-package, S-waiting-on-review

#15420 fix(build): Correct name of CARGO_CFG_FEATURE
  crates/build-rs/src/input.rs
Labels: A-build-scripts, S-waiting-on-review

#15421 chore: Bump build-rs version
  Cargo.lock
  Cargo.toml
  crates/build-rs/Cargo.toml
Labels: A-build-scripts, S-waiting-on-review

#15221 Make sure search paths inside OUT_DIR precede external paths
  src/cargo/core/compiler/build_runner/mod.rs
  src/cargo/core/compiler/custom_build.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/util/context/target.rs
  tests/testsuite/build_script.rs
Labels: A-build-execution, A-build-scripts, S-waiting-on-review

#15429 test(rustfix): Use `snapbox` for snapshot testing
  Cargo.lock
  crates/rustfix/Cargo.toml
  crates/rustfix/tests/everything/multiple-solutions.fixed.rs
  crates/rustfix/tests/everything/multiple-solutions.json
  crates/rustfix/tests/everything/multiple-solutions.rs
  crates/rustfix/tests/parse_and_replace.rs
Labels: Command-fix, S-waiting-on-review

#15417 use `zlib-rs` for gzip compression in rust code
  Cargo.lock
  Cargo.toml
  README.md
  src/doc/src/reference/features.md
Labels: relnotes, S-waiting-on-review

#15434 Fix formatting of CliUnstable parsing
  src/cargo/core/features.rs
Labels: S-waiting-on-review, A-unstable

#14649 Implement RFC3695: Allow boolean literals as cfg predicates
  Cargo.lock
  Cargo.toml
  crates/cargo-platform/Cargo.toml
  crates/cargo-platform/src/cfg.rs
  crates/cargo-platform/src/lib.rs
  crates/cargo-platform/tests/test_cfg.rs
  tests/testsuite/cfg.rs
Labels: A-documenting-cargo-itself, A-manifest, S-waiting-on-review, A-cfg-expr

#15447 fix(unit-graph): switch to Package ID Spec
  src/cargo/core/compiler/unit_graph.rs
  tests/testsuite/unit_graph.rs
Labels: S-waiting-on-review

#15454 fix: Suggest similar looking feature names when feature is missing
  src/cargo/core/resolver/dep_cache.rs
  src/cargo/core/resolver/errors.rs
  src/cargo/core/resolver/types.rs
  src/cargo/core/summary.rs
  tests/testsuite/build_script.rs
  tests/testsuite/features.rs
  tests/testsuite/features_namespaced.rs
  tests/testsuite/package_features.rs
  tests/testsuite/test.rs
Labels: A-dependency-resolution, S-waiting-on-review

#15455 Update doctest xcompile flags
  src/cargo/ops/cargo_test.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/test.rs
Labels: A-documenting-cargo-itself, Command-test, S-waiting-on-review

#14287 Stabilize automatic garbage collection.
  src/cargo/core/gc.rs
  src/doc/src/reference/config.md
  src/doc/src/reference/environment-variables.md
  src/doc/src/reference/unstable.md
  tests/testsuite/global_cache_tracker.rs
Labels: A-documenting-cargo-itself, T-cargo, finished-final-comment-period, disposition-merge, S-waiting-on-review, Z-gc, to-announce

#15458 source-replacement.md: fix typo
  src/doc/src/reference/source-replacement.md
Labels: A-documenting-cargo-itself, S-waiting-on-review

#15459 overriding-dependencies.md: better readability
  src/doc/src/reference/overriding-dependencies.md
Labels: A-documenting-cargo-itself, S-waiting-on-review

#15461 Trivial tweaks to 'target_short_hash'
  src/cargo/core/compiler/build_runner/compilation_files.rs
Labels: S-waiting-on-review, A-layout

#15464 Added tracing spans for rustc invocations
  src/cargo/core/compiler/mod.rs
Labels: A-build-execution, S-waiting-on-review

#15457 fix grammar, and remove confusing example
  src/doc/src/reference/source-replacement.md
Labels: A-documenting-cargo-itself, S-waiting-on-review
