Repository rust-lang/cargo, pull requests merged in 2025-02, with the labels that each got.

#15132 Revert "Conditionally mark the `test` cfg as a well known cfg (#15007)"
  src/cargo/core/compiler/mod.rs
  src/doc/src/reference/cargo-targets.md
  tests/testsuite/check_cfg.rs
  tests/testsuite/test.rs
Labels: A-documenting-cargo-itself, A-build-execution, S-waiting-on-review

#15136 removed a word that was repeated
  src/doc/src/reference/manifest.md
Labels: A-documenting-cargo-itself, S-waiting-on-review

#15135 allow windows reserved names in CI
  crates/cargo-test-support/src/paths.rs
Labels: A-testing-cargo-itself, S-waiting-on-review

#15123 Remove the original changelog
  CHANGELOG.md
  README.md
Labels: S-waiting-on-review

#15142 Fix changelog link
  CHANGELOG.md
Labels: S-waiting-on-review

#15138 fix: Don't use "did you mean" in errors
  src/bin/cargo/commands/run.rs
  src/bin/cargo/main.rs
  src/cargo/core/package_id_spec.rs
  src/cargo/core/profiles.rs
  src/cargo/ops/cargo_clean.rs
  src/cargo/ops/cargo_compile/unit_generator.rs
  src/cargo/util/edit_distance.rs
  src/cargo/util/toml/mod.rs
  tests/testsuite/build.rs
  tests/testsuite/cargo_command.rs
  tests/testsuite/clean.rs
  tests/testsuite/help.rs
  tests/testsuite/package_features.rs
  tests/testsuite/pkgid.rs
  tests/testsuite/profile_overrides.rs
  tests/testsuite/publish.rs
  tests/testsuite/run.rs
  tests/testsuite/script.rs
  tests/testsuite/tree.rs
Labels: Command-run, Command-clean, A-profiles, A-manifest, S-waiting-on-review, A-cli, A-cargo-targets

#15133 Suggest similar feature names on CLI
  src/cargo/core/resolver/dep_cache.rs
  tests/testsuite/features_namespaced.rs
  tests/testsuite/package_features.rs
Labels: A-diagnostics, A-dependency-resolution, S-waiting-on-review

#15040 Small resolver cleanups
  src/cargo/core/resolver/context.rs
  src/cargo/core/resolver/mod.rs
Labels: A-dependency-resolution, S-waiting-on-review

#15147 Make cache tracking resilient to unexpected files
  src/cargo/core/global_cache_tracker.rs
  tests/testsuite/global_cache_tracker.rs
Labels: S-waiting-on-review

#15071 feat: emit error if package not found within workspace
  src/cargo/ops/cargo_compile/packages.rs
  src/cargo/ops/cargo_output_metadata.rs
  tests/testsuite/workspaces.rs
Labels: Command-publish, Command-metadata, Command-package, S-waiting-on-review, A-cli, Command-tree, Command-add, Command-remove

#15143 Don't use on Solaris libc::LOCK_* which were removed from libc in ver…
  src/cargo/util/flock.rs
Labels: S-waiting-on-review, A-filesystem

#15150 Simplify backtrack
  src/cargo/core/resolver/mod.rs
Labels: A-dependency-resolution

#15161 fix: align first line of unordered list with following
  crates/mdman/doc/out/mdman.1
  crates/mdman/src/format/man.rs
  crates/mdman/tests/compare/expected/formatting.1
  crates/mdman/tests/compare/expected/options.1
  src/etc/man/cargo-add.1
  src/etc/man/cargo-bench.1
  src/etc/man/cargo-build.1
  src/etc/man/cargo-check.1
  src/etc/man/cargo-clean.1
  src/etc/man/cargo-doc.1
  src/etc/man/cargo-fetch.1
  src/etc/man/cargo-fix.1
  src/etc/man/cargo-generate-lockfile.1
  src/etc/man/cargo-info.1
  src/etc/man/cargo-init.1
  src/etc/man/cargo-install.1
  src/etc/man/cargo-locate-project.1
  src/etc/man/cargo-login.1
  src/etc/man/cargo-logout.1
  src/etc/man/cargo-metadata.1
  src/etc/man/cargo-new.1
  src/etc/man/cargo-owner.1
  src/etc/man/cargo-package.1
  src/etc/man/cargo-pkgid.1
  src/etc/man/cargo-publish.1
  src/etc/man/cargo-remove.1
  src/etc/man/cargo-run.1
  src/etc/man/cargo-rustc.1
  src/etc/man/cargo-rustdoc.1
  src/etc/man/cargo-search.1
  src/etc/man/cargo-test.1
  src/etc/man/cargo-tree.1
  src/etc/man/cargo-uninstall.1
  src/etc/man/cargo-update.1
  src/etc/man/cargo-vendor.1
  src/etc/man/cargo-yank.1
  src/etc/man/cargo.1
Labels: S-waiting-on-review, A-cli-help

#15163 Update rusqlite from 0.32.1 to 0.33.0
  Cargo.lock
  Cargo.toml
  deny.toml
Labels: S-waiting-on-review, A-infrastructure

#15164 Update deny.toml
  deny.toml
Labels: S-waiting-on-review, A-infrastructure

#15165 Update annotate-snippets from 0.11.4 to 0.11.5
  Cargo.lock
  Cargo.toml
  tests/testsuite/alt_registry.rs
  tests/testsuite/cargo_add/invalid_manifest/stderr.term.svg
  tests/testsuite/lints/error/stderr.term.svg
  tests/testsuite/lints/inherited/stderr.term.svg
  tests/testsuite/lints/warning/stderr.term.svg
Labels: S-waiting-on-review

#15162 Update curl from 8.9.0 to 8.12.0
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-review

#15166 Update all dependencies
  Cargo.lock
  Cargo.toml
  deny.toml
Labels: S-waiting-on-review, A-infrastructure

#15169 Fix race condition in panic_abort_tests
  tests/testsuite/test.rs
Labels: S-waiting-on-review

#15157 feat: implement workspace feature unification
  src/cargo/core/features.rs
  src/cargo/core/workspace.rs
  src/cargo/ops/cargo_install.rs
  src/cargo/ops/fix.rs
  src/cargo/ops/resolve.rs
  src/cargo/util/context/mod.rs
  tests/testsuite/cargo/z_help/stdout.term.svg
  tests/testsuite/feature_unification.rs
  tests/testsuite/main.rs
Labels: A-configuration, Command-install, A-workspaces, Command-fix, S-waiting-on-review, A-unstable

#15173 docs(embedded): Note the shebang deviation
  src/cargo/util/toml/embedded.rs
Labels: S-waiting-on-review

#15172 refactor: Consolidate creation of SourceId from manifest path
  src/cargo/core/source_id.rs
  src/cargo/core/workspace.rs
  src/cargo/util/toml/mod.rs
Labels: A-workspaces, A-manifest, S-waiting-on-review

#15182 Fix the description of the `"root"` field of the `cargo metadata`'s output
  src/doc/man/cargo-metadata.md
  src/doc/man/generated_txt/cargo-metadata.txt
  src/doc/src/commands/cargo-metadata.md
  src/etc/man/cargo-metadata.1
Labels: A-documenting-cargo-itself, S-waiting-on-review, A-cli-help

#15191 Fix man page with malformed `{{#options}}` block
  src/doc/man/cargo-publish.md
  src/doc/man/generated_txt/cargo-publish.txt
  src/doc/src/commands/cargo-publish.md
  src/etc/man/cargo-publish.1
Labels: A-documenting-cargo-itself, S-waiting-on-review, A-cli-help

#15189 docs: docs for `-Zfeature-unification`
  src/doc/src/reference/unstable.md
Labels: A-documenting-cargo-itself, S-waiting-on-review

#15187 fix(embedded): Handle more parsing corner cases
  src/cargo/util/toml/embedded.rs
Labels: S-waiting-on-review

#15197 docs: Improve comments
  src/cargo/ops/fix.rs
Labels: Command-fix, S-waiting-on-review, A-cli

#15200 fix(add): Focus on error, rather than large feature lists
  src/cargo/ops/cargo_add/mod.rs
  tests/testsuite/cargo_add/features_error_activated_over_limit/in/Cargo.toml
  tests/testsuite/cargo_add/features_error_activated_over_limit/in/src/lib.rs
  tests/testsuite/cargo_add/features_error_activated_over_limit/mod.rs
  tests/testsuite/cargo_add/features_error_activated_over_limit/out/Cargo.toml
  tests/testsuite/cargo_add/features_error_activated_over_limit/stderr.term.svg
  tests/testsuite/cargo_add/features_error_deactivated_over_limit/in/Cargo.toml
  tests/testsuite/cargo_add/features_error_deactivated_over_limit/in/src/lib.rs
  tests/testsuite/cargo_add/features_error_deactivated_over_limit/mod.rs
  tests/testsuite/cargo_add/features_error_deactivated_over_limit/out/Cargo.toml
  tests/testsuite/cargo_add/features_error_deactivated_over_limit/stderr.term.svg
  tests/testsuite/cargo_add/mod.rs
Labels: S-waiting-on-review, Command-add

#15201 Typo: "explicitally" -> "explicitly"
  crates/cargo-util/src/process_builder.rs
Labels: S-waiting-on-review

#15202 chore: bump to 0.88.0; update changelog
  Cargo.lock
  Cargo.toml
  src/doc/src/CHANGELOG.md
Labels: A-documenting-cargo-itself, S-waiting-on-review

#15204 Typo: "togother" -> "together"
  tests/testsuite/workspaces.rs
Labels: S-waiting-on-review

#15206 fix: build warning in windows_reserved_names_are_allowed
  Cargo.lock
  crates/cargo-test-support/Cargo.toml
  crates/cargo-test-support/src/paths.rs
Labels: A-testing-cargo-itself, S-waiting-on-review

#15215 fix: mention "3" as a valid value for "resolver" field in error message
  src/cargo/core/resolver/types.rs
  tests/testsuite/features2.rs
Labels: A-dependency-resolution, S-waiting-on-review

#15213 docs(ref): Shift focus to resolver v3
  src/doc/src/reference/workspaces.md
Labels: A-documenting-cargo-itself, S-waiting-on-review

#15212 chore(ci): Auto-update cargo-semver-checks
  .github/renovate.json5
Labels: S-waiting-on-review, A-infrastructure

#15218 chore(ci): Visually group output in Github
  ci/validate-version-bump.sh
  crates/xtask-bump-check/src/xtask.rs
Labels: S-waiting-on-review, A-infrastructure

#15216 fix(package): Fix lookups to capitalized workspace member's index entry
  crates/cargo-util/src/registry.rs
  src/cargo/ops/cargo_package/mod.rs
  src/cargo/sources/registry/index/mod.rs
  tests/testsuite/package.rs
Labels: Command-package, A-registries, S-waiting-on-review

#15222 chore: dont check cargo-util semver until 1.86 is released
  crates/xtask-bump-check/src/xtask.rs
Labels: S-waiting-on-review, A-infrastructure

#15224 chore: depend on openssl-sys to correctly pin its version
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-review

#15223 chore: semver-check build-rs against beta channel
  crates/xtask-bump-check/src/xtask.rs
Labels: S-waiting-on-review, A-infrastructure

#15226 [beta-1.86] depend on openssl-sys to correctly pin its version
  Cargo.lock
  Cargo.toml
  tests/testsuite/global_cache_tracker.rs
Labels: S-waiting-on-review

#15225 feat: add completions for `--manifest-path`
  src/cargo/util/command_prelude.rs
Labels: S-waiting-on-review, A-cli

#15104 Implemented `build.build-dir` config option
  src/cargo/core/compiler/build_runner/compilation_files.rs
  src/cargo/core/compiler/custom_build.rs
  src/cargo/core/compiler/fingerprint/dep_info.rs
  src/cargo/core/compiler/fingerprint/mod.rs
  src/cargo/core/compiler/future_incompat.rs
  src/cargo/core/compiler/layout.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/core/features.rs
  src/cargo/core/workspace.rs
  src/cargo/ops/cargo_clean.rs
  src/cargo/ops/cargo_package/mod.rs
  src/cargo/ops/cargo_package/verify.rs
  src/cargo/util/context/mod.rs
  src/cargo/util/flock.rs
  src/cargo/util/workspace.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/build_dir.rs
  tests/testsuite/cargo/z_help/stdout.term.svg
  tests/testsuite/main.rs
Labels: A-documenting-cargo-itself, A-configuration, Command-clean, A-build-execution, Command-package, A-workspaces, A-rebuild-detection, A-build-scripts, S-waiting-on-review, A-filesystem, A-layout, A-unstable, A-future-incompat

#15232 chore: bump openssl to v3
  .github/renovate.json5
  Cargo.lock
  Cargo.toml
Labels: relnotes, S-waiting-on-review, A-infrastructure

#15233 refactor(tree): Abstract the concept of an edge
  src/cargo/ops/tree/graph.rs
  src/cargo/ops/tree/mod.rs
Labels: S-waiting-on-review, Command-tree

#13709 feat: implement RFC 3553 to add SBOM support
  Cargo.lock
  crates/cargo-test-support/Cargo.toml
  crates/cargo-test-support/src/lib.rs
  src/cargo/core/compiler/build_config.rs
  src/cargo/core/compiler/build_context/target_info.rs
  src/cargo/core/compiler/build_runner/compilation_files.rs
  src/cargo/core/compiler/build_runner/mod.rs
  src/cargo/core/compiler/fingerprint/mod.rs
  src/cargo/core/compiler/mod.rs
  src/cargo/core/compiler/output_depinfo.rs
  src/cargo/core/compiler/output_sbom.rs
  src/cargo/core/features.rs
  src/cargo/util/context/mod.rs
  src/doc/src/reference/unstable.md
  tests/testsuite/cargo/z_help/stdout.term.svg
  tests/testsuite/main.rs
  tests/testsuite/sbom.rs
Labels: A-documenting-cargo-itself, A-configuration, A-build-execution, A-rebuild-detection, A-testing-cargo-itself, S-waiting-on-review, A-cfg-expr, A-layout, A-dep-info, A-unstable

#15237 refactor(tree): Abstract the concept of a NodeId
  src/cargo/ops/tree/format/mod.rs
  src/cargo/ops/tree/graph.rs
  src/cargo/ops/tree/mod.rs
Labels: S-waiting-on-review, Command-tree

#15245 Bump `cc` to 1.2.16 to fix `x86` windows jobs in rust-lang/rust CI
  Cargo.lock
Labels: S-waiting-on-review

#15240 fix(package): Ensure we can package directories ending with '.rs'
  src/cargo/util/toml/mod.rs
  tests/testsuite/package.rs
  tests/testsuite/script.rs
Labels: A-manifest, S-waiting-on-review, regression-from-stable-to-beta

#15246 refactor: control byte display precision with std::fmt options
  Cargo.lock
  Cargo.toml
  src/cargo/core/package.rs
  src/cargo/ops/cargo_clean.rs
  src/cargo/ops/cargo_package/mod.rs
  src/cargo/sources/git/oxide.rs
  src/cargo/sources/git/utils.rs
  src/cargo/util/mod.rs
  tests/testsuite/package.rs
  tests/testsuite/progress.rs
Labels: A-git, Command-clean, Command-package, S-waiting-on-review

#15199 Get all members as `available targets` even though default-members was specified.
  src/cargo/ops/cargo_compile/mod.rs
  src/cargo/ops/cargo_compile/unit_generator.rs
  tests/testsuite/build.rs
  tests/testsuite/run.rs
  tests/testsuite/test.rs
  tests/testsuite/workspaces.rs
Labels: A-workspaces, S-waiting-on-review, A-cli, A-cargo-targets

#15208 fix: reset $CARGO if the running program is real `cargo[.exe]`
  src/cargo/util/context/mod.rs
  tests/testsuite/cargo_command.rs
  tests/testsuite/test.rs
Labels: A-configuration, A-environment-variables, S-waiting-on-review, A-custom-subcommands
